-- ONE SELECT-only statement / ONE result row. No application RPC calls.
-- Stop on failed_checks. Preserve and compare ALL protected_target_evidence / upstream_evidence_hashes before/after.
-- No fixed Ledger/Compensation row-count gate; those systems remain operational. No business UAT actions here.
with prerequisites(signature,hash) as(values ('public.current_user_can_view_finance_payments()','ee655ca91809471d32a79909a8178f66'),
('public.calculate_finance_billable_charge_amounts(numeric,numeric,text,numeric)','caf162441a1bb1dbeea2aba6461b4b5a'),
('public.assert_finance_billable_charge_context(uuid,bigint,uuid)','79ea6c5b4cae8483a652384ed1385e60'),
('public.finance_vat_treatment(jsonb,boolean,numeric)','d56bba89766a1ee28411a6854f8c573c'),
('public.finance_payment_wht_review_v2(jsonb,jsonb)','4af13910a5ee37ce68948fb6c9c7156e'),
('public.money_allocation_admin()','b6c3626891400d6817c575526fedd1c0'),
('public.money_allocation_source(uuid)','8d5731f472b38ccc8819bf895c7980ab'),
('public.vp_distribution_frozen_source(jsonb,jsonb)','dd7c249818f0918fd05b711d4af60d2d'),
('public.vp_distribution_choices(jsonb,jsonb,boolean)','9ba3597e77ecbee804cbca3dc2e8d7d6'),
('public.vp_distribution_immutable()','b11fdf476b490cc8971fc62d33ba7ea1'),
('public.save_finance_vp_distribution(uuid,uuid,integer,jsonb,jsonb,text)','276a63b50873c2ae5fd971207c0d6a69'),
('public.transition_finance_vp_distribution(uuid,integer,jsonb,text,boolean,text)','1c80933e8c6df2b50a601cd3f5182a2b'),
('public.guard_vp_distribution_source()','d9c2dfe4aedd09392bf393e1a91587ab'),
('public.vp_distribution_validate()','28858e2881c548358be1eedd2f8f178d'),
('public.get_finance_vp_distribution(uuid)','6e6d47836c88dd5616e7e42b6b9aa015'),
('public.vp_compensation_formula_catalog()','e7dd3b4645419ad707ba60494dd9d301'),
('public.vp_distribution_amount_choices_v1(jsonb,jsonb,boolean)','6bc574a243fe094d1443ff0ff6343c78'),
('public.vp_formula_calculate(numeric,text,integer,jsonb,jsonb)','db2a144bd77af5c64a72f28cf81fa4f8'),
('public.vp_formula_result_guard()','c0e42b906d2a4198ee95ce82ab1cdf5a')),
 prerequisite_differences as(select e.signature,e.hash as expected_hash,md5(p.prosrc) as actual_hash from prerequisites e left join pg_proc p on p.oid=to_regprocedure(e.signature) where p.oid is null or md5(p.prosrc) is distinct from e.hash),protected as(select jsonb_build_object('finance_payments',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_payments r),
'finance_payment_invoice_allocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_payment_invoice_allocations r),
'finance_payment_effective_invoice_allocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_payment_effective_invoice_allocations r),
'finance_payment_wht_components',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_payment_wht_components r),
'finance_payment_allocation_reallocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_payment_allocation_reallocations r),
'finance_payment_audit_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_payment_audit_events r),
'finance_invoices',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_invoices r),
'finance_invoice_items',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_invoice_items r),
'finance_invoice_audit_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_invoice_audit_events r),
'finance_invoice_settlement_summary',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_invoice_settlement_summary r),
'finance_cash_transactions',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_cash_transactions r),
'finance_account_opening_balances',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_account_opening_balances r),
'finance_cash_transaction_audit_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_cash_transaction_audit_events r),
'finance_company_ledger',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_company_ledger r),
'finance_compensation_batches',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_compensation_batches r),
'finance_compensation_allocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_compensation_allocations r),
'finance_receipts',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_receipts r),
'finance_receipt_invoice_allocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_receipt_invoice_allocations r),
'finance_receipt_audit_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_receipt_audit_events r),
'finance_tax_invoices',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_tax_invoices r),
'finance_tax_invoice_items',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_tax_invoice_items r),
'finance_tax_point_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_tax_point_events r),
'finance_combined_documents',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_combined_documents r),
'finance_combined_document_audit_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_combined_document_audit_events r),
'finance_document_counters',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_document_counters r),
'finance_payment_money_allocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_payment_money_allocations r),
'finance_payment_money_allocation_audit',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_payment_money_allocation_audit r),
'finance_vp_revenue_distributions',(select md5(coalesce(jsonb_agg((to_jsonb(r)-'direct_money_receipt_id') order by (to_jsonb(r)-'direct_money_receipt_id')::text),'[]')::text) from public.finance_vp_revenue_distributions r),
'finance_vp_revenue_distribution_audit',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_vp_revenue_distribution_audit r)) as hashes), protected_targets as(select jsonb_build_object(
 'payment_95E22D0E',(select to_jsonb(p) from public.finance_payments p where id='95e22d0e-1996-4f16-98e4-218db1cbd857'),
 'invoice_VP_IV_202609_000004',(select to_jsonb(i) from public.finance_invoices i where invoice_no='VP-IV-202609-000004'),
 'combined_D903B209',(select to_jsonb(c) from public.finance_combined_documents c where upper(left(id::text,8))='D903B209')) as evidence), checks(name,passed) as(values
 ('exact_prerequisite_functions',not exists(select 1 from prerequisite_differences)),
 ('047_namespace_unused',to_regclass('public.finance_direct_money_receipts') is null and to_regclass('public.finance_direct_money_receipt_audit') is null
  and not exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname in('finance_structured_wht_amount','direct_money_lines','direct_money_payload','direct_money_snapshot','save_finance_direct_money_receipt','transition_finance_direct_money_receipt','direct_money_guard','direct_money_classification_lines','direct_money_integrity','classify_finance_direct_money_receipt','vp_received_line_economics','vp_direct_frozen_source','vp_received_source','vp_received_frozen','vp_received_lock','save_finance_vp_received_distribution','save_finance_direct_vp_distribution','get_finance_vp_received_distribution','get_finance_direct_vp_formula_context','get_finance_received_money_source'))
  and not exists(select 1 from pg_attribute where attrelid='public.finance_vp_revenue_distributions'::regclass and attname='direct_money_receipt_id' and not attisdropped)),
 ('matter_master_shape',(select count(*)=2 and bool_and(case when c.relname='cases' then a.atttypid='bigint'::regtype else a.atttypid='uuid'::regtype end)
   from pg_attribute a join pg_class c on c.oid=a.attrelid where c.relnamespace='public'::regnamespace and c.relname in('cases','advisory_matters') and a.attname='id' and not a.attisdropped)),
 ('bank_master_shape',(select count(*)=4 from pg_attribute where attrelid='public.finance_bank_accounts'::regclass and attname in('id','short_name','bank_name','is_active') and not attisdropped))
 ) select (select jsonb_object_agg(name,passed order by name) from checks) as checks,
 (select coalesce(jsonb_agg(name order by name) filter(where passed is distinct from true),'[]') from checks) as failed_checks,
 (select bool_and(passed is true) from checks) as direct_money_receipt_foundation_preflight_pass,
 (select hashes from protected) as upstream_evidence_hashes,
 (select evidence from protected_targets) as protected_target_evidence,
 '[]'::jsonb as catalog_differences,
 (select coalesce(jsonb_agg(to_jsonb(d)),'[]') from prerequisite_differences d) as function_differences,
 jsonb_build_object('legacy_ledger_rows',(select count(*) from finance_company_ledger),'compensation_rows',(select count(*) from finance_compensation_allocations),
 'payment_rows',(select count(*) from finance_payments), 'cash_rows',(select count(*) from finance_cash_transactions),'opening_rows',(select count(*) from finance_account_opening_balances)
 ) as observability_only,
 current_setting('server_version_num')::integer as server_version_num;
