-- ONE SELECT-only statement / ONE row. No application RPC calls.
-- Stop on any failed check. Compare upstream_evidence_hashes before/after apply.
-- No backfill. Existing external/name-only and aggregate-only distributions require separate identity/evidence resolution.
with prerequisite_functions(signature,hash,security_definer,volatility,is_new,return_type,language,argument_names,default_count,is_strict,parallel,leakproof) as (values ('public.current_user_can_view_finance_payments()','ee655ca91809471d32a79909a8178f66',true,'v',false,'boolean','sql',null::text[],0,false,'u',false),
('public.money_allocation_admin()','b6c3626891400d6817c575526fedd1c0',true,'s',false,'boolean','sql',null::text[],0,false,'u',false),
('public.vp_distribution_choices(jsonb,jsonb,boolean)','a81c9b3f218f662dd41e5092dc05e0fb',false,'i',false,'jsonb','plpgsql',array['p_source','p_choices','p_complete']::text[],0,false,'u',false),
('public.vp_distribution_immutable()','71ab2be543407aa3a1610c4882e227fd',true,'v',false,'trigger','plpgsql',null::text[],0,false,'u',false),
('public.transition_finance_vp_distribution(uuid,integer,jsonb,text,boolean,text)','234e3f2e768a7856af3515ad74076e84',true,'v',false,'uuid','plpgsql',array['p_id','p_expected_version','p_source','p_action','p_acknowledged','p_reason']::text[],0,false,'u',false),
('public.vp_distribution_validate()','386dddc7e227fc12d3d0b12faaac3e62',true,'v',false,'trigger','plpgsql',null::text[],0,false,'u',false),
('public.vp_distribution_amount_choices_v1(jsonb,jsonb,boolean)','240df9ff78400a6ed8aae924f36cbf20',false,'i',false,'jsonb','plpgsql',array['p_source','p_choices','p_complete']::text[],0,false,'u',false),
('public.vp_formula_calculate(numeric,text,integer,jsonb,jsonb)','db2a144bd77af5c64a72f28cf81fa4f8',false,'i',false,'jsonb','plpgsql',array['p_pool','p_code','p_version','p_definition','p_recipients']::text[],0,false,'u',false),
('public.vp_formula_result_guard()','c0e42b906d2a4198ee95ce82ab1cdf5a',true,'v',false,'trigger','plpgsql',null::text[],0,false,'u',false),
('public.vp_received_frozen(jsonb)','4a6e39b62924cfb5cc6da2cbe209f96f',false,'i',false,'jsonb','sql',array['p_source']::text[],0,false,'u',false),
('public.vp_received_lock(uuid,uuid)','6ea0cee2f0d2bad0d46263ca6d11c6fd',true,'v',false,'void','plpgsql',array['p_payment_id','p_direct_id']::text[],0,false,'u',false),
('public.save_finance_vp_received_distribution(uuid,uuid,uuid,integer,jsonb,jsonb,text)','845627702267502da870422c3f9f2b61',true,'v',false,'uuid','plpgsql',array['p_payment_id','p_direct_id','p_expected_id','p_expected_version','p_source','p_choices','p_note']::text[],0,false,'u',false)),
 prerequisite_facts as(select e.*,p.oid,md5(p.prosrc) as actual_hash,p.prosecdef,p.provolatile,p.proconfig,p.prokind,p.prorettype,p.proretset,l.lanname,p.proargnames,p.pronargdefaults,p.proisstrict,p.proparallel,p.proleakproof from prerequisite_functions e left join pg_proc p on p.oid=to_regprocedure(e.signature) left join pg_language l on l.oid=p.prolang),
 prerequisite_differences as(select * from prerequisite_facts where oid is null or actual_hash is distinct from hash or prosecdef is distinct from security_definer or provolatile::text is distinct from volatility or prokind<>'f' or proconfig is distinct from array['search_path=public']
 or prorettype is distinct from to_regtype(return_type) or proretset or lanname is distinct from language or proargnames is distinct from argument_names or pronargdefaults is distinct from default_count or proisstrict is distinct from is_strict or proparallel::text is distinct from parallel or proleakproof is distinct from leakproof),protected as(select jsonb_build_object('finance_payments',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_payments r),
'finance_payment_invoice_allocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_payment_invoice_allocations r),
'finance_payment_effective_invoice_allocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_payment_effective_invoice_allocations r),
'finance_payment_wht_components',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_payment_wht_components r),
'finance_payment_allocation_reallocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_payment_allocation_reallocations r),
'finance_payment_audit_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_payment_audit_events r),
'finance_invoices',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_invoices r),
'finance_invoice_items',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_invoice_items r),
'finance_invoice_audit_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_invoice_audit_events r),
'finance_invoice_settlement_summary',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_invoice_settlement_summary r),
'finance_cash_transactions',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_cash_transactions r),
'finance_account_opening_balances',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_account_opening_balances r),
'finance_cash_transaction_audit_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_cash_transaction_audit_events r),
'finance_company_ledger',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_company_ledger r),
'finance_compensation_batches',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_compensation_batches r),
'finance_compensation_allocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_compensation_allocations r),
'finance_receipts',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_receipts r),
'finance_receipt_invoice_allocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_receipt_invoice_allocations r),
'finance_receipt_audit_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_receipt_audit_events r),
'finance_tax_invoices',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_tax_invoices r),
'finance_tax_invoice_items',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_tax_invoice_items r),
'finance_tax_point_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_tax_point_events r),
'finance_combined_documents',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_combined_documents r),
'finance_combined_document_audit_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_combined_document_audit_events r),
'finance_document_counters',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_document_counters r),
'finance_payment_money_allocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_payment_money_allocations r),
'finance_payment_money_allocation_audit',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_payment_money_allocation_audit r),
'finance_vp_revenue_distributions',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_vp_revenue_distributions r),
'finance_vp_revenue_distribution_audit',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_vp_revenue_distribution_audit r),
'finance_direct_money_receipts',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_direct_money_receipts r),
'finance_direct_money_receipt_audit',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by to_jsonb(r)::text),'[]')::text) from public.finance_direct_money_receipt_audit r)) as hashes),checks(name,passed) as(values
 ('exact_upstream_functions',not exists(select 1 from prerequisite_differences)),
 ('048_namespace_unused',to_regclass('public.finance_payable_entitlement_sources') is null and to_regclass('public.finance_payable_entitlements') is null and to_regclass('public.finance_payable_entitlement_audit') is null
  and not exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname in('payable_frozen_components','payable_assert_distribution','payable_materialize','payable_assert_unpaid_contract','payable_distribution_transition','payable_immutable','payable_integrity','ensure_finance_payable_entitlements','get_finance_payable_entitlements'))
  and not exists(select 1 from pg_trigger where tgrelid='public.finance_vp_revenue_distributions'::regclass and tgname like 'payable_%'))
 ) select (select jsonb_object_agg(name,passed order by name) from checks) as checks,
 (select coalesce(jsonb_agg(name order by name) filter(where passed is distinct from true),'[]') from checks) as failed_checks,
 (select bool_and(passed is true) from checks) as payable_entitlement_foundation_preflight_pass,
 (select hashes from protected) as upstream_evidence_hashes,
 '[]'::jsonb as catalog_differences,
 (select coalesce(jsonb_agg(to_jsonb(d)),'[]') from prerequisite_differences d) as prerequisite_differences,
 '[]'::jsonb as function_differences,
 jsonb_build_object('finalized_distributions',(select count(*) from finance_vp_revenue_distributions where status='finalized'),
 'legacy_ledger_rows',(select count(*) from finance_company_ledger),'compensation_rows',(select count(*) from finance_compensation_allocations),
 'cash_rows',(select count(*) from finance_cash_transactions),'opening_rows',(select count(*) from finance_account_opening_balances)
 ) as observability_only,
 current_setting('server_version_num')::integer as server_version_num;
