-- ONE SELECT-only statement, ONE result row. No lifecycle calls or business writes.
-- Compare protected_evidence_hashes between preflight and verification.
-- Mandatory human gate: change FALSE only after confirming no external VP-RTI use/reservations.
with manual_gate as (select false as external_vp_rti_unused_confirmed),
 expected_functions(signature,hash,callable,security_definer,volatility) as (values ('public.save_finance_billable_charge_draft(uuid,uuid,bigint,uuid,text,text,jsonb,text,numeric,text,numeric,text,date,text,text,numeric,text)','3f9b98e1e6dab5c2e076cb3edf5d3e99',false,true,'v'),
('public.mark_finance_billable_charge_ready(uuid,boolean)','b726c01090e397c0f9db155377986aa8',false,true,'v'),
('public.apply_finance_quotation_draft_item_tax_modes(uuid,jsonb)','a4b4ac97d7cff139ab943a5b5c542c50',true,true,'v'),
('public.create_finance_quotation_draft_atomic_v3(uuid,bigint,uuid,date,date,text,text,text,text,text,text,text,text,text,jsonb,jsonb,jsonb,jsonb,text,text,jsonb)','5709bc308b5966bd3cae22991b67ab50',true,true,'v'),
('public.freeze_finance_quotation_commercial_terms_v2()','a6c8001adf967b6c2e405253bce1b9cb',false,true,'v'),
('public.build_finance_receipt_source(uuid)','1fe91b4d85e36bdc913b5427f5a8e270',false,true,'v'),
('public.create_finance_receipt_draft_from_payment(uuid,boolean)','e7a845489934cd709a195c597184da7b',false,true,'v'),
('public.refresh_finance_receipt_draft(uuid)','99c9e30d64fffcb396dff606b527d856',false,true,'v'),
('public.issue_finance_receipt(uuid,boolean,jsonb)','4bba2218365fa335a69c65a563c86f03',false,true,'v'),
('public.cancel_finance_receipt_draft(uuid,text)','5322719551e81b50a970e62e100e45f3',false,true,'v'),
('public.void_finance_receipt(uuid,text,boolean)','1cd5e5f8e8b1e790452daabc70ac7973',false,true,'v'),
('public.generate_finance_document_no(text,date)','ab7482a8fee260d784ee579184d59517',false,true,'v'),
('public.document_logo_evidence(text)','a76bf15714d1c4811e7845033b4afe72',false,true,'v'),
('public.build_finance_tax_invoice_source(uuid)','be385f81fd68a12a3929901550ae7106',false,true,'v'),
('public.finance_tax_invoice_draft_snapshot(jsonb,jsonb,date)','e49e30e3642346e411eb479c3c172521',false,false,'i'),
('public.finance_tax_invoice_issue_blockers(jsonb)','9956fcd2141247a996e3ac72600eff67',false,false,'i'),
('public.get_finance_tax_invoice_eligibility(uuid)','d1517db4abb2c4437225928bee6c8173',false,true,'v'),
('public.create_finance_tax_invoice_draft(uuid)','36460837a51d8bf25e3c15c8071cccf8',false,true,'v'),
('public.save_finance_tax_invoice_draft(uuid,date,jsonb,timestamptz)','982f39ad0345366279a9c49b45a081e3',false,true,'v'),
('public.refresh_finance_tax_invoice_draft(uuid,timestamptz)','dde80410373f2c781a6900b8edc2bbfd',false,true,'v'),
('public.issue_finance_tax_invoice(uuid,jsonb,boolean,boolean)','82817a02817e85f05d992ab05ad3f183',false,true,'v'),
('public.cancel_finance_tax_invoice_draft(uuid,text)','f8b815d6f05e1b217e816a1db65fb4b1',false,true,'v'),
('public.validate_finance_tax_invoice_integrity()','b67d9db41ffb7c4407f62ce5f523eed6',false,true,'v')),
 function_facts as (select e.*,p.oid,md5(p.prosrc)=e.hash as exact_body,p.proconfig,p.prosecdef,p.provolatile,
   coalesce(has_function_privilege('authenticated',p.oid,'EXECUTE'),false) as authenticated_execute,
   coalesce(has_function_privilege('anon',p.oid,'EXECUTE'),false) as anon_execute
 from expected_functions e left join pg_proc p on p.oid=to_regprocedure(e.signature)), protected_payment as (select * from public.finance_payments where id='9e2f601e-13ef-4165-8e2c-1887c3ad8861'),
 protected_invoice as (select * from public.finance_invoices where id='74461042-e3ba-4922-9b64-55aac9ebd8aa'),
 protected_receipt as (select * from public.finance_receipts where id='a76cd43d-fe52-4008-ade1-f1d79a9f27bf'),
 protected_checks(name,passed) as (values
 ('protected_payment',(select count(*)=1 and coalesce(bool_and(status='confirmed' and cash_amount=4859.81 and wht_amount=140.19 and settlement_amount=5000),false) from protected_payment)),
 ('protected_invoice',(select count(*)=1 and coalesce(bool_and(document_status='issued' and invoice_no='VP-IV-202609-000003' and total_amount=5000 and amount_before_vat=4672.90 and vat_amount=327.10),false) from protected_invoice)),
 ('protected_receipt',(select count(*)=1 and coalesce(bool_and(status='issued' and receipt_no='VP-RC-202609-000001' and payment_id='9e2f601e-13ef-4165-8e2c-1887c3ad8861' and issued_snapshot_json->>'schema_version'='2'),false) from protected_receipt)),
 ('no_cash_cutover',not exists(select 1 from public.finance_cash_transactions) and not exists(select 1 from public.finance_account_opening_balances))
 ),
 checks(name,passed) as (select * from protected_checks union all select * from (values
 ('040_objects_absent',to_regclass('public.finance_combined_documents') is null and to_regclass('public.finance_combined_document_audit_events') is null and to_regprocedure('public.create_finance_combined_document_draft(uuid,boolean,boolean)') is null),
 ('predecessor_functions_exact',(select bool_and(oid is not null and exact_body) from function_facts)),
 ('no_prior_rti_profile',not exists(select 1 from public.document_numbering_profiles where document_type='receipt_tax_invoice' or display_prefix='VP-RTI')),
 ('no_prior_rti_counter',not exists(select 1 from public.finance_document_counters where doc_type='receipt_tax_invoice' or prefix like 'VP-RTI-%')),
 ('prospective_columns_absent',not exists(select 1 from information_schema.columns where table_schema='public' and column_name in ('combined_document_id','vat_treatment_json') and table_name in ('finance_receipts','finance_tax_invoices','finance_quotation_items','finance_fee_agreement_items','finance_billing_installment_items','finance_billable_charges','finance_invoice_items'))),
 ('no_existing_tax_documents',not exists(select 1 from public.finance_tax_invoices)),
 ('standalone_profiles_compatible',(select count(*)=2 and bool_and(period_scope='monthly' and sequence_width=6 and is_active and display_prefix=case document_type when 'receipt' then 'VP-RC' else 'VP-TI' end) from public.document_numbering_profiles where document_type in ('receipt','tax_invoice'))),
 ('external_manual_vp_rti_gate',(select external_vp_rti_unused_confirmed from manual_gate))
 ) x(name,passed)) select (select jsonb_object_agg(name,passed order by name) from checks) as checks,
 (select coalesce(jsonb_agg(name order by name) filter(where passed is distinct from true),'[]') from checks) as failed_checks,
 (select bool_and(passed is true) from checks) as combined_receipt_tax_invoice_preflight_pass,
 jsonb_build_object('payment',(select md5(to_jsonb(p)::text) from protected_payment p),'invoice',(select md5(to_jsonb(i)::text) from protected_invoice i),
   'receipt',(select md5((to_jsonb(r)-'combined_document_id')::text) from protected_receipt r)) as protected_evidence_hashes,
 true as manual_external_number_check_required,
 (select coalesce(jsonb_agg(signature),'[]') from function_facts where oid is null or exact_body is distinct from true) as predecessor_differences;
