-- ONE SELECT-only statement / ONE row. No application RPCs or mutations.
-- STOP on failed_checks. Compare upstream_evidence_hashes before/after apply.
-- No fixed Ledger/Compensation/Payment row-count baseline. No cutover or receipt backfill.
with expected_functions(signature,hash,security_definer,volatility,is_new,return_type,language,argument_names,default_count,is_strict,parallel,leakproof) as (values ('public.confirm_finance_payment(uuid,boolean)','deae5aa01dc48eb0faa64afa82bca8b7',true,'v',false,'uuid','plpgsql',array['p_payment_id','p_confirmation_acknowledged']::text[],0,false,'u',false),
('public.reverse_finance_payment(uuid,text)','ef2a35fb3570b503f7447614885b81b2',true,'v',false,'uuid','plpgsql',array['p_payment_id','p_reason']::text[],0,false,'u',false),
('public.current_user_can_view_finance_cash_transactions()','4752ce3f50858cae684320fc48d3d9c1',true,'v',false,'boolean','sql',null::text[],0,false,'u',false),
('public.current_user_can_view_finance_cash_bank_account(uuid)','d6d07f8f1bf3e284372471729c93ffff',true,'v',false,'boolean','sql',array['p_bank_account_id']::text[],0,false,'u',false),
('public.enforce_finance_cash_transaction_lifecycle()','25b0d232b75fb166cfd7aed4db9208ac',true,'v',false,'trigger','plpgsql',null::text[],0,false,'u',false),
('public.validate_finance_cash_transaction_integrity(uuid)','44c9100afcaae32cdaa42a9ef69104aa',true,'v',false,'void','plpgsql',array['p_cash_transaction_id']::text[],0,false,'u',false),
('public.enforce_finance_opening_balance_lifecycle()','17376bfec1cf4029b366be16cfc73fc5',true,'v',false,'trigger','plpgsql',null::text[],0,false,'u',false),
('public.validate_finance_opening_balance_integrity(uuid)','9fa53788f776c9d47c32cedc08fcef1d',true,'v',false,'void','plpgsql',array['p_opening_balance_id']::text[],0,false,'u',false),
('public.protect_finance_cash_audit_event()','65fbae5a7c161b60242fe8ac96388aff',true,'v',false,'trigger','plpgsql',null::text[],0,false,'u',false),
('public.post_confirmed_payment_to_finance_cash_transaction(uuid)','5cff47abdf1ae86983b201d88cd8e64c',true,'v',false,'jsonb','plpgsql',array['p_payment_id']::text[],0,false,'u',false),
('public.correct_erroneous_finance_payment(uuid,text,boolean)','fe65b1aa1657e9c8e093a0b5378b82a2',true,'v',false,'uuid','plpgsql',array['p_payment_id','p_reason','p_acknowledged']::text[],0,false,'u',false),
('public.money_allocation_admin()','b6c3626891400d6817c575526fedd1c0',true,'s',false,'boolean','sql',null::text[],0,false,'u',false),
('public.direct_money_payload(jsonb)','93a1f42cb8b6e7ae05182558cf4f1e40',true,'s',false,'jsonb','plpgsql',array['p_input']::text[],0,false,'u',false),
('public.direct_money_snapshot(public.finance_direct_money_receipts)','287a1077274b2ebf3889f7cda0de3d7c',true,'s',false,'jsonb','sql',array['p']::text[],0,false,'u',false),
('public.save_finance_direct_money_receipt(uuid,integer,jsonb)','238cad995c70864a383522f5626f4b26',true,'v',false,'uuid','plpgsql',array['p_id','p_expected_version','p_input']::text[],0,false,'u',false),
('public.transition_finance_direct_money_receipt(uuid,integer,text,boolean,text)','621fd126935fcfac21556d0ac95a44ee',true,'v',false,'uuid','plpgsql',array['p_id','p_expected_version','p_action','p_acknowledged','p_reason']::text[],0,false,'u',false),
('public.direct_money_guard()','f6ca48044ecbdb35d1aadd1191bcbe0e',true,'v',false,'trigger','plpgsql',null::text[],0,false,'u',false),
('public.direct_money_integrity()','9750729c08f92127574d751654214993',true,'v',false,'trigger','plpgsql',null::text[],0,false,'u',false)),
 function_facts as(select e.*,p.oid,md5(p.prosrc) as actual_hash,p.prosecdef,p.provolatile,p.proconfig,p.prokind,p.prorettype,p.proretset,l.lanname,p.proargnames,p.pronargdefaults,p.proisstrict,p.proparallel,p.proleakproof from expected_functions e left join pg_proc p on p.oid=to_regprocedure(e.signature) left join pg_language l on l.oid=p.prolang),
 function_differences as(select * from function_facts where oid is null or actual_hash is distinct from hash or prosecdef is distinct from security_definer or provolatile::text is distinct from volatility or prokind<>'f' or proconfig is distinct from array['search_path=public']
 or prorettype is distinct from to_regtype(return_type) or proretset or lanname is distinct from language or proargnames is distinct from argument_names or pronargdefaults is distinct from default_count or proisstrict is distinct from is_strict or proparallel::text is distinct from parallel or proleakproof is distinct from leakproof),protected as(select jsonb_build_object('finance_payments',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_payments r),
'finance_payment_invoice_allocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_payment_invoice_allocations r),
'finance_payment_effective_invoice_allocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_payment_effective_invoice_allocations r),
'finance_payment_wht_components',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_payment_wht_components r),
'finance_payment_allocation_reallocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_payment_allocation_reallocations r),
'finance_payment_audit_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_payment_audit_events r),
'finance_invoices',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_invoices r),
'finance_invoice_items',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_invoice_items r),
'finance_invoice_audit_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_invoice_audit_events r),
'finance_invoice_settlement_summary',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_invoice_settlement_summary r),
'finance_cash_transactions',(select md5(coalesce(jsonb_agg(to_jsonb(r)-array['cash_location_id','source_direct_money_receipt_id','source_snapshot_json'] order by (to_jsonb(r)-array['cash_location_id','source_direct_money_receipt_id','source_snapshot_json'])::text),'[]')::text) from public.finance_cash_transactions r),
'finance_account_opening_balances',(select md5(coalesce(jsonb_agg(to_jsonb(r)-'cash_location_id' order by (to_jsonb(r)-'cash_location_id')::text),'[]')::text) from public.finance_account_opening_balances r),
'finance_cash_transaction_audit_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_cash_transaction_audit_events r),
'finance_account_opening_balance_audit_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_account_opening_balance_audit_events r),
'finance_company_ledger',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_company_ledger r),
'finance_compensation_batches',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_compensation_batches r),
'finance_compensation_allocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_compensation_allocations r),
'finance_receipts',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_receipts r),
'finance_receipt_invoice_allocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_receipt_invoice_allocations r),
'finance_receipt_audit_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_receipt_audit_events r),
'finance_tax_invoices',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_tax_invoices r),
'finance_tax_invoice_items',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_tax_invoice_items r),
'finance_tax_point_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_tax_point_events r),
'finance_combined_documents',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_combined_documents r),
'finance_combined_document_audit_events',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_combined_document_audit_events r),
'finance_document_counters',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_document_counters r),
'finance_payment_money_allocations',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_payment_money_allocations r),
'finance_payment_money_allocation_audit',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_payment_money_allocation_audit r),
'finance_vp_revenue_distributions',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_vp_revenue_distributions r),
'finance_vp_revenue_distribution_audit',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_vp_revenue_distribution_audit r),
'finance_direct_money_receipts',(select md5(coalesce(jsonb_agg(to_jsonb(r)-'receiving_cash_location_id' order by (to_jsonb(r)-'receiving_cash_location_id')::text),'[]')::text) from public.finance_direct_money_receipts r),
'finance_direct_money_receipt_audit',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_direct_money_receipt_audit r),
'finance_payable_entitlement_sources',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_payable_entitlement_sources r),
'finance_payable_entitlements',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_payable_entitlements r),
'finance_payable_entitlement_audit',(select md5(coalesce(jsonb_agg(to_jsonb(r) order by (to_jsonb(r))::text),'[]')::text) from public.finance_payable_entitlement_audit r)) as hashes),checks(name,passed) as(values
 ('upstream_functions_exact',not exists(select 1 from function_differences)),('no_cash_cutover',not exists(select 1 from finance_cash_transactions) and not exists(select 1 from finance_account_opening_balances)
 and not exists(select 1 from finance_cash_transaction_audit_events) and not exists(select 1 from finance_account_opening_balance_audit_events)),
 ('049_namespace_unused',to_regclass('public.finance_cash_locations') is null and to_regclass('public.finance_treasury_accounts') is null and to_regclass('public.finance_treasury_balances') is null
 and not exists(select 1 from pg_proc where pronamespace='public'::regnamespace and (proname like 'treasury_%' or proname in('treasury_direct_input_location','treasury_can_view','treasury_location_active','treasury_source','treasury_post_source','treasury_confirm_direct','treasury_source_reversal_guard','materialize_finance_treasury_source','save_finance_treasury_opening','confirm_finance_treasury_opening','get_finance_treasury','direct_money_payload_before_treasury','direct_money_snapshot_before_treasury')))
 and not exists(select 1 from pg_attribute where attrelid in('finance_cash_transactions'::regclass,'finance_account_opening_balances'::regclass,'finance_direct_money_receipts'::regclass) and attname in('cash_location_id','source_direct_money_receipt_id','source_snapshot_json','receiving_cash_location_id') and not attisdropped))
 ) select (select jsonb_object_agg(name,passed is true order by name) from checks) as checks,
 (select coalesce(jsonb_agg(name order by name) filter(where passed is distinct from true),'[]') from checks) as failed_checks,
 (select bool_and(passed is true) from checks) as treasury_cashbook_foundation_preflight_pass,
 (select hashes from protected) as upstream_evidence_hashes,
 (select coalesce(jsonb_agg(to_jsonb(d)),'[]') from function_differences d) as function_differences,
 '[]'::jsonb as catalog_differences,
 jsonb_build_object('cash_rows',(select count(*) from finance_cash_transactions),'opening_rows',(select count(*) from finance_account_opening_balances),
 'legacy_ledger_rows',(select count(*) from finance_company_ledger),'compensation_rows',(select count(*) from finance_compensation_allocations),
 'payment_rows',(select count(*) from finance_payments),'direct_money_rows',(select count(*) from finance_direct_money_receipts)) as observability,
 current_setting('server_version_num')::integer as catalog_server_version_num;
