"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { useParams, useSearchParams } from "next/navigation";
import { QuotationGuard } from "../../../quotations/shared";
import { supabase } from "../../../../../lib/supabase";

type Json = Record<string, unknown>;
type Agreement = { id: string; agreement_no: string | null; title: string; status: string; language_code: string; effective_date: string | null; commencement_date: string | null; expiry_date: string | null; currency: string; amount_before_tax: number | string; vat_amount: number | string; total_amount: number | string; client_snapshot_json: Json | null; matter_snapshot_json: Json | null; source_document_snapshot_json: Json | null; commercial_terms_snapshot_json: Json | null; legal_terms_json: Json | null; signatories_json: unknown[] | null; custom_clauses_json: unknown[] | null; selected_template_version_id: string | null; resolved_document_snapshot_json: Json | null; signed_document_snapshot_json: Json | null; created_at: string };
type Item = { id: string; description: string; quantity: number | string; unit_price: number | string; vat_applicable: boolean; vat_rate: number | string; amount_before_tax: number | string; vat_amount: number | string; line_total: number | string; sort_order: number };

const asObject = (value: unknown): Json => value && typeof value === "object" && !Array.isArray(value) ? value as Json : {};
const string = (value: unknown, fallback = "-") => typeof value === "string" && value.trim() ? value : fallback;
const amount = (value: unknown) => Number(value || 0);
const money = (value: unknown, currency = "THB") => `${amount(value).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${currency}`;
const date = (value: unknown) => typeof value === "string" && value ? value.slice(0, 10) : "-";
const isGeneratedInstallmentTitle = (value: unknown, installmentNo: number) => { const title = string(value, "").toLowerCase().replace(/\s+/g, " ").trim(); return !title || new RegExp(`^(งวดที่\\s*${installmentNo}|installment\\s*${installmentNo})(\\s*[/—-]\\s*(งวดที่\\s*${installmentNo}|installment\\s*${installmentNo}))?$`, "i").test(title); };
const dueDescription = (installment: Json) => { if (installment.due_date) return `ครบกำหนดวันที่ ${date(installment.due_date)}`; const days = Number(installment.payment_due_days); const period = Number.isFinite(days) && days > 0 ? `ชำระภายใน ${days} วัน` : ""; const trigger = string(installment.trigger_type, ""); if (trigger === "quotation_acceptance") return period ? `${period}นับแต่ลูกค้าตอบรับใบเสนอราคา` : "นับแต่ลูกค้าตอบรับใบเสนอราคา"; if (trigger === "agreement_effective") return period ? `${period}นับแต่สัญญามีผล` : "นับแต่สัญญามีผล"; if (["case_milestone", "recurring_period", "manual"].includes(trigger) && string(installment.trigger_description, "")) return period ? `${period}นับแต่${string(installment.trigger_description)}` : string(installment.trigger_description); return period || string(installment.trigger_description, ""); };

export default function FeeAgreementPreviewPage() {
  const params = useParams(); const id = Array.isArray(params.id) ? params.id[0] : params.id || "";
  return <QuotationGuard>{() => <Preview id={id} />}</QuotationGuard>;
}

function Preview({ id }: { id: string }) {
  const params = useSearchParams(); const printed = useRef(false);
  const [agreement, setAgreement] = useState<Agreement | null>(null); const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => {
    if (!id) { setError("ไม่พบ Fee Agreement"); setLoading(false); return; }
    const header = await supabase.from("finance_fee_agreements").select("id,agreement_no,title,status,language_code,effective_date,commencement_date,expiry_date,currency,amount_before_tax,vat_amount,total_amount,client_snapshot_json,matter_snapshot_json,source_document_snapshot_json,commercial_terms_snapshot_json,legal_terms_json,signatories_json,custom_clauses_json,selected_template_version_id,resolved_document_snapshot_json,signed_document_snapshot_json,created_at").eq("id", id).maybeSingle();
    if (header.error || !header.data) { setError("ไม่สามารถโหลด Fee Agreement ได้"); setLoading(false); return; }
    const itemRes = await supabase.from("finance_fee_agreement_items").select("id,description,quantity,unit_price,vat_applicable,vat_rate,amount_before_tax,vat_amount,line_total,sort_order").eq("fee_agreement_id", id).order("sort_order").order("id");
    if (itemRes.error) setError("ไม่สามารถโหลดรายการค่าบริการได้");
    setAgreement(header.data as Agreement); setItems((itemRes.data || []) as Item[]); setLoading(false);
  }, [id]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { if (params.get("print") === "1" && !loading && agreement && !printed.current) { printed.current = true; window.setTimeout(() => window.print(), 100); } }, [agreement, loading, params]);
  const document = useMemo(() => {
    if (!agreement) return {};
    if (agreement.status === "signed" && agreement.signed_document_snapshot_json) return agreement.signed_document_snapshot_json;
    if (["sent", "signed", "completed", "cancelled"].includes(agreement.status) && agreement.resolved_document_snapshot_json) return agreement.resolved_document_snapshot_json;
    return {};
  }, [agreement]);
  if (loading) return <main style={shell}>Loading Fee Agreement preview...</main>; if (!agreement) return <main style={shell}>{error || "Fee Agreement not found."}</main>;
  const snapAgreement = asObject(document.agreement); const source = asObject(document.source_quotation_snapshot || agreement.source_document_snapshot_json); const commercialSnapshot = asObject(document.commercial_terms || agreement.commercial_terms_snapshot_json); const commercial = asObject(commercialSnapshot.commercial); const legal = asObject(document.legal_terms || agreement.legal_terms_json); const client = asObject(document.source_snapshots ? asObject(document.source_snapshots).client : agreement.client_snapshot_json); const matter = asObject(document.source_snapshots ? asObject(document.source_snapshots).matter : agreement.matter_snapshot_json); const templateSnapshot = asObject(document.template); const snapshotItems = Array.isArray(document.agreement_items) ? document.agreement_items.map(asObject) : [];
  const renderedItems = snapshotItems.length ? snapshotItems : items;
  const signatories = Array.isArray(document.signatories) ? document.signatories : (agreement.signatories_json || []);
  const resolvedClauses = Array.isArray(templateSnapshot.resolved_clause_versions) ? templateSnapshot.resolved_clause_versions : [];
  const customClauses = Array.isArray(agreement.custom_clauses_json) ? agreement.custom_clauses_json : [];
  const clauses = resolvedClauses.length ? resolvedClauses : customClauses;
  const currency = string(snapAgreement.currency, agreement.currency); const total = snapAgreement.totals ? asObject(snapAgreement.totals) : agreement;
  const documentTitle = /^Fee Agreement\s*-\s*/i.test(agreement.title) || !agreement.title.trim() ? "สัญญาว่าจ้างให้บริการทางกฎหมาย" : string(snapAgreement.title, agreement.title);
  const coreLegalTerms = [legal.scope_clarification, legal.client_obligations, legal.firm_obligations, legal.confidentiality, legal.termination_provisions, legal.dispute_jurisdiction];
  const previewIncomplete = ["draft", "under_review"].includes(agreement.status) && (!agreement.agreement_no || !renderedItems.length || !agreement.effective_date || !string(client.name, string(client.display_name, "")) || !signatories.some((entry) => asObject(entry).party === "client") || !signatories.some((entry) => asObject(entry).party === "firm") || (!agreement.selected_template_version_id && !coreLegalTerms.some((value) => string(value, ""))));
  return <main style={shell}><div className="screen-controls" style={controls}><Link href={`/finance/fee-agreements/${agreement.id}`}>Back to Fee Agreement</Link><button type="button" onClick={() => window.print()}>Print</button><span>เพื่อเอกสารที่สะอาด กรุณาปิด Headers and footers ในหน้าต่าง Print</span></div>{previewIncomplete ? <div className="fee-agreement-preview-readiness" style={readinessNotice}>เอกสารฉบับนี้ยังอยู่ระหว่างจัดทำและอาจมีข้อมูลไม่ครบถ้วน</div> : null}
    <article className="fee-agreement-document" style={documentStyle}><header className="fee-agreement-document-header" style={header}><div><div style={brand}>VP</div><strong>บริษัท วีพี พาร์ทเนอร์ จำกัด</strong><div style={muted}>VP Partners Co., Ltd.</div></div><div style={right}><h1 style={titleStyle}>{documentTitle}</h1><div>Fee Agreement</div><div style={docNo}>{string(snapAgreement.agreement_no, agreement.agreement_no || "-")}</div></div></header>
      <section style={infoGrid}><Info title="คู่สัญญา" rows={[["ลูกค้า", string(client.name, string(client.display_name))], ["เลขประจำตัวผู้เสียภาษี", string(client.tax_id)], ["ที่อยู่", string(client.address)], ["เรื่อง/คดี", string(matter.title, string(matter.file_no, string(matter.matter_no)))]]} /><Info title="ข้อมูลเอกสาร" rows={[["สถานะ", string(snapAgreement.status, agreement.status)], ["วันที่สัญญามีผล", date(snapAgreement.effective_date || agreement.effective_date)], ["วันที่เริ่มให้บริการ", date(snapAgreement.commencement_date || agreement.commencement_date)], ["วันที่สิ้นสุดตามกำหนด", date(snapAgreement.expiry_date || agreement.expiry_date)], ["ใบเสนอราคาต้นทาง", string(source.quotation_no)]]} /></section>
      <section style={section}><SectionTitle>ขอบเขตการให้บริการ</SectionTitle><p style={pre}>{string(commercial.scope_of_legal_services, string(legal.scope_clarification, "-"))}</p>{([ ["งานที่รวมอยู่ในค่าบริการ", commercial.included_services], ["งานหรือค่าใช้จ่ายที่ไม่รวม", commercial.excluded_services] ] as Array<[string, unknown]>).filter(([, value]) => value).map(([label, value]) => <div key={label} style={term}><strong>{label}</strong><p style={pre}>{string(value)}</p></div>)}</section>
      <section style={section}><SectionTitle>รายการค่าบริการ</SectionTitle><div style={tableWrap}><table style={table}><thead><tr><th>ลำดับ</th><th>รายละเอียด</th><th>จำนวน</th><th>ราคาต่อหน่วย</th><th>VAT</th><th>ก่อน VAT</th><th>รวม</th></tr></thead><tbody>{renderedItems.map((item, index) => { const itemRow = asObject(item); return <tr key={string(itemRow.id, String(index))}><td>{index + 1}</td><td>{string(itemRow.description)}</td><td>{String(itemRow.quantity || "-")}</td><td>{money(itemRow.unit_price, currency)}</td><td>{itemRow.vat_applicable ? `${itemRow.vat_rate}%` : "ไม่มี VAT"}</td><td>{money(itemRow.amount_before_tax, currency)}</td><td>{money(itemRow.line_total, currency)}</td></tr>; })}</tbody></table></div></section>
      <section style={section}><SectionTitle>เงื่อนไขการชำระเงิน</SectionTitle><PaymentTerms payment={asObject(source.payment_terms || commercialSnapshot.payment_terms)} currency={currency} /></section>
      <section style={section}><SectionTitle>ข้อกำหนดของสัญญา</SectionTitle>{legalEntries(legal).map(([label, value]) => <div key={label} style={term}><strong>{label}</strong><p style={pre}>{string(value)}</p></div>)}</section>
      {clauses.length ? <section style={section}><SectionTitle>ข้อกำหนดเพิ่มเติม</SectionTitle><ClauseList clauses={clauses} /></section> : null}
      <section style={summary}><div>ก่อน VAT <strong>{money(total.amount_before_tax, currency)}</strong></div><div>VAT <strong>{money(total.vat_amount, currency)}</strong></div><div style={grand}>จำนวนเงินตามข้อตกลง <strong>{money(total.total_amount, currency)}</strong></div></section>
      <section style={section}><SectionTitle>ผู้ลงนาม</SectionTitle><SignatoryList rows={signatories} /></section><section style={signatureGrid}><Signature title="ผู้ให้บริการ / สำนักงาน" rows={signatories.filter((entry) => asObject(entry).party === "firm")} /><Signature title="ผู้รับบริการ / ลูกค้า" rows={signatories.filter((entry) => asObject(entry).party === "client")} /></section>
    </article><style jsx global>{`@page { size: A4 portrait; margin: 11mm; } @media print { body { background: #fff !important; } .screen-controls, .fee-agreement-preview-readiness, nav, header:not(.fee-agreement-document-header), aside, button, [role="dialog"] { display: none !important; } .fee-agreement-document { box-shadow: none !important; border: 0 !important; max-width: none !important; margin: 0 !important; padding: 0 !important; } .fee-agreement-document table { width: 100% !important; } .fee-agreement-document tr, .fee-agreement-document section { break-inside: avoid; page-break-inside: avoid; } }`}</style></main>;
}

function Info({ title, rows }: { title: string; rows: Array<[string, string]> }) { return <section style={info}><strong>{title}</strong>{rows.map(([label, value]) => <div key={label} style={infoRow}><span>{label}</span><span>{value}</span></div>)}</section>; }
function SectionTitle({ children }: { children: string }) { return <h2 style={sectionTitle}>{children}</h2>; }
function PaymentTerms({ payment, currency }: { payment: Json; currency: string }) { const installments = Array.isArray(payment.installments) ? payment.installments.map(asObject) : []; if (!installments.length) return <p style={muted}>ยังไม่มีเงื่อนไขการชำระเงินที่บันทึกไว้</p>; return <>{payment.client_summary ? <p style={pre}>{string(payment.client_summary)}</p> : null}<div style={paymentGrid}>{installments.map((installment, index) => { const no = Number(installment.installment_no || index + 1); const customTitle = string(installment.title, ""); const due = dueDescription(installment); return <div key={String(installment.installment_no || index)} style={paymentCard}><strong>งวดที่ {no}</strong>{!isGeneratedInstallmentTitle(customTitle, no) ? <div style={{ color: "#475569", marginTop: 2 }}>{customTitle}</div> : null}<div>จำนวนก่อน VAT: {money(installment.amount_before_tax, currency)}</div><div>VAT: {money(installment.vat_amount, currency)}</div><div>จำนวนรวม: {money(installment.total_amount, currency)}</div>{due ? <div><strong>ครบกำหนด:</strong> {due}</div> : null}{installment.client_note ? <div style={pre}>{string(installment.client_note)}</div> : null}{Array.isArray(installment.items) && installment.items.length ? <div style={{ marginTop: 6 }}><strong>รายการในงวดนี้</strong>{installment.items.map((entry, entryIndex) => { const row = asObject(entry); return <div key={`${string(row.description, "item")}-${entryIndex}`} style={allocated}><span>{string(row.description)}</span><span>{money(row.allocated_total || row.line_total, currency)}</span></div>; })}</div> : null}</div>; })}</div></>; }
function ClauseList({ clauses }: { clauses: unknown[] }) { return <>{clauses.length ? clauses.map((clause, index) => { const entry = asObject(clause); return <div key={String(entry.clause_version_id || index)} style={term}><strong>{string(entry.title, `ข้อกำหนด ${index + 1}`)}</strong><p style={pre}>{string(entry.content, typeof clause === "string" ? clause : "-")}</p></div>; }) : <p style={muted}>-</p>}</>; }
function SignatoryList({ rows }: { rows: unknown[] }) { const entries = rows.map(asObject).filter((row) => string(row.name, string(row.display_name, "")) !== "").sort((left, right) => Number(left.sort_order || 0) - Number(right.sort_order || 0)); return entries.length ? <div>{entries.map((row, index) => <div key={`${string(row.name, String(index))}-${index}`} style={term}><strong>{string(row.name, string(row.display_name))}</strong><div>{string(row.capacity, string(row.title, "-"))} · {partyLabel[string(row.party, string(row.side, "other"))] || string(row.party, string(row.side, "อื่น ๆ"))}</div></div>)}</div> : <p style={muted}>ยังไม่มีข้อมูลผู้ลงนาม</p>; }
function Signature({ title, rows }: { title: unknown; rows: unknown[] }) { const signer = rows.map(asObject)[0] || {}; return <div style={signature}><strong>{String(title)}</strong><div style={line} /><div>ชื่อ: {string(signer.name, string(signer.display_name))}</div><div>ตำแหน่ง/ฐานะ: {string(signer.capacity, string(signer.title))}</div><div>วันที่: ____________________</div></div>; }
function legalEntries(legal: Json) { const labels: Record<string, string> = { client_obligations: "หน้าที่ของลูกค้า", firm_obligations: "หน้าที่ของสำนักงาน", exclusions: "งานที่ไม่รวม", expenses_disbursements: "ค่าใช้จ่ายและเงินทดรอง", confidentiality: "การรักษาความลับ", termination_provisions: "การเลิกสัญญา", dispute_jurisdiction: "กฎหมายที่ใช้บังคับ/เขตอำนาจ", additional_terms: "ข้อกำหนดเพิ่มเติม" }; return Object.entries(labels).filter(([key]) => legal[key]).map(([key, label]) => [label, legal[key]] as [string, unknown]); }
const partyLabel: Record<string, string> = { client: "ลูกค้า", firm: "สำนักงาน", witness: "พยาน", other: "อื่น ๆ" };

const shell = { maxWidth: 1180, margin: "0 auto", padding: 24 }; const controls = { display: "flex", gap: 12, flexWrap: "wrap" as const, alignItems: "center", marginBottom: 16, color: "#475569", fontSize: 14 }; const readinessNotice = { maxWidth: 820, margin: "0 auto 14px", background: "#fff7ed", borderLeft: "3px solid #f59e0b", color: "#92400e", padding: "10px 12px", fontSize: 14 }; const documentStyle = { maxWidth: 820, margin: "0 auto", background: "#fff", border: "1px solid #e5e7eb", boxShadow: "0 6px 20px rgb(15 23 42 / .08)", padding: 36, color: "#1f2937" }; const header = { display: "flex", justifyContent: "space-between", gap: 24, borderBottom: "3px solid #15803d", paddingBottom: 18, marginBottom: 20 }; const brand = { display: "inline-grid", placeItems: "center", width: 36, height: 36, marginRight: 8, background: "#15803d", color: "#fff", fontWeight: 800 }; const right = { textAlign: "right" as const }; const titleStyle = { color: "#15803d", margin: 0, fontSize: 27 }; const docNo = { marginTop: 8, fontWeight: 700 }; const muted = { color: "#64748b", fontSize: 13 }; const infoGrid = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(280px,1fr))", gap: 14, marginBottom: 20 }; const info = { border: "1px solid #e5e7eb", padding: 14 }; const infoRow = { display: "grid", gridTemplateColumns: "120px minmax(0,1fr)", gap: 8, marginTop: 7, fontSize: 13, overflowWrap: "anywhere" as const }; const section = { margin: "20px 0", breakInside: "avoid" as const }; const sectionTitle = { color: "#15803d", fontSize: 17, borderBottom: "1px solid #bbf7d0", paddingBottom: 6, margin: "0 0 10px" }; const pre = { whiteSpace: "pre-wrap" as const, lineHeight: 1.6, margin: "7px 0" }; const term = { padding: "8px 0", borderBottom: "1px solid #e5e7eb" }; const tableWrap = { overflowX: "auto" as const }; const table = { width: "100%", borderCollapse: "collapse" as const, fontSize: 13 }; const summary = { marginLeft: "auto", maxWidth: 380, background: "#f0fdf4", border: "1px solid #bbf7d0", padding: 14, display: "grid", gap: 8, textAlign: "right" as const, breakInside: "avoid" as const }; const grand = { borderTop: "1px solid #86efac", paddingTop: 8, fontSize: 16, color: "#166534" }; const signatureGrid = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(260px,1fr))", gap: 26, marginTop: 34, breakInside: "avoid" as const }; const signature = { minHeight: 130, borderTop: "1px solid #94a3b8", paddingTop: 10, fontSize: 13, lineHeight: 1.8 }; const line = { height: 48, borderBottom: "1px solid #64748b", marginBottom: 8 }; const paymentGrid = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(240px,1fr))", gap: 12 }; const paymentCard = { border: "1px solid #e5e7eb", borderRadius: 6, padding: 12, lineHeight: 1.6 }; const allocated = { display: "flex", justifyContent: "space-between", gap: 10, padding: "3px 0", borderBottom: "1px solid #f1f5f9" };
