export const labels={
 title:['คลังภาพระบบ','Visual Asset Library'],subtitle:['จัดเก็บและจัดการภาพสำหรับงานนอกคดีและคดี ใช้ข้อมูลขั้นตอนแบบซ้อนทับภายหลัง','Shared artwork for Non-Litigation and Case. Stage data stays in the interface.'],
 upload:['อัปโหลดภาพ','Upload image'],refresh:['รีเฟรช','Refresh'],all:['ทั้งหมด','All'],search:['ค้นหาชื่อ คีย์ ธีม หรือแท็ก','Search name, key, theme or tags'],type:['ประเภท','Type'],scope:['ขอบเขตการใช้','Scope'],status:['สถานะ','Status'],theme:['ธีม','Theme'],tags:['แท็ก (คั่นด้วยจุลภาค)','Tags (comma separated)'],
 journey:['แผนการดำเนินงาน','Journey'],background:['ภาพพื้นหลัง','Background'],banner:['แบนเนอร์','Banner'],illustration:['ภาพประกอบ','Illustration'],non_litigation:['งานนอกคดี','Non-Litigation'],case:['คดี','Case'],both:['ใช้ร่วมกัน','Both'],draft:['ฉบับร่าง','Draft'],active:['ใช้งาน','Active'],retired:['เลิกใช้','Retired'],
 key:['คีย์ภาพ','Artwork key'],name_th:['ชื่อภาษาไทย','Thai name'],name_en:['ชื่อภาษาอังกฤษ','English name'],save:['บันทึก','Save'],cancel:['ยกเลิก','Cancel'],edit:['แก้ไขข้อมูล','Edit metadata'],remove:['ลบภาพ','Delete image'],retire:['เลิกใช้ภาพ','Retire image'],close:['ปิด','Close'],
 empty:['ยังไม่มีภาพที่ตรงกับตัวกรอง','No matching artwork'],emptyHint:['เพิ่มภาพต้นฉบับ ระบบจะปรับขนาดและสร้างภาพย่อให้','Upload an original image. Resizing and gallery thumbnails are automatic.'],choose:['เลือกภาพเพื่อดูรายละเอียด','Select an image to preview'],file:['ไฟล์ภาพ','Image file'],fileHint:['JPG, PNG หรือ WebP ไม่เกิน 20 MB • ด้านยาวสูงสุด 2,560 พิกเซล • คงสัดส่วนเดิม','JPG, PNG or WebP up to 20 MB · Maximum long edge 2,560 px · Original aspect ratio'],
 rule:['ภาพต้องไม่มีข้อความขั้นตอน สถานะ วันที่ หรือบุคคลฝังในภาพ','Artwork must not contain baked-in stage text, status, dates or users.'],attest:['ยืนยันว่าภาพพร้อมใช้ซ้อนทับข้อมูลแบบไดนามิก','I confirm this artwork is suitable for dynamic data overlays.'],
 preview:['ดูภาพและพื้นที่ซ้อนทับ','Image & safe area preview'],safe:['ทดลองพื้นที่ซ้อนทับ','Safe area preview'],stages:['จำนวนขั้นตอน','Stage count'],stage:['ขั้นตอน','Stage'],safeHint:['ข้อมูลตัวอย่างเพื่อทดสอบพื้นที่เท่านั้น ไม่บันทึกหรือแก้ไขแผนงานจริง','Sample overlays only. This does not save or change any real Journey.'],off:['ไม่แสดง','Off'],
 mapping:['การเลือกภาพตามตระกูลแผนงาน','Journey family mapping'],family:['คีย์ตระกูลแผนงาน','Journey family key'],mappingHint:['กำหนดตระกูลแผนงาน ไม่ใช่ประเภทงาน คีย์ universal ใช้เป็นภาพสำรองร่วมกัน','Map a Journey family, not a Work Type. The universal key provides the shared fallback.'],fallback:['ภาพสำรองร่วมกัน','Universal fallback'],noFallback:['ยังไม่ได้กำหนดภาพสำรอง ระบบจะใช้พื้นหลังเรียบ','No universal fallback configured. A neutral background is used.'],map:['กำหนดภาพ','Assign artwork'],unmap:['ยกเลิกการกำหนด','Remove mapping'],
 deleteHint:['ลบไฟล์ต้นฉบับที่ปรับแล้วและภาพย่อถาวร ภาพที่ถูกกำหนดใช้งานต้องยกเลิกการกำหนดก่อน','Permanently deletes the optimized master and thumbnail. Remove mappings before deleting.'],confirmKey:['พิมพ์คีย์ภาพเพื่อยืนยัน','Type the artwork key to confirm'],pending:['รอล้างไฟล์ให้เสร็จ กดลบเพื่อทำต่อ','File cleanup pending. Retry delete to finish.'],busy:['กำลังดำเนินการ…','Working…'],success:['บันทึกเรียบร้อย','Saved successfully'],loading:['กำลังโหลด…','Loading…'],error:['ดำเนินการไม่สำเร็จ กรุณารีเฟรชแล้วลองใหม่','Unable to complete. Refresh and try again.'],conflict:['ข้อมูลเปลี่ยนแล้ว กรุณารีเฟรชก่อนแก้ไข','This record changed. Refresh before editing.'],inUse:['ภาพนี้ยังถูกกำหนดใช้งาน กรุณาเปลี่ยนหรือลบ mapping ก่อน','Artwork is mapped. Replace or remove its mappings first.'],invalid:['กรุณาตรวจข้อมูลและยืนยันข้อกำหนดภาพ','Check the fields and confirm the artwork requirements.'],imageError:['ไฟล์ไม่ใช่ภาพที่รองรับ ภาพเสียหาย มีภาพเคลื่อนไหว หรือเกิน 40 ล้านพิกเซล','Unsupported, corrupt, animated or over 40-megapixel image.'],sizeError:['รองรับ JPG, PNG และ WebP ขนาดไม่เกิน 20 MB','Use JPG, PNG or WebP up to 20 MB.'],denied:['สิทธิ์ไม่เพียงพอ ต้องเป็นผู้ดูแลระบบที่เปิดใช้งาน','Access denied. Active Admin required.'],limit:['คลังภาพรองรับสูงสุด 50 ภาพ','The library supports up to 50 images.'],dimensions:['ขนาดภาพ','Dimensions'],size:['ขนาดไฟล์','File size'],ratio:['อัตราส่วน','Aspect ratio'],count:['ภาพ','images'],private:['พื้นที่จัดเก็บส่วนตัว • ผู้ดูแลระบบเท่านั้น','Private storage · Admin only'],
} as const;
export type VisualLabel=keyof typeof labels;
export const assetText=(locale:string,key:VisualLabel)=>labels[key][locale==='en'?1:0];
export function assetError(locale:string,error:unknown){const code=error instanceof Error?error.message:'';return assetText(locale,code==='VISUAL_CONFLICT'?'conflict':code==='VISUAL_IN_USE'?'inUse':code==='VISUAL_IMAGE_INVALID'?'imageError':code==='VISUAL_FILE_SIZE'?'sizeError':code==='VISUAL_INVALID'?'invalid':code==='VISUAL_LIMIT'?'limit':/UNAUTHORIZED|FORBIDDEN/.test(code)?'denied':'error');}
