'use client';
/* eslint-disable @next/next/no-img-element -- Private, short-lived Storage URLs; contain preserves artwork. */
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {Image as ImageIcon,Upload,RefreshCw,Search,ShieldCheck,SlidersHorizontal,X,Trash2,Pencil,ScanEye,Copy,Check} from 'lucide-react';
import AppTopNav from '../../components/AppTopNav';
import DetailModal from '../../components/DetailModal';
import {useI18n} from '../../../lib/i18n/provider';
import {supabase} from '../../../lib/supabase';
import {VISUAL_BUCKET,VISUAL_SCOPES,VISUAL_TYPES,VISUAL_STATUSES,type VisualAsset,type VisualMapping,visualMetadata,visualAssetCode,visualUseInstruction} from '../../../lib/visual-assets';
import {assetText,assetError,type VisualLabel} from './labels';
import {visualRequest} from './client';
import css from './visual-assets.module.css';

const size=(bytes:number)=>`${(bytes/1024/1024).toFixed(2)} MB`;
export function SafeAreaPreview({asset,count,locale}:{asset:VisualAsset;count:number;locale:string}){
 return <figure className={css.artwork} style={{aspectRatio:`${asset.width}/${asset.height}`}}>
  <img src={asset.master_url} alt={locale==='en'?asset.name_en:asset.name_th}/>
  {count>0&&<div className={css.overlay} aria-label={assetText(locale,'safe')}><div className={css.safeBoundary}/>{Array.from({length:count},(_,i)=><span className={css.node} key={i} style={{left:`${8+84*i/(count-1)}%`,top:`${i%2?62:40}%`}}><b>{i+1}</b><small>{assetText(locale,'stage')} {i+1}</small></span>)}</div>}
 </figure>;
}
export default function VisualAssetLibrary(){
 const {locale}=useI18n(),t=(k:VisualLabel)=>assetText(locale,k);
 const [assets,setAssets]=useState<VisualAsset[]>([]),[mappings,setMappings]=useState<VisualMapping[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [search,setSearch]=useState(''),[scope,setScope]=useState(''),[type,setType]=useState(''),[status,setStatus]=useState(''),[selected,setSelected]=useState<string|null>(null),[edit,setEdit]=useState<VisualAsset|'upload'|null>(null),[preview,setPreview]=useState(false),[remove,setRemove]=useState(false),[mapping,setMapping]=useState(false),[count,setCount]=useState(7),[busy,setBusy]=useState(false);
 const [copied,setCopied]=useState<Record<string,boolean>>({}),copyTimers=useRef(new Map<string,ReturnType<typeof setTimeout>>());
 useEffect(()=>{const timers=copyTimers.current;return()=>{timers.forEach(clearTimeout);};},[]);
 const lock=useRef(false),sequence=useRef(0),panel=useRef<HTMLElement>(null);
 const uploadRetry=useRef<{file:File;id:string;path:string;token:string;uploaded:boolean}|null>(null);
 const reload=useCallback(async()=>{const n=++sequence.current;setLoading(true);try{const r=await visualRequest();if(n===sequence.current){setAssets(r.assets);setMappings(r.mappings);setError('');}}catch(e){if(n===sequence.current)setError(assetError(locale,e));}finally{if(n===sequence.current)setLoading(false);}},[locale]);
 useEffect(()=>{const counter=sequence;void reload();return()=>{counter.current++;};},[reload]);
 async function perform(action:()=>Promise<unknown>,done?:()=>void){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await action();done?.();setNotice(t('success'));await reload();}catch(e){setError(assetError(locale,e));await reload();setError(assetError(locale,e));}finally{lock.current=false;setBusy(false);}}
 const current=assets.find(a=>a.id===selected),filtered=assets.filter(a=>(!scope||a.scope===scope||a.scope==='both')&&(!type||a.asset_type===type)&&(!status||a.status===status)&&[a.artwork_key,a.name_th,a.name_en,a.theme,...a.tags].join(' ').toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 const name=(a:VisualAsset)=>locale==='en'?a.name_en:a.name_th;
 async function copyReference(asset:VisualAsset,instruction=false){
  try{await navigator.clipboard.writeText(instruction?visualUseInstruction(asset.artwork_key,locale):visualAssetCode(asset.artwork_key));setError('');const key=asset.id+':'+instruction;clearTimeout(copyTimers.current.get(key));setCopied(old=>({...old,[key]:true}));copyTimers.current.set(key,setTimeout(()=>{setCopied(old=>({...old,[key]:false}));copyTimers.current.delete(key);},1800));}
  catch{setError(t('copyError'));}
 }
 const copyButtons=(asset:VisualAsset)=><div className={css.copyActions}>{[false,true].map(instruction=>{const done=copied[asset.id+':'+instruction];return <button key={String(instruction)} disabled={asset.delete_pending} aria-label={t(instruction?'copyInstruction':'copyCode')} data-copied={!!done} onClick={()=>void copyReference(asset,instruction)}>{done?<Check size={14}/>:<Copy size={14}/>}<span role={done?'status':undefined}>{t(done?(instruction?'copiedInstruction':'copiedCode'):(instruction?'copyInstruction':'copyCode'))}</span></button>;})}</div>;
 async function saveMetadata(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;
  await perform(async()=>{
   if(edit&&edit!=='upload'){
    const d=new FormData(form),metadata=visualMetadata({artwork_key:edit.artwork_key,name_th:d.get('name_th'),name_en:d.get('name_en'),asset_type:d.get('asset_type'),scope:d.get('scope'),theme:d.get('theme'),tags:String(d.get('tags')||'').split(','),status:d.get('status'),overlay_ready:edit.overlay_ready});
    return visualRequest({action:'edit',id:edit.id,version:edit.version,metadata});
   }
   const file=(form.elements.namedItem('file') as HTMLInputElement)?.files?.[0];if(!(file instanceof File)||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>20*1024*1024||!file.size)throw Error('VISUAL_FILE_SIZE');
   if(uploadRetry.current?.file!==file){const start=await visualRequest({action:'upload-start',type:file.type,size:file.size});uploadRetry.current={...start,file,uploaded:false};}
   const start=uploadRetry.current!;
   if(!start.uploaded){const uploaded=await supabase.storage.from(VISUAL_BUCKET).uploadToSignedUrl(start.path,start.token,file,{contentType:file.type,upsert:false});if(uploaded.error)throw Error('VISUAL_OPERATION_FAILED');start.uploaded=true;}
   const r=await visualRequest({action:'upload-finish',id:start.id});uploadRetry.current=null;setSelected(r.asset.id);setSearch('');setScope('');setType('');setStatus('');
  },()=>setEdit(null));
 }
 return <main className={css.page}><AppTopNav title={t('title')} activePage="visualAssets"/>
  <header className={css.header}><div className={css.title}><span><ImageIcon size={30}/></span><div><h1>{t('title')}</h1><p>{t('subtitle')}</p></div></div><div className={css.actions}><button onClick={()=>void reload()} disabled={busy}><RefreshCw size={17}/>{t('refresh')}</button><button className={css.primary} disabled={busy} onClick={()=>{setError('');setEdit('upload');}}><Upload size={17}/>{t('upload')}</button></div></header>
  <section className={css.toolbar}><label className={css.search}><span><Search size={16}/>{t('search')}</span><input value={search} onChange={e=>setSearch(e.target.value)}/></label><details className={css.advanced}><summary>{t('advanced')}</summary><div className={css.advancedBody}>{[['scope',VISUAL_SCOPES,scope,setScope],['type',VISUAL_TYPES,type,setType],['status',VISUAL_STATUSES,status,setStatus]].map(([key,choices,value,setter])=><label key={String(key)}>{t(key as VisualLabel)}<select value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}><option value="">{t('all')}</option>{(choices as readonly string[]).map(c=><option key={c} value={c}>{t(c as VisualLabel)}</option>)}</select></label>)}<button onClick={()=>setMapping(true)}><SlidersHorizontal size={16}/>{t('mapping')}</button></div></details></section>
  {error&&<p role="alert" className={css.error}>{error}</p>}{notice&&<p role="status" className={css.notice}>{notice}</p>}
  <div className={css.workspace}><section aria-busy={loading}><div className={css.grid}>{filtered.map(a=><article className={css.card} data-selected={a.id===selected} key={a.id}><button className={css.cardSelect} aria-label={`${t('preview')}: ${visualAssetCode(a.artwork_key)}`} onClick={()=>{setSelected(a.id);requestAnimationFrame(()=>{if(window.innerWidth<1100)panel.current?.scrollIntoView({behavior:'smooth',block:'start'});});}}>
   <div className={css.thumb}>{a.thumbnail_url?<img src={a.thumbnail_url} alt=""/>:<ImageIcon size={40}/>}</div><div className={css.cardBody}><strong>{visualAssetCode(a.artwork_key)}</strong><small>{name(a)}</small></div></button>{copyButtons(a)}</article>)}</div>
   {!filtered.length&&<div className={css.empty}><ImageIcon size={38}/><h2>{loading?t('loading'):t('empty')}</h2><p>{t('emptyHint')}</p></div>}<p className={css.muted}>{filtered.length} / {assets.length} {t('count')}</p>
  </section><aside ref={panel} className={css.panel} aria-label={t('preview')}>{current?<><div className={css.panelHead}><strong>{name(current)}</strong><button aria-label={t('close')} onClick={()=>setSelected(null)}><X size={17}/></button></div><SafeAreaPreview asset={current} count={0} locale={locale}/><code>{visualAssetCode(current.artwork_key)}</code>{copyButtons(current)}<div className={css.badges}><span data-status={current.status}>{t(current.status as VisualLabel)}</span><span>{t(current.asset_type as VisualLabel)}</span></div><dl className={css.details}><dt>{t('dimensions')}</dt><dd>{current.width} × {current.height} px</dd><dt>{t('ratio')}</dt><dd>{(current.width/current.height).toFixed(3)} : 1</dd><dt>{t('size')}</dt><dd>{size(current.byte_size)} · WebP</dd><dt>{t('scope')}</dt><dd>{t(current.scope as VisualLabel)}</dd><dt>{t('theme')}</dt><dd>{current.theme||'—'}</dd><dt>{t('tags')}</dt><dd>{current.tags.join(', ')||'—'}</dd></dl>
   {current.delete_pending?<p className={css.error}>{t('pending')}</p>:<><button className={css.previewButton} onClick={()=>setPreview(true)}><ScanEye size={18}/>{t('preview')}</button></>}
   <div className={css.actions}><button disabled={busy||current.delete_pending} onClick={()=>{setError('');setEdit(current);}}><Pencil size={16}/>{t('edit')}</button>{current.status==='draft'&&<button className={css.primary} disabled={busy||current.delete_pending} onClick={()=>void perform(()=>visualRequest({action:'edit',id:current.id,version:current.version,metadata:{...current,status:'active'}}))}><Check size={16}/>{t('activate')}</button>}{current.status==='active'&&<button disabled={busy||current.delete_pending} onClick={()=>void perform(()=>visualRequest({action:'edit',id:current.id,version:current.version,metadata:{...current,status:'retired'}}))}>{t('retire')}</button>}<button className={css.danger} disabled={busy} onClick={()=>setRemove(true)}><Trash2 size={16}/>{t('remove')}</button></div></>:<div className={css.empty}><ImageIcon size={40}/><p>{t('choose')}</p></div>}</aside></div>
  <footer className={css.footer}><ShieldCheck size={16}/>{t('private')}<span>{t('referenceHint')}</span></footer>
  {edit&&<DetailModal open title={t(edit==='upload'?'upload':'edit')} onClose={()=>{if(!busy)setEdit(null);}} size="edit"><form className={css.form} onSubmit={e=>{void saveMetadata(e).catch(err=>setError(assetError(locale,err)));}}>{error&&<p role="alert" className={css.error}>{error}</p>}<fieldset disabled={busy}>
   {edit==='upload'?<><label>{t('file')}<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required/><small>{t('fileHint')}</small></label><p className={css.hint}>{t('autoHint')}</p></>:<><label>{t('key')}<input value={visualAssetCode(edit.artwork_key)} readOnly/></label><div className={css.formGrid}>{['name_th','name_en','theme','tags'].map(k=><label key={k}>{t(k as VisualLabel)}<input name={k} required={!['theme','tags'].includes(k)} maxLength={k==='theme'?80:k==='tags'?500:160} defaultValue={k==='tags'?edit.tags.join(', '):String(edit[k as keyof VisualAsset]||'')}/></label>)}{[['asset_type',VISUAL_TYPES],['scope',VISUAL_SCOPES],['status',VISUAL_STATUSES]].map(([k,options])=><label key={String(k)}>{t((k==='asset_type'?'type':k) as VisualLabel)}<select name={String(k)} defaultValue={String(edit[k as keyof VisualAsset])}>{(options as readonly string[]).map(s=><option key={s} value={s}>{t(s as VisualLabel)}</option>)}</select></label>)}</div></>}</fieldset><div className={css.actions}><button type="button" disabled={busy} onClick={()=>setEdit(null)}>{t('cancel')}</button><button className={css.primary} disabled={busy}>{t(busy?'busy':edit==='upload'?'upload':'save')}</button></div></form></DetailModal>}
  {preview&&current&&<DetailModal open size="workflow" title={t('preview')} onClose={()=>setPreview(false)}><div className={css.form}><label>{t('stages')}<select value={count} onChange={e=>setCount(Number(e.target.value))}>{[0,5,7,9].map(n=><option key={n} value={n}>{n||t('off')}</option>)}</select></label><SafeAreaPreview asset={current} count={count} locale={locale}/><p className={css.hint}>{t('safeHint')}</p></div></DetailModal>}
  {remove&&current&&<DetailModal open size="confirm" title={t('remove')} onClose={()=>{if(!busy)setRemove(false);}}><form className={css.form} onSubmit={e=>{e.preventDefault();void perform(()=>visualRequest({action:'delete',id:current.id,version:current.version}),()=>{setRemove(false);setSelected(null);});}}>{error&&<p role="alert" className={css.error}>{error}</p>}<p>{t('deleteHint')}</p><label>{t('confirmKey')}<input required pattern={visualAssetCode(current.artwork_key)} placeholder={visualAssetCode(current.artwork_key)} disabled={busy}/></label><button className={css.danger} disabled={busy}>{t(busy?'busy':'remove')}</button></form></DetailModal>}
  {mapping&&<DetailModal open title={t('mapping')} onClose={()=>{if(!busy)setMapping(false);}} size="edit"><div className={css.form}><p className={css.hint}>{t('mappingHint')}</p>{error&&<p role="alert" className={css.error}>{error}</p>}<ul className={css.mappingList}>{mappings.map(m=><li key={m.scope+':'+m.family_key}><span>{t(m.scope as VisualLabel)} · <code>{m.family_key}</code> → <code>{m.artwork_key}</code></span><button disabled={busy} onClick={()=>void perform(()=>visualRequest({action:'unmap',scope:m.scope,family_key:m.family_key,expected_key:m.artwork_key}))}>{t('unmap')}</button></li>)}</ul><form className={css.form} onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget),s=String(d.get('scope')),f=String(d.get('family_key'));void perform(()=>visualRequest({action:'map',scope:s,family_key:f,artwork_key:d.get('artwork_key'),expected_key:mappings.find(m=>m.scope===s&&m.family_key===f)?.artwork_key||null}));}}><label>{t('scope')}<select name="scope" disabled={busy}>{VISUAL_SCOPES.map(s=><option value={s} key={s}>{t(s)}</option>)}</select></label><label>{t('family')}<input name="family_key" required pattern="[a-z][a-z0-9_-]{2,79}" placeholder="universal" disabled={busy}/></label><label>{t('key')}<select name="artwork_key" required disabled={busy}><option value="">—</option>{assets.filter(a=>a.status==='active'&&!a.delete_pending).map(a=><option key={a.id} value={a.artwork_key}>{name(a)} · {a.artwork_key}</option>)}</select></label><button disabled={busy} className={css.primary}>{t(busy?'busy':'map')}</button></form></div></DetailModal>}
 </main>;
}
