/* eslint-disable @typescript-eslint/no-require-imports */
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function setup(){const timers=new Map();let clock=1000,next=0;const box={exports:{},Date,Promise,Map,Set,require:()=>({ARTWORK_TTL:180}),setTimeout:(fn,ms)=>{timers.set(++next,{fn,ms});return next;},clearTimeout:id=>timers.delete(id)};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/advisory-artwork-cache.ts','utf8'),{compilerOptions:{module:1,target:9}}).outputText,box);const cache=box.exports.createArtworkCache(()=>clock);cache.setScope('user-a-token');return {cache,timers,tick:ms=>{clock+=ms;},asset:()=>({code:'approved-key',url:'signed-image',width:1600,height:900,expires_at:181000})};}
test('preload and modal share one resolution/decode, warm reopen reuses it',async()=>{const {cache,asset}=setup();let reads=0,images=0;const resolve=async()=>{reads++;return asset();},decode=async()=>{images++;};const [a,b]=await Promise.all([cache.load('matter:v3',resolve,decode),cache.load('matter:v3',resolve,decode)]);assert.equal(a,b);assert.equal(await cache.load('matter:v3',resolve,decode),a);assert.equal(reads,1);assert.equal(images,1);cache.clear();});
test('expiry capped at 180 seconds and never extended by reopen; expired capabilities resolved anew',async()=>{const {cache,asset,tick,timers}=setup();let reads=0;const resolve=async()=>{reads++;return {...asset(),expires_at:900000};};const a=await cache.load('m:v3',resolve,async()=>{});assert.equal(a.expires_at,181000);tick(179000);assert.equal((await cache.load('m:v3',resolve,async()=>{})).expires_at,181000);assert.equal(reads,1);tick(1001);await cache.load('m:v3',resolve,async()=>{});assert.equal(reads,2);assert.equal(timers.size,1);cache.clear();});
test('short server TTL and elapsed image decode time are respected',async()=>{const {cache,asset,tick}=setup();const a=await cache.load('m',async()=>({...asset(),expires_at:1500}),async()=>{tick(600);});assert.equal(a,null);cache.clear();});
test('logout/session switch discards resolved and in-flight private payloads',async()=>{const {cache,asset}=setup();let finish;const pending=cache.load('m',()=>new Promise(r=>{finish=r;}),async()=>{});cache.setScope('');finish(asset());assert.equal(await pending,null);let called=false;assert.equal(await cache.load('m',async()=>{called=true;return asset();},async()=>{}),null);assert.equal(called,false);cache.setScope('user-b-token');assert.ok(await cache.load('m',async()=>asset(),async()=>{}));cache.setScope('user-a-new-token');assert.ok(await cache.load('m',async()=>{called=true;return asset();},async()=>{}));assert.equal(called,true);cache.clear();});
test('different Matter/version never reuses another authorization and invalid images retry safely',async()=>{const {cache,asset}=setup();let reads=0;const resolve=async()=>{reads++;return asset();};assert.equal(await cache.load('m:v3',resolve,async()=>{throw Error('bad image');}),null);await cache.load('m:v3',resolve,async()=>{});await cache.load('m:v4',resolve,async()=>{});await cache.load('other:v3',resolve,async()=>{});assert.equal(reads,4);cache.clear();});
test('capabilities are bounded and expiry invalidates consumers',async()=>{const {cache,asset,timers}=setup();let invalidated=0;const unsubscribe=cache.subscribe(()=>invalidated++);for(let i=0;i<10;i++)await cache.load('m'+i,async()=>asset(),async()=>{});assert.equal(timers.size,8);const timer=timers.values().next().value;timer.fn();assert.equal(invalidated,1);unsubscribe();cache.clear();assert.equal(invalidated,1);});
