/* eslint-disable @typescript-eslint/no-require-imports */
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{spawnSync}=require('node:child_process');
const A=require('./case-flow-101-artifacts.cjs'),fixture=require('./case-core-098-fixture.cjs');
const bin='/Applications/Postgres.app/Contents/Versions/18/bin';let dir,started=false,beforeRows;
const uid=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
function cmd(n,args,input){return spawnSync(path.join(bin,n),args,{input,encoding:'utf8',env:{PATH:process.env.PATH,LC_ALL:'C',LANG:'C'},maxBuffer:32*1024*1024});}
function check(n,args,input){const r=cmd(n,args,input);assert.equal(r.status,0,r.stderr||r.stdout);return r.stdout.trim();}
const args=()=>['-X','-qAt','-v','ON_ERROR_STOP=1','-h',dir,'-p','58501','-U','postgres','-d','postgres'];
const sql=s=>check('psql',args(),s),json=s=>JSON.parse(sql(s));
const act=(n,s,role='authenticated')=>`BEGIN;SET LOCAL request.jwt.claims='{"sub":"${uid(n)}"}';SET LOCAL ROLE ${role};${s};ROLLBACK;`;
const run=(n,s,role)=>sql(act(n,s,role));
const start={stage:'service',filing_method:'efiling_v3',start_kind:'cut_in',acknowledged:true};
const save=(action='start',data=start,version=0,request=501,id=401,caseId=1)=>`SELECT case101_save(${caseId},'${uid(id)}',${version},'${uid(request)}','${action}',${A.j(data)})`;
const perform=s=>`DO $$ BEGIN PERFORM ${s.replace(/^SELECT /,'')}; END $$;`;
const begin=()=>perform(save());
function deny(n,s,pattern=/CASE101_|permission denied/,role){const r=cmd('psql',args(),act(n,s,role));assert.notEqual(r.status,0,r.stdout);assert.match(r.stderr,pattern);}
before(()=>{dir=fs.mkdtempSync('/private/tmp/case101-pg-');fs.chmodSync(dir,0o700);check('initdb',['-D',dir+'/data','-U','postgres','-A','trust','--encoding=UTF8','--no-locale']);check('pg_ctl',['-D',dir+'/data','-l',dir+'/server.log','-o',`-F -k ${dir} -p 58501 -c listen_addresses='' -c unix_socket_permissions=0700`,'-w','start']);started=true;
 sql(fixture());for(const name of ['case-core-098','case-proceedings-099','case-engagement-100'])sql(A.read(require('./'+name+'-artifacts.cjs').candidate));
 assert.equal(json(A.gate()).gate_pass,true,JSON.stringify(json(A.gate())));beforeRows=json(A.rows());sql(A.read(A.candidate));const catalog={...json(A.footprint()),seed:json(A.seed())};
 if(process.env.CAPTURE_CASE101==='1'){fs.writeFileSync(path.join(A.root,A.afterPath),JSON.stringify(catalog,null,2)+'\n');A.generate();}else assert.deepEqual(catalog,JSON.parse(A.read(A.afterPath)));
});
after(()=>{if(started)check('pg_ctl',['-D',dir+'/data','-m','fast','-w','stop']);console.log('Owned disposable PostgreSQL stopped:',dir);});
test('additive installation preserves 097–100 catalog and legacy/Finance rows; no Case backfill',()=>{assert.deepEqual(json(A.rows()),beforeRows);const actual=json(A.footprint());for(const kind of ['tables','functions'])for(const[name,obj]of Object.entries(A.accepted[kind]))assert.deepEqual(actual[kind][name],obj);for(const t of ['case_flow_instances','case_flow_transitions'])assert.equal(sql('SELECT count(*) FROM '+t),'0');assert.equal(json(A.seed()).stages.length,12);assert.equal(sql("SELECT facts->>'untouched' FROM finance_case097_preservation_canary"),'true');});
test('existing six roles read; only Lawyer/Partner/Admin start; Assistant can transition; Staff/Viewer/reset/inactive denied',()=>{for(const n of [1,2,3,4,5,6])assert.equal(JSON.parse(run(n,'SELECT case101_read(1)')).instance,null);for(const n of [1,2,3])assert.equal(JSON.parse(run(n,save())).instance.started_by,uid(n));for(const n of [4,5,6,7,8,99])deny(n,save(),/FORBIDDEN/);for(const n of [1,2,3,4])assert.equal(JSON.parse(run(1,`${begin()}SET request.jwt.claims='{"sub":"${uid(n)}"}';${save('advance',{stage:'defence'},1,502)}`)).history[0].actor_id,uid(n));for(const n of [5,6,7,8])deny(1,`${begin()}SET request.jwt.claims='{"sub":"${uid(n)}"}';${save('advance',{stage:'defence'},1,502)}`,/FORBIDDEN/);for(const n of [7,8,99])deny(n,'SELECT case101_read(1)',/FORBIDDEN/);for(const role of ['anon','service_role'])deny(1,'SELECT case101_read(1)',/permission denied/,role);});
test('cut-in records one actual starting fact, correct profile and no earlier visits/tasks/deadlines/owner guessing',()=>{const r=JSON.parse(run(3,save()));assert.equal(r.instance.current_stage,'service');assert.equal(r.instance.track_key,'main');assert.equal(r.instance.start_kind,'cut_in');assert.equal(r.instance.filing_method,'efiling_v3');assert.equal(r.template.represented_role,'plaintiff');assert.equal(r.history.length,1);assert.equal(r.history[0].from_stage,null);assert.equal(r.history[0].transition_code,null);assert.deepEqual(json(A.rows()),beforeRows);for(const patch of [{acknowledged:false},{stage:'unknown'},{start_kind:'new'},{actor_id:uid(2)},{track_key:'appeal'},{filing_method:'unknown'}])deny(1,save('start',{...start,...patch}));const fresh=JSON.parse(run(1,save('start',{...start,stage:'prepare_claim',start_kind:'new',filing_method:'not_filed'})));assert.equal(fresh.history.length,1);});
test('manual NEXT/REPEAT/SKIP/RETURN and pause/resume/exit record facts with required reasons',()=>{for(const [stage,code]of [['defence','NEXT'],['service','REPEAT'],['evidence','SKIP'],['file_claim','RETURN']]){const r=JSON.parse(run(1,`${begin()}${save('advance',{stage,reason:'Actual change'},1,502)}`));assert.equal(r.history[0].transition_code,code);assert.equal(r.history[0].from_stage,'service');assert.equal(r.history[0].to_stage,stage);assert.equal(r.instance.version,2);}for(const stage of ['service','evidence','file_claim'])deny(1,`${begin()}${save('advance',{stage},1,502)}`,/REASON_REQUIRED/);
 const paused=perform(save('pause',{reason:'Explicit pause'},1,502));assert.equal(JSON.parse(run(1,`${begin()}${paused}SELECT case101_read(1)`)).instance.lifecycle,'paused');deny(1,`${begin()}${paused}${save('advance',{stage:'defence'},2,503)}`,/STATE/);assert.equal(JSON.parse(run(1,`${begin()}${paused}${save('resume',{reason:'Continue'},2,503)}`)).instance.lifecycle,'active');const exit=perform(save('exit',{reason:'Work stopped'},1,502));deny(1,`${begin()}${exit}${save('advance',{stage:'defence'},2,503)}`,/STATE/);deny(1,`${begin()}${save('parallel',{stage:'defence',reason:'Not enabled'},1,502)}`,/INVALID_INPUT/);});
test('immutable history, controlled correction retains original and requires latest event/version/reason',()=>{const out=JSON.parse(run(1,`${begin()}DO $$DECLARE last_id uuid; BEGIN SELECT id INTO last_id FROM case_flow_transitions WHERE instance_id='${uid(401)}';PERFORM case101_save(1,'${uid(401)}',1,'${uid(502)}','correct',jsonb_build_object('stage','defence','corrects_id',last_id,'reason','Wrong cut-in selection'));END $$;SELECT case101_read(1)`));assert.equal(out.history.length,2);assert.equal(out.history[1].to_stage,'service');assert.equal(out.history[0].event_kind,'correction');assert.equal(out.history[0].corrects_id,out.history[1].id);assert.equal(out.instance.current_stage,'defence');assert.equal(out.instance.started_stage,'service');const twice=JSON.parse(run(1,`${begin()}DO $$DECLARE latest uuid; v integer; BEGIN FOR v IN 1..2 LOOP SELECT id INTO latest FROM case_flow_transitions WHERE instance_id='${uid(401)}' ORDER BY sequence_no DESC LIMIT 1;PERFORM case101_save(1,'${uid(401)}',v,gen_random_uuid(),'correct',jsonb_build_object('stage','defence','corrects_id',latest,'reason','Correct latest fact'));END LOOP;END $$;SELECT case101_read(1)`));assert.equal(twice.history.length,3);assert.equal(twice.history[0].corrects_id,twice.history[1].id);deny(1,`${begin()}${save('correct',{stage:'defence',corrects_id:uid(999),reason:'Correction'},1,502)}`,/STALE/);
 for(const t of A.newTables)for(const op of ['DELETE FROM','TRUNCATE'])deny(1,`${begin()}${op} ${t}`,/permission denied/);for(const t of ['case_flow_versions','case_flow_stages']){const r=cmd('psql',args(),`BEGIN;UPDATE ${t} SET title_en='Changed';ROLLBACK;`);assert.match(r.stderr,/IMMUTABLE/);}const r=cmd('psql',args(),`BEGIN;DELETE FROM case_flow_transitions;ROLLBACK;`);assert.match(r.stderr,/IMMUTABLE/);
});
test('retry does not duplicate even after another transition; conflicting/cross-Case/stale input fails',()=>{const r=JSON.parse(run(1,`${begin()}${perform(save('advance',{stage:'defence'},1,502))}${save()}`));assert.equal(r.history.length,2);assert.equal(r.instance.version,2);deny(1,`${begin()}${save('start',{...start,stage:'defence'})}`,/REQUEST_CONFLICT/);deny(1,`${begin()}${save('advance',{stage:'defence'},0,502)}`,/STALE/);deny(1,`${begin()}${save('advance',{stage:'defence'},1,502,402)}`,/NOT_FOUND/);deny(1,save('start',start,0,501,401,999),/NOT_FOUND/);deny(1,`${begin()}${save('start',start,0,502,402)}`,/STALE/);});
test('atomic rollback on failed audit; actor and before/after audit are server derived',()=>{const r=JSON.parse(run(3,`${begin()}${perform(save('advance',{stage:'defence'},1,502))}SELECT jsonb_build_object('audit',(SELECT to_jsonb(a) FROM case_audit_logs a WHERE note='case101_advance'),'history',(SELECT count(*) FROM case_flow_transitions))`));assert.equal(r.audit.user_id,uid(3));assert.equal(r.audit.old_data.current_stage,'service');assert.equal(r.audit.new_data.current_stage,'defence');assert.equal(r.history,2);
 sql("CREATE FUNCTION fail101audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.note LIKE 'case101_%' THEN RAISE EXCEPTION 'AUDIT_FAILED'; END IF;RETURN NEW;END $$;CREATE TRIGGER fail101audit BEFORE INSERT ON case_audit_logs FOR EACH ROW EXECUTE FUNCTION fail101audit();");try{deny(1,save(),/AUDIT_FAILED/);assert.equal(sql('SELECT count(*) FROM case_flow_instances'),'0');assert.equal(sql('SELECT count(*) FROM case_flow_transitions'),'0');}finally{sql('DROP TRIGGER fail101audit ON case_audit_logs;DROP FUNCTION fail101audit();');}
});
test('scoped verifier fails closed unbound; explicit local binding passes; schema/security drift fails',()=>{const bound=A.gate(true);const unbound=bound.replaceAll(A.j(JSON.parse(A.read(A.reviewedPath))),A.j({candidate_sha256:null,accepted_contract_sha256:null}));assert.deepEqual(json(unbound).failed_checks,['reviewed_contract_bound']);assert.equal(json(bound).gate_pass,true);
 for(const statement of ['GRANT TRUNCATE ON case_flow_instances TO authenticated','ALTER TABLE case_flow_instances DISABLE ROW LEVEL SECURITY','ALTER TABLE case_flow_instances DROP CONSTRAINT case_flow_instances_started_by_fkey','ALTER FUNCTION case101_read(bigint) SECURITY INVOKER']){const r=JSON.parse(sql('BEGIN;'+statement+';'+bound+'ROLLBACK;'));assert.equal(r.gate_pass,false);assert.ok(r.failed_checks.includes('contract_exact'));}
 assert.equal(A.additiveApplySql(A.read(A.candidate)+'\nUPDATE public.cases SET title=title;'),false);
});
