/* eslint-disable @typescript-eslint/no-require-imports */
const {test}=require('node:test'),assert=require('node:assert/strict'),ts=require('typescript');
require('./receipt-render-fixture.cjs');const React=require('react');const {workspaceFixture}=require('./i18n-workspace-fixture.cjs'),A=require('./case-service-102-artifacts.cjs');
const {detailText}=require('../../app/cases/[id]/labels.ts');const M=require('../../app/cases/[id]/service-model.ts');
const f=workspaceFixture('app/cases/[id]/CaseService.tsx',['ServiceEditor','ServiceView','AnswerView'],{'./CaseCore':{CoreEditor:()=>null},'./CaseEditModal':{default:({title,children})=>React.createElement('section',{role:'dialog'},title,children)}});
const person={id:'p1',name:'Local defendant',order_no:1,control:null,attempts:[],answer_deadline:null,default_deadline:null,extensions:[]};
const attempt={id:'a1',method:'posting',attempted_on:'2026-10-03',result:'served',failure_kind:null,failure_reason:null,note:null,recorded_at:'2026-10-03T10:00:00Z'};
const lawful={...person,control:{version:2,required:true,lawful_attempt_id:'a1',lawful_at:'2026-10-04',answer_filed_on:null,absent_hearing_id:null},attempts:[attempt]};
const data={today:'2026-10-10',flow:{current_stage:'service',lifecycle:'active',version:1},defendants:[lawful,person],deadlines:[],hearings:[],history:[]};
test('reviewed user rule matrix is suggestions only; UTC calendar arithmetic, leap/month boundaries and invalid dates',()=>{assert.equal(M.answerSuggestion(lawful),'2026-11-02');assert.equal(M.answerSuggestion({...lawful,attempts:[{...attempt,method:'electronic'}]}),'2026-11-02');assert.equal(M.answerSuggestion({...lawful,attempts:[{...attempt,method:'normal'}]}),'2026-10-18');for(const p of [person,{...lawful,attempts:[{...attempt,method:'other'}]},{...lawful,attempts:[{...attempt,result:'void'}]}])assert.equal(M.answerSuggestion(p),null);assert.equal(M.addCalendarDays('2028-02-20',15),'2028-03-06');assert.equal(M.addCalendarDays('2026-02-30',15),null);assert.equal(M.addCalendarDays('invalid',15),null);
 const overdue={...lawful,answer_deadline:{status:'Active',current_due_date:'2026-09-30',deleted_at:null}};assert.equal(M.defaultSuggestion(overdue,'2026-10-01'),'2026-10-15');assert.equal(M.defaultSuggestion(overdue,'2026-09-30'),null);assert.equal(M.defaultSuggestion({...overdue,control:{...overdue.control,answer_filed_on:'2026-09-29'}},'2026-10-01'),null);assert.equal(M.defaultSuggestion({...overdue,answer_deadline:{...overdue.answer_deadline,status:'Done'}},'2026-10-01'),null);
});
test('scope/per-defendant state: no fabricated history, all-required lawful evidence and nonappearance needed',()=>{assert.equal(M.serviceStatus(person),'unrecorded');assert.equal(M.serviceStatus({...person,attempts:[attempt]}),'served');assert.equal(M.serviceStatus(lawful),'served');assert.deepEqual(M.serviceFlowSuggestions(data),{advance:false,branch:false});assert.deepEqual(M.serviceFlowSuggestions({...data,defendants:[lawful]}),{advance:true,branch:false});assert.equal(M.serviceFlowSuggestions({...data,defendants:[]}).advance,false);assert.equal(M.serviceFlowSuggestions({...data,defendants:[{...lawful,control:{...lawful.control,absent_hearing_id:'h1'}}]}).branch,true);});
test('viewer has read-only modal; legal confirmations and assistant recording remain distinct; no cut-in backfill',()=>{for(const locale of ['th','en']){const view=f.render(locale,{}, {data,canRecord:false,canConfirm:false,onEdit:()=>{},onDeadlines:()=>{}},'ServiceView');assert.ok(view.includes('Local defendant'));assert.ok(view.includes(detailText('service.noAttempt',locale)));for(const key of ['record','confirmLawful','recordAnswer','next','advance','branch'])assert.ok(!view.includes(detailText('service.'+key,locale)+'</button>'),key);const assistant=f.render(locale,{}, {data,canRecord:true,canConfirm:false,onEdit:()=>{},onDeadlines:()=>{}},'ServiceView');assert.ok(assistant.includes(detailText('service.record',locale)+'</button>'));assert.ok(!assistant.includes(detailText('service.confirmAnswerDue',locale)+'</button>'));assert.equal(f.render(locale,{'CaseService.data':{...data,flow:null}}, {caseId:1,revision:0,canRecord:true,canConfirm:true,onSection:()=>{}}),'');}});
test('same existing modal pattern, no automatic confirmation; answer due is editable and other method gets no assumed date',()=>{for(const locale of ['th','en']){const props={action:'deadline',person:lawful,kind:'answer',data,caseId:1,onClose:()=>{},onSaved:()=>{}};const html=f.render(locale,{},props,'ServiceEditor');assert.match(html,/type="date" required="" value="2026-11-02"/);assert.match(html,/type="checkbox" required=""/);assert.doesNotMatch(html,/checked=""/);assert.ok(html.includes(detailText('service.rule30',locale)));const other=f.render(locale,{}, {...props,person:{...lawful,attempts:[{...attempt,method:'other'}]}},'ServiceEditor');assert.match(other,/type="date" required="" value=""/);const attemptForm=f.render(locale,{}, {...props,action:'attempt',person},'ServiceEditor');assert.ok(attemptForm.includes(detailText('service.notLawfulHint',locale)));assert.match(attemptForm,/type="date" required="" max="2026-10-10" value=""/);}});
test('scoped artifacts are deterministic, reviewed verifier is bound; old migrations and template untouched',()=>{assert.equal(A.read(A.candidate),A.migration());assert.equal(A.read('scripts/sql/preflight_case_service_102.sql'),A.gate());assert.equal(A.read('scripts/sql/verify_case_service_102.sql'),A.gate(true));assert.deepEqual(JSON.parse(A.read(A.reviewedPath)),{candidate_sha256:A.hash(A.read(A.candidate)),accepted_contract_sha256:A.acceptedContractSha});assert.doesNotMatch(A.gate()+A.gate(true),/rows_sha256|query_to_xml|auth\.users|row_fingerprints/);assert.equal(A.additiveApplySql(A.read(A.candidate)),true);for(const dml of ['UPDATE public.cases SET title=title;','DELETE FROM public.parties;','INSERT INTO public.case_timeline DEFAULT VALUES;','TRUNCATE public.case_tasks;'])assert.equal(A.additiveApplySql(A.read(A.candidate)+dml),false);assert.equal(A.hash(A.read('supabase/migrations/202610090101_case_civil_flow_foundation.sql')),'7e88a49065a7ebbd0c50c9514ec5608869291a7464218921233c2970a21d311c');assert.deepEqual(JSON.parse(A.read(A.afterPath)).seed,A.accepted.seed);const contract=A.read('scripts/sql/case_service_102_contract.sql');assert.doesNotMatch(contract,/CREATE OR REPLACE|UPDATE public\.(cases|parties|case_tasks)|INSERT INTO public\.case_tasks|finance_/i);});
test('all fixed and dynamic labels/business errors use shared TH/EN; only controlled RPC writes',()=>{const src=A.read('app/cases/[id]/CaseService.tsx'),ast=ts.createSourceFile('x.tsx',src,99,true,4);const dictionary=JSON.parse(A.read('app/cases/[id]/detail-labels.json'));function visit(n){if(ts.isCallExpression(n)&&n.expression.getText(ast)==='tr'&&ts.isStringLiteral(n.arguments[0])){const key=n.arguments[0].text;assert.match(detailText(key,'th'),/[ก-๙]/,key);assert.doesNotMatch(detailText(key,'en'),/[ก-๙]/,key);}ts.forEachChild(n,visit);}visit(ast);for(const[k,v]of Object.entries(dictionary).filter(([k])=>k.startsWith('service.')||k.startsWith('CASE102_'))){assert.match(v.th,/[ก-๙]/,k);assert.doesNotMatch(v.en,/[ก-๙]|CASE102_/,k);}for(const match of A.read('scripts/sql/case_service_102_contract.sql').matchAll(/RAISE EXCEPTION '(CASE102_[A-Z_]+)'/g)){assert.ok(dictionary[M.serviceError(match[1])],match[1]);}assert.doesNotMatch(src,/\.(?:insert|update|delete|upsert)\(|case101_save|createAuditLog/);assert.match(src,/loadAssignmentPeople/);assert.match(src,/SearchableCombobox/);assert.match(src,/crypto.randomUUID/);});
test('UAT: no-attempt and pending follow-up use primary next action, an explicit actual method, and no inferred legal due',()=>{
 for(const locale of ['th','en']){
  const props={action:'next',person,data,caseId:1,onClose:()=>{},onSaved:()=>{}};
  const html=f.render(locale,{},props,'ServiceEditor');assert.ok(html.includes(detailText('service.followupNext',locale)));assert.ok(html.includes(detailText('service.optionalDue',locale)));assert.match(html,/type="date" value=""/);
  const known=f.render(locale,{}, {...props,person:lawful},'ServiceEditor');assert.doesNotMatch(known,/value="2026-11-02"/);
  const create=f.render(locale,{}, {...props,action:'attempt'},'ServiceEditor');assert.match(create,/select required=""/);assert.ok(create.includes(detailText('service.chooseMethod',locale)));assert.match(create,/option value="" selected=""/);
  const view=f.render(locale,{}, {data,canRecord:true,canConfirm:true,onEdit:()=>{},onDeadlines:()=>{}},'ServiceView');assert.ok(view.includes(detailText('service.noAttemptHint',locale)));assert.ok(view.includes(detailText('service.followupAction',locale)));
  const core={core:{next_mode:'manual',next_title:'Existing priority',next_due:'2026-10-12'},team:[],people:[],tasks:[]};const replacing=f.render(locale,{'ServiceEditor.core':core},props,'ServiceEditor');assert.ok(replacing.includes('Existing priority'));assert.ok(replacing.includes(detailText('service.replaceNextHint',locale)));
 }
});
test('UAT: each defendant derives its own answer state from current extended deadline, with explicit default-motion suggestion',()=>{
 const active={...lawful,answer_deadline:{id:'d1',status:'Active',current_due_date:'2026-10-09',deleted_at:null}};
 const extended={...active,id:'p2',name:'Second defendant',answer_deadline:{...active.answer_deadline,id:'d2',current_due_date:'2026-10-20'},extensions:[{id:'ext',extension_no:1,granted_until_date:'2026-10-20',note:'Actual order'}]};
 assert.equal(M.serviceStatus(person,data.today),'unrecorded');assert.equal(M.serviceStatus({...person,attempts:[{...attempt,result:'pending'}]},data.today),'pending');assert.equal(M.serviceStatus(lawful),'served');assert.equal(M.answerStatus(active,data.today),'overdue');assert.equal(M.answerStatus(extended,data.today),'awaitingAnswer');assert.equal(M.answerStatus({...active,control:{...active.control,answer_filed_on:'2026-10-09'}},data.today),'answered');assert.equal(M.defaultSuggestion(active,data.today),'2026-10-24');assert.equal(M.defaultSuggestion(extended,data.today),null);
 assert.equal(M.serviceNextSuggestion(active),null);assert.equal(M.serviceNextSuggestion(person,data.today),'service.followupNext');
 for(const locale of ['th','en']){const multi={...data,defendants:[active,extended]};const view=f.render(locale,{}, {data:multi,canRecord:true,canConfirm:true,onEdit:()=>{},onDeadlines:()=>{},onReview:()=>{}},'AnswerView');assert.match(view,/data-state="overdue"/);assert.match(view,/data-state="awaitingAnswer"/);assert.equal(view.split(detailText('answer.confirmNotFiled',locale)).length-1,1);assert.equal(view.split(detailText('service.manageExtensions',locale)).length-1,2);const html=f.render(locale,{}, {action:'next',defaultMotion:true,person:active,data:multi,caseId:1,onClose:()=>{},onSaved:()=>{}},'ServiceEditor');assert.ok(html.includes(detailText('service.defaultMotionNext',locale)));assert.match(html,/type="date" value=""/);}
});
test('UAT: older pending attempts remain editable and before/after plus void reasons stay visible without delete',()=>{
 const pending={...attempt,id:'pending',result:'pending'},final={...pending,result:'failed',failure_reason:'Actual failed result'};
 const event={id:'e1',party_id:'p1',action:'attempt',actor_name:'Local lawyer',occurred_at:'2026-10-10',before_data:{attempts:[pending]},after_data:{attempts:[final]}};
 assert.deepEqual(M.serviceAttemptChanges(event),[{before:pending,after:final}]);assert.deepEqual(M.serviceAttemptChanges({...event,before_data:null}),[]);
 const p={...lawful,attempts:[{...attempt,id:'void',result:'void',void_reason:'Incorrect entry'},attempt,pending]};assert.equal(M.latestServiceAttempt(p).id,attempt.id);
 for(const locale of ['th','en']){const view=f.render(locale,{}, {data:{...data,defendants:[p],history:[event]},canRecord:true,canConfirm:true,onEdit:()=>{},onDeadlines:()=>{}},'ServiceView');assert.ok(view.includes(detailText('service.updatePending',locale)));assert.ok(view.includes(detailText('service.audit.before',locale)));assert.ok(view.includes(detailText('service.audit.after',locale)));assert.ok(view.includes('Actual failed result'));assert.ok(view.includes('Incorrect entry'));const form=f.render(locale,{}, {action:'void',person:p,attempt:{...attempt,note:'Old unrelated note'},data,caseId:1,onClose:()=>{},onSaved:()=>{}},'ServiceEditor');assert.doesNotMatch(form,/Old unrelated note/);assert.match(form,/textarea required=""/);}
 const source=A.read('app/cases/[id]/CaseService.tsx');assert.match(source,/onExtensions\(p.id,due.id\)/);assert.match(A.read('app/cases/[id]/components/DeadlinesSection.tsx'),/id=\{`case-deadline-\$\{item.id\}`\}/);
});
