/* eslint-disable @typescript-eslint/no-require-imports */
const{test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{spawnSync}=require('node:child_process');
const A=require('./case-core-098-artifacts.cjs');const fixture=require('./case-core-098-fixture.cjs');
const bin='/Applications/Postgres.app/Contents/Versions/18/bin';let dir,started=false,beforeRows;
const uid=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
function cmd(n,args,input){return spawnSync(path.join(bin,n),args,{input,encoding:'utf8',env:{PATH:process.env.PATH,LC_ALL:'C',LANG:'C'},maxBuffer:16*1024*1024});}
function check(n,args,input){const r=cmd(n,args,input);assert.equal(r.status,0,r.stderr||r.stdout);return r.stdout.trim();}
const args=()=>['-X','-qAt','-v','ON_ERROR_STOP=1','-h',dir,'-p','58498','-U','postgres','-d','postgres'];
const sql=s=>check('psql',args(),s),json=s=>JSON.parse(sql(s));
const act=(n,s,role='authenticated')=>`BEGIN;SET LOCAL request.jwt.claims='{"sub":"${uid(n)}"}';SET LOCAL ROLE ${role};${s};ROLLBACK;`;
const save=(section,data,version=0,id=1)=>`SELECT case098_save(${id},${version},${A.q(section)},${A.j(data)})`;
const run=(n,s,role)=>sql(act(n,s,role));
function deny(n,s,pattern=/CASE098_|permission denied/,role){const r=cmd('psql',args(),act(n,s,role));assert.notEqual(r.status,0,r.stdout);assert.match(r.stderr,pattern);}
before(()=>{dir=fs.mkdtempSync('/private/tmp/case098-pg-');fs.chmodSync(dir,0o700);check('initdb',['-D',dir+'/data','-U','postgres','-A','trust','--encoding=UTF8','--no-locale']);check('pg_ctl',['-D',dir+'/data','-l',dir+'/server.log','-o',`-F -k ${dir} -p 58498 -c listen_addresses='' -c unix_socket_permissions=0700`,'-w','start']);started=true;sql(fixture());assert.equal(json(A.gate()).gate_pass,true);beforeRows=json(A.rows());sql(A.read(A.candidate));const after=json(A.footprint());if(process.env.CAPTURE_CASE098==='1'){fs.writeFileSync(path.join(A.root,A.afterPath),JSON.stringify(after,null,2)+'\n');A.generate();}else assert.deepEqual(after,JSON.parse(A.read(A.afterPath)));});
after(()=>{if(started)check('pg_ctl',['-D',dir+'/data','-m','fast','-w','stop']);console.log('Owned disposable PostgreSQL stopped:',dir);});
test('additive migration preserves every accepted Case/child/audit/counter row and 097 object',()=>{assert.deepEqual(json(A.rows()),beforeRows);const now=json(A.footprint());for(const kind of ['tables','functions'])for(const[name,obj]of Object.entries(A.accepted[kind]))assert.deepEqual(now[kind][name],obj);assert.equal(sql('SELECT count(*) FROM case_work_core'),'0');assert.equal(sql("SELECT facts->>'untouched' FROM finance_case097_preservation_canary"),'true');});
test('all six existing read roles; inactive/reset/unknown/anon denied',()=>{for(const n of [1,2,3,4,5,6])assert.equal(JSON.parse(run(n,'SELECT case098_read(1)')).core,null);for(const n of [7,8,99])deny(n,'SELECT case098_read(1)');deny(1,'SELECT case098_read(1)',undefined,'anon');});
test('team and work preserve process permissions; primary next action preserves Task writer roles',()=>{for(const n of [1,2,3,4])run(n,save('team',{assignments:[]}));for(const n of [5,6,7,8,99])deny(n,save('team',{assignments:[]}));for(const n of [1,2,3,4])run(n,save('work',{work_state:'waiting_court'}));for(const n of [5,6])deny(n,save('work',{work_state:'waiting_court'}));for(const n of [1,2,3,4,5])run(n,save('next',{mode:'manual',title:'Real work',assignee_id:uid(3),due:'2026-10-20'}));for(const n of [6,7,8,99])deny(n,save('next',{mode:'none'}));});
test('one person may hold several roles; Lead and actor independent; audit authentic and atomic',()=>{const data={assignments:[{person_id:uid(3),team_role:'lead'},{person_id:uid(3),team_role:'strategy'},{person_id:uid(4),team_role:'current_actor'},{person_id:uid(5),team_role:'member'}]};const output=JSON.parse(run(1,save('team',data)));assert.equal(output.team.length,4);assert.equal(output.core.version,1);assert.equal(run(1,`DO $$ BEGIN PERFORM case098_save(1,0,'team',${A.j(data)});END $$;SELECT user_id::text FROM case_audit_logs WHERE table_name='case_work_core'`),uid(1));assert.deepEqual(json(A.rows()),beforeRows);});
test('ineligible new people denied but existing assignment/history remains readable',()=>{deny(1,save('team',{assignments:[{person_id:uid(7),team_role:'lead'}]}),/PERSON_INELIGIBLE/);const out=json(`BEGIN;SET request.jwt.claims='{"sub":"${uid(1)}"}';DO $$BEGIN PERFORM case098_save(1,0,'team','{"assignments":[{"person_id":"${uid(3)}","team_role":"lead"}]}');END$$;UPDATE user_profiles SET active=false,assignable=false WHERE id='${uid(3)}';SELECT case098_read(1);ROLLBACK;`);assert.equal(out.team[0].person_id,uid(3));assert.equal(out.people.find(p=>p.id===uid(3)).eligible,false);});
test('link existing task derives live facts; cross-case/done/deleted rejected; no Task duplication',()=>{let output=JSON.parse(run(5,save('next',{mode:'task',task_id:uid(201)})));assert.equal(output.core.next_task_id,uid(201));assert.equal(output.core.next_title,null);deny(5,save('next',{mode:'task',task_id:uid(999)}),/TASK_UNAVAILABLE/);for(const patch of ["status='Done'","deleted_at=now()"]){const r=cmd('psql',args(),`BEGIN;SET request.jwt.claims='{"sub":"${uid(1)}"}';UPDATE case_tasks SET ${patch};${save('next',{mode:'task',task_id:uid(201)})};ROLLBACK;`);assert.notEqual(r.status,0);assert.match(r.stderr,/TASK_UNAVAILABLE/);}assert.equal(sql('SELECT count(*) FROM case_tasks'),'1');});
test('manual no owner/due supported; clear means no action; Work State independent of legal status',()=>{const c=JSON.parse(run(1,save('next',{mode:'manual',title:'Review documents'}))).core;assert.equal(c.next_assignee_id,null);assert.equal(c.next_due,null);assert.equal(c.work_state,null);assert.equal(JSON.parse(run(1,save('next',{mode:'none'}))).core.next_mode,'none');assert.deepEqual(json(A.rows()),beforeRows);});
test('stale edit, invalid fields/date/amount-like title and duplicate role fail without partial audit',()=>{deny(1,save('team',{assignments:[]},1),/STALE/);for(const d of [{mode:'manual',title:''},{mode:'manual',title:'X',due:'2026-02-31'},{mode:'manual',title:'X',due:'infinity'},{mode:'other'},{mode:'none',unexpected:true}])deny(1,save('next',d),/INVALID_INPUT/);deny(1,save('team',{assignments:[{person_id:uid(3),team_role:'lead'},{person_id:uid(4),team_role:'lead'}]}),/INVALID_INPUT/);assert.equal(sql('SELECT count(*) FROM case_work_core'),'0');assert.deepEqual(json(A.rows()),beforeRows);});
test('API direct writes/truncate denied; no API audit spoof path added',()=>{for(const table of A.newTables)for(const role of ['anon','authenticated','service_role']){deny(1,`DELETE FROM ${table}`,/permission denied/,role);deny(1,`TRUNCATE ${table}`,/permission denied/,role);}deny(1,"INSERT INTO case_audit_logs(case_id,table_name,action,user_id) VALUES(1,'case_work_core','update','"+uid(2)+"')",/row-level security/);});
test('verifier binds approved objects, accepts normal business activity and rejects schema/security drift',()=>{
 const gate=A.gate(true),binding=A.j(JSON.parse(A.read(A.reviewedPath)));
 const unbound=gate.replaceAll(binding,A.j({candidate_sha256:null,accepted_contract_sha256:null}));
 const bound=gate.replaceAll(binding,A.j({candidate_sha256:A.approvedCandidateSha,accepted_contract_sha256:A.acceptedContractSha}));
 assert.equal(json(unbound).gate_pass,false);assert.equal(json(bound).gate_pass,true);
 assert.equal(json(gate.replaceAll(binding,A.j({candidate_sha256:'wrong',accepted_contract_sha256:A.acceptedContractSha}))).gate_pass,false);
 const normal=`BEGIN;INSERT INTO cases SELECT (jsonb_populate_record(NULL::cases,to_jsonb(c)||'{"id":2,"file_no":"Fixture 2"}'::jsonb)).* FROM cases c WHERE id=1;
 INSERT INTO parties SELECT (jsonb_populate_record(NULL::parties,to_jsonb(p)||'{"id":"${uid(302)}","case_id":2}'::jsonb)).* FROM parties p LIMIT 1;
 INSERT INTO case_timeline SELECT (jsonb_populate_record(NULL::case_timeline,to_jsonb(t)||'{"id":"${uid(303)}","case_id":2}'::jsonb)).* FROM case_timeline t LIMIT 1;
 INSERT INTO case_audit_logs(case_id,table_name,action) VALUES(2,'cases','create');UPDATE file_no_counters SET last_number=last_number+1;UPDATE cases SET title='Normal edit' WHERE id=1;`;
 assert.equal(json(normal+bound+'ROLLBACK;').gate_pass,true);
 assert.equal(json(`BEGIN;SET request.jwt.claims='{"sub":"${uid(1)}"}';DO $$BEGIN PERFORM case098_save(1,0,'work','{"work_state":"waiting_court"}');END$$;`+bound+'ROLLBACK;').gate_pass,true);
 for(const drift of ['GRANT UPDATE ON case_work_core TO authenticated;','ALTER TABLE cases ADD COLUMN unintended text;','DROP POLICY case098_read ON case_team_assignments;','ALTER TABLE case_work_core DROP CONSTRAINT case_work_core_next_assignee_id_fkey;'])assert.equal(json('BEGIN;'+drift+bound+'ROLLBACK;').gate_pass,false);
});

test('actual cross-case task link denied and a second same-version edit rolls back atomically',()=>{
 const r=cmd('psql',args(),`BEGIN;INSERT INTO cases SELECT (jsonb_populate_record(NULL::cases,to_jsonb(c)||'{"id":2,"file_no":"Fixture 2"}'::jsonb)).* FROM cases c WHERE id=1;INSERT INTO case_tasks(id,case_id,status) VALUES('${uid(301)}',2,'Pending');SET request.jwt.claims='{"sub":"${uid(1)}"}';${save('next',{mode:'task',task_id:uid(301)})};ROLLBACK;`);assert.notEqual(r.status,0);assert.match(r.stderr,/TASK_UNAVAILABLE/);
 deny(1,`DO $$BEGIN PERFORM case098_save(1,0,'next','{"mode":"manual","title":"First edit"}');PERFORM case098_save(1,0,'work','{"work_state":"waiting_client"}');END$$`,/STALE/);assert.deepEqual(json(A.rows()),beforeRows);assert.equal(sql('SELECT count(*) FROM case_work_core'),'0');
});
