/* eslint-disable @typescript-eslint/no-require-imports */
const{test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{spawnSync}=require('node:child_process');
const A=require('./case-engagement-100-artifacts.cjs'),B=require('./case-proceedings-099-artifacts.cjs'),C=require('./case-core-098-artifacts.cjs'),fixture=require('./case-core-098-fixture.cjs');
const bin='/Applications/Postgres.app/Contents/Versions/18/bin';let dir,started=false,beforeRows;
const uid=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
function cmd(n,args,input){return spawnSync(path.join(bin,n),args,{input,encoding:'utf8',env:{PATH:process.env.PATH,LC_ALL:'C',LANG:'C'},maxBuffer:16*1024*1024});}
function check(n,args,input){const r=cmd(n,args,input);assert.equal(r.status,0,r.stderr||r.stdout);return r.stdout.trim();}
const args=()=>['-X','-qAt','-v','ON_ERROR_STOP=1','-h',dir,'-p','58500','-U','postgres','-d','postgres'];
const sql=s=>check('psql',args(),s),json=s=>JSON.parse(sql(s));
const act=(n,s,role='authenticated')=>`BEGIN;SET LOCAL request.jwt.claims='{"sub":"${uid(n)}"}';SET LOCAL ROLE ${role};${s};ROLLBACK;`;
const run=(n,s,role)=>sql(act(n,s,role));
const decision={decision:'end',confirmed_on:'2026-01-02',note:'Client confirmation'};
const rescue={escalated_to:uid(3),subject:'Expert advice needed',reason:'Exceptional issue',occurred_at:'2026-01-02T03:00:00Z',status:'open',resolution:null};
const review={objective:'partial',closed_at:'2026-01-02',lessons:'Record actual facts',document_ref:'https://drive.google.com/example'};
const save=(section='decision',data=decision,id=401,version=0,request=501,current=null)=>`SELECT case100_save(1,'${section}','${uid(id)}',${version},'${uid(request)}',${current===null?'NULL':`'${uid(current)}'`},${A.j(data)})`;
const perform=s=>`DO $$ BEGIN PERFORM ${s.replace(/^SELECT /,'')}; END $$;`;
function deny(n,s,pattern=/CASE100_|permission denied/,role){const r=cmd('psql',args(),act(n,s,role));assert.notEqual(r.status,0,r.stdout);assert.match(r.stderr,pattern);}
before(()=>{dir=fs.mkdtempSync('/private/tmp/case100-pg-');fs.chmodSync(dir,0o700);check('initdb',['-D',dir+'/data','-U','postgres','-A','trust','--encoding=UTF8','--no-locale']);check('pg_ctl',['-D',dir+'/data','-l',dir+'/server.log','-o',`-F -k ${dir} -p 58500 -c listen_addresses='' -c unix_socket_permissions=0700`,'-w','start']);started=true;
 sql(fixture()+'\n'+A.read(C.candidate)+'\n'+A.read(B.candidate));assert.equal(json(A.gate()).gate_pass,true);beforeRows=json(A.rows());sql(A.read(A.candidate));const catalog=json(A.footprint());if(process.env.CAPTURE_CASE100==='1'){fs.writeFileSync(path.join(A.root,A.afterPath),JSON.stringify(catalog,null,2)+'\n');A.generate();}else assert.deepEqual(catalog,JSON.parse(A.read(A.afterPath)));});
after(()=>{if(started)check('pg_ctl',['-D',dir+'/data','-m','fast','-w','stop']);console.log('Owned disposable PostgreSQL stopped:',dir);});
test('additive Apply preserves all accepted 097/098/099 objects, Case/history/counters and Finance rows',()=>{assert.deepEqual(json(A.rows()),beforeRows);for(const kind of ['tables','functions'])for(const[name,obj]of Object.entries(A.accepted[kind]))assert.deepEqual(json(A.footprint())[kind][name],obj);for(const t of A.newTables)assert.equal(sql('SELECT count(*) FROM '+t),'0');assert.equal(sql("SELECT facts->>'untouched' FROM finance_case097_preservation_canary"),'true');});
test('six roles read, process writers save; inactive/reset/anonymous/service denied; no direct API writes or truncate',()=>{for(const n of [1,2,3,4,5,6])assert.deepEqual(JSON.parse(run(n,'SELECT case100_read(1)')),{decisions:[],rescues:[],reviews:[]});for(const n of [1,2,3,4])assert.equal(JSON.parse(run(n,save())).decisions[0].recorded_by,uid(n));for(const n of [5,6,7,8,99]){deny(n,save(),/FORBIDDEN/);deny(n,save('rescue',rescue),/FORBIDDEN/);deny(n,save('review',review),/FORBIDDEN/);}for(const n of [7,8,99])deny(n,'SELECT case100_read(1)',/FORBIDDEN/);for(const role of ['anon','authenticated','service_role'])for(const t of A.newTables)for(const op of ['DELETE FROM','TRUNCATE'])deny(1,`${op} ${t}`,/permission denied/,role);deny(1,'SELECT case100_read(1)',/permission denied/,'anon');deny(1,save(),/permission denied/,'service_role');});
test('decisions are explicit append history; waiting has no invented confirmation; retry and concurrent decisions guarded',()=>{const out=JSON.parse(run(1,`${perform(save('decision',{decision:'waiting'},401))}${perform(save('decision',{decision:'continue',confirmed_on:'2026-01-02'},402,0,502,401))}SELECT case100_read(1)`));assert.equal(out.decisions.length,2);assert.equal(out.decisions[0].decision,'continue');assert.equal(out.decisions[1].confirmed_on,null);
 assert.equal(JSON.parse(run(1,`${perform(save())}${save()}`)).decisions.length,1);deny(1,`${perform(save())}${save('decision',{...decision,note:'Changed'})}`,/APPEND_ONLY/);deny(1,`${perform(save())}${save('decision',decision,402,0,502)}`,/STALE/);deny(1,save('decision',{decision:'continue'}),/INVALID_INPUT/);deny(1,save('decision',{decision:'waiting',confirmed_on:'2026-01-02'}),/INVALID_INPUT/);
});
test('rescue captures real requester, permits same person in normal team without auto-generating rescue; resolve/reopen/edit has before/after audit',()=>{
 const result=JSON.parse(run(1,`${perform(save('rescue',rescue))}SET request.jwt.claims='{"sub":"${uid(2)}"}';${perform(save('rescue',{...rescue,status:'resolved',resolution:'Expert helped'},401,1,502))}SELECT jsonb_build_object('data',case100_read(1),'audit',(SELECT to_jsonb(a) FROM case_audit_logs a WHERE table_name='case_rescue_requests' AND action='update'),'team',(SELECT count(*) FROM case_team_assignments))`));
 const r=result.data.rescues[0];assert.equal(r.requested_by,uid(1));assert.equal(r.updated_by,uid(2));assert.equal(r.resolved_by,uid(2));assert.ok(r.resolved_at);assert.equal(result.audit.old_data.status,'open');assert.equal(result.audit.new_data.resolution,'Expert helped');assert.equal(result.team,0);
 const reopened=JSON.parse(run(1,`${perform(save('rescue',{...rescue,status:'resolved',resolution:'Done'}))}${save('rescue',rescue,401,1,502)}`)).rescues[0];assert.equal(reopened.status,'open');assert.equal(reopened.resolved_at,null);
 deny(1,save('rescue',{...rescue,status:'resolved',resolution:''}),/INVALID_INPUT/);deny(1,save('rescue',{...rescue,requested_by:uid(2)}),/INVALID_INPUT/);
});
test('new rescue assignments enforce operational active assignable password-ready non-Viewer; unchanged historical recipient remains readable/editable',()=>{for(const id of [6,7,8,999])deny(1,save('rescue',{...rescue,escalated_to:uid(id)}),/PERSON_INELIGIBLE/);
 for(const patch of ["account_type='test'","account_type=NULL","assignable=false","role='external'"]){const out=cmd('psql',args(),`BEGIN;UPDATE user_profiles SET ${patch} WHERE id='${uid(3)}';SET request.jwt.claims='{"sub":"${uid(1)}"}';${save('rescue',rescue)};ROLLBACK;`);assert.notEqual(out.status,0);assert.match(out.stderr,/PERSON_INELIGIBLE/);}
 const out=json(`BEGIN;SET request.jwt.claims='{"sub":"${uid(1)}"}';${perform(save('rescue',rescue))}UPDATE user_profiles SET active=false WHERE id='${uid(3)}';${save('rescue',{...rescue,status:'resolved',resolution:'Resolved for former colleague'},401,1,502)};ROLLBACK;`);assert.equal(out.rescues[0].status,'resolved');
});
test('close review requires current ended scope, explicit objective/date; derives team identity and keeps prior closure after continuation',()=>{deny(1,save('review',review),/END_REQUIRED/);
 const out=JSON.parse(run(1,`DO $$BEGIN PERFORM case098_save(1,0,'team','{"assignments":[{"person_id":"${uid(3)}","team_role":"lead"},{"person_id":"${uid(3)}","team_role":"qc"}]}');END$$;${perform(save())}${perform(save('review',review,402,0,502,401))}${perform(save('decision',{decision:'continue',confirmed_on:'2026-02-01'},403,0,503,401))}SELECT case100_read(1)`));
 assert.equal(out.reviews.length,1);assert.equal(out.reviews[0].decision_id,uid(401));assert.equal(out.reviews[0].team_evidence.length,2);assert.equal(out.reviews[0].author_name,'Fixture person');assert.equal(out.decisions[0].decision,'continue');
 deny(1,`${perform(save('decision',{decision:'waiting'}))}${save('review',review,402,0,502,401)}`,/END_REQUIRED/);
 deny(1,`${perform(save())}${save('review',{...review,objective:null},402,0,502,401)}`,/INVALID_INPUT/);
});
test('review correction preserves creator/team evidence and audit, does not rewrite old legal or Case core facts',()=>{
 const out=JSON.parse(run(1,`${perform(save())}${perform(save('review',review,402,0,502,401))}SET request.jwt.claims='{"sub":"${uid(2)}"}';${perform(save('review',{...review,objective:'achieved'},402,1,503,401))}SELECT jsonb_build_object('review',(SELECT to_jsonb(r) FROM case_close_reviews r),'audit',(SELECT to_jsonb(a) FROM case_audit_logs a WHERE table_name='case_close_reviews' AND action='update'),'core',(SELECT count(*) FROM case_work_core))`));assert.equal(out.review.recorded_by,uid(1));assert.equal(out.review.updated_by,uid(2));assert.equal(out.audit.old_data.objective,'partial');assert.equal(out.audit.new_data.objective,'achieved');assert.equal(out.core,0);
});
test('stale saves, cross-case IDs, spoofed actor, invalid dates and documents reject atomically',()=>{
 deny(1,`${perform(save('rescue',rescue))}${save('rescue',rescue,401,0,502)}`,/STALE/);
 deny(1,`${perform(save('rescue',rescue))}${save('rescue',{...rescue,reason:'Changed'},401,0,501)}`,/REQUEST_CONFLICT/);
 for(const invalid of [{...decision,recorded_by:uid(2)},{...decision,confirmed_on:'infinity'},{...decision,confirmed_on:'2099-01-01'},{...decision,confirmed_on:'2026-02-31'}])deny(1,save('decision',invalid),/INVALID_/);
 deny(1,`${perform(save())}${save('review',{...review,document_ref:'javascript:alert(1)'},402,0,502,401)}`,/INVALID_INPUT/);
 const crossed=cmd('psql',args(),`BEGIN;SET request.jwt.claims='{"sub":"${uid(1)}"}';${perform(save('rescue',rescue))}INSERT INTO cases SELECT(jsonb_populate_record(NULL::cases,to_jsonb(c)||'{"id":2,"file_no":"Local 2"}'::jsonb)).* FROM cases c WHERE id=1;${save('rescue',rescue,401,1,502).replace('case100_save(1,','case100_save(2,')};ROLLBACK;`);assert.notEqual(crossed.status,0);assert.match(crossed.stderr,/NOT_FOUND/);
 assert.deepEqual(json(A.rows()),beforeRows);for(const t of A.newTables)assert.equal(sql('SELECT count(*) FROM '+t),'0');
});
test('audit failure rolls back new facts; exact request retry does not duplicate rescue/review/audit',()=>{
 sql("CREATE FUNCTION local_fail_audit() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'LOCAL_AUDIT_FAILURE';END$$;CREATE TRIGGER local_fail BEFORE INSERT ON case_audit_logs FOR EACH ROW EXECUTE FUNCTION local_fail_audit();");deny(1,save(),/LOCAL_AUDIT_FAILURE/);assert.equal(sql('SELECT count(*) FROM case_continuation_decisions'),'0');sql('DROP TRIGGER local_fail ON case_audit_logs; DROP FUNCTION local_fail_audit();');
 const out=JSON.parse(run(1,`${perform(save())}${perform(save('review',review,402,0,502,401))}${perform(save('review',review,402,0,502,401))}${perform(save('rescue',rescue,403,0,503))}${perform(save('rescue',rescue,403,0,503))}SELECT jsonb_build_object('reviews',(SELECT count(*) FROM case_close_reviews),'rescues',(SELECT count(*) FROM case_rescue_requests),'audits',(SELECT count(*) FROM case_audit_logs WHERE note LIKE 'case100_%'))`));assert.deepEqual(out,{reviews:1,rescues:1,audits:3});
});
test('unbound verifier fails closed; normal activity accepted; grants/RLS/FK/097/098/099 drift rejected',()=>{const gate=A.gate(true),unbound=gate.replaceAll(A.j(JSON.parse(A.read(A.reviewedPath))),A.j({candidate_sha256:null,accepted_contract_sha256:null})),bound=gate.replaceAll(A.j(JSON.parse(A.read(A.reviewedPath))),A.j({candidate_sha256:A.hash(A.read(A.candidate)),accepted_contract_sha256:A.acceptedContractSha}));assert.equal(json(unbound).gate_pass,false);assert.equal(json(gate).gate_pass,true);assert.equal(json(bound).gate_pass,true);assert.equal(json("BEGIN;UPDATE cases SET title='Normal activity';INSERT INTO case_audit_logs(case_id,table_name,action) VALUES(1,'cases','update');"+bound+'ROLLBACK;').gate_pass,true);for(const drift of ['GRANT UPDATE ON case_close_reviews TO authenticated;','DROP POLICY case100_read ON case_rescue_requests;','ALTER TABLE case_close_reviews DROP CONSTRAINT case_close_reviews_decision_id_case_id_fkey;','ALTER FUNCTION case099_read(bigint) SECURITY INVOKER;','ALTER FUNCTION case098_read(bigint) SECURITY INVOKER;'])assert.equal(json('BEGIN;'+drift+bound+'ROLLBACK;').gate_pass,false);});
