/* eslint-disable @typescript-eslint/no-require-imports */
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{spawnSync}=require('node:child_process');
const A=require('./case-service-103-artifacts.cjs'),fixture=require('./case-core-098-fixture.cjs');
const bin='/Applications/Postgres.app/Contents/Versions/18/bin';let dir,started=false,beforeRows;
const uid=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
function cmd(n,args,input){return spawnSync(path.join(bin,n),args,{input,encoding:'utf8',env:{PATH:process.env.PATH,LC_ALL:'C',LANG:'C'},maxBuffer:32*1024*1024});}
function check(n,args,input){const r=cmd(n,args,input);assert.equal(r.status,0,r.stderr||r.stdout);return r.stdout.trim();}
const args=()=>['-X','-qAt','-v','ON_ERROR_STOP=1','-h',dir,'-p','58503','-U','postgres','-d','postgres'];
const sql=s=>check('psql',args(),s),json=s=>JSON.parse(sql(s));
const act=(n,s,role='authenticated')=>`BEGIN;SET LOCAL request.jwt.claims='{"sub":"${uid(n)}"}';SET LOCAL ROLE ${role};${s};ROLLBACK;`;
const run=(n,s,role)=>sql(act(n,s,role));
const flow=`SELECT case101_save(1,'${uid(401)}',0,'${uid(501)}','start','{"stage":"service","filing_method":"paper","start_kind":"cut_in","acknowledged":true}')`;
const perform=s=>`DO $$ BEGIN PERFORM ${s.replace(/^SELECT /,'')}; END $$;`;
const save=(action,data={},version=0,request=601,party=201)=>`SELECT case102_save(1,${party===null?'NULL':"'"+uid(party)+"'"},${version},'${uid(request)}','${action}',${A.j(data)})`;
const attempt={method:'posting',attempted_on:'2026-01-01',result:'served'};
const begin=()=>perform(flow);
const prepared=()=>`${begin()}${perform(save('attempt',attempt))}DO $$ DECLARE a uuid;BEGIN SELECT id INTO a FROM case_service_attempts WHERE party_id='${uid(201)}';PERFORM case102_save(1,'${uid(201)}',1,'${uid(602)}','lawful',jsonb_build_object('attempt_id',a,'confirmed',true));END $$;`;
const deadline=()=>perform(save('deadline',{kind:'answer',due:'2026-02-03',confirmed:true},2,603));
function deny(n,s,pattern=/CASE102_|permission denied/,role){const r=cmd('psql',args(),act(n,s,role));assert.notEqual(r.status,0,r.stdout);assert.match(r.stderr,pattern);}
before(()=>{dir=fs.mkdtempSync('/private/tmp/case103-pg-');fs.chmodSync(dir,0o700);check('initdb',['-D',dir+'/data','-U','postgres','-A','trust','--encoding=UTF8','--no-locale']);check('pg_ctl',['-D',dir+'/data','-l',dir+'/server.log','-o',`-F -k ${dir} -p 58503 -c listen_addresses='' -c unix_socket_permissions=0700`,'-w','start']);started=true;
 sql(fixture());for(const name of ['case-core-098','case-proceedings-099','case-engagement-100','case-flow-101'])sql(A.read(require('./'+name+'-artifacts.cjs').candidate));
 sql(A.read(require('./case-service-102-artifacts.cjs').candidate));
 sql("UPDATE parties SET role='defendant',first_name='Local defendant',entity_type='individual';UPDATE case_timeline SET event_date='2026-01-02',event_type='hearing',status='Done';");
 assert.equal(json(A.gate()).gate_pass,true,JSON.stringify(json(A.gate())));beforeRows=json(A.rows());sql(A.read(A.candidate));const catalog={...json(A.footprint()),seed:json(A.seed())};
 if(process.env.CAPTURE_CASE103==='1'){fs.writeFileSync(path.join(A.root,A.afterPath),JSON.stringify(catalog,null,2)+'\n');A.generate();}else assert.deepEqual(catalog,JSON.parse(A.read(A.afterPath)));
});
after(()=>{if(started)check('pg_ctl',['-D',dir+'/data','-m','fast','-w','stop']);console.log('Owned disposable PostgreSQL stopped:',dir);});
test('DDL only preserves all accepted objects, immutable 12 stages, business history and Finance canary',()=>{assert.deepEqual(json(A.rows()),beforeRows);const actual=json(A.footprint());for(const kind of ['tables','functions'])for(const[name,obj]of Object.entries(A.accepted[kind]))if(!['case_service_attempts','case102_save(bigint,uuid,integer,uuid,text,jsonb)'].includes(name))assert.deepEqual(actual[kind][name],obj,name);for(const t of A.newTables)assert.equal(sql('SELECT count(*) FROM '+t),'0');assert.deepEqual(json(A.seed()),A.accepted.seed);assert.equal(A.additiveApplySql(A.read(A.candidate)),true);});
test('role parity, reset/inactive/anon/service denial; lawyer-only lawful and legal confirmation',()=>{for(const n of [1,2,3,4,5,6])assert.equal(JSON.parse(run(n,'SELECT case102_read(1)')).defendants.length,1);for(const n of [1,2,3,4]){const r=JSON.parse(run(1,`${begin()}SET request.jwt.claims='{"sub":"${uid(n)}"}';${save('attempt',attempt)}`));assert.equal(r.defendants[0].attempts[0].recorded_by,uid(n));assert.equal(r.defendants[0].control.lawful_at,null);}for(const n of [5,6,7,8,99])deny(1,`${begin()}SET request.jwt.claims='{"sub":"${uid(n)}"}';${save('attempt',attempt)}`,/FORBIDDEN/);for(const n of [7,8,99])deny(n,'SELECT case102_read(1)',/FORBIDDEN/);for(const role of ['anon','service_role'])deny(1,'SELECT case102_read(1)',/permission denied/,role);deny(1,`${begin()}SET request.jwt.claims='{"sub":"${uid(4)}"}';${save('lawful',{confirmed:true})}`,/LAWYER_REQUIRED/);});
test('attempts preserve Party identity; pending completion and failures do not move flow or create deadlines/tasks',()=>{const r=JSON.parse(run(1,`${begin()}${perform(save('attempt',{...attempt,result:'failed',failure_kind:'not_found',failure_reason:'Actual address not found'}))}${save('attempt',{...attempt,method:'normal'},1,602)}`));assert.equal(r.flow.current_stage,'service');assert.equal(r.defendants[0].attempts.length,2);assert.equal(r.defendants[0].control.lawful_attempt_id,null);deny(1,save('attempt',attempt),/PILOT_REQUIRED/);deny(1,`${begin()}${save('attempt',attempt,0,601,999)}`,/PARTY_UNAVAILABLE/);deny(1,`${begin()}${save('attempt',{...attempt,recorded_by:uid(2)})}`,/INVALID_INPUT/);deny(1,`${begin()}${save('attempt',{...attempt,result:'failed'})}`,/INVALID_INPUT/);
 const pending=JSON.parse(run(1,`${begin()}${perform(save('attempt',{...attempt,result:'pending'}))}DO $$DECLARE a uuid;BEGIN SELECT id INTO a FROM case_service_attempts;PERFORM case102_save(1,'${uid(201)}',1,'${uid(602)}','attempt',jsonb_build_object('attempt_id',a,'method','normal','attempted_on','2026-01-01','result','served'));END $$;SELECT case102_read(1)`));assert.equal(pending.defendants[0].attempts.length,1);assert.equal(pending.defendants[0].attempts[0].result,'served');assert.equal(pending.history.length,2);
});
test('lawful service creates no deadline: reviewed override or explicit link reuses Case Deadline Core',()=>{const r=JSON.parse(run(3,`${prepared()}SELECT case102_read(1)`));assert.ok(r.defendants[0].control.lawful_by);assert.equal(r.defendants[0].answer_deadline,null);const d=JSON.parse(run(3,`${prepared()}${deadline()}SELECT case102_read(1)`));assert.equal(d.defendants[0].answer_deadline.current_due_date,'2026-02-03');assert.equal(d.defendants[0].answer_deadline.deadline_type,'answer');assert.equal(d.flow.current_stage,'service');deny(1,`${prepared()}${save('deadline',{kind:'answer',due:'2026-02-03'},2,603)}`,/CONFIRM_REQUIRED/);deny(1,`${prepared()}${deadline()}${save('deadline',{kind:'answer',due:'2026-02-04',confirmed:true},3,604)}`,/DEADLINE_LINKED/);
 const linked=JSON.parse(run(1,`${prepared()}DO $$DECLARE d case_deadlines;BEGIN SELECT * INTO d FROM case_deadlines WHERE id='${uid(201)}';PERFORM case102_save(1,'${uid(201)}',2,'${uid(603)}','deadline',jsonb_build_object('kind','answer','existing_id',d.id,'expected_due',d.current_due_date,'expected_updated_at',d.updated_at,'confirmed',true));END $$;SELECT case102_read(1)`));assert.equal(linked.defendants[0].control.answer_deadline_id,uid(201));
});
test('existing extension history stays authoritative; stale due blocks default motion and answer; answer completes only linked deadline',()=>{const ext=`RESET ROLE;INSERT INTO case_deadline_extensions(deadline_id,extension_no,granted_until_date,note) SELECT answer_deadline_id,1,'2026-03-03','Actual order' FROM case_service_controls;UPDATE case_deadlines SET current_due_date='2026-03-03',updated_at=clock_timestamp() WHERE id IN(SELECT answer_deadline_id FROM case_service_controls);SET LOCAL ROLE authenticated;`;
 const r=JSON.parse(run(1,`${prepared()}${deadline()}${ext}DO $$DECLARE d case_deadlines;BEGIN SELECT * INTO d FROM case_deadlines WHERE id=(SELECT answer_deadline_id FROM case_service_controls);PERFORM case102_save(1,'${uid(201)}',3,'${uid(604)}','answer',jsonb_build_object('date','2026-03-02','expected_due',d.current_due_date,'expected_updated_at',d.updated_at));END $$;SELECT case102_read(1)`));assert.equal(r.defendants[0].answer_deadline.status,'Done');assert.equal(r.defendants[0].extensions.length,1);assert.equal(r.defendants[0].control.answer_filed_on,'2026-03-02');
 deny(1,`${prepared()}${deadline()}${ext}${save('answer',{date:'2026-03-02',expected_due:'2026-02-03'},3,604)}`,/STALE/);
 const def=JSON.parse(run(1,`${prepared()}${deadline()}DO $$DECLARE d case_deadlines;BEGIN SELECT * INTO d FROM case_deadlines WHERE id=(SELECT answer_deadline_id FROM case_service_controls);PERFORM case102_save(1,'${uid(201)}',3,'${uid(604)}','deadline',jsonb_build_object('kind','default','due','2026-02-18','confirmed',true,'expected_due',d.current_due_date,'expected_updated_at',d.updated_at));END $$;SELECT case102_read(1)`));assert.equal(def.defendants[0].default_deadline.current_due_date,'2026-02-18');
});
test('all-required lawful guard then explicitly confirmed 101 transition, never implicit; branch uses actual hearing evidence',()=>{deny(1,`${begin()}${save('advance',{confirmed:true,flow_version:1},0,601,null)}`,/NOT_ALL_LAWFUL/);deny(1,`${prepared()}${save('advance',{flow_version:1},0,603,null)}`,/CONFIRM_REQUIRED/);
 const r=JSON.parse(run(1,`${prepared()}${save('advance',{confirmed:true,flow_version:1},0,603,null)}`));assert.equal(r.flow.current_stage,'defence');assert.equal(r.flow.version,2);deny(1,`${prepared()}${save('branch',{confirmed:true,flow_version:1,reason:'Actual ex parte decision'},0,603,null)}`,/BRANCH_EVIDENCE_REQUIRED/);
 const branch=JSON.parse(run(1,`${prepared()}${perform(save('absence',{confirmed:true,hearing_id:uid(201)},2,603))}${perform(save('branch',{confirmed:true,flow_version:1,reason:'โจทก์สืบพยานฝ่ายเดียว: reviewed hearing outcome'},0,604,null))}SELECT case101_read(1)`));assert.equal(branch.instance.current_stage,'evidence');assert.equal(branch.history[0].transition_code,'BRANCH');assert.equal(branch.history.length,2);
 deny(1,`${prepared()}RESET ROLE;INSERT INTO parties(id,case_id,role,first_name) VALUES('${uid(202)}',1,'defendant','Second actual defendant');SET LOCAL ROLE authenticated;${save('advance',{confirmed:true,flow_version:1},0,603,null)}`,/NOT_ALL_LAWFUL/);
});
test('failed-service follow-up reuses 098: no task or stage created, ineligible People and stale core rejected',()=>{const next={mode:'manual',title:'Report address search to court',assignee_id:uid(3),due:'2026-10-20'};const r=JSON.parse(run(1,`${begin()}${perform(save('next',{core_version:0,next}))}SELECT case098_read(1)`));assert.equal(r.core.next_title,next.title);assert.equal(r.core.next_mode,'manual');deny(1,`${begin()}${save('next',{core_version:0,next:{...next,assignee_id:uid(6)}})}`,/PERSON_INELIGIBLE/);deny(1,`${begin()}${save('next',{core_version:20,next})}`,/CASE098_STALE/);});
test('void is reasoned, cannot silently invalidate an active answer deadline; old facts remain audited',()=>{deny(1,`${prepared()}${deadline()}DO $$DECLARE a uuid;BEGIN SELECT lawful_attempt_id INTO a FROM case_service_controls;PERFORM case102_save(1,'${uid(201)}',3,'${uid(604)}','void',jsonb_build_object('attempt_id',a,'reason','Wrong service fact'));END $$`,/DEADLINE_REVIEW_REQUIRED/);const r=JSON.parse(run(1,`${prepared()}DO $$DECLARE a uuid;BEGIN SELECT lawful_attempt_id INTO a FROM case_service_controls;PERFORM case102_save(1,'${uid(201)}',2,'${uid(603)}','void',jsonb_build_object('attempt_id',a,'reason','Wrong service fact'));END $$;SELECT case102_read(1)`));assert.equal(r.defendants[0].attempts[0].result,'void');assert.equal(r.defendants[0].control.lawful_attempt_id,null);assert.equal(r.history[0].before_data.control.lawful_attempt_id,r.defendants[0].attempts[0].id);});
test('exact retry/concurrency and audit failure rollback; no history delete, direct write or TRUNCATE',()=>{const r=JSON.parse(run(1,`${begin()}${perform(save('attempt',attempt))}${save('attempt',attempt)}`));assert.equal(r.history.length,1);assert.equal(r.defendants[0].attempts.length,1);deny(1,`${begin()}${perform(save('attempt',attempt))}${save('attempt',{...attempt,method:'normal'})}`,/REQUEST_CONFLICT/);deny(1,`${begin()}${perform(save('attempt',attempt))}${save('attempt',attempt,0,602)}`,/STALE/);
 for(const t of A.newTables)for(const op of ['DELETE FROM','TRUNCATE'])deny(1,`${op} ${t}`,/permission denied/);assert.match(cmd('psql',args(),'DELETE FROM case_service_events;').stderr,/IMMUTABLE/);
 sql("CREATE FUNCTION fail102audit() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.note LIKE 'case102_%' THEN RAISE EXCEPTION 'AUDIT_FAILED';END IF;RETURN NEW;END $$;CREATE TRIGGER fail102audit BEFORE INSERT ON case_audit_logs FOR EACH ROW EXECUTE FUNCTION fail102audit();");try{deny(1,`${begin()}${save('attempt',attempt)}`,/AUDIT_FAILED/);assert.equal(sql('SELECT count(*) FROM case_service_controls'),'0');assert.equal(sql('SELECT count(*) FROM case_service_events'),'0');}finally{sql('DROP TRIGGER fail102audit ON case_audit_logs;DROP FUNCTION fail102audit();');}
 assert.deepEqual(json(A.rows()),beforeRows);
});
test('verifier fail-closed unbound; local reviewed binding succeeds; object drift fails but ordinary row activity does not',()=>{const bound=A.gate(true).replaceAll(A.j(JSON.parse(A.read(A.reviewedPath))),A.j({candidate_sha256:A.hash(A.read(A.candidate)),accepted_contract_sha256:A.acceptedContractSha}));const unbound=bound.replaceAll(A.j({candidate_sha256:A.hash(A.read(A.candidate)),accepted_contract_sha256:A.acceptedContractSha}),A.j({candidate_sha256:null,accepted_contract_sha256:null}));assert.deepEqual(json(unbound).failed_checks,['reviewed_contract_bound']);assert.equal(json(bound).gate_pass,true);assert.equal(JSON.parse(sql('BEGIN;UPDATE cases SET title=title;'+bound+'ROLLBACK;')).gate_pass,true);for(const statement of ['GRANT TRUNCATE ON case_service_controls TO authenticated','ALTER TABLE case_service_attempts DISABLE ROW LEVEL SECURITY','ALTER FUNCTION case102_save(bigint,uuid,integer,uuid,text,jsonb) SECURITY INVOKER'])assert.equal(JSON.parse(sql('BEGIN;'+statement+';'+bound+'ROLLBACK;')).gate_pass,false);});
test('UAT: unknown service follow-up needs no attempt/deadline/task and preserves current actor',()=>{
 const counts=json("SELECT jsonb_build_object('tasks',(SELECT count(*) FROM case_tasks),'deadlines',(SELECT count(*) FROM case_deadlines))");
 const team=perform(`SELECT case098_save(1,0,'team','{"assignments":[{"person_id":"${uid(3)}","team_role":"current_actor"}]}')`);
 const next={mode:'manual',title:'Follow up service for defendant A',assignee_id:uid(3),due:'2026-11-01'};
 const result=JSON.parse(run(1,`${begin()}${team}${perform(save('next',{core_version:1,next}))}SELECT jsonb_build_object('service',case102_read(1),'core',case098_read(1),'tasks',(SELECT count(*) FROM case_tasks),'deadlines',(SELECT count(*) FROM case_deadlines))`));
 assert.equal(result.service.defendants[0].attempts.length,0);assert.equal(result.service.defendants[0].answer_deadline,null);assert.equal(result.service.flow.current_stage,'service');assert.equal(result.tasks,counts.tasks);assert.equal(result.deadlines,counts.deadlines);assert.equal(result.core.core.next_due,next.due);assert.equal(result.core.team[0].person_id,uid(3));assert.equal(result.core.team[0].team_role,'current_actor');
});
test('UAT: two defendants keep separate pending attempts; completion and reasoned void retain exact before/after identity',()=>{
 const second=`RESET ROLE;INSERT INTO parties(id,case_id,role,first_name) VALUES('${uid(202)}',1,'defendant','Second defendant');SET LOCAL ROLE authenticated;`;
 const update=`DO $$DECLARE a uuid;BEGIN SELECT id INTO a FROM case_service_attempts WHERE party_id='${uid(201)}';PERFORM case102_save(1,'${uid(201)}',1,'${uid(603)}','attempt',jsonb_build_object('attempt_id',a,'method','posting','attempted_on','2026-01-01','result','failed','failure_kind','not_found','failure_reason','Address not found'));PERFORM case102_save(1,'${uid(201)}',2,'${uid(604)}','void',jsonb_build_object('attempt_id',a,'reason','Incorrect source report'));END $$;`;
 const result=JSON.parse(run(1,`${begin()}${second}${perform(save('attempt',{...attempt,result:'pending'}))}${perform(save('attempt',{...attempt,result:'pending'},0,602,202))}${update}SELECT case102_read(1)`));
 const first=result.defendants.find(x=>x.id===uid(201)),other=result.defendants.find(x=>x.id===uid(202));assert.equal(first.attempts.length,1);assert.equal(first.attempts[0].result,'void');assert.equal(first.attempts[0].void_reason,'Incorrect source report');assert.equal(other.attempts.length,1);assert.equal(other.attempts[0].result,'pending');assert.equal(other.control.version,1);assert.equal(result.flow.current_stage,'service');
 const edit=result.history.find(x=>x.party_id===uid(201)&&x.action==='attempt'&&x.before_data.attempts?.length);assert.equal(edit.before_data.attempts[0].id,first.attempts[0].id);assert.equal(edit.before_data.attempts[0].result,'pending');assert.equal(edit.after_data.attempts[0].result,'failed');assert.equal(result.history.filter(x=>x.party_id===uid(202)).length,1);
});
test('103: failed attempts accept independently unknown method/date; served and pending never invent facts',()=>{
 for(const facts of [{},{method:'normal'},{attempted_on:'2026-01-01'},{method:'',attempted_on:''}]){
  const r=JSON.parse(run(3,`${begin()}${save('attempt',{...facts,result:'failed',failure_kind:'not_found',failure_reason:'Known failed outcome; other facts unavailable'})}`));
  assert.equal(r.defendants[0].attempts[0].method,facts.method||null);assert.equal(r.defendants[0].attempts[0].attempted_on,facts.attempted_on||null);assert.equal(r.defendants[0].control.lawful_attempt_id,null);assert.equal(r.defendants[0].answer_deadline,null);assert.equal(r.flow.current_stage,'service');
 }
 for(const result of ['served','pending'])for(const facts of [{},{method:'normal'},{attempted_on:'2026-01-01'}])deny(3,`${begin()}${save('attempt',{result,...facts})}`,/INVALID_INPUT/);
 for(const facts of [{method:'guessed'},{attempted_on:'infinity'},{attempted_on:'2999-01-01'},{attempted_on:'not a date'}])deny(3,`${begin()}${save('attempt',{result:'failed',failure_kind:'other',failure_reason:'Known failure',...facts})}`,/INVALID_INPUT/);
 for(const result of ['served','pending'])assert.match(cmd('psql',args(),`BEGIN;ALTER TABLE case_service_attempts DISABLE TRIGGER ALL;INSERT INTO case_service_attempts(id,party_id,case_id,result,recorded_by,updated_by) VALUES('${uid(999)}','${uid(201)}',1,'${result}','${uid(1)}','${uid(1)}');ROLLBACK;`).stderr,/case103_result_facts/);
});
test('103: served result plus explicit save confirmation is atomic and lawyer-only; retry returns one event',()=>{
 const facts={...attempt,confirm_lawful:true};
 for(const actor of [1,2,3]){const r=JSON.parse(run(actor,`${begin()}${perform(save('attempt',facts))}${save('attempt',facts)}`));const p=r.defendants[0];assert.equal(p.control.lawful_attempt_id,p.attempts[0].id);assert.equal(p.control.lawful_by,uid(actor));assert.equal(r.history.length,1);assert.equal(r.history[0].after_data.control.lawful_attempt_id,p.attempts[0].id);assert.equal(p.answer_deadline,null);assert.equal(r.flow.current_stage,'service');}
 deny(1,`${begin()}SET request.jwt.claims='{"sub":"${uid(4)}"}';${save('attempt',facts)}`,/LAWYER_REQUIRED/);
 for(const confirm_lawful of [false,null,'true'])deny(3,`${begin()}${save('attempt',{...attempt,confirm_lawful})}`,/INVALID_INPUT/);
 for(const result of ['pending','failed'])deny(3,`${begin()}${save('attempt',{...facts,result})}`,/INVALID_INPUT/);
 deny(3,`${begin()}${perform(save('attempt',facts))}${save('attempt',facts,1,602)}`,/ATTEMPT_FINAL/);
});
test('103: pending completion keeps ID and before/after; failed without facts can be reasoned void, not deleted',()=>{
 const edit=`DO $$DECLARE a uuid;BEGIN SELECT id INTO a FROM case_service_attempts;PERFORM case102_save(1,'${uid(201)}',1,'${uid(602)}','attempt',jsonb_build_object('attempt_id',a,'result','failed','failure_kind','other','failure_reason','The original method and date were entered incorrectly','note','Correction based on source report'));PERFORM case102_save(1,'${uid(201)}',2,'${uid(603)}','void',jsonb_build_object('attempt_id',a,'reason','Incorrect report'));END $$;`;
 const r=JSON.parse(run(3,`${begin()}${perform(save('attempt',{...attempt,result:'pending'}))}${edit}SELECT case102_read(1)`));const p=r.defendants[0];assert.equal(p.attempts.length,1);assert.equal(p.attempts[0].method,null);assert.equal(p.attempts[0].attempted_on,null);assert.equal(p.attempts[0].result,'void');assert.equal(r.history.length,3);assert.equal(r.history[1].before_data.attempts[0].method,'posting');assert.equal(r.history[1].after_data.attempts[0].id,p.attempts[0].id);
 const completed=JSON.parse(run(3,`${begin()}${perform(save('attempt',{...attempt,result:'pending'}))}DO $$DECLARE a uuid;BEGIN SELECT id INTO a FROM case_service_attempts;PERFORM case102_save(1,'${uid(201)}',1,'${uid(602)}','attempt',jsonb_build_object('attempt_id',a,'result','served','method','normal','attempted_on','2026-01-01','confirm_lawful',true));END $$;SELECT case102_read(1)`));assert.equal(completed.defendants[0].attempts.length,1);assert.equal(completed.defendants[0].control.lawful_attempt_id,completed.defendants[0].attempts[0].id);
});
test('103: failed nullable facts preserve exact retry/concurrency and atomic audit rollback',()=>{
 const facts={result:'failed',failure_kind:'other',failure_reason:'No method or date in source report'};
 const r=JSON.parse(run(3,`${begin()}${perform(save('attempt',facts))}${save('attempt',facts)}`));assert.equal(r.history.length,1);deny(3,`${begin()}${perform(save('attempt',facts))}${save('attempt',{...facts,method:'normal'})}`,/REQUEST_CONFLICT/);deny(3,`${begin()}${perform(save('attempt',facts))}${save('attempt',facts,0,602)}`,/STALE/);
 sql("CREATE FUNCTION fail103audit() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.note LIKE 'case102_%' THEN RAISE EXCEPTION 'AUDIT_FAILED';END IF;RETURN NEW;END $$;CREATE TRIGGER fail103audit BEFORE INSERT ON case_audit_logs FOR EACH ROW EXECUTE FUNCTION fail103audit();");try{for(const data of [facts,{...attempt,confirm_lawful:true}]){deny(3,`${begin()}${save('attempt',data)}`,/AUDIT_FAILED/);assert.equal(sql('SELECT count(*) FROM case_service_controls'),'0');assert.equal(sql('SELECT count(*) FROM case_service_attempts'),'0');assert.equal(sql('SELECT count(*) FROM case_service_events'),'0');}}finally{sql('DROP TRIGGER fail103audit ON case_audit_logs;DROP FUNCTION fail103audit();');}
});
test('103: installing over populated 102 preserves every existing service record byte-for-byte',()=>{
 const old=A.read('scripts/sql/case_service_102_contract.sql');const fn=old.slice(old.indexOf('CREATE FUNCTION public.case102_save'),old.indexOf('ALTER FUNCTION public.case102_read')).replace('CREATE FUNCTION','CREATE OR REPLACE FUNCTION');
 const reset=`ALTER TABLE case_service_attempts DROP CONSTRAINT case103_result_facts,ALTER COLUMN method SET NOT NULL,ALTER COLUMN attempted_on SET NOT NULL;${fn}`;
 const seeds=`${perform(save('attempt',attempt))}${perform(save('attempt',{...attempt,result:'pending'},1,602))}${perform(save('attempt',{...attempt,result:'failed',failure_kind:'other',failure_reason:'Legacy failure'},2,603))}DO $$DECLARE a uuid;BEGIN SELECT id INTO a FROM case_service_attempts WHERE result='failed';PERFORM case102_save(1,'${uid(201)}',3,'${uid(604)}','void',jsonb_build_object('attempt_id',a,'reason','Legacy void'));END $$;`;
 const capture=`SELECT jsonb_build_object('controls',(SELECT jsonb_agg(to_jsonb(x) ORDER BY party_id) FROM case_service_controls x),'attempts',(SELECT jsonb_agg(to_jsonb(x) ORDER BY id) FROM case_service_attempts x),'events',(SELECT jsonb_agg(to_jsonb(x) ORDER BY id) FROM case_service_events x),'legacy',(${A.rows()}))`;
 const output=sql(`BEGIN;${reset}SET LOCAL request.jwt.claims='{"sub":"${uid(3)}"}';SET LOCAL ROLE authenticated;${begin()}${seeds}RESET ROLE;${capture};${A.read('scripts/sql/case_service_103_contract.sql')}${capture};ROLLBACK;`).split('\n').map(JSON.parse);assert.deepEqual(output[1],output[0]);assert.equal(output[0].attempts.length,3);
});

test('final answer cleanup: three defendants file, extend and default independently without duplicate deadlines/tasks or stage advance',()=>{
 const second=`RESET ROLE;INSERT INTO parties(id,case_id,role,first_name,entity_type) VALUES('${uid(202)}',1,'defendant','Second defendant','individual'),('${uid(203)}',1,'defendant','Third defendant','individual');SET LOCAL ROLE authenticated;`;
 const seeded=[201,202,203].map((party,n)=>perform(save('attempt',{method:'posting',attempted_on:'2026-01-01',result:'served',confirm_lawful:true},0,710+n,party))+perform(save('deadline',{kind:'answer',due:'2026-02-03',confirmed:true},1,720+n,party))).join('');
 const actions=`DO $$DECLARE d case_deadlines; c case_service_controls; payload jsonb;BEGIN
 PERFORM case102_save(1,NULL,0,'${uid(730)}','advance','{"flow_version":1,"confirmed":true}');
 SELECT * INTO c FROM case_service_controls WHERE party_id='${uid(201)}';SELECT * INTO d FROM case_deadlines WHERE id=c.answer_deadline_id;
 payload:=jsonb_build_object('date','2026-02-02','expected_due',d.current_due_date,'expected_updated_at',d.updated_at);
 PERFORM case102_save(1,c.party_id,c.version,'${uid(731)}','answer',payload);
 PERFORM case102_save(1,c.party_id,c.version,'${uid(731)}','answer',payload);
 SELECT * INTO c FROM case_service_controls WHERE party_id='${uid(202)}';
 INSERT INTO case_deadline_extensions(deadline_id,extension_no,granted_until_date,note) VALUES(c.answer_deadline_id,1,'2099-11-01','Actual order for second defendant');
 UPDATE case_deadlines SET current_due_date='2099-11-01',updated_at=clock_timestamp() WHERE id=c.answer_deadline_id;
 SELECT * INTO c FROM case_service_controls WHERE party_id='${uid(203)}';SELECT * INTO d FROM case_deadlines WHERE id=c.answer_deadline_id;
 payload:=jsonb_build_object('kind','default','due',d.current_due_date+15,'confirmed',true,'expected_due',d.current_due_date,'expected_updated_at',d.updated_at);
 PERFORM case102_save(1,c.party_id,c.version,'${uid(732)}','deadline',payload);
 PERFORM case102_save(1,c.party_id,c.version,'${uid(732)}','deadline',payload);
 BEGIN PERFORM case102_save(1,c.party_id,c.version+1,'${uid(733)}','deadline',payload);RAISE EXCEPTION 'DUPLICATE_ACCEPTED';EXCEPTION WHEN OTHERS THEN IF SQLERRM NOT LIKE '%CASE102_DEADLINE_LINKED%' THEN RAISE;END IF;END;
 END $$;`;
 const taskCount=Number(sql('SELECT count(*) FROM case_tasks'));
 const result=JSON.parse(run(3,`${second}${begin()}${seeded}${actions}SELECT jsonb_build_object('service',case102_read(1),'tasks',(SELECT count(*) FROM case_tasks),'flow_events',(SELECT count(*) FROM case_flow_transitions))`));
 const one=result.service.defendants.find(x=>x.id===uid(201)),two=result.service.defendants.find(x=>x.id===uid(202)),three=result.service.defendants.find(x=>x.id===uid(203));
 assert.equal(one.control.answer_filed_on,'2026-02-02');assert.equal(one.answer_deadline.status,'Done');assert.equal(one.default_deadline,null);
 assert.equal(two.control.answer_filed_on,null);assert.equal(two.answer_deadline.current_due_date,'2099-11-01');assert.equal(two.extensions.length,1);assert.equal(two.default_deadline,null);
 assert.equal(three.control.answer_filed_on,null);assert.equal(three.answer_deadline.status,'Active');assert.equal(three.extensions.length,0);assert.equal(three.default_deadline.current_due_date,'2026-02-18');
 assert.equal(new Set([one,two,three].map(p=>p.answer_deadline.id)).size,3);assert.equal(result.tasks,taskCount);assert.equal(result.flow_events,2);assert.equal(result.service.flow.current_stage,'defence');
 assert.deepEqual(json(A.rows()),beforeRows);
});
