/* eslint-disable @typescript-eslint/no-require-imports */
const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
require('./receipt-render-fixture.cjs');const React=require('react');const{workspaceFixture}=require('./i18n-workspace-fixture.cjs');const A=require('./case-core-098-artifacts.cjs');
const{primaryAction,personLabel,coreError}=require('../../app/cases/[id]/core-model.ts');const{detailText}=require('../../app/cases/[id]/labels.ts');
const person={id:'11111111-1111-1111-1111-111111111111',name:'Person',full_name:'Person identity',eligible:true};
const data={core:null,team:[],people:[person],tasks:[]};
test('artifacts match candidate, preserve 097 SHA and verifier binding is explicit',()=>{assert.equal(A.read(A.candidate),A.migration());assert.equal(A.read('scripts/sql/preflight_case_core_098.sql'),A.gate());assert.equal(A.read('scripts/sql/verify_case_core_098.sql'),A.gate(true));assert.equal(A.hash(A.read('supabase/migrations/202610080097_case_security_parity.sql')),'bddd266cc305bf676b4fe4564181035dee25db830b367c279f6bb79729d57db6');const binding=JSON.parse(A.read(A.reviewedPath));assert.deepEqual(Object.keys(binding).sort(),['accepted_contract_sha256','candidate_sha256']);if(binding.candidate_sha256!==null)assert.deepEqual(binding,{candidate_sha256:A.approvedCandidateSha,accepted_contract_sha256:A.acceptedContractSha});assert.equal(A.hash(A.read(A.candidate)),A.approvedCandidateSha);assert.equal(A.additiveApplySql(),true);assert.equal(A.additiveApplySql(A.read(A.candidate)+'\nUPDATE public.cases SET title=title;'),false);assert.doesNotMatch(A.gate()+A.gate(true),/row_fingerprints|rows_sha256|historical_rows_preserved|no_backfill/);});
test('no action is truly empty; linked task facts derive without name identity guessing',()=>{assert.equal(primaryAction(data),null);const task={id:'task',task_type:'อื่นๆ',task_other:'Prepare',assignee_name:'Legacy text',due_date:'2026-10-20',status:'Pending',deleted_at:null};const d={...data,core:{next_mode:'task',next_task_id:'task'},tasks:[task]};assert.deepEqual(primaryAction(d),{title:'Prepare',assignee:'Legacy text',due:'2026-10-20',linked:true});task.status='Done';assert.equal(primaryAction(d),null);task.status='Pending';task.deleted_at='2026-10-08';assert.equal(primaryAction(d),null);assert.match(personLabel(person),/11111111/);});
test('empty/assigned core and all three editors render TH/EN with standard modal and no inferred stage',()=>{const modal={default:({title,children})=>React.createElement('section',{role:'dialog'},title,children)};const f=workspaceFixture('app/cases/[id]/CaseCore.tsx',['CoreEditor'],{'./CaseEditModal':modal,'./CaseSummary':{default:()=>null}});for(const locale of ['th','en']){const html=f.render(locale,{'CaseCore.data':data},{caseId:1,revision:0,canManage:true,canNext:true,onSection:()=>{}});assert.ok(html.includes(detailText('No primary next action',locale)));assert.ok(html.includes(detailText('Work state not recorded',locale)));for(const mode of ['team','work','next']){const out=f.render(locale,{}, {mode,data,caseId:1,onClose:()=>{},onSaved:()=>{}},'CoreEditor');assert.match(out,/role="dialog"/);assert.ok(out.includes(detailText('Save',locale)));}for(const mode of ['manual','task']){const out=f.render(locale,{'CoreEditor.nextMode':mode},{mode:'next',data,caseId:1,onClose:()=>{},onSaved:()=>{}},'CoreEditor');assert.ok(out.includes(detailText('Due date',locale))||mode==='task');}const readonly=f.render(locale,{'CaseCore.data':data},{caseId:1,revision:0,canManage:false,canNext:false,onSection:()=>{}});assert.ok(!readonly.includes(detailText('Manage team',locale)));assert.ok(!readonly.includes(detailText('Set primary next action',locale)));}});
test('known errors useful in both languages; staff task permission distinct from process permission',()=>{for(const code of ['CASE098_FORBIDDEN','CASE098_STALE','CASE098_INVALID_INPUT','CASE098_PERSON_INELIGIBLE','CASE098_TASK_UNAVAILABLE']){assert.equal(coreError('error '+code),code);assert.notEqual(detailText(code,'en'),code);assert.doesNotMatch(detailText(code,'th'),/CASE098/);}const source=fs.readFileSync('app/cases/[id]/page.tsx','utf8');assert.match(source,/canManage=\{permissions.canEditCaseInfo\}/);assert.match(source,/canNext=\{permissions.canEditTasks\}/);const contract=A.read('scripts/sql/case_core_098_contract.sql');assert.doesNotMatch(contract,/UPDATE public\.(cases|case_tasks)|INSERT INTO public\.case_tasks|UPDATE public\.finance_/);});
