/* eslint-disable @typescript-eslint/no-require-imports */
const{test}=require('node:test'),assert=require('node:assert/strict'),ts=require('typescript');
require('./receipt-render-fixture.cjs');const React=require('react');const{workspaceFixture}=require('./i18n-workspace-fixture.cjs');const A=require('./case-engagement-100-artifacts.cjs');const{detailText}=require('../../app/cases/[id]/labels.ts');const{engagementError}=require('../../app/cases/[id]/engagement-model.ts');const{buildPermissions}=require('../../lib/permissions.ts');
const modal={default:({title,children})=>React.createElement('section',{role:'dialog'},title,children)};
const f=workspaceFixture('app/cases/[id]/CaseEngagement.tsx',['EngagementEditor'],{'./CaseEditModal':modal});
const people=[{id:'eligible',name:'ทนายตัวอย่าง',full_name:'ชื่อจริง นามสกุล',eligible:true},{id:'uat',name:'UAT account',eligible:false}];
const decision={id:'decision',sequence_no:1,decision:'end',confirmed_on:'2026-01-02',note:'Actual client confirmation',recorded_by:'writer',recorded_at:'2026-01-02T03:30:00Z',author_name:'Recorded author'};
const rescue={id:'rescue',escalated_to:'eligible',subject:'Exceptional support',reason:'Actual reason',occurred_at:'2026-01-02T03:30:00Z',status:'open',resolution:null,requested_by:'writer',recorded_at:'2026-01-02T03:30:00Z',updated_at:'2026-01-02T03:30:00Z',version:1,requester_name:'Real requester',recipient_name:'Real recipient',editor_name:'Real editor'};
const review={id:'review',decision_id:'decision',objective:'partial',closed_at:'2026-01-02',variance:'Variance facts',lessons:'Lessons facts',knowledge:'Reusable facts',document_ref:'https://drive.google.com/example',recorded_at:'2026-01-02T03:30:00Z',updated_at:'2026-01-02T03:30:00Z',author_name:'Real author',editor_name:'Real editor',team_evidence:[{person_id:'person',team_role:'lead',name:'Recorded lead'}],version:1};
const data={decisions:[decision],rescues:[rescue],reviews:[review]};
test('deterministic additive candidate, fail-closed review binding, no changes to accepted 097–099',()=>{assert.equal(A.read(A.candidate),A.migration());assert.equal(A.read('scripts/sql/preflight_case_engagement_100.sql'),A.gate());assert.equal(A.read('scripts/sql/verify_case_engagement_100.sql'),A.gate(true));assert.equal(A.additiveApplySql(A.read(A.candidate)),true);assert.deepEqual(JSON.parse(A.read(A.reviewedPath)),{candidate_sha256:'5680dee06e16a668cbb55784c69055c7f7c8447a30ed5d003be0474d58dda0f1',accepted_contract_sha256:A.acceptedContractSha});assert.equal(A.hash(A.read(A.candidate)),JSON.parse(A.read(A.reviewedPath)).candidate_sha256);assert.doesNotMatch(A.gate()+A.gate(true),/rows_sha256|row_fingerprints|query_to_xml|auth\.users/);
 for(const [file,hash]of [['202610080097_case_security_parity','bddd266cc305bf676b4fe4564181035dee25db830b367c279f6bb79729d57db6'],['202610080098_case_accountability_next_action','c9cf604b4e92eeb2dde685a00816cfc5770e7d02ba45a58ff76b744fee81570c'],['202610080099_case_hearing_proceedings','3756a06a439210310ea6efb84003d5de1d722abadccb4f9e15e72834c03103f1']])assert.equal(A.hash(A.read('supabase/migrations/'+file+'.sql')),hash);
 const contract=A.read('scripts/sql/case_engagement_100_contract.sql');assert.doesNotMatch(contract,/UPDATE public\.(cases|case_work_core|case_tasks|case_timeline)|INSERT INTO public\.(case_tasks|case_timeline)|finance_|case098_save|case099_save|owner_name/);assert.match(contract,/case097_process_writer\(\)/);assert.match(contract,/auth\.uid\(\)/);
});
test('simple continuation modal has three choices; waiting never asks for a false confirmation',()=>{for(const locale of ['th','en']){const props={editor:{mode:'decision'},caseId:1,data:{decisions:[],rescues:[],reviews:[]},people,onClose:()=>{},onSaved:()=>{}};const html=f.render(locale,{},props,'EngagementEditor');assert.equal((html.match(/type="radio"/g)||[]).length,3);assert.doesNotMatch(html,/type="date"/);assert.match(html,/textarea/);assert.ok(html.includes(detailText('Save',locale)));const ended=f.render(locale,{'EngagementEditor.decision':'end'},props,'EngagementEditor');assert.match(ended,/type="date" required/);assert.ok(!ended.includes('VP-2026-049'));}});
test('rescue and close review reuse concise modal, standard eligible People, no manual requester/team/scoring',()=>{for(const locale of ['th','en']){const props={editor:{mode:'rescue',rescue},caseId:1,data,people,onClose:()=>{},onSaved:()=>{}};const html=f.render(locale,{},props,'EngagementEditor');assert.match(html,/combobox/);assert.ok(html.includes(detailText('Mark resolved',locale)));assert.doesNotMatch(html,/UAT account|requested_by|score|ranking/);const resolved=f.render(locale,{'EngagementEditor.resolved':true},props,'EngagementEditor');assert.ok(resolved.includes(detailText('Resolution',locale)));const closed=f.render(locale,{}, {...props,editor:{mode:'review'}},'EngagementEditor');assert.match(closed,/<details>/);assert.equal((closed.match(/<select/g)||[]).length,1);assert.doesNotMatch(closed,/role\.lead|role\.qc|current_actor|case_tasks/);}});
test('close review only appears after ended scope; Viewer/Staff cannot mutate; old history remains after continuing',()=>{for(const role of ['viewer','staff','assistant_lawyer','lawyer','partner','admin']){const canEdit=buildPermissions({role}).canEditCaseInfo;const html=f.render('en',{'CaseEngagement.data':data},{caseId:1,revision:0,people,canEdit,canViewHistory:false});assert.equal(html.includes('Record continuation decision</button>'),canEdit);assert.equal(html.includes('Request help / escalate</button>'),canEdit);assert.equal(html.includes('Edit close review</button>'),canEdit);}
 const ongoing=f.render('en',{'CaseEngagement.data':{...data,decisions:[{...decision,decision:'continue'}]}},{caseId:1,revision:0,people,canEdit:true,canViewHistory:true});assert.doesNotMatch(ongoing,/Edit close review/);assert.match(ongoing,/Engagement history/);
 for(const locale of ['th','en']){const history=f.render(locale,{'CaseEngagement.data':data,'CaseEngagement.history':true},{caseId:1,revision:0,people,canEdit:false,canViewHistory:false});for(const fact of ['Actual client confirmation','Actual reason','Real requester','Real recipient','Variance facts','Lessons facts','Reusable facts','Recorded lead','https://drive.google.com/example'])assert.ok(history.includes(fact),fact);assert.doesNotMatch(history,/href="#history"/);}
});
test('new vocabulary and business errors have single-language TH/EN labels',()=>{const source=A.read('app/cases/[id]/CaseEngagement.tsx'),ast=ts.createSourceFile('x.tsx',source,99,true,4);function visit(n){if(ts.isCallExpression(n)&&n.expression.getText(ast)==='tr'&&ts.isStringLiteral(n.arguments[0])){const key=n.arguments[0].text;assert.doesNotMatch(detailText(key,'en'),/[ก-๙]/,key);assert.doesNotMatch(detailText(key,'th'),/[A-Za-z]{3,}/,key);}ts.forEachChild(n,visit);}visit(ast);for(const code of ['FORBIDDEN','STALE','INVALID_INPUT','PERSON_INELIGIBLE','END_REQUIRED','DECISION_APPEND_ONLY','REQUEST_CONFLICT']){const key=engagementError('CASE100_'+code);assert.doesNotMatch(detailText(key,'en'),/CASE100|[ก-๙]/);assert.match(detailText(key,'th'),/[ก-๙]/);}assert.match(source,/\.filter\(p=>p.eligible\)/);assert.match(source,/personLabel/);assert.doesNotMatch(source,/createAuditLog|\.from\('case_tasks'\)|work_state\s*:/);});
