"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { CSSProperties, ReactNode } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { FinanceSubNav, QuotationGuard } from "../../quotations/shared";
import { supabase } from "../../../../lib/supabase";

type Json = Record<string, unknown>;
type Agreement = { id: string; agreement_no: string | null; title: string; client_id: string; case_id: number | null; advisory_matter_id: string | null; source_type: string; source_quotation_id: string | null; source_reference: string | null; status: string; effective_date: string | null; commencement_date: string | null; expiry_date: string | null; currency: string; amount_before_tax: number | string; vat_amount: number | string; total_amount: number | string; billing_method: string; language_code: string; legal_terms_json: Json | null; signatories_json: unknown[] | null; custom_clauses_json: unknown[] | null; selected_template_version_id: string | null; client_snapshot_json: Json | null; matter_snapshot_json: Json | null; source_document_snapshot_json: Json | null; commercial_terms_snapshot_json: Json | null; allocation_snapshot_json: Json | null; resolved_document_snapshot_json: Json | null; signed_document_snapshot_json: Json | null; document_version: number; created_at: string; updated_at: string };
type Item = { id: string; description: string; quantity: number | string; unit_price: number | string; vat_applicable: boolean; vat_rate: number | string; amount_before_tax: number | string; vat_amount: number | string; line_total: number | string; sort_order: number };
type Quote = { id: string; quotation_no: string; status: string; issue_date: string | null; valid_until: string | null };
type Version = { id: string; version_no: number; event_type: string; reason: string | null; actor_name: string | null; actor_email: string | null; created_at: string };
type Template = { id: string; template_id: string; language_code: string; version_no: number; document_templates?: { name?: string; template_code?: string } | null };
type MetadataForm = { title: string; effectiveDate: string; expiryDate: string; billingMethod: string };
type LegalForm = { language: string; commencementDate: string; templateVersionId: string; scopeClarification: string; clientObligations: string; firmObligations: string; exclusions: string; expenses: string; confidentiality: string; termination: string; dispute: string; additionalTerms: string; internalNote: string; signatories: string; customClauses: string };

const statusLabel: Record<string, string> = { draft: "Draft / ร่าง", under_review: "Under Review / ตรวจทาน", sent: "Sent / ส่งแล้ว", signed: "Signed / ลงนามแล้ว", completed: "Completed / เสร็จสมบูรณ์", cancelled: "Cancelled / ยกเลิก", active: "Active / Legacy" };
const billingLabels: Record<string, string> = { single: "งวดเดียว", installments: "หลายงวด", milestone: "ตามเหตุการณ์สำคัญ", recurring: "เรียกเก็บเป็นรอบ", manual: "กำหนดเอง" };
const amount = (value: number | string | null | undefined) => Number(value || 0);
const money = (value: number | string | null | undefined, currency = "THB") => `${amount(value).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${currency}`;
const date = (value: string | null | undefined) => value ? value.slice(0, 10) : "-";
const text = (value: unknown, fallback = "-") => typeof value === "string" && value.trim() ? value : fallback;
const object = (value: unknown) => value && typeof value === "object" && !Array.isArray(value) ? value as Json : {};
const prettyJson = (value: unknown) => JSON.stringify(value || [], null, 2);

export default function FeeAgreementDetailPage() { return <QuotationGuard>{(access) => <Detail permissions={access.permissions} />}</QuotationGuard>; }

function Detail({ permissions }: { permissions: { canEditFinanceQuotation: boolean } }) {
  const params = useParams();
  const id = Array.isArray(params.id) ? params.id[0] : params.id || "";
  const [agreement, setAgreement] = useState<Agreement | null>(null); const [items, setItems] = useState<Item[]>([]); const [quote, setQuote] = useState<Quote | null>(null); const [versions, setVersions] = useState<Version[]>([]); const [templates, setTemplates] = useState<Template[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [lifecycleSaving, setLifecycleSaving] = useState(false); const [message, setMessage] = useState(""); const [formError, setFormError] = useState(""); const [dirty, setDirty] = useState(false);
  const [metadata, setMetadata] = useState<MetadataForm>({ title: "", effectiveDate: "", expiryDate: "", billingMethod: "single" });
  const [legal, setLegal] = useState<LegalForm>(emptyLegalForm);
  const editable = Boolean(agreement && permissions.canEditFinanceQuotation && ["draft", "under_review"].includes(agreement.status));

  const load = useCallback(async () => {
    if (!id) { setError("Fee Agreement not found."); setLoading(false); return; }
    setLoading(true); setError("");
    const header = await supabase.from("finance_fee_agreements").select("id,agreement_no,title,client_id,case_id,advisory_matter_id,source_type,source_quotation_id,source_reference,status,effective_date,commencement_date,expiry_date,currency,amount_before_tax,vat_amount,total_amount,billing_method,language_code,legal_terms_json,signatories_json,custom_clauses_json,selected_template_version_id,client_snapshot_json,matter_snapshot_json,source_document_snapshot_json,commercial_terms_snapshot_json,allocation_snapshot_json,resolved_document_snapshot_json,signed_document_snapshot_json,document_version,created_at,updated_at").eq("id", id).maybeSingle();
    if (header.error || !header.data) { setError(header.error ? "ไม่สามารถโหลด Fee Agreement ได้" : "ไม่พบ Fee Agreement"); setLoading(false); return; }
    const row = header.data as Agreement;
    const [itemRes, quoteRes, versionRes, templateRes] = await Promise.all([
      supabase.from("finance_fee_agreement_items").select("id,description,quantity,unit_price,vat_applicable,vat_rate,amount_before_tax,vat_amount,line_total,sort_order").eq("fee_agreement_id", id).order("sort_order").order("id"),
      row.source_quotation_id ? supabase.from("finance_quotations").select("id,quotation_no,status,issue_date,valid_until").eq("id", row.source_quotation_id).maybeSingle() : Promise.resolve({ data: null, error: null }),
      supabase.from("finance_fee_agreement_versions").select("id,version_no,event_type,reason,actor_name,actor_email,created_at").eq("fee_agreement_id", id).order("version_no", { ascending: false }),
      supabase.from("document_template_versions").select("id,template_id,language_code,version_no,document_templates!inner(name,template_code,document_type)").eq("status", "published").eq("document_templates.document_type", "fee_agreement").order("version_no", { ascending: false }),
    ]);
    if (itemRes.error || quoteRes.error || versionRes.error || templateRes.error) setError("ข้อมูลบางส่วนไม่สามารถโหลดได้ กรุณารีเฟรชอีกครั้ง");
    setAgreement(row); setItems((itemRes.data || []) as Item[]); setQuote((quoteRes.data || null) as Quote | null); setVersions((versionRes.data || []) as Version[]); setTemplates((templateRes.data || []) as Template[]);
    setMetadata({ title: row.title, effectiveDate: row.effective_date || "", expiryDate: row.expiry_date || "", billingMethod: row.billing_method }); setLegal(legalFormFrom(row)); setDirty(false); setLoading(false);
  }, [id]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);

  const saveMetadata = async () => {
    if (!agreement || !editable || saving) return;
    if (!metadata.title.trim()) { setFormError("กรุณาระบุชื่อข้อตกลง"); return; }
    if (metadata.effectiveDate && metadata.expiryDate && metadata.expiryDate < metadata.effectiveDate) { setFormError("วันสิ้นสุดต้องไม่ก่อนวันเริ่มมีผล"); return; }
    setSaving(true); setFormError(""); setMessage("");
    const result = await supabase.rpc("save_finance_fee_agreement_draft_metadata", { p_fee_agreement_id: agreement.id, p_title: metadata.title.trim(), p_effective_date: metadata.effectiveDate || null, p_expiry_date: metadata.expiryDate || null, p_billing_method: metadata.billingMethod });
    if (result.error) { setFormError(mapRpcError(result.error.message)); setSaving(false); return; }
    await load(); setMessage("บันทึกข้อมูลบริหารข้อตกลงและสร้างประวัติเวอร์ชันแล้ว"); setSaving(false);
  };
  const saveLegal = async () => {
    if (!agreement || !editable || saving) return;
    let signatories: unknown[]; let clauses: unknown[];
    try { signatories = parseArray(legal.signatories, "ข้อมูลผู้ลงนาม"); clauses = parseArray(legal.customClauses, "Custom clauses"); } catch (parseError) { setFormError(parseError instanceof Error ? parseError.message : "ข้อมูล JSON ไม่ถูกต้อง"); return; }
    setSaving(true); setFormError(""); setMessage("");
    const legalTerms = { scope_clarification: blankToNull(legal.scopeClarification), client_obligations: blankToNull(legal.clientObligations), firm_obligations: blankToNull(legal.firmObligations), exclusions: blankToNull(legal.exclusions), expenses_disbursements: blankToNull(legal.expenses), confidentiality: blankToNull(legal.confidentiality), termination_provisions: blankToNull(legal.termination), dispute_jurisdiction: blankToNull(legal.dispute), additional_terms: blankToNull(legal.additionalTerms), internal_note: blankToNull(legal.internalNote) };
    const result = await supabase.rpc("save_finance_fee_agreement_draft_legal_terms", { p_fee_agreement_id: agreement.id, p_legal_terms_json: legalTerms, p_signatories_json: signatories, p_custom_clauses_json: clauses, p_template_version_id: legal.templateVersionId || null, p_language_code: legal.language, p_commencement_date: legal.commencementDate || null });
    if (result.error) { setFormError(mapRpcError(result.error.message)); setSaving(false); return; }
    await load(); setMessage("บันทึกเงื่อนไขทางกฎหมายและสร้างประวัติเวอร์ชันแล้ว"); setSaving(false);
  };
  const transition = async (nextStatus: "under_review" | "sent" | "signed" | "completed" | "cancelled") => {
    if (!agreement || lifecycleSaving || !permissions.canEditFinanceQuotation) return;
    if (!window.confirm(nextStatus === "cancelled" ? "ยืนยันการยกเลิกข้อตกลง?" : `ยืนยันเปลี่ยนสถานะเป็น ${statusLabel[nextStatus]}?`)) return;
    setLifecycleSaving(true); setFormError(""); setMessage("");
    const result = await supabase.rpc("set_finance_fee_agreement_status", { p_fee_agreement_id: agreement.id, p_next_status: nextStatus });
    if (result.error) setFormError(mapRpcError(result.error.message)); else { await load(); setMessage("อัปเดตสถานะและบันทึกหลักฐานเวอร์ชันแล้ว"); }
    setLifecycleSaving(false);
  };
  const mismatch = useMemo(() => agreement ? Math.abs(items.reduce((sum, item) => sum + amount(item.amount_before_tax), 0) - amount(agreement.amount_before_tax)) > .005 || Math.abs(items.reduce((sum, item) => sum + amount(item.vat_amount), 0) - amount(agreement.vat_amount)) > .005 || Math.abs(items.reduce((sum, item) => sum + amount(item.line_total), 0) - amount(agreement.total_amount)) > .005 : false, [agreement, items]);
  if (loading) return <main style={page}>Loading Fee Agreement...</main>; if (!agreement) return <main style={page}>{error || "Fee Agreement not found."}</main>;
  const source = object(agreement.source_document_snapshot_json); const terms = object(agreement.commercial_terms_snapshot_json); const client = text(agreement.client_snapshot_json?.name, text(agreement.client_snapshot_json?.display_name)); const matter = text(agreement.matter_snapshot_json?.title, text(agreement.matter_snapshot_json?.file_no, agreement.case_id || agreement.advisory_matter_id ? "-" : "Client-level agreement")); const sourceNo = text(source.quotation_no, text(agreement.source_reference));
  return <main style={page}><FinanceSubNav activePage="fee-agreements" permissions={permissions as never} /><div style={actions}><Link href="/finance/fee-agreements">Back to Fee Agreements</Link>{agreement.source_quotation_id ? <Link href={`/finance/quotations/${agreement.source_quotation_id}`}>Source Quotation</Link> : null}<Link href={`/finance/fee-agreements/${agreement.id}/preview`}>Preview / Print</Link></div>
    {error ? <div style={warning}>{error}</div> : null}{formError ? <div style={warning}>{formError}</div> : null}{message ? <div style={success}>{message}</div> : null}
    <section style={card}><h1 style={{ marginTop: 0 }}>{agreement.title}</h1><div style={grid}><Field label="Agreement No." value={agreement.agreement_no || "Legacy agreement"} /><Field label="Status" value={<StatusBadge status={agreement.status} />} /><Field label="Language" value={agreement.language_code === "en" ? "English" : "Thai"} /><Field label="Document version" value={agreement.document_version} /><Field label="Effective" value={date(agreement.effective_date)} /><Field label="Updated" value={date(agreement.updated_at)} /></div></section>
    <section style={card}><h2>Commercial Evidence / หลักฐานทางการค้า</h2><p style={notice}>ข้อมูลส่วนนี้มาจาก snapshot ของใบเสนอราคาที่รับรองแล้วและรายการ Fee Agreement ที่คัดลอกไว้ จึงแก้ไขจากหน้านี้ไม่ได้</p><div style={grid}><Field label="Client" value={client} /><Field label="Matter" value={matter} /><Field label="Source Quotation" value={agreement.source_quotation_id ? <Link href={`/finance/quotations/${agreement.source_quotation_id}`}>{sourceNo}</Link> : sourceNo} /><Field label="Quotation status" value={quote?.status || text(source.status)} /><Field label="Billing method" value={billingLabels[agreement.billing_method] || agreement.billing_method} /></div><CommercialTerms terms={terms} source={source} /></section>
    <section style={card}><h2>Agreement Items / รายการค่าบริการ</h2>{items.length === 0 ? <div style={warning}>Integrity warning: ไม่มีรายการค่าบริการในข้อตกลง</div> : <ItemsTable items={items} currency={agreement.currency} />}</section>
    <section style={card}><h2>Stored Totals / ยอดที่บันทึก</h2>{mismatch ? <div style={warning}>Integrity warning: ยอดรายการไม่ตรงกับยอด header ของข้อตกลง</div> : null}<div style={grid}><Field label="Amount before VAT" value={money(agreement.amount_before_tax, agreement.currency)} /><Field label="VAT" value={money(agreement.vat_amount, agreement.currency)} /><Field label="Agreement Total" value={money(agreement.total_amount, agreement.currency)} /></div></section>
    <section style={card}><h2>Payment Terms & Allocation Evidence</h2><Evidence value={object(source.payment_terms)} fallback="ไม่มีข้อมูล Payment Terms ใน source snapshot" /><Evidence value={agreement.allocation_snapshot_json || {}} fallback="ไม่มีข้อมูล allocation snapshot" /></section>
    <section style={card}><h2>Legal and Administrative Content / เนื้อหากฎหมายและการบริหาร</h2>{editable ? <><MetadataEditor value={metadata} disabled={saving} onChange={(next) => { setMetadata(next); setDirty(true); }} /><button style={primaryButton} onClick={() => void saveMetadata()} disabled={saving}>{saving ? "Saving..." : "Save Administrative Content"}</button><hr style={divider} /><LegalEditor value={legal} templates={templates} disabled={saving} onChange={(next) => { setLegal(next); setDirty(true); }} /><button style={primaryButton} onClick={() => void saveLegal()} disabled={saving}>{saving ? "Saving..." : "Save Legal Content"}</button></> : <LegalReadOnly agreement={agreement} />}</section>
    <section style={card}><h2>Lifecycle</h2><p style={notice}>{editable ? "Draft และ Under Review แก้ไขได้โดยผู้จัดการ Finance เท่านั้น ทุกการบันทึกจะสร้าง version history" : "สถานะนี้เป็น read-only; commercial evidence และเนื้อหาเอกสารถูกเก็บเป็นหลักฐาน"}</p>{permissions.canEditFinanceQuotation ? <div style={actions}>{lifecycleActions(agreement.status).map((action) => <button key={action.status} style={action.status === "cancelled" ? dangerButton : secondaryButton} disabled={lifecycleSaving} onClick={() => void transition(action.status)}>{lifecycleSaving ? "Working..." : action.label}</button>)}</div> : <p style={muted}>เฉพาะผู้จัดการ Finance เท่านั้นที่เปลี่ยนสถานะได้</p>}</section>
    <section style={card}><h2>Version History / ประวัติเวอร์ชัน</h2>{versions.length === 0 ? <p>ยังไม่มี version history สำหรับ Legacy record นี้</p> : <div style={scroll}><table style={table}><thead><tr><th>Version</th><th>Event</th><th>Actor</th><th>Timestamp</th><th>Reason</th></tr></thead><tbody>{versions.map((version) => <tr key={version.id}><td>v{version.version_no}</td><td>{version.event_type}</td><td>{version.actor_name || version.actor_email || "-"}</td><td>{new Date(version.created_at).toLocaleString("th-TH", { timeZone: "Asia/Bangkok" })}</td><td>{version.reason || "-"}</td></tr>)}</tbody></table></div>}</section>
  </main>;
}

const emptyLegalForm: LegalForm = { language: "th", commencementDate: "", templateVersionId: "", scopeClarification: "", clientObligations: "", firmObligations: "", exclusions: "", expenses: "", confidentiality: "", termination: "", dispute: "", additionalTerms: "", internalNote: "", signatories: "[]", customClauses: "[]" };
function legalFormFrom(agreement: Agreement): LegalForm { const legal = object(agreement.legal_terms_json); return { language: agreement.language_code || "th", commencementDate: agreement.commencement_date || "", templateVersionId: agreement.selected_template_version_id || "", scopeClarification: text(legal.scope_clarification, ""), clientObligations: text(legal.client_obligations, ""), firmObligations: text(legal.firm_obligations, ""), exclusions: text(legal.exclusions, ""), expenses: text(legal.expenses_disbursements, ""), confidentiality: text(legal.confidentiality, ""), termination: text(legal.termination_provisions, ""), dispute: text(legal.dispute_jurisdiction, ""), additionalTerms: text(legal.additional_terms, ""), internalNote: text(legal.internal_note, ""), signatories: prettyJson(agreement.signatories_json), customClauses: prettyJson(agreement.custom_clauses_json) }; }
function blankToNull(value: string) { return value.trim() || null; }
function parseArray(value: string, label: string) { const parsed: unknown = JSON.parse(value || "[]"); if (!Array.isArray(parsed)) throw new Error(`${label} ต้องเป็น JSON array`); return parsed; }
function mapRpcError(error: string) { if (error.includes("Only draft or under review")) return "ข้อตกลงนี้ไม่สามารถแก้ไขในสถานะปัจจุบันได้"; if (error.includes("Not allowed")) return "คุณไม่มีสิทธิ์ดำเนินการนี้"; if (error.includes("template")) return "Template ที่เลือกไม่พร้อมใช้งานหรือภาษาไม่ตรงกัน"; if (error.includes("legal document data")) return "กรุณากรอกข้อมูลเอกสารและผู้ลงนามก่อนส่ง"; if (error.includes("Billing Plan")) return "ต้องยกเลิก Billing Plan ที่ยังมีผลก่อน"; if (error.includes("Invalid")) return "สถานะหรือข้อมูลข้อตกลงไม่ถูกต้อง กรุณารีเฟรช"; return error || "ไม่สามารถบันทึกข้อมูลได้"; }
function lifecycleActions(status: string): Array<{ status: "under_review" | "sent" | "signed" | "completed" | "cancelled"; label: string }> { if (status === "draft") return [{ status: "under_review", label: "Submit for Review" }, { status: "cancelled", label: "Cancel" }]; if (status === "under_review") return [{ status: "sent", label: "Mark Sent" }, { status: "cancelled", label: "Cancel" }]; if (status === "sent") return [{ status: "signed", label: "Mark Signed" }, { status: "cancelled", label: "Cancel" }]; if (status === "signed") return [{ status: "completed", label: "Mark Completed" }]; return []; }
function Field({ label, value }: { label: string; value: ReactNode }) { return <div><small style={muted}>{label}</small><div>{value}</div></div>; }
function StatusBadge({ status }: { status: string }) { return <span style={{ ...badge, ...(badgeColor[status] || {}) }}>{statusLabel[status] || status}</span>; }
function ItemsTable({ items, currency }: { items: Item[]; currency: string }) { return <div style={scroll}><table style={table}><thead><tr><th>No.</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>VAT</th><th>Before VAT</th><th>VAT</th><th>Total</th></tr></thead><tbody>{items.map((item, index) => <tr key={item.id}><td>{index + 1}</td><td>{item.description}</td><td>{item.quantity}</td><td>{money(item.unit_price, currency)}</td><td>{item.vat_applicable ? `${item.vat_rate}%` : "Non-VAT"}</td><td>{money(item.amount_before_tax, currency)}</td><td>{money(item.vat_amount, currency)}</td><td>{money(item.line_total, currency)}</td></tr>)}</tbody></table></div>; }
function CommercialTerms({ terms, source }: { terms: Json; source: Json }) { const values: Array<[string, unknown]> = [["Scope of Legal Services", terms.scope_of_legal_services || source.scope_of_legal_services], ["Included Services", terms.included_services || source.included_services], ["Excluded Services", terms.excluded_services || source.excluded_services], ["Quotation Note", terms.note || source.note]]; return <div>{values.filter(([, value]) => text(value, "") !== "").map(([label, value]) => <div key={label} style={term}><strong>{label}</strong><div style={{ whiteSpace: "pre-wrap" }}>{text(value)}</div></div>)}</div>; }
function Evidence({ value, fallback }: { value: Json; fallback: string }) { return Object.keys(value).length ? <pre style={evidence}>{JSON.stringify(value, null, 2)}</pre> : <p style={muted}>{fallback}</p>; }
function MetadataEditor({ value, disabled, onChange }: { value: MetadataForm; disabled: boolean; onChange: (next: MetadataForm) => void }) { return <div style={formGrid}><Input label="Agreement Title" value={value.title} disabled={disabled} onChange={(title) => onChange({ ...value, title })} /><Input label="Effective Date" type="date" value={value.effectiveDate} disabled={disabled} onChange={(effectiveDate) => onChange({ ...value, effectiveDate })} /><Input label="End / Termination Date" type="date" value={value.expiryDate} disabled={disabled} onChange={(expiryDate) => onChange({ ...value, expiryDate })} /><label style={labelStyle}>Billing Method<select style={input} value={value.billingMethod} disabled={disabled} onChange={(event) => onChange({ ...value, billingMethod: event.target.value })}>{Object.entries(billingLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div>; }
function LegalEditor({ value, templates, disabled, onChange }: { value: LegalForm; templates: Template[]; disabled: boolean; onChange: (next: LegalForm) => void }) { const update = (key: keyof LegalForm, next: string) => onChange({ ...value, [key]: next }); return <div style={formGrid}><label style={labelStyle}>Language<select style={input} value={value.language} disabled={disabled} onChange={(event) => update("language", event.target.value)}><option value="th">Thai</option><option value="en">English</option></select></label><Input label="Commencement Date" type="date" value={value.commencementDate} disabled={disabled} onChange={(next) => update("commencementDate", next)} /><label style={labelStyle}>Published Template Version<select style={input} value={value.templateVersionId} disabled={disabled} onChange={(event) => update("templateVersionId", event.target.value)}><option value="">No template / structured fallback</option>{templates.filter((template) => template.language_code === value.language).map((template) => <option key={template.id} value={template.id}>{template.document_templates?.template_code || "Template"} v{template.version_no} — {template.document_templates?.name || ""}</option>)}</select></label><TextArea label="Scope Clarification" value={value.scopeClarification} disabled={disabled} onChange={(next) => update("scopeClarification", next)} /><TextArea label="Client Obligations" value={value.clientObligations} disabled={disabled} onChange={(next) => update("clientObligations", next)} /><TextArea label="Firm Obligations" value={value.firmObligations} disabled={disabled} onChange={(next) => update("firmObligations", next)} /><TextArea label="Exclusions" value={value.exclusions} disabled={disabled} onChange={(next) => update("exclusions", next)} /><TextArea label="Expenses / Disbursements" value={value.expenses} disabled={disabled} onChange={(next) => update("expenses", next)} /><TextArea label="Confidentiality" value={value.confidentiality} disabled={disabled} onChange={(next) => update("confidentiality", next)} /><TextArea label="Termination Provisions" value={value.termination} disabled={disabled} onChange={(next) => update("termination", next)} /><TextArea label="Dispute / Jurisdiction" value={value.dispute} disabled={disabled} onChange={(next) => update("dispute", next)} /><TextArea label="Additional Terms" value={value.additionalTerms} disabled={disabled} onChange={(next) => update("additionalTerms", next)} /><TextArea label="Signatories (JSON array)" value={value.signatories} disabled={disabled} onChange={(next) => update("signatories", next)} /><TextArea label="Custom Clauses (JSON array)" value={value.customClauses} disabled={disabled} onChange={(next) => update("customClauses", next)} /><TextArea label="Internal Note (never printed)" value={value.internalNote} disabled={disabled} onChange={(next) => update("internalNote", next)} /></div>; }
function LegalReadOnly({ agreement }: { agreement: Agreement }) { const legal = object(agreement.legal_terms_json); const entries = Object.entries(legal).filter(([key]) => key !== "internal_note"); return <div>{entries.length ? entries.map(([key, value]) => <div key={key} style={term}><strong>{key.replaceAll("_", " ")}</strong><div style={{ whiteSpace: "pre-wrap" }}>{text(value)}</div></div>) : <p>ยังไม่มีเนื้อหากฎหมายที่บันทึกไว้</p>}<div style={term}><strong>Signatories</strong><Evidence value={{ signatories: agreement.signatories_json || [] }} fallback="-" /></div><div style={term}><strong>Custom Clauses</strong><Evidence value={{ custom_clauses: agreement.custom_clauses_json || [] }} fallback="-" /></div></div>; }
function Input({ label, value, disabled, onChange, type = "text" }: { label: string; value: string; disabled: boolean; onChange: (value: string) => void; type?: string }) { return <label style={labelStyle}>{label}<input style={input} type={type} value={value} disabled={disabled} onChange={(event) => onChange(event.target.value)} /></label>; }
function TextArea({ label, value, disabled, onChange }: { label: string; value: string; disabled: boolean; onChange: (value: string) => void }) { return <label style={labelStyle}>{label}<textarea style={{ ...input, minHeight: 88, resize: "vertical" }} value={value} disabled={disabled} onChange={(event) => onChange(event.target.value)} /></label>; }

const page: CSSProperties = { maxWidth: 1180, margin: "0 auto", padding: 24 }; const card: CSSProperties = { background: "#fff", border: "1px solid #e5e7eb", borderRadius: 8, padding: 18, marginBottom: 16 }; const grid: CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(190px,1fr))", gap: 14 }; const formGrid: CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(250px,1fr))", gap: 14, marginBottom: 16 }; const actions: CSSProperties = { display: "flex", gap: 12, flexWrap: "wrap", marginBottom: 16 }; const muted: CSSProperties = { color: "#64748b", fontSize: 13 }; const warning: CSSProperties = { background: "#fff7ed", color: "#9a3412", padding: 12, borderRadius: 6, marginBottom: 12 }; const success: CSSProperties = { background: "#dcfce7", color: "#166534", padding: 12, borderRadius: 6, marginBottom: 12 }; const notice: CSSProperties = { background: "#f8fafc", borderLeft: "3px solid #64748b", color: "#334155", padding: 12 }; const scroll: CSSProperties = { overflowX: "auto" }; const table: CSSProperties = { width: "100%", minWidth: 780, borderCollapse: "collapse" }; const term: CSSProperties = { padding: "10px 0", borderBottom: "1px solid #e5e7eb" }; const evidence: CSSProperties = { margin: "10px 0", padding: 12, background: "#f8fafc", borderRadius: 6, overflowX: "auto", whiteSpace: "pre-wrap", fontSize: 12 }; const divider: CSSProperties = { border: 0, borderTop: "1px solid #e5e7eb", margin: "20px 0" }; const labelStyle: CSSProperties = { display: "grid", gap: 6, color: "#334155", fontSize: 14 }; const input: CSSProperties = { boxSizing: "border-box", width: "100%", minWidth: 0, border: "1px solid #cbd5e1", borderRadius: 6, padding: "9px 10px", background: "#fff", font: "inherit" }; const primaryButton: CSSProperties = { border: 0, borderRadius: 6, padding: "10px 14px", background: "#166534", color: "#fff", cursor: "pointer", marginBottom: 12 }; const secondaryButton: CSSProperties = { border: "1px solid #94a3b8", borderRadius: 6, padding: "9px 12px", background: "#fff", color: "#334155", cursor: "pointer" }; const dangerButton: CSSProperties = { ...secondaryButton, borderColor: "#fecaca", color: "#b91c1c" }; const badge: CSSProperties = { display: "inline-block", padding: "3px 8px", borderRadius: 999, fontSize: 12 }; const badgeColor: Record<string, CSSProperties> = { draft: { background: "#e5e7eb", color: "#374151" }, under_review: { background: "#fef3c7", color: "#92400e" }, sent: { background: "#dbeafe", color: "#1d4ed8" }, signed: { background: "#dcfce7", color: "#166534" }, completed: { background: "#e0e7ff", color: "#3730a3" }, cancelled: { background: "#fee2e2", color: "#b91c1c" }, active: { background: "#f3f4f6", color: "#4b5563" } };
