import type { MessageCatalog } from "../core";
const pairs: Record<string, [string, string]> = {
 legacySection: ["ระบบเดิม", "Legacy systems"],
 checkTitle: ["ข้อควรตรวจสอบก่อนยืนยัน", "Review before confirming"], checkPayee: ["ผู้รับและบัญชีปลายทาง", "Payee and destination"], checkRights: ["สิทธิและยอดเต็มแต่ละรายการ", "Rights and full component amounts"], checkTax: ["การหักภาษีของแต่ละรายการ", "Each component's withholding treatment"], checkAccount: ["บัญชีบริษัทและยอดโอนจริง", "Company account and actual payment"], reference: ["เลขที่รายการ", "Payout reference"],
 title: ["จ่ายเงิน (Payout)", "Payout"], subtitle: ["ชำระสิทธิที่รอจ่าย ตรวจสอบภาษี และบันทึกการจ่ายเงินจริงจากบัญชีของบริษัท", "Settle payable rights, review withholding and record the company's actual cash payment."],
 recipient: ["เลือกผู้รับเงิน", "Choose payee"], choose: ["เลือก", "Select"], internal: ["บุคลากร VP", "VP person"], external: ["บุคคลภายนอก", "External payee"], add: ["เพิ่มผู้รับเงินภายนอก", "Add external payee"], edit: ["ข้อมูลผู้รับเงิน", "Payee details"],
 natural_person: ["บุคคลธรรมดา", "Individual"], juristic_person: ["นิติบุคคล", "Legal entity"], entity: ["ประเภทผู้รับ", "Entity type"], name: ["ชื่อ / ชื่อจดทะเบียน", "Name / legal name"], taxId: ["เลขประจำตัวผู้เสียภาษี", "Tax ID"], bank: ["ธนาคารผู้รับ", "Recipient bank"], accountName: ["ชื่อบัญชี", "Account name"], accountNumber: ["เลขบัญชี", "Account number"],
 identityHelp: ["บันทึกชื่อผู้รับได้ก่อน แล้วเติมข้อมูลภาษีและบัญชีเมื่อจำเป็นก่อนจ่าย", "Save the identity first. Complete tax and bank details before a payment needs them."], ready: ["ข้อมูลพร้อมจ่าย", "Payment details complete"], bankMissing: ["ข้อมูลรับเงินยังไม่ครบ", "Bank destination incomplete"], taxMissing: ["ข้อมูลภาษียังไม่ครบ", "Tax identity incomplete"], inactive: ["ผู้รับเงินไม่ใช้งาน", "Inactive payee"], active: ["ใช้งาน", "Active"],
 rights: ["เลือกสิทธิที่รอจ่าย", "Choose payable rights"], selected: ["เลือกแล้ว {count} รายการ", "{count} selected"], selectAll: ["เลือกทั้งหมด", "Select all"], noRights: ["ไม่มีสิทธิที่รอจ่ายสำหรับผู้รับรายนี้", "No open rights for this payee"],
 wht: ["การหักภาษี ณ ที่จ่าย (WHT ขาออก)", "Outgoing withholding tax"], whtHelp: ["เลือกตามแต่ละรายการ ระบบคำนวณยอดหักและยอดโอนจริงให้ อัตราที่เสนอไม่ใช่คำวินิจฉัยทางภาษี", "Choose treatment per component. Withholding and net payment are calculated; offered rates are not a tax determination."], none: ["ไม่หัก", "No withholding"], other: ["อื่น ๆ", "Other"], rate: ["อัตรา (%)", "Rate (%)"],
 account: ["เลือกบัญชีสำหรับจ่ายเงิน", "Company payment account"], date: ["วันที่จ่ายเงินจริง", "Actual payment date"], note: ["หมายเหตุการจ่าย (ไม่บังคับ)", "Payment note (optional)"], summary: ["สรุปการจ่ายเงิน", "Payment summary"], gross: ["ยอดสิทธิที่เลือกจ่าย", "Selected gross rights"], withheld: ["ภาษีหัก ณ ที่จ่าย (WHT)", "Withheld tax (WHT)"], net: ["ยอดโอนจริง", "Actual cash payment"], before: ["ยอดตามระบบก่อนจ่าย", "System balance before payment"], after: ["ยอดตามระบบหลังจ่าย", "System balance after payment"], unknown: ["ยังไม่มียอดตั้งต้นที่ยืนยันแล้ว", "No confirmed opening balance"], balanceHelp: ["ยอดตามระบบ ไม่ใช่ยอดกระทบธนาคาร", "System balance, not a reconciled bank balance"], negative: ["ยอดตามระบบหลังจ่ายติดลบ โปรดตรวจสอบก่อนยืนยัน", "The resulting system balance is negative. Review before confirming."],
 save: ["บันทึกร่าง", "Save draft"], review: ["ตรวจสอบและยืนยัน", "Review and confirm"], confirm: ["ยืนยันการจ่ายเงินจริง", "Confirm actual payment"], confirmHelp: ["ยืนยันเมื่อจ่ายเงินจริงแล้ว ระบบจะบันทึกเงินออกหนึ่งรายการ ไม่ได้สั่งโอนเงินผ่านธนาคาร", "Confirm only after paying. This records one cash outflow; it does not initiate a bank transfer."], ack: ["ตรวจสอบผู้รับ สิทธิ ภาษี บัญชี และยอดจ่ายแล้ว และได้จ่ายเงินจริงแล้ว", "I checked the payee, rights, tax, account and amount, and the actual payment has occurred."], cancel: ["ยกเลิกร่าง", "Cancel draft"], cancelHelp: ["ยกเลิกเฉพาะร่างนี้ ไม่มีการจ่ายเงินหรือเปลี่ยนสิทธิ", "Cancel this draft only. No cash movement or entitlement settlement occurs."], history: ["ประวัติการจ่ายเงินของผู้รับรายนี้", "Payee payout history"], emptyHistory: ["ยังไม่มีรายการจ่ายเงิน", "No payouts yet"], draft: ["ร่าง", "Draft"], confirmed: ["จ่ายแล้ว", "Paid"], cancelled: ["ยกเลิก", "Cancelled"], done: ["เสร็จสิ้น", "Complete"], dirty: ["บันทึกการเปลี่ยนแปลงก่อนยืนยัน", "Save changes before confirmation"], saved: ["บันทึกแล้ว", "Saved"], readOnly: ["หลักฐานการจ่ายที่ยืนยันแล้ว แก้ไขไม่ได้", "Confirmed payment evidence is read-only"], required: ["เลือกผู้รับ สิทธิ ภาษี และบัญชีให้ครบถ้วน", "Complete the payee, rights, withholding and account selections"], failed: ["ดำเนินการไม่สำเร็จ โปรดโหลดข้อมูลใหม่และลองอีกครั้ง", "The action failed. Reload and try again."], stale: ["ข้อมูลเปลี่ยนแปลง โปรดโหลดใหม่ก่อนยืนยัน", "Evidence changed. Reload before confirming."], permission: ["ไม่มีสิทธิ์ดำเนินการนี้", "You do not have permission for this action"], cutoff: ["วันที่จ่ายต้องอยู่หลังวันตัดยอดตั้งต้น", "Payment must be after the opening cutoff"], reviewStep: ["กำหนดภาษีและบัญชี", "Tax and account"], settled: ["จ่ายสิทธิแล้ว", "Settled rights"], outgoingHeld: ["WHT ขาออกที่หักไว้", "Outgoing WHT withheld"], outgoingDue: ["WHT ขาออกรอนำส่ง", "Outgoing WHT awaiting remittance"], notRemitted: ["ยังไม่ยื่น / ยังไม่นำส่ง", "Unfiled / not remitted"],
};
export const payoutMessages: MessageCatalog = Object.fromEntries(Object.entries(pairs).map(([key, [th, en]]) => [`payout.${key}`, { th, en }]));
