import type { MessageCatalog } from "../core";
const labels: Record<string, [string, string]> = {
 title: ["การจัดสรรรายได้", "Revenue Distribution"],
 description: ["จัดสรรรายได้จากเงินรับที่ยืนยันแล้ว แบ่งส่วนบริษัทและผู้ร่วมงาน และติดตามสถานะการจัดสรร", "Allocate confirmed receipts between the company and participants, and track distribution status."],
 pending: ["รอจัดสรร", "To allocate"], unpaid: ["รอจ่าย", "Unpaid"], partial: ["จ่ายบางส่วน", "Partially paid"], paid: ["จ่ายครบ", "Paid"], history: ["ประวัติ", "History"], confirmed: ["ยืนยันแล้ว · ไม่มีส่วนบุคคลรอจ่าย", "Confirmed · no individual shares due"],
 all: ["ทั้งหมด", "All"], month: ["เดือนที่รับเงิน", "Receipt month"], source: ["แหล่งที่มา", "Source"], payment: ["Payment · รับชำระใบแจ้งหนี้", "Payment · Invoice settlement"], direct_money_receipt: ["Direct Money · รับเงินตรง", "Direct Money"],
 search: ["ค้นหาเลขอ้างอิง ลูกค้า คดี / งาน", "Search reference, client or matter"], status: ["สถานะ", "Status"], date: ["วันที่รับเงิน", "Received date"], reference: ["เลขอ้างอิง", "Reference"], client: ["ลูกค้า / ผู้ชำระ", "Client / payer"], matter: ["คดี / งาน", "Case / Advisory"], account: ["บัญชี / จุดรับเงิน", "Receiving account / cash location"], cash: ["เงินรับจริง", "Actual cash"], basis: ["ฐานจัดสรร", "Distribution basis"], basisTitle: ["ฐานรายได้สำหรับจัดสรร", "Revenue basis for distribution"], vat: ["VAT", "VAT"], wht: ["WHT ที่ลูกค้าหักไว้", "Incoming WHT credit"], gross: ["ยอดก่อนหัก WHT", "Settlement before WHT"],
 basisHelp: ["ไม่รวม VAT · ไม่หัก WHT ที่ลูกค้าหักไว้ · ใช้ฐานรายได้ต้นทางที่ยืนยันแล้ว", "Excludes VAT · incoming WHT does not reduce the basis · uses authoritative source revenue"],
 v1: ["รายการเดิม: คงฐานและผลจัดสรรตามนโยบายเดิม ไม่คำนวณใหม่", "Historical distribution: original policy and amounts are preserved."],
 facts: ["ข้อมูลเงินรับ (จากระบบ)", "Receipt facts (from source)"], formula: ["สูตรการจัดสรรและผู้รับส่วนแบ่ง", "Distribution formula and participants"], summary: ["สรุปการจัดสรร", "Distribution summary"], company: ["ส่วนบริษัท", "Company share"], individuals: ["ส่วนบุคคล", "Individual shares"], total: ["รวมจัดสรร", "Total allocated"], remaining: ["คงเหลือ", "Remaining"],
 allocate: ["จัดสรร", "Allocate"], detail: ["ดูรายละเอียด", "View details"], confirm: ["ยืนยันการจัดสรร", "Confirm distribution"], draft: ["บันทึกฉบับร่าง", "Save draft"], note: ["หมายเหตุ (ถ้ามี)", "Note (optional)"], saved: ["บันทึกแล้ว", "Saved"], success: ["ยืนยันการจัดสรรแล้ว", "Distribution confirmed"],
 confirmHelp: ["เมื่อยืนยัน ระบบจะตรึงส่วนบริษัทและส่วนบุคคล โดยยังไม่เกิดการจ่ายเงินหรือบันทึกเงินเข้าบริษัท", "Confirmation freezes company and individual shares. It does not pay money or post company income."],
 sourceLink: ["ดูรายการต้นทาง", "View source"], back: ["กลับ", "Back"], breakdown: ["รายละเอียดฐานรายรายการ", "Source line breakdown"], audit: ["ประวัติการจัดสรร", "Distribution history"], role: ["บทบาท", "Role"], recipient: ["ผู้รับส่วนแบ่ง", "Recipient"], percent: ["เปอร์เซ็นต์", "Percent"], amount: ["จำนวนเงิน", "Amount"],
 blocked: ["ต้องตรวจข้อมูลต้นทาง", "Source evidence required"], partialBlock: ["ยังไม่สามารถจัดสรรรายการรับชำระบางส่วนนี้ได้ เนื่องจากยังไม่มีฐานรายได้รายรายการที่ยืนยันได้", "This partial receipt cannot be allocated until authoritative revenue evidence is available for each line."],
 unknown: ["ยังยืนยันฐานไม่ได้", "Basis unresolved"], unresolved: ["มีรายการที่ยังยืนยันฐานไม่ได้", "Includes unresolved bases"], empty: ["ไม่พบรายการตามตัวกรอง", "No matching receipts"], readonly: ["ดูข้อมูลได้ การแก้ไขและยืนยันจำกัดเฉพาะผู้ดูแลระบบ", "Read-only. Distribution changes and confirmation require Admin."], retry: ["โหลดข้อมูลล่าสุด", "Reload current data"], conflict: ["ข้อมูลอาจเปลี่ยนแปลง กรุณาโหลดข้อมูลล่าสุดก่อนดำเนินการต่อ", "The operation may have completed or the source changed. Reload before continuing."], invalid: ["กรุณาตรวจสูตร ผู้รับ และยอดรวมให้ตรงกับฐานจัดสรร", "Check the formula, recipients and exact allocation total."], rows: ["รายการ", "items"], previous: ["ก่อนหน้า", "Previous"], next: ["ถัดไป", "Next"], review: ["ตรวจแล้ว · รอยืนยัน", "Reviewed · awaiting confirmation"], drafting: ["ฉบับร่าง", "Draft"], sourceOnly: ["ยอดที่จัดเข้าบริษัทโดยตรงตามประเภทต้นทาง", "Amounts routed directly to the company by source classification"],
};
export const revenueDistributionMessages: MessageCatalog = Object.fromEntries(Object.entries(labels).map(([key, [th, en]]) => [`revenueDistribution.${key}`, { th, en }]));
