'use client';
import {useEffect,useRef,useState} from 'react';
import {Send,FileText} from 'lucide-react';
import {supabase} from '../../../lib/supabase';
import {SearchableCombobox} from '../../finance/expenses/searchable-combobox';
import CaseEditModal from './CaseEditModal';
import {CoreEditor} from './CaseCore';
import {useCaseDetailText} from './labels';
import {loadAssignmentPeople} from './core-people';
import {personLabel,primaryAction,type CoreData} from './core-model';
import {answerSuggestion,defaultSuggestion,lawfulAttempt,serviceStatus,answerStatus,answerDeadlineState,latestServiceAttempt,serviceNextSuggestion,serviceAttemptChanges,serviceFlowSuggestions,serviceError,type ServiceAction,type ServiceData,type ServicePerson,type ServiceAttempt,type AnswerRequest} from './service-model';
import {useCaseBusinessDate} from './use-case-business-date';
import base from './case-detail.module.css';
import css from './case-service.module.css';

type Editor={action:Exclude<ServiceAction,'absence'>;person?:ServicePerson;attempt?:ServiceAttempt;kind?:'answer'|'default'|'court';defaultMotion?:boolean};
export default function CaseService({caseId,revision,canRecord,canConfirm,onExtend,answerRequest}:{caseId:number;revision:number;canRecord:boolean;canConfirm:boolean;onExtend:(partyId:string,deadlineId:string)=>void;answerRequest?:AnswerRequest|null}){
 const today=useCaseBusinessDate();
 const {tr,date}=useCaseDetailText();const [data,setData]=useState<ServiceData|null>(null),[failed,setFailed]=useState(false),[view,setView]=useState<'service'|'answer'|null>(null),[editor,setEditor]=useState<Editor|null>(null),[reload,setReload]=useState(0),[review,setReview]=useState<ServicePerson|null>(null);
 const [answerParty,setAnswerParty]=useState<string|null>(null);
 const [handledAnswer,setHandledAnswer]=useState<AnswerRequest|null>(null);
 if((answerRequest??null)!==handledAnswer){setHandledAnswer(answerRequest??null);if(answerRequest){setAnswerParty(answerRequest.partyId);setView('answer');setEditor(null);setReview(null);}}
 useEffect(()=>{let live=true;void(async()=>{const r=await supabase.rpc('case102_read',{p_case_id:caseId});if(live){setFailed(!!r.error);if(!r.error)setData(r.data as ServiceData);}})().catch(()=>{if(live)setFailed(true);});return()=>{live=false;};},[caseId,revision,reload]);
 if(failed)return <p className={base.notice} role="alert">{tr('service.loadError')} <button onClick={()=>setReload(n=>n+1)}>{tr('Reload')}</button></p>;
 if(!data?.flow)return null;
 const edit=(value:Editor)=>{setEditor(value);};const legal=canConfirm&&data.flow.lifecycle==='active',record=canRecord&&data.flow.lifecycle==='active';
 const required=data.defendants.filter(p=>p.control?.required!==false),done=required.filter(p=>serviceStatus(p)==='served').length;
 const closeEditor=()=>setEditor(null);
 const openExtension=(partyId:string,deadlineId:string)=>{setView(null);onExtend(partyId,deadlineId);};
 return <>
 <section className={css.card} aria-label={tr('service.title')}><div className={css.heading}><Send size={20}/><div><h2>{tr('service.title')}</h2><p>{tr('service.summary')} {done} / {required.length}</p></div></div><div className={css.compact}>{data.defendants.map(p=><span key={p.id}>{p.name||tr('service.unnamed')} <small data-state={serviceStatus(p)}>{tr('service.status.'+serviceStatus(p))}</small>{latestServiceAttempt(p)&&<small>{tr(latestServiceAttempt(p)!.method?'service.method.'+latestServiceAttempt(p)!.method:'service.methodUnknown')} · {date(latestServiceAttempt(p)!.attempted_on)}</small>}</span>)}{data.defendants.length===0&&<span>{tr('service.noDefendants')}</span>}</div><button className={base.secondary} onClick={()=>setView('service')}>{tr('service.manage')}</button></section>
 <section className={css.card} aria-label={tr('answer.title')}><div className={css.heading}><FileText size={20}/><div><h2>{tr('answer.title')}</h2><p>{tr('answer.separateTrack')}</p></div></div><div className={css.compact}>{data.defendants.map(p=>{const state=answerDeadlineState(p.control,p.answer_deadline,today);return <span key={p.id}>{p.name||tr('service.unnamed')} <small data-state={answerStatus(p,today)}>{tr('answer.status.'+answerStatus(p,today))}</small>{p.control?.answer_filed_on?<small>{tr('service.answeredOn')} {date(p.control.answer_filed_on)}</small>:state.status!=='unconfirmed'&&p.answer_deadline?.current_due_date&&<small>{date(p.answer_deadline.current_due_date)}</small>}{state.overdueDays>0&&<><small data-state="overdue">{tr('answer.overdueDays').replace('{days}',String(state.overdueDays))}</small><span className={css.overdueWarning}>{tr('answer.overdueHint')}</span></>}</span>;})}{!data.defendants.length&&<span>{tr('service.noDefendants')}</span>}</div><button className={base.secondary} onClick={()=>{setAnswerParty(null);setView('answer');}}>{tr('answer.manage')}</button></section>
 {view&&!editor&&!review&&<CaseEditModal title={tr(view==='service'?'service.title':'answer.title')} className={css.viewer} onClose={()=>setView(null)}>{view==='service'?<ServiceView data={data} canRecord={record} canConfirm={legal} onEdit={edit}/>:<AnswerView today={today} data={data} canRecord={record} canConfirm={legal} onEdit={edit} onExtensions={openExtension} onReview={setReview} partyId={answerParty} onAll={()=>setAnswerParty(null)}/>}</CaseEditModal>}
 {review&&<DefaultMotionReview person={review} data={data} onClose={()=>setReview(null)} onProceed={()=>{setReview(null);setEditor({action:review.control?.default_deadline_id?'next':'deadline',kind:'default',person:review,defaultMotion:true});}}/>}
 {editor&&<ServiceEditor key={editor.action+editor.kind+editor.person?.id} {...editor} canConfirm={legal} data={data} caseId={caseId} onClose={closeEditor} onSaved={value=>{setData(value);setEditor(editor.action==='deadline'&&editor.kind==='default'?{action:'next',person:value.defendants.find(p=>p.id===editor.person?.id),defaultMotion:true}:null);window.dispatchEvent(new Event('case-detail-updated'));}}/>}
 </>;
}

function ServiceView({data,canRecord,canConfirm,onEdit}:{data:ServiceData;canRecord:boolean;canConfirm:boolean;onEdit:(v:Editor)=>void}){
 const {tr,date}=useCaseDetailText();
 return <div className={css.body}><p className={css.hint}>{tr('service.onlyServiceHint')}</p>{!data.defendants.length&&<p>{tr('service.noDefendants')}</p>}{data.defendants.map((p,index)=>{const latest=latestServiceAttempt(p);return <article className={css.person} key={p.id}><header><strong>{index+1}. {p.name||tr('service.unnamed')}</strong><span className={css.badge} data-state={serviceStatus(p)}>{tr('service.status.'+serviceStatus(p))}</span></header>
 {!latest&&<p className={css.hint}>{tr('service.noAttemptHint')}</p>}
 <dl><div><dt>{tr('service.latest')}</dt><dd>{latest?`${tr(latest.method?'service.method.'+latest.method:'service.methodUnknown')} · ${date(latest.attempted_on)} · ${tr('service.status.'+latest.result)}`:tr('service.noAttempt')}</dd></div></dl>
 {latest?.result==='failed'&&<p className={css.warning}>{latest.failure_reason}<br/>{tr(latest.failure_kind==='demolished'?'service.demolishedSuggestion':latest.failure_kind==='not_found'?'service.notFoundSuggestion':'service.investigateSuggestion')}</p>}
 {canRecord&&<div className={css.actions}><button className={base.secondary} onClick={()=>onEdit({action:'attempt',person:p})}>{tr('service.record')}</button>{latest?.result==='pending'&&<button className={base.secondary} onClick={()=>onEdit({action:'attempt',person:p,attempt:latest})}>{tr('service.updatePending')}</button>}{(!latest||latest.result!=='served')&&<button className={base.secondary} onClick={()=>onEdit({action:'next',person:p})}>{tr('service.followupAction')}</button>}</div>}
 <details><summary>{tr('service.historyMore')}</summary><div className={css.actions}>{canConfirm&&<><button className={base.secondary} onClick={()=>onEdit({action:'deadline',person:p,kind:'court'})}>{tr('service.courtDue')}</button><button className={base.secondary} onClick={()=>onEdit({action:'required',person:p})}>{tr('service.requiredScope')}</button></>}</div>{p.control?.exemption_reason&&<p>{p.control.exemption_reason}</p>}{p.attempts.map(a=><div className={css.history} data-current={a.id===latest?.id} data-void={a.result==='void'} key={a.id}><div className={css.historyHeading}><strong>{date(a.attempted_on)} · {tr(a.method?'service.method.'+a.method:'service.methodUnknown')}</strong><span className={css.badge} data-state={a.result}>{tr('service.status.'+a.result)}</span>{a.id===latest?.id&&<small className={css.currentResult}>{tr('service.currentResult')}</small>}</div>{a.failure_reason&&<p>{a.failure_reason}</p>}{a.note&&<p>{a.note}</p>}{a.void_reason&&<p>{tr('service.voidReason')}: {a.void_reason}</p>}{canRecord&&a.result==='pending'&&a.id!==latest?.id&&<button className={base.coreTextButton} onClick={()=>onEdit({action:'attempt',person:p,attempt:a})}>{tr('service.updatePending')}</button>}{canConfirm&&a.result!=='void'&&<button className={base.coreTextButton} onClick={()=>onEdit({action:'void',person:p,attempt:a})}>{tr('service.void')}</button>}</div>)}{data.history.filter(e=>e.party_id===p.id&&['attempt','lawful','void','required'].includes(e.action)).map(e=><div className={css.history} key={e.id}><strong>{tr(e.action==='attempt'&&serviceAttemptChanges(e).length?'service.historyCorrection':'service.action.'+e.action)}</strong><small>{e.actor_name} · {date(e.occurred_at,true)}</small>{serviceAttemptChanges(e).map(change=><div key={change.after.id} className={css.auditChange}>{(['before','after'] as const).map(side=><p key={side} data-side={side}><strong>{tr('service.audit.'+side)}: </strong>{tr(change[side].method?'service.method.'+change[side].method:'service.methodUnknown')} · {date(change[side].attempted_on)} · {tr('service.status.'+change[side].result)}{change[side].failure_reason&&<><br/>{change[side].failure_reason}</>}{change[side].note&&<><br/>{change[side].note}</>}{change[side].void_reason&&<><br/>{tr('service.voidReason')}: {change[side].void_reason}</>}</p>)}</div>)}</div>)}</details>
 </article>;})}</div>;
}
function AnswerView({data,today=data.today,canRecord,canConfirm,onEdit,onExtensions,onReview,partyId,onAll}:{data:ServiceData;canRecord:boolean;canConfirm:boolean;onEdit:(v:Editor)=>void;onExtensions:(partyId:string,deadlineId:string)=>void;partyId?:string|null;onAll?:()=>void;onReview:(p:ServicePerson)=>void;today?:string}){
 const {tr,date}=useCaseDetailText();const flow=serviceFlowSuggestions(data);
 return <div className={css.body}><p className={css.hint}>{tr('answer.separateTrack')}</p>{partyId&&onAll&&<button className={base.coreTextButton} onClick={onAll}>{tr('answer.showAllDefendants')}</button>}{!data.defendants.length&&<p>{tr('service.noDefendants')}</p>}{data.defendants.filter(p=>!partyId||p.id===partyId).map((p,index)=>{const state=answerDeadlineState(p.control,p.answer_deadline,today),due=state.status==='unconfirmed'?null:p.answer_deadline,status=answerStatus(p,today),lawful=lawfulAttempt(p);return <article className={css.person} key={p.id}><header><strong>{index+1}. {p.name||tr('service.unnamed')}</strong><span className={css.badge} data-state={status}>{tr('answer.status.'+status)}</span></header>
 <dl><div><dt>{tr('service.answerDue')}</dt><dd>{due?`${date(due.current_due_date)} · ${tr(due.deleted_at?'service.removed':'service.deadlineStatus.'+due.status)}`:tr('service.noDeadline')}</dd></div>{p.control?.answer_filed_on&&<div><dt>{tr('service.answeredOn')}</dt><dd>{date(p.control.answer_filed_on)}</dd></div>}{p.default_deadline&&<div><dt>{tr('service.defaultDue')}</dt><dd>{date(p.default_deadline.current_due_date)} · {tr(p.default_deadline.deleted_at?'service.removed':'service.deadlineStatus.'+p.default_deadline.status)}</dd></div>}</dl>
 {state.overdueDays>0&&<><span className={css.badge} data-state="overdue">{tr('answer.overdueDays').replace('{days}',String(state.overdueDays))}</span><p className={css.warning}>{tr('answer.overdueHint')}</p></>}
 <div className={css.actions}>{canConfirm&&<>{lawful&&!p.control?.answer_filed_on&&!p.control?.answer_deadline_id&&<button className={base.secondary} onClick={()=>onEdit({action:'deadline',person:p,kind:'answer'})}>{tr('service.confirmAnswerDue')}</button>}{!p.control?.answer_filed_on&&<button className={base.secondary} onClick={()=>onEdit({action:'answer',person:p})}>{tr('service.recordAnswer')}</button>}{defaultSuggestion(p,data.today)&&<button className={base.secondary} onClick={()=>onReview(p)}>{tr('answer.confirmNotFiled')}</button>}</>}{canRecord&&!p.control?.answer_filed_on&&due&&!due.deleted_at&&due.status==='Active'&&<button className={base.secondary} onClick={()=>onExtensions(p.id,due.id)}>{tr('service.manageExtensions')}</button>}</div>
 <details><summary>{tr('answer.history')}</summary>{!p.extensions.length&&<p>{tr('answer.noExtensions')}</p>}{p.extensions.map(e=><p key={e.id}>{tr('service.extension')} {e.extension_no} · {date(e.granted_until_date)} · {e.note}</p>)}{data.history.filter(e=>e.party_id===p.id&&['deadline','answer','next','absence'].includes(e.action)).map(e=><div className={css.history} key={e.id}><strong>{tr('service.action.'+e.action)}</strong><small>{e.actor_name} · {date(e.occurred_at,true)}</small></div>)}</details>
 </article>;})}{canConfirm&&(flow.advance||flow.branch)&&<div className={css.suggestions}><p>{tr('service.flowHint')}</p>{flow.advance&&<button className={base.primary} onClick={()=>onEdit({action:'advance'})}>{tr('service.advance')}</button>}{flow.branch&&<button className={base.secondary} onClick={()=>onEdit({action:'branch'})}>{tr('service.branch')}</button>}</div>}</div>;
}
function DefaultMotionReview({person,data,onClose,onProceed}:{person:ServicePerson;data:ServiceData;onClose:()=>void;onProceed:()=>void}){
 const {tr,date}=useCaseDetailText();const [notFiled,setNotFiled]=useState(false),[choice,setChoice]=useState('');
 return <CaseEditModal title={tr('answer.confirmNotFiled')} className={css.editor} onClose={onClose}><div className={base.coreForm}><p className={css.identity}>{person.name}</p><p>{tr('service.answerDue')}: {date(person.answer_deadline?.current_due_date)}</p><p className={css.hint}>{tr('answer.overdueHint')}</p><div className={css.fields}><label className={css.check}><input type="checkbox" checked={notFiled} onChange={e=>{setNotFiled(e.target.checked);setChoice('');}}/>{tr('answer.confirmNotFiled')}</label>{notFiled&&<fieldset className={css.fields}><legend>{tr('answer.motionQuestion')}</legend>{['yes','no'].map(v=><label key={v} className={css.check}><input type="radio" name="motion-decision" value={v} checked={choice===v} onChange={()=>setChoice(v)}/>{tr('answer.motion.'+v)}</label>)}</fieldset>}{notFiled&&choice==='no'&&<p className={css.hint}>{tr('answer.noMotionHint')}</p>}</div><footer className={base.coreFooter}><button className={base.secondary} onClick={onClose}>{tr('Close')}</button>{notFiled&&choice==='yes'&&<button className={base.primary} disabled={!defaultSuggestion(person,data.today)} onClick={onProceed}>{tr(person.control?.default_deadline_id?'answer.existingMotionNext':'service.confirmDefaultDue')}</button>}</footer></div></CaseEditModal>;
}
function ServiceEditor({action,person,attempt,kind='answer',defaultMotion=false,canConfirm=false,data,caseId,onClose,onSaved}:Editor&{canConfirm?:boolean;data:ServiceData;caseId:number;onClose:()=>void;onSaved:(d:ServiceData)=>void}){
 const {tr,date}=useCaseDetailText();const suggestion=action==='deadline'&&person?(kind==='default'?defaultSuggestion(person,data.today):kind==='answer'?answerSuggestion(person):null):null;
 const [method,setMethod]=useState<NonNullable<ServiceAttempt['method']>|''>(attempt?.method||''),[day,setDay]=useState(attempt?.attempted_on||''),[result,setResult]=useState(attempt?.result==='void'?'pending':attempt?.result||'served');
 const [failure,setFailure]=useState(attempt?.failure_kind||'investigating'),[failureReason,setFailureReason]=useState(attempt?.failure_reason||''),[reason,setReason]=useState(action==='void'?'':attempt?.note||''),[due,setDue]=useState(suggestion||''),[confirmed,setConfirmed]=useState(false),[required,setRequired]=useState(person?.control?.required!==false),[existing,setExisting]=useState('');
 const [core,setCore]=useState<CoreData|null>(null),[mode,setMode]=useState('manual'),[task,setTask]=useState(''),[title,setTitle]=useState(()=>{const key=defaultMotion?'service.defaultMotionNext':person&&serviceNextSuggestion(person);return key?`${tr(key)} — ${person!.name||tr('service.unnamed')}`:'';}),[assignee,setAssignee]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[teamEditor,setTeamEditor]=useState(false);const lock=useRef(false),retry=useRef<{body:string;id:string}|null>(null);
 useEffect(()=>{if(action!=='next')return;let live=true;void(async()=>{const r=await supabase.rpc('case098_read',{p_case_id:caseId});if(r.error)throw r.error;const c=await loadAssignmentPeople(r.data as CoreData,supabase);if(live)setCore(c);})().catch(()=>{if(live)setError('service.loadError');});return()=>{live=false;};},[action,caseId]);
 async function save(e:React.FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{
  if(action==='deadline'&&kind==='default'&&(!defaultMotion||!canConfirm||!person||!defaultSuggestion(person,data.today))){setError('CASE102_CONFIRM_REQUIRED');return;}
  let payload:Record<string,unknown>={};const d=existing?data.deadlines.find(x=>x.id===existing):person?.answer_deadline;
  const expected={expected_due:d?.current_due_date||null,expected_updated_at:d?.updated_at||null};
  if(action==='attempt')payload={attempt_id:attempt?.id||null,method:method||null,attempted_on:day||null,result,...(canConfirm&&result==='served'&&!person?.control?.lawful_attempt_id?{confirm_lawful:true}:{}),failure_kind:result==='failed'?failure:null,failure_reason:result==='failed'?failureReason:null,note:reason||null};
  if(action==='lawful')payload={attempt_id:attempt?.id,confirmed:true};
  if(action==='void')payload={attempt_id:attempt?.id,reason};
  if(action==='required')payload={required,reason};
  if(action==='deadline')payload={kind,due:existing?null:due,existing_id:existing||null,confirmed,reason:kind==='default'?`${tr('answer.confirmNotFiled')} · ${tr('answer.motion.yes')}${reason?' — '+reason:''}`:reason||null,...expected};
  if(action==='answer')payload={date:day,...expected};
  if(action==='advance'||action==='branch')payload={flow_version:data.flow?.version,confirmed,...(action==='branch'?{reason}:{})};
  if(action==='next'){if(!core)throw Error('service.loadError');payload={core_version:core.core?.version||0,next:mode==='task'?{mode,task_id:task}:{mode:'manual',title,assignee_id:assignee||null,due:due||null}};}
  const body=JSON.stringify(payload);if(retry.current?.body!==body)retry.current={body,id:crypto.randomUUID()};
  const r=await supabase.rpc('case102_save',{p_case_id:caseId,p_party_id:person?.id||null,p_version:person?.control?.version||0,p_request_id:retry.current!.id,p_action:action,p_data:payload});if(r.error){setError(serviceError(r.error.message));return;}onSaved(r.data as ServiceData);
 }catch{setError('service.saveError');}finally{lock.current=false;setBusy(false);}}
 const currentNext=core?primaryAction(core):null;
 const correctingFacts=!!attempt&&(method!==(attempt.method||'')||day!==(attempt.attempted_on||''));
 const needsConfirm=['deadline','advance','branch'].includes(action);
 if(teamEditor&&core)return <CoreEditor mode="team" data={core} caseId={caseId} onClose={()=>setTeamEditor(false)} onSaved={value=>{setCore(value);setTeamEditor(false);window.dispatchEvent(new Event('case-detail-updated'));}}/>;
 return <CaseEditModal title={tr(action==='attempt'&&attempt?'service.updatePending':'service.action.'+action)} className={css.editor} busy={busy} onClose={onClose}><form className={base.coreForm} onSubmit={save}>{person&&<p className={css.identity}>{person.name||tr('service.unnamed')}</p>}<fieldset disabled={busy} className={css.fields}>
 {action==='attempt'&&<><label>{tr('service.result')}<select value={result} onChange={e=>setResult(e.target.value as 'pending'|'served'|'failed')}>{['served','failed','pending'].map(v=><option key={v} value={v}>{tr('service.status.'+v)}</option>)}</select></label>{result==='pending'&&<p className={css.hint}>{tr('service.pendingFactsHint')}</p>}{result==='failed'&&<><label>{tr('service.failureKind')}<select value={failure} onChange={e=>setFailure(e.target.value)}>{['investigating','not_found','demolished','other'].map(v=><option key={v} value={v}>{tr('service.failure.'+v)}</option>)}</select></label><label>{tr('service.failureReason')}<textarea required rows={2} maxLength={10000} value={failureReason} onChange={e=>setFailureReason(e.target.value)}/></label></>}<div className={css.two}><label>{tr(result==='failed'?'service.methodOptional':'service.method')}<select required={result!=='failed'} value={method} onChange={e=>setMethod(e.target.value as NonNullable<ServiceAttempt['method']>)}><option value="">{tr('service.chooseMethod')}</option>{['normal','posting','electronic','other'].map(v=><option key={v} value={v}>{tr('service.method.'+v)}</option>)}</select></label><label>{tr(result==='failed'?'service.dateOptional':'service.date')}<input type="date" required={result!=='failed'} max={data.today} value={day} onChange={e=>setDay(e.target.value)}/></label></div><label>{tr(correctingFacts?'service.correctionReason':'service.notes')}<textarea required={correctingFacts} rows={2} maxLength={10000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{result==='served'&&<p className={css.hint}>{tr(canConfirm&&!person?.control?.lawful_attempt_id?'service.servedSaveHint':'service.notLawfulHint')}</p>}</>}
 {action==='lawful'&&<p className={css.hint}>{tr('service.lawfulHint')}<br/>{attempt&&`${tr(attempt.method?'service.method.'+attempt.method:'service.methodUnknown')} · ${date(attempt.attempted_on)}`}</p>}
 {action==='deadline'&&<><p className={css.hint}>{tr('service.reviewHint')}{suggestion&&<><br/>{tr('service.suggestedDue')}: {date(suggestion)} · {tr(kind==='default'?'service.ruleDefault':lawfulAttempt(person!)?.method==='normal'?'service.rule15':'service.rule30')}</>}</p>{kind==='answer'&&<label>{tr('service.useExisting')}<select value={existing} onChange={e=>setExisting(e.target.value)}><option value="">{tr('service.createReviewed')}</option>{data.deadlines.filter(d=>d.deadline_type==='answer'&&!data.defendants.some(p=>p.control?.answer_deadline_id===d.id)).map(d=><option key={d.id} value={d.id}>{date(d.current_due_date)} · {d.deadline_other||tr('service.answerDue')}</option>)}</select></label>}{!existing&&<label>{tr('service.reviewedDue')}<input type="date" required value={due} onChange={e=>setDue(e.target.value)}/></label>}<label>{tr(kind==='court'?'service.courtOrder':'service.notes')}<textarea required={kind==='court'} rows={2} maxLength={10000} value={reason} onChange={e=>setReason(e.target.value)}/></label></>}
 {action==='answer'&&<><label>{tr('service.answeredOn')}<input type="date" required max={data.today} value={day} onChange={e=>setDay(e.target.value)}/></label><p className={css.hint}>{tr('service.answerHint')}</p></>}
 {action==='required'&&<label className={css.check}><input type="checkbox" checked={required} onChange={e=>setRequired(e.target.checked)}/>{tr('service.required')}</label>}
 {['void','required','branch'].includes(action)&&<label>{tr('service.reason')}<textarea required rows={3} maxLength={10000} value={reason} onChange={e=>setReason(e.target.value)}/></label>}
 {action==='advance'&&<p className={css.hint}>{tr('service.advanceHint')}</p>}{action==='branch'&&<p className={css.hint}>{tr('service.branchHint')}</p>}{action==='void'&&<p className={css.hint}>{tr('service.voidHint')}</p>}
 {action==='next'&&<>{defaultMotion&&<p className={css.hint}>{tr('answer.nextOptional')}</p>}{currentNext&&<p className={css.warning}>{tr('service.replaceNextHint')}<br/><strong>{currentNext.title}</strong>{currentNext.assignee&&<> · {currentNext.assignee}</>}{currentNext.due&&<> · {date(currentNext.due)}</>}</p>}<label>{tr('service.nextMode')}<select value={mode} onChange={e=>setMode(e.target.value)}><option value="manual">{tr('service.manualNext')}</option><option value="task">{tr('service.linkTask')}</option></select></label>{mode==='task'?<label>{tr('service.task')}<select required value={task} onChange={e=>setTask(e.target.value)}><option value="">{tr('service.chooseTask')}</option>{core?.tasks.filter(t=>!t.deleted_at&&t.status!=='Done').map(t=><option key={t.id} value={t.id}>{t.task_other||tr(t.task_type||'service.task')}</option>)}</select></label>:<><label>{tr('service.what')}<textarea required rows={3} maxLength={500} value={title} onChange={e=>setTitle(e.target.value)}/></label><label htmlFor="case102-person">{tr('service.assignee')}</label><SearchableCombobox id="case102-person" value={assignee} disabled={busy||!core} onChange={setAssignee} label={tr('service.assignee')} placeholder={tr('service.choosePerson')} options={(core?.people.filter(p=>p.eligible)||[]).map(p=>({value:p.id,label:{th:personLabel(p,core!.people),en:personLabel(p,core!.people)},keywords:`${p.name} ${p.full_name||''}`}))}/>{assignee&&<button type="button" className={base.coreTextButton} onClick={()=>setAssignee('')}>{tr('service.clearAssignee')}</button>}<label>{tr('service.optionalDue')}<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label></>}<p className={css.hint}>{tr('service.nextHint')}</p>{defaultMotion&&core&&<div><p>{tr('role.current_actor')}: {core.people.find(p=>p.id===core.team.find(t=>t.team_role==='current_actor')?.person_id)?.name||tr('Unassigned')}</p>{canConfirm&&<button type="button" className={base.secondary} onClick={()=>setTeamEditor(true)}>{tr('Manage team')}</button>}</div>}</>}
 {needsConfirm&&<label className={css.check}><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{tr(action==='deadline'?'service.confirmDueFact':'service.confirmFlowFact')}</label>}
 </fieldset>{error&&<p role="alert" className={base.coreError}>{tr(error)}</p>}<footer className={base.coreFooter}><button type="button" disabled={busy} className={base.secondary} onClick={onClose}>{tr('Cancel')}</button><button className={base.primary} disabled={busy||(action==='next'&&!core)}>{tr(busy?'Saving...':'Save')}</button></footer></form></CaseEditModal>;
}
