'use client';
import {useEffect,useRef,useState} from 'react';
import {Send} from 'lucide-react';
import {supabase} from '../../../lib/supabase';
import {SearchableCombobox} from '../../finance/expenses/searchable-combobox';
import CaseEditModal from './CaseEditModal';
import {useCaseDetailText} from './labels';
import {loadAssignmentPeople} from './core-people';
import {personLabel,type CoreData} from './core-model';
import {answerSuggestion,defaultSuggestion,lawfulAttempt,serviceStatus,serviceFlowSuggestions,serviceError,type ServiceAction,type ServiceData,type ServicePerson,type ServiceAttempt} from './service-model';
import base from './case-detail.module.css';
import css from './case-service.module.css';

type Editor={action:ServiceAction;person?:ServicePerson;attempt?:ServiceAttempt;kind?:'answer'|'default'|'court'};
export default function CaseService({caseId,revision,canRecord,canConfirm,onSection}:{caseId:number;revision:number;canRecord:boolean;canConfirm:boolean;onSection:(s:string)=>void}){
 const {tr}=useCaseDetailText();const [data,setData]=useState<ServiceData|null>(null),[failed,setFailed]=useState(false),[view,setView]=useState(false),[editor,setEditor]=useState<Editor|null>(null),[reload,setReload]=useState(0);
 useEffect(()=>{let live=true;void(async()=>{const r=await supabase.rpc('case102_read',{p_case_id:caseId});if(live){setFailed(!!r.error);if(!r.error)setData(r.data as ServiceData);}})().catch(()=>{if(live)setFailed(true);});return()=>{live=false;};},[caseId,revision,reload]);
 if(failed)return <p className={base.notice} role="alert">{tr('service.loadError')} <button onClick={()=>setReload(n=>n+1)}>{tr('Reload')}</button></p>;
 if(!data?.flow)return null;
 const edit=(value:Editor)=>{setView(false);setEditor(value);};const legal=canConfirm&&data.flow.lifecycle==='active',record=canRecord&&data.flow.lifecycle==='active';
 const required=data.defendants.filter(p=>p.control?.required!==false),done=required.filter(p=>lawfulAttempt(p)).length;
 return <section className={css.card} aria-label={tr('service.title')}><div className={css.heading}><Send size={20}/><div><h2>{tr('service.title')}</h2><p>{tr('service.summary')} {done} / {required.length}</p></div></div><div className={css.compact}>{data.defendants.slice(0,4).map(p=><span key={p.id}>{p.name||tr('service.unnamed')} <small data-state={serviceStatus(p)}>{tr('service.status.'+serviceStatus(p))}</small></span>)}{data.defendants.length===0&&<span>{tr('service.noDefendants')}</span>}</div><button className={base.secondary} onClick={()=>setView(true)}>{tr('service.manage')}</button>
 {view&&<CaseEditModal title={tr('service.title')} className={css.viewer} onClose={()=>setView(false)}><ServiceView data={data} canRecord={record} canConfirm={legal} onEdit={edit} onDeadlines={()=>{setView(false);onSection('deadlines');}}/></CaseEditModal>}
 {editor&&<ServiceEditor {...editor} data={data} caseId={caseId} onClose={()=>{setEditor(null);setView(true);}} onSaved={value=>{setData(value);setEditor(null);setView(true);window.dispatchEvent(new Event('case-detail-updated'));}}/>}
 </section>;
}
function ServiceView({data,canRecord,canConfirm,onEdit,onDeadlines}:{data:ServiceData;canRecord:boolean;canConfirm:boolean;onEdit:(v:Editor)=>void;onDeadlines:()=>void}){
 const {tr,date}=useCaseDetailText();const flow=serviceFlowSuggestions(data);
 return <div className={css.body}><p className={css.hint}>{tr('service.reviewHint')}</p>{!data.defendants.length&&<p>{tr('service.noDefendants')}</p>}{data.defendants.map((p,index)=>{const latest=p.attempts[0],lawful=lawfulAttempt(p),due=p.answer_deadline,defaultDue=defaultSuggestion(p,data.today);return <article className={css.person} key={p.id}><header><strong>{index+1}. {p.name||tr('service.unnamed')}</strong><span className={css.badge} data-state={serviceStatus(p)}>{tr('service.status.'+serviceStatus(p))}</span></header>
 <dl><div><dt>{tr('service.latest')}</dt><dd>{latest?`${tr('service.method.'+latest.method)} · ${date(latest.attempted_on)} · ${tr('service.status.'+latest.result)}`:tr('service.noAttempt')}</dd></div>{lawful&&<div><dt>{tr('service.lawful')}</dt><dd>{date(p.control?.lawful_at,true)}</dd></div>}<div><dt>{tr('service.answerDue')}</dt><dd>{due?`${date(due.current_due_date)} · ${tr(due.deleted_at?'service.removed':'service.deadlineStatus.'+due.status)}`:tr('service.noDeadline')}</dd></div>{p.control?.answer_filed_on&&<div><dt>{tr('service.answeredOn')}</dt><dd>{date(p.control.answer_filed_on)}</dd></div>}{p.default_deadline&&<div><dt>{tr('service.defaultDue')}</dt><dd>{date(p.default_deadline.current_due_date)} · {tr(p.default_deadline.deleted_at?'service.removed':'service.deadlineStatus.'+p.default_deadline.status)}</dd></div>}</dl>
 {latest?.result==='failed'&&<p className={css.warning}>{latest.failure_reason}<br/>{tr(latest.failure_kind==='demolished'?'service.demolishedSuggestion':latest.failure_kind==='not_found'?'service.notFoundSuggestion':'service.investigateSuggestion')}</p>}
 {canRecord&&<div className={css.actions}><button className={base.secondary} onClick={()=>onEdit({action:'attempt',person:p})}>{tr('service.record')}</button>{latest?.result==='pending'&&<button className={base.secondary} onClick={()=>onEdit({action:'attempt',person:p,attempt:latest})}>{tr('service.updatePending')}</button>}{canConfirm&&!lawful&&latest?.result==='served'&&<button className={base.primary} onClick={()=>onEdit({action:'lawful',person:p,attempt:latest})}>{tr('service.confirmLawful')}</button>}{canConfirm&&lawful&&!p.control?.answer_filed_on&&!p.control?.answer_deadline_id&&<button className={base.secondary} onClick={()=>onEdit({action:'deadline',person:p,kind:'answer'})}>{tr('service.confirmAnswerDue')}</button>}{canConfirm&&defaultDue&&!p.control?.default_deadline_id&&<button className={base.secondary} onClick={()=>onEdit({action:'deadline',person:p,kind:'default'})}>{tr('service.confirmDefaultDue')}</button>}{canConfirm&&!p.control?.answer_filed_on&&<button className={base.secondary} onClick={()=>onEdit({action:'answer',person:p})}>{tr('service.recordAnswer')}</button>}<button className={base.secondary} onClick={()=>onEdit({action:'next',person:p})}>{tr('service.next')}</button></div>}
 <details><summary>{tr('service.historyMore')}</summary><div className={css.actions}>{due&&<button className={base.secondary} onClick={onDeadlines}>{tr('service.manageExtensions')}</button>}{canConfirm&&<><button className={base.secondary} onClick={()=>onEdit({action:'deadline',person:p,kind:'court'})}>{tr('service.courtDue')}</button><button className={base.secondary} onClick={()=>onEdit({action:'required',person:p})}>{tr('service.requiredScope')}</button>{lawful&&<button className={base.secondary} onClick={()=>onEdit({action:'absence',person:p})}>{tr('service.recordAbsence')}</button>}</>}</div>{p.control?.exemption_reason&&<p>{p.control.exemption_reason}</p>}{p.extensions.map(e=><p key={e.id}>{tr('service.extension')} {e.extension_no} · {date(e.granted_until_date)} · {e.note}</p>)}{p.attempts.map(a=><div className={css.history} key={a.id}><strong>{date(a.attempted_on)} · {tr('service.method.'+a.method)} · {tr('service.status.'+a.result)}</strong>{a.failure_reason&&<p>{a.failure_reason}</p>}{a.note&&<p>{a.note}</p>}{a.void_reason&&<p>{tr('service.voidReason')}: {a.void_reason}</p>}{canConfirm&&a.result!=='void'&&<button className={base.coreTextButton} onClick={()=>onEdit({action:'void',person:p,attempt:a})}>{tr('service.void')}</button>}</div>)}{data.history.filter(e=>e.party_id===p.id).map(e=><div className={css.history} key={e.id}><strong>{tr('service.action.'+e.action)}</strong><small>{e.actor_name} · {date(e.occurred_at,true)}</small></div>)}</details>
 </article>;})}{canConfirm&&(flow.advance||flow.branch)&&<div className={css.suggestions}><p>{tr('service.flowHint')}</p>{flow.advance&&<button className={base.primary} onClick={()=>onEdit({action:'advance'})}>{tr('service.advance')}</button>}{flow.branch&&<button className={base.secondary} onClick={()=>onEdit({action:'branch'})}>{tr('service.branch')}</button>}</div>}</div>;
}
function ServiceEditor({action,person,attempt,kind='answer',data,caseId,onClose,onSaved}:Editor&{data:ServiceData;caseId:number;onClose:()=>void;onSaved:(d:ServiceData)=>void}){
 const {tr,date}=useCaseDetailText();const suggestion=person?(kind==='default'?defaultSuggestion(person,data.today):kind==='answer'?answerSuggestion(person):null):null;
 const [method,setMethod]=useState(attempt?.method||'normal'),[day,setDay]=useState(attempt?.attempted_on||''),[result,setResult]=useState(attempt?.result==='void'?'pending':attempt?.result||'pending');
 const [failure,setFailure]=useState(attempt?.failure_kind||'investigating'),[failureReason,setFailureReason]=useState(attempt?.failure_reason||''),[reason,setReason]=useState(attempt?.note||''),[due,setDue]=useState(suggestion||''),[confirmed,setConfirmed]=useState(false),[required,setRequired]=useState(person?.control?.required!==false),[hearing,setHearing]=useState(''),[existing,setExisting]=useState('');
 const [core,setCore]=useState<CoreData|null>(null),[mode,setMode]=useState('manual'),[task,setTask]=useState(''),[title,setTitle]=useState(person?.attempts[0]?.failure_kind==='demolished'?tr('service.demolishedNext'):person?.attempts[0]?.failure_kind==='not_found'?tr('service.notFoundNext'):''),[assignee,setAssignee]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false),retry=useRef<{body:string;id:string}|null>(null);
 useEffect(()=>{if(action!=='next')return;let live=true;void(async()=>{const r=await supabase.rpc('case098_read',{p_case_id:caseId});if(r.error)throw r.error;const c=await loadAssignmentPeople(r.data as CoreData,supabase);if(live)setCore(c);})().catch(()=>{if(live)setError('service.loadError');});return()=>{live=false;};},[action,caseId]);
 async function save(e:React.FormEvent){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{
  let payload:Record<string,unknown>={};const d=existing?data.deadlines.find(x=>x.id===existing):person?.answer_deadline;
  const expected={expected_due:d?.current_due_date||null,expected_updated_at:d?.updated_at||null};
  if(action==='attempt')payload={attempt_id:attempt?.id||null,method,attempted_on:day,result,failure_kind:result==='failed'?failure:null,failure_reason:result==='failed'?failureReason:null,note:reason||null};
  if(action==='lawful')payload={attempt_id:attempt?.id,confirmed};
  if(action==='void')payload={attempt_id:attempt?.id,reason};
  if(action==='required')payload={required,reason};
  if(action==='deadline')payload={kind,due:existing?null:due,existing_id:existing||null,confirmed,reason:reason||null,...expected};
  if(action==='answer')payload={date:day,...expected};
  if(action==='absence')payload={hearing_id:hearing,confirmed};
  if(action==='advance'||action==='branch')payload={flow_version:data.flow?.version,confirmed,...(action==='branch'?{reason}:{})};
  if(action==='next'){if(!core)throw Error('service.loadError');payload={core_version:core.core?.version||0,next:mode==='task'?{mode,task_id:task}:{mode:'manual',title,assignee_id:assignee||null,due:due||null}};}
  const body=JSON.stringify(payload);if(retry.current?.body!==body)retry.current={body,id:crypto.randomUUID()};
  const r=await supabase.rpc('case102_save',{p_case_id:caseId,p_party_id:person?.id||null,p_version:person?.control?.version||0,p_request_id:retry.current!.id,p_action:action,p_data:payload});if(r.error){setError(serviceError(r.error.message));return;}onSaved(r.data as ServiceData);
 }catch{setError('service.saveError');}finally{lock.current=false;setBusy(false);}}
 const needsConfirm=['lawful','deadline','absence','advance','branch'].includes(action);
 return <CaseEditModal title={tr('service.action.'+action)} className={css.editor} busy={busy} onClose={onClose}><form className={base.coreForm} onSubmit={save}>{person&&<p className={css.identity}>{person.name||tr('service.unnamed')}</p>}<fieldset disabled={busy} className={css.fields}>
 {action==='attempt'&&<><div className={css.two}><label>{tr('service.method')}<select value={method} onChange={e=>setMethod(e.target.value as ServiceAttempt['method'])}>{['normal','posting','electronic','other'].map(v=><option key={v} value={v}>{tr('service.method.'+v)}</option>)}</select></label><label>{tr('service.date')}<input type="date" required max={data.today} value={day} onChange={e=>setDay(e.target.value)}/></label></div><label>{tr('service.result')}<select value={result} onChange={e=>setResult(e.target.value as 'pending'|'served'|'failed')}>{['pending','served','failed'].map(v=><option key={v} value={v}>{tr('service.status.'+v)}</option>)}</select></label>{result==='failed'&&<><label>{tr('service.failureKind')}<select value={failure} onChange={e=>setFailure(e.target.value)}>{['investigating','not_found','demolished','other'].map(v=><option key={v} value={v}>{tr('service.failure.'+v)}</option>)}</select></label><label>{tr('service.failureReason')}<textarea required rows={2} maxLength={10000} value={failureReason} onChange={e=>setFailureReason(e.target.value)}/></label></>}<label>{tr('service.notes')}<textarea rows={2} maxLength={10000} value={reason} onChange={e=>setReason(e.target.value)}/></label><p className={css.hint}>{tr('service.notLawfulHint')}</p></>}
 {action==='lawful'&&<p className={css.hint}>{tr('service.lawfulHint')}<br/>{attempt&&`${tr('service.method.'+attempt.method)} · ${date(attempt.attempted_on)}`}</p>}
 {action==='deadline'&&<><p className={css.hint}>{tr('service.reviewHint')}{suggestion&&<><br/>{tr('service.suggestedDue')}: {date(suggestion)} · {tr(kind==='default'?'service.ruleDefault':lawfulAttempt(person!)?.method==='normal'?'service.rule15':'service.rule30')}</>}</p>{kind==='answer'&&<label>{tr('service.useExisting')}<select value={existing} onChange={e=>setExisting(e.target.value)}><option value="">{tr('service.createReviewed')}</option>{data.deadlines.filter(d=>d.deadline_type==='answer'&&!data.defendants.some(p=>p.control?.answer_deadline_id===d.id)).map(d=><option key={d.id} value={d.id}>{date(d.current_due_date)} · {d.deadline_other||tr('service.answerDue')}</option>)}</select></label>}{!existing&&<label>{tr('service.reviewedDue')}<input type="date" required value={due} onChange={e=>setDue(e.target.value)}/></label>}<label>{tr(kind==='court'?'service.courtOrder':'service.notes')}<textarea required={kind==='court'} rows={2} maxLength={10000} value={reason} onChange={e=>setReason(e.target.value)}/></label></>}
 {action==='answer'&&<><label>{tr('service.answeredOn')}<input type="date" required max={data.today} value={day} onChange={e=>setDay(e.target.value)}/></label><p className={css.hint}>{tr('service.answerHint')}</p></>}
 {action==='absence'&&<><label>{tr('service.actualHearing')}<select required value={hearing} onChange={e=>setHearing(e.target.value)}><option value="">{tr('service.chooseHearing')}</option>{data.hearings.filter(h=>h.event_date&&h.event_date<=data.today).map(h=><option key={h.id} value={h.id}>{date(h.event_date)} · {h.appointment_other||tr(h.appointment_type||'service.hearing')}</option>)}</select></label><p className={css.hint}>{tr('service.absenceHint')}</p></>}
 {action==='required'&&<label className={css.check}><input type="checkbox" checked={required} onChange={e=>setRequired(e.target.checked)}/>{tr('service.required')}</label>}
 {['void','required','branch'].includes(action)&&<label>{tr('service.reason')}<textarea required rows={3} maxLength={10000} value={reason} onChange={e=>setReason(e.target.value)}/></label>}
 {action==='advance'&&<p className={css.hint}>{tr('service.advanceHint')}</p>}{action==='branch'&&<p className={css.hint}>{tr('service.branchHint')}</p>}{action==='void'&&<p className={css.hint}>{tr('service.voidHint')}</p>}
 {action==='next'&&<><label>{tr('service.nextMode')}<select value={mode} onChange={e=>setMode(e.target.value)}><option value="manual">{tr('service.manualNext')}</option><option value="task">{tr('service.linkTask')}</option></select></label>{mode==='task'?<label>{tr('service.task')}<select required value={task} onChange={e=>setTask(e.target.value)}><option value="">{tr('service.chooseTask')}</option>{core?.tasks.filter(t=>!t.deleted_at&&t.status!=='Done').map(t=><option key={t.id} value={t.id}>{t.task_other||tr(t.task_type||'service.task')}</option>)}</select></label>:<><label>{tr('service.what')}<input required maxLength={500} value={title} onChange={e=>setTitle(e.target.value)}/></label><label htmlFor="case102-person">{tr('service.assignee')}</label><SearchableCombobox id="case102-person" value={assignee} disabled={busy||!core} onChange={setAssignee} label={tr('service.assignee')} placeholder={tr('service.choosePerson')} options={(core?.people.filter(p=>p.eligible)||[]).map(p=>({value:p.id,label:{th:personLabel(p,core!.people),en:personLabel(p,core!.people)},keywords:`${p.name} ${p.full_name||''}`}))}/>{assignee&&<button type="button" className={base.coreTextButton} onClick={()=>setAssignee('')}>{tr('service.clearAssignee')}</button>}<label>{tr('service.optionalDue')}<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label></>}<p className={css.hint}>{tr('service.nextHint')}</p></>}
 {needsConfirm&&<label className={css.check}><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{tr(action==='lawful'?'service.confirmLawfulFact':action==='deadline'?'service.confirmDueFact':action==='absence'?'service.confirmAbsentFact':'service.confirmFlowFact')}</label>}
 </fieldset>{error&&<p role="alert" className={base.coreError}>{tr(error)}</p>}<footer className={base.coreFooter}><button type="button" disabled={busy} className={base.secondary} onClick={onClose}>{tr('Cancel')}</button><button className={base.primary} disabled={busy||(action==='next'&&!core)}>{tr(busy?'Saving...':'Save')}</button></footer></form></CaseEditModal>;
}
