'use client';
import { useEffect, useRef, useState } from 'react';
import { supabase } from '../../../lib/supabase';
import { SearchableCombobox } from '../../finance/expenses/searchable-combobox';
import CaseEditModal from './CaseEditModal';
import { useCaseDetailText } from './labels';
import { personLabel, type CoreData } from './core-model';
import { DECISIONS, OBJECTIVES, engagementError, localDateTime, type EngagementData, type Rescue, type CloseReview } from './engagement-model';
import css from './case-detail.module.css';

type Editor = { mode: 'decision' | 'rescue' | 'review'; rescue?: Rescue; review?: CloseReview };
export default function CaseEngagement({ caseId, revision, people, canEdit, canViewHistory }: { caseId: number; revision: number; people: CoreData['people']; canEdit: boolean; canViewHistory: boolean }) {
 const { tr, date } = useCaseDetailText();
 const [data, setData] = useState<EngagementData | null>(null), [failed, setFailed] = useState(false), [reload, setReload] = useState(0);
 const [editor, setEditor] = useState<Editor | null>(null), [history, setHistory] = useState(false);
 useEffect(()=>{let live=true;void(async()=>{try{const r=await supabase.rpc('case100_read',{p_case_id:caseId});if(r.error)throw r.error;if(live){setData(r.data as EngagementData);setFailed(false);}}catch{if(live)setFailed(true);}})();return()=>{live=false;};},[caseId,revision,reload]);
 const current=data?.decisions[0], review=data?.reviews.find(r=>r.decision_id===current?.id);
 if(failed)return <p role="alert" className={css.notice}>{tr('Could not load engagement facts.')} <button onClick={()=>setReload(n=>n+1)}>{tr('Reload')}</button></p>;
 if(!data)return null;
 return <section className={css.engagement} aria-label={tr('VP engagement')}>
  <div className={css.engagementBar}>
   <div><strong>{tr('VP engagement')}</strong><span className={css.engagementStatus} data-state={current?.decision}>{tr(current?'decision.'+current.decision:'No continuation decision recorded')}</span>{current?.confirmed_on&&<small>{date(current.confirmed_on)}</small>}</div>
   <div className={css.engagementActions}>
    {canEdit&&<button type="button" className={css.secondary} onClick={()=>setEditor({mode:'decision'})}>{tr('Record continuation decision')}</button>}
    {canEdit&&<button type="button" className={css.secondary} onClick={()=>setEditor({mode:'rescue'})}>{tr('Request help / escalate')}</button>}
    {(data.decisions.length>0||data.rescues.length>0)&&<button type="button" className={css.coreTextButton} onClick={()=>setHistory(true)}>{tr('Engagement history')}{data.rescues.some(r=>r.status==='open')&&<span> · {tr('Open help requests')}: {data.rescues.filter(r=>r.status==='open').length}</span>}</button>}
   </div>
  </div>
  {current?.decision==='end'&&<div className={css.engagementClose}><div><strong>{tr('Close review')}</strong><p className={css.coreMuted}>{tr(review?'objective.'+review.objective:'Review the completed VP scope. The legal case status stays unchanged.')}</p></div>{canEdit?<button type="button" className={css.secondary} onClick={()=>setEditor({mode:'review',review})}>{tr(review?'Edit close review':'Record close review')}</button>:review&&<button type="button" className={css.coreTextButton} onClick={()=>setHistory(true)}>{tr('View details')}</button>}</div>}
  {editor&&<EngagementEditor key={editor.mode+(editor.rescue?.id||editor.review?.id||'new')} editor={editor} caseId={caseId} data={data} people={people} onClose={()=>setEditor(null)} onSaved={value=>{setData(value);setEditor(null);window.dispatchEvent(new Event('case-detail-updated'));}}/>}
  {history&&<CaseEditModal title={tr('Engagement history')} className={css.coreEditor} onClose={()=>setHistory(false)}><div className={css.engagementHistory}>
   <section><h3>{tr('Continuation decisions')}</h3>{data.decisions.length===0&&<p>{tr('No continuation decision recorded')}</p>}{data.decisions.map(d=><article key={d.id}><strong>{tr('decision.'+d.decision)}</strong>{d.confirmed_on&&<p>{tr('Confirmation date')}: {date(d.confirmed_on)}</p>}{d.note&&<p>{d.note}</p>}<small>{tr('Recorded by')}: {d.author_name} · {date(d.recorded_at,true)}</small></article>)}</section>
   <section><h3>{tr('Help requests')}</h3>{!data.rescues.length&&<p>{tr('No help requests recorded')}</p>}{data.rescues.map(r=><article key={r.id}><header><strong>{r.subject}</strong><span>{tr('rescue.'+r.status)}</span></header><p>{r.reason}</p><p>{tr('Help from')}: {r.recipient_name} · {date(r.occurred_at,true)}</p><small>{tr('Requested by')}: {r.requester_name} · {date(r.recorded_at,true)}</small>{r.resolution&&<p>{tr('Resolution')}: {r.resolution}<br/>{r.resolver_name} · {date(r.resolved_at,true)}</p>}<small>{tr('Last edited by')}: {r.editor_name} · {date(r.updated_at,true)}</small>{canEdit&&<button type="button" className={css.secondary} onClick={()=>{setHistory(false);setEditor({mode:'rescue',rescue:r});}}>{tr(r.status==='open'?'Update / resolve':'Edit')}</button>}</article>)}</section>
   {data.reviews.length>0&&<section><h3>{tr('Close reviews')}</h3>{data.reviews.map(r=><article key={r.id}><strong>{tr('objective.'+r.objective)} · {date(r.closed_at)}</strong>{[['What differed from the plan',r.variance],['Key lessons',r.lessons],['Reusable knowledge',r.knowledge]].map(([label,value])=>value&&<p key={label}><b>{tr(label)}</b><br/>{value}</p>)}{r.document_ref&&<a href={r.document_ref} target="_blank" rel="noreferrer">{tr('Open document')}</a>}<p>{tr('Team at review recording')}</p><ul>{r.team_evidence.map(t=><li key={t.person_id+t.team_role}>{tr('role.'+t.team_role)}: {t.name}</li>)}</ul><small>{tr('Recorded by')}: {r.author_name} · {date(r.recorded_at,true)}<br/>{tr('Last edited by')}: {r.editor_name} · {date(r.updated_at,true)}</small></article>)}</section>}
   {canViewHistory&&<a href="#history" onClick={()=>setHistory(false)}>{tr('History / Audit Log')}</a>}
  </div></CaseEditModal>}
 </section>;
}

function EngagementEditor({editor,caseId,data,people,onClose,onSaved}:{editor:Editor;caseId:number;data:EngagementData;people:CoreData['people'];onClose:()=>void;onSaved:(value:EngagementData)=>void}) {
 const {tr}=useCaseDetailText();const current=data.decisions[0],r=editor.rescue,v=editor.review;
 const [decision,setDecision]=useState(current?.decision||'waiting'),[confirmed,setConfirmed]=useState(''),[note,setNote]=useState('');
 const [recipient,setRecipient]=useState(r?.escalated_to||''),[subject,setSubject]=useState(r?.subject||''),[reason,setReason]=useState(r?.reason||''),[occurred,setOccurred]=useState(()=>localDateTime(r?.occurred_at||new Date().toISOString())),[resolved,setResolved]=useState(r?.status==='resolved'),[resolution,setResolution]=useState(r?.resolution||'');
 const [objective,setObjective]=useState(v?.objective||''),[variance,setVariance]=useState(v?.variance||''),[lessons,setLessons]=useState(v?.lessons||''),[knowledge,setKnowledge]=useState(v?.knowledge||''),[documentRef,setDocumentRef]=useState(v?.document_ref||''),[closed,setClosed]=useState(v?.closed_at||'');
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const [id]=useState(()=>r?.id||v?.id||crypto.randomUUID());const retry=useRef<{payload:string;id:string}|null>(null);
 const eligible=people.filter(p=>p.eligible),retained=!!recipient&&!eligible.some(p=>p.id===recipient);
 const title=editor.mode==='decision'?'Continuation decision':editor.mode==='rescue'?'Request help / escalate':'Close review';
 const text=(label:string,value:string,set:(s:string)=>void,required=false)=><label>{tr(label)}<textarea value={value} onChange={e=>set(e.target.value)} required={required} maxLength={10000} rows={2}/></label>;
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{
  if(editor.mode==='rescue'&&!recipient){setError('CASE100_PERSON_INELIGIBLE');return;}
  const payload=editor.mode==='decision'?{decision,confirmed_on:decision==='waiting'?null:confirmed,note:note||null}:editor.mode==='rescue'?{escalated_to:recipient,subject,reason,occurred_at:new Date(occurred).toISOString(),status:resolved?'resolved':'open',resolution:resolved?resolution:null}:{objective,variance:variance||null,lessons:lessons||null,knowledge:knowledge||null,document_ref:documentRef||null,closed_at:closed};
  const serialized=JSON.stringify(payload);if(retry.current?.payload!==serialized)retry.current={payload:serialized,id:crypto.randomUUID()};
  const result=await supabase.rpc('case100_save',{p_case_id:caseId,p_section:editor.mode,p_id:id,p_version:r?.version||v?.version||0,p_request_id:retry.current!.id,p_current_decision:current?.id||null,p_data:payload});
  if(result.error){setError(engagementError(result.error.message));return;}onSaved(result.data as EngagementData);
 }catch{setError('Engagement could not be saved. Please try again.');}finally{setBusy(false);}}
 return <CaseEditModal title={tr(title)} className={css.engagementEditor} onClose={onClose} busy={busy}><form className={css.coreForm} onSubmit={save}><fieldset disabled={busy} className={css.engagementFields}>
  {editor.mode==='decision'&&<><p className={css.engagementHint}>{tr('This records the VP scope only. It does not change the legal case status or start an appeal.')}</p><fieldset className={css.decisionChoices}><legend>{tr('Decision')}</legend>{DECISIONS.map(value=><label key={value}><input type="radio" name="continuation" value={value} checked={decision===value} onChange={()=>setDecision(value)}/><span>{tr('decision.'+value)}</span></label>)}</fieldset>{decision!=='waiting'&&<label>{tr('Confirmation date')}<input type="date" required value={confirmed} onChange={e=>setConfirmed(e.target.value)}/></label>}{text('Notes (optional)',note,setNote)}{current&&<p className={css.coreMuted}>{tr('The previous decision stays in history.')}</p>}</>}
  {editor.mode==='rescue'&&<><p className={css.coreMuted}>{tr('Use for an issue that needs additional help or a decision, not routine strategy or quality review.')}</p><div className={css.coreField}><label htmlFor="case-rescue-person">{tr('Help from')}</label><SearchableCombobox id="case-rescue-person" label={tr('Help from')} placeholder={retained?(r?.recipient_name||tr('Unassigned')):tr('Search people')} value={recipient} onChange={setRecipient} disabled={busy} options={eligible.map(p=>({value:p.id,label:{th:personLabel(p,eligible),en:personLabel(p,eligible)},keywords:[p.name,p.full_name].filter(Boolean).join(' ')}))}/>{retained&&<p className={css.coreMuted}>{tr('Existing assignment is kept. This person is unavailable for new assignments.')}</p>}</div><label>{tr('Subject')}<input required maxLength={500} value={subject} onChange={e=>setSubject(e.target.value)}/></label>{text('Reason for help',reason,setReason,true)}<label>{tr('Occurred at')}<input type="datetime-local" required value={occurred} onChange={e=>setOccurred(e.target.value)}/></label>{r&&<label className={css.engagementCheck}><input type="checkbox" checked={resolved} onChange={e=>setResolved(e.target.checked)}/>{tr('Mark resolved')}</label>}{resolved&&text('Resolution',resolution,setResolution,true)}</>}
  {editor.mode==='review'&&<><p className={css.engagementHint}>{tr('Review the completed VP scope. The legal case status stays unchanged.')}</p><label>{tr('Client objective achieved')}<select required value={objective} onChange={e=>setObjective(e.target.value as typeof objective)}><option value="">{tr('Choose an outcome')}</option>{OBJECTIVES.map(value=><option key={value} value={value}>{tr('objective.'+value)}</option>)}</select></label><label>{tr('VP scope ended on')}<input required type="date" value={closed} onChange={e=>setClosed(e.target.value)}/></label><details><summary>{tr('Lessons / knowledge (optional)')}</summary><div className={css.engagementFields}>{text('What differed from the plan',variance,setVariance)}{text('Key lessons',lessons,setLessons)}{text('Reusable knowledge',knowledge,setKnowledge)}<label>{tr('Document link (optional)')}<input type="url" pattern="https://[^\s]+" maxLength={2000} value={documentRef} onChange={e=>setDocumentRef(e.target.value)}/></label></div></details><p className={css.coreMuted}>{tr('The system records the author and existing team. No need to enter them again.')}</p></>}
 </fieldset>{error&&<p role="alert" className={css.coreError}>{tr(error)}</p>}<footer className={css.coreFooter}><button type="button" className={css.secondary} onClick={onClose} disabled={busy}>{tr('Cancel')}</button><button className={css.primary} disabled={busy}>{tr(busy?'Saving...':'Save')}</button></footer></form></CaseEditModal>;
}
