'use client';
import {useState} from 'react';
import {FileText,UsersRound,Route,CalendarClock} from 'lucide-react';
import CaseEditModal from './CaseEditModal';
import DefendantEditor,{type DefendantEdit} from './DefendantEditor';
import {useDefendantText} from './defendant-labels';
import {DefendantDeadline,ObligationStatus} from './DefendantDeadline';
import {currentCoverage,defendantObligation,defendantSuggestion,filingsFor,flowReadiness,liveRepresentations,partyLabel,type DefendantContext,type DefendantData,type Filing} from './defendant-model';
import type {AnswerRequest} from './service-model';
import base from './case-detail.module.css';
import css from './case-defendant.module.css';


export default function CaseDefendant({caseId,context,canLegal,canRecord,onSaved,onReload,answerRequest}:{caseId:number;context:DefendantContext;canLegal:boolean;canRecord:boolean;onSaved:()=>void;onReload:()=>void;answerRequest?:AnswerRequest|null}){
 const {t,date,locale}=useDefendantText(),data=context.data;
 const [localView,setLocalView]=useState<string|null>(null),[handledRequest,setHandledRequest]=useState<number|null>(null),[edit,setEdit]=useState<DefendantEdit|null>(null);
 const view=answerRequest&&answerRequest.key!==handledRequest?'answer':localView;
 const setView=(value:string|null)=>{setLocalView(value);setHandledRequest(answerRequest?.key??null);};
 const active=liveRepresentations(data),ready=flowReadiness(data),flow=data.flow;
 const party=(id:string)=>context.parties.find(p=>p.id===id)||data.represented.find(r=>r.party_id===id)?.party;
 const names=(ids:string[])=>ids.map(id=>party(id)?partyLabel(party(id)!):t('none')).join(' · ');
 const coverage=(f:Filing)=>names(currentCoverage(f).map(c=>c.party_id));
 const stageName=(key:string|null)=>data.stages.find(s=>s.stage_key===key)?.[locale==='th'?'title_th':'title_en']||t('none');
 const manage=(v:DefendantEdit)=>setEdit(v);
 const targetFiling=view?.startsWith('filing:')?data.filings.find(f=>f.id===view.slice(7)):null;
 const targetClaim=view?.startsWith('claim:')?data.counterclaims.find(f=>f.id===view.slice(6)):null;
 const detail=targetFiling||targetClaim;
 const historyLink=<button type="button" className={base.coreTextButton} onClick={()=>setView('history')}>{t('history')}</button>;
 const flowActions=<>{!flow?canLegal&&<button disabled={active.length===0} className={base.primary} onClick={()=>manage({kind:'flow_start'})}>{t('start')}</button>:canRecord&&flow.lifecycle==='active'&&<>{ready.inconsistent?<button className={base.primary} onClick={()=>manage({kind:'flow_transition',targetStage:'D-CIV-02'})}>{t('return')}</button>:flow.current_stage==='D-CIV-01'&&ready.readyForPreparation?<button className={base.secondary} onClick={()=>manage({kind:'flow_transition',targetStage:'D-CIV-02'})}>{t('prepare')}</button>:ready.readyForHearing&&flow.current_stage!=='D-CIV-03'?<button className={base.primary} onClick={()=>manage({kind:'flow_transition',targetStage:'D-CIV-03'})}>{t('awaitHearing')}</button>:null}</>}</>;
 const answerRows=<div className={css.tableWrap}><table className={css.table}><thead><tr><th>{t('represented')}</th><th>{t('currentDue')}</th><th>{t('answer')}</th><th>{t('filings')}</th></tr></thead><tbody>{active.map(r=>{const s=defendantObligation(data,r,'');return <tr key={r.party_id} data-party={r.party_id}><td>{partyLabel(r.party)}</td><td>{date(s.due)}{s.extended&&<small>{t('extensions')} · {r.extensions.filter(e=>!e.deleted_at).length}</small>}</td><td><ObligationStatus data={data} person={r}/></td><td>{s.filings.map(f=><button className={base.coreTextButton} key={f.id} onClick={()=>setView('filing:'+f.id)}>{t('filing')} {data.filings.indexOf(f)+1}</button>)}{!s.filings.length&&'—'}</td></tr>;})}</tbody></table></div>;
 const filingList=<div className={css.records}>{data.filings.map((f,i)=><button className={css.record} data-inactive={f.lifecycle!=='active'} key={f.id} onClick={()=>setView('filing:'+f.id)}><span><strong>{t('filing')} {i+1}</strong><small>{date(f.filed_on)} · {coverage(f)}</small></span><span className={css.badge}>{t(f.lifecycle)}</span>{data.counterclaims.some(c=>c.filing_id===f.id&&c.lifecycle==='active')&&<span className={css.badge}>{t('hasCounterclaim')}</span>}</button>)}{!data.filings.length&&<p className={css.muted}>{t('none')}</p>}</div>;
 const extensionList=<div className={css.records}>{data.extension_groups.map(g=>{const blocked=g.coverage.some(c=>filingsFor(data,c.party_id).length>0||!active.some(r=>r.party_id===c.party_id));return <article key={g.id} className={css.record}><div><strong>{t(g.lifecycle==='pending'?'pendingExtension':'granted')}</strong><small>{names(g.coverage.map(c=>c.party_id))} · {date(g.requested_on)}</small>{g.coverage.map(c=>{const r=data.represented.find(x=>x.party_id===c.party_id),ex=r?.extensions.find(x=>x.id===c.extension_id);return <small key={c.party_id}>{names([c.party_id])} · {date(ex?.granted_until_date||r?.deadline?.current_due_date)}</small>;})}{g.note&&<p>{g.note}</p>}{g.document_ref&&<a href={g.document_ref} target="_blank" rel="noreferrer">{t('document')}</a>}{g.lifecycle==='pending'&&blocked&&<p className={css.warning}>{t('pendingBlocked')}</p>}</div>{canLegal&&!blocked&&<button className={base.secondary} onClick={()=>manage({kind:'extension',id:g.id})}>{t(g.lifecycle==='pending'?'grant':'correct')}</button>}</article>;})}{!data.extension_groups.length&&<p className={css.muted}>{t('none')}</p>}</div>;
 return <section className={css.root} aria-label={t('title')}>
 <div className={css.grid}>
 <section className={css.card}><header><h2><UsersRound size={19}/>{t('represented')}</h2>{canLegal&&<button className={base.secondary} onClick={()=>manage({kind:'representation'})}>{t('manage')}</button>}</header><p className={css.muted}>{t('title')} · {active.length} / {context.parties.filter(p=>p.role==='defendant'&&!p.deleted_at).length}</p>
 <div className={css.representation}>{context.parties.filter(p=>p.role==='defendant'&&!p.deleted_at).map(p=><div key={p.id}><span>{partyLabel(p)}</span><span className={css.badge} data-active={active.some(r=>r.party_id===p.id)}>{t(active.some(r=>r.party_id===p.id)?'representedYes':data.represented.some(r=>r.party_id===p.id)?'withdrawn':'representedNo')}</span></div>)}</div>{!context.parties.some(p=>p.role==='defendant'&&!p.deleted_at)&&<p>{t('noParties')}</p>}
 </section>
 <section className={css.card}><header><h2><Route size={19}/>{t('procedure')}</h2><button className={base.secondary} onClick={()=>setView('flow')}>{t('viewFlow')}</button></header><p className={css.muted}>{t('title')}{flow&&<> · {t(flow.filing_method||'notSpecified')}</>}</p><strong className={css.stage}>{flow?stageName(flow.current_stage):t('none')}</strong>{ready.inconsistent&&<p className={css.warning}>{t('inconsistency')}</p>}{ready.pending.length>0&&<p className={css.hint}>{t('pendingReview')}</p>}<div className={css.actions}>{flowActions}</div></section>
 </div>
 <section className={css.card}><header><h2><FileText size={19}/>{t('answer')}</h2><div className={css.actions}><button className={base.secondary} onClick={()=>setView('summons')}><CalendarClock size={15}/>{t('manageSummons')}</button>{canLegal&&active.length>0&&<button className={base.primary} onClick={()=>manage({kind:'filing'})}>{t('fileAnswer')}</button>}</div></header>
 {active.length?answerRows:<p className={css.muted}>{t('none')}</p>}
 <div className={css.actions}>{canLegal&&active.some(r=>r.deadline?.status==='Active'&&!filingsFor(data,r.party_id).length)&&<button className={base.secondary} onClick={()=>manage({kind:'extension'})}>{t('extension')}</button>}<button className={base.secondary} onClick={()=>setView('answer')}>{t('details')}</button>{historyLink}</div>
 <details className={css.disclosure}><summary>{t('filings')} · {data.filings.length}</summary>{filingList}</details>
 </section>
 {view&&!edit&&<CaseEditModal title={t(view==='summons'?'summons':view==='flow'?'procedure':view==='history'?'history':targetClaim?'counterclaim':targetFiling?'filing':'answer')} className={css.viewer} onClose={()=>setView(null)}><div className={css.body}>
 {view==='answer'&&<>{answerRows}<div className={css.actions}>{canLegal&&active.length>0&&<button className={base.primary} onClick={()=>manage({kind:'filing'})}>{t('fileAnswer')}</button>}{canLegal&&active.some(r=>r.deadline?.status==='Active'&&!filingsFor(data,r.party_id).length)&&<button className={base.secondary} onClick={()=>manage({kind:'extension'})}>{t('extension')}</button>}</div><h3>{t('filings')}</h3>{filingList}<h3>{t('extensions')}</h3>{extensionList}{historyLink}</>}
 {view==='summons'&&<>{active.map(r=><article key={r.party_id} className={css.person}><header><strong>{partyLabel(r.party)}</strong>{canRecord&&<button className={base.secondary} onClick={()=>manage({kind:'service',partyId:r.party_id})}>{t('service')}</button>}</header>{[...r.attempts].reverse().map(a=><div className={css.attempt} data-inactive={a.result==='void'} key={a.id}><strong>{t(a.result)} · {t(a.method||'unknown')}</strong><span>{date(a.attempted_on)}</span>{a.failure_reason&&<p>{a.failure_reason}</p>}{a.note&&<p>{a.note}</p>}{a.void_reason&&<p>{t('reason')}: {a.void_reason}</p>}<div className={css.actions}>{canRecord&&a.result==='pending'&&<button className={base.secondary} onClick={()=>manage({kind:'service',partyId:r.party_id,id:a.id})}>{t('serviceEdit')}</button>}{canLegal&&a.result!=='void'&&<button className={base.coreTextButton} onClick={()=>manage({kind:'service_void',partyId:r.party_id,id:a.id})}>{t('serviceVoid')}</button>}</div></div>)}{!r.attempts.length&&<p className={css.muted}>{t('none')}</p>}{r.deadline?<DefendantDeadline data={data} person={r} onAnswer={()=>setView('answer')}/>:<><p>{t('unconfirmed')}</p>{defendantSuggestion(r)&&<p>{t('suggested')}: <strong>{date(defendantSuggestion(r)!.date)}</strong></p>}{canLegal&&!filingsFor(data,r.party_id).length&&<button className={base.primary} onClick={()=>manage({kind:'deadline',partyId:r.party_id})}>{t('confirmDue')}</button>}</>}</article>)}{historyLink}</>}
 {detail&&<><p className={css.identity}>{targetFiling?`${t('filing')} ${data.filings.indexOf(targetFiling)+1}`:t('counterclaim')} · <span className={css.badge}>{t(detail.lifecycle)}</span></p><dl className={css.facts}><div><dt>{t('filedOn')}</dt><dd>{date(detail.filed_on)}</dd></div><div><dt>{t(targetClaim?'claimants':'coverage')}</dt><dd>{names(currentCoverage(detail).filter(c=>!targetClaim||c.side==='claimant').map(c=>c.party_id))}</dd></div>{targetClaim&&<div><dt>{t('targets')}</dt><dd>{names(currentCoverage(targetClaim).filter(c=>c.side==='target').map(c=>c.party_id))}</dd></div>}<div><dt>{t('note')}</dt><dd>{detail.note||'—'}</dd></div>{detail.reason&&<div><dt>{t('reason')}</dt><dd>{detail.reason}</dd></div>}</dl>{detail.document_ref&&<a href={detail.document_ref} target="_blank" rel="noreferrer">{t('document')}</a>}
 {targetFiling&&<><h3>{t('counterclaims')}</h3>{data.counterclaims.filter(c=>c.filing_id===targetFiling.id).map(c=><button key={c.id} className={css.record} onClick={()=>setView('claim:'+c.id)}><span>{t('counterclaim')} · {date(c.filed_on)}<small>{names(currentCoverage(c).filter(x=>x.side==='claimant').map(x=>x.party_id))}</small></span><span>{t(c.lifecycle)}</span></button>)}</>}
 {canLegal&&detail.lifecycle==='active'&&<div className={css.actions}><button className={base.secondary} onClick={()=>manage({kind:targetClaim?'counterclaim':'filing',id:detail.id})}>{t('correct')}</button><button className={base.secondary} onClick={()=>manage({kind:targetClaim?'counterclaim_void':'filing_void',id:detail.id})}>{t('voidAction')}</button>{targetClaim?<button className={base.secondary} onClick={()=>manage({kind:'counterclaim_relink',id:detail.id})}>{t('relink')}</button>:<button className={base.secondary} onClick={()=>manage({kind:'counterclaim',filingId:detail.id})}>{t('recordCounterclaim')}</button>}</div>}{historyLink}</>}
 {view==='flow'&&<><p className={css.hint}>{t('cutInHint')}{flow&&<> · {date(flow.started_at,true)}</>}</p><ol className={css.steps}>{data.stages.map(s=>{const corrected=new Set(data.transitions.map(e=>e.corrects_id));const state=flow?.current_stage===s.stage_key?'current':data.transitions.some(e=>!corrected.has(e.id)&&e.to_stage===s.stage_key)?'recorded':'unrecorded';return <li key={s.stage_key} data-current={state==='current'}><span>{s.ordinal}</span><div><strong>{s[locale==='th'?'title_th':'title_en']}</strong><small>{t(state)}</small></div></li>;})}</ol>{ready.inconsistent&&<p className={css.warning}>{t('inconsistency')}</p>}<div className={css.actions}>{flowActions}{canRecord&&flow?.lifecycle==='active'&&<button className={base.secondary} onClick={()=>manage({kind:'flow_transition'})}>{t('nextStage')}</button>}{canRecord&&flow&&data.transitions.length>0&&<button className={base.secondary} onClick={()=>manage({kind:'flow_transition',correct:true})}>{t('flowCorrect')}</button>}</div><h3>{t('history')}</h3>{data.transitions.map(e=><article className={css.attempt} key={e.id}><strong>{e.from_stage?stageName(e.from_stage)+' → ':''}{stageName(e.to_stage)}</strong><small>{context.actors[e.actor_id]||t('actor')} · {date(e.occurred_at,true)}</small>{e.reason&&<p>{e.reason}</p>}</article>)}</>}
 {view==='history'&&<>{data.history.map(e=><details key={e.id} className={css.disclosure}><summary>{t(actionLabel(e.action))} · {date(e.occurred_at,true)} · {context.actors[e.actor_id]||t('actor')}</summary><h4>{t('before')}</h4><Snapshot facts={e.before_data} context={context}/><h4>{t('after')}</h4><Snapshot facts={e.after_data} context={context}/></details>)}{!data.history.length&&<p>{t('none')}</p>}</>}
 </div></CaseEditModal>}
 {edit&&<DefendantEditor key={JSON.stringify(edit)} edit={edit} context={context} caseId={caseId} canLegal={canLegal} onClose={()=>setEdit(null)} onReload={()=>{setEdit(null);onReload();}} onSaved={()=>{setEdit(null);setView('answer');onSaved();}}/>}
 </section>;
}
function actionLabel(action:string){return ({representation:'manage',service:'service',service_void:'serviceVoid',deadline:'confirmDue',filing_create:'fileAnswer',filing_correct:'correct',filing_void:'voidFiling',extension:'extension',counterclaim_create:'recordCounterclaim',counterclaim_correct:'correct',counterclaim_void:'void',counterclaim_relink:'relink',flow_start:'start',flow_transition:'nextStage',next:'Primary next action'} as Record<string,string>)[action.replace('case104_','')]||'history';}
// Snapshots stay read-only. Their business facts are rendered with Party names, not opaque identifiers.
function Snapshot({facts,context}:{facts:Record<string,unknown>;context:DefendantContext}){
 const {t,date}=useDefendantText();
 const value=facts as Partial<DefendantData>;
 const name=(id:string)=>{const p=context.parties.find(p=>p.id===id)||context.data.represented.find(r=>r.party_id===id)?.party;return p?partyLabel(p):t('none');};
 return <div className={css.snapshot}>
 {(value.represented||[]).map(r=><div key={r.party_id}><strong>{name(r.party_id)} · {t(r.active?'representedYes':'withdrawn')}</strong>{r.reason&&<p>{r.reason}</p>}{r.deadline&&<p>{t('due')}: {date(r.deadline.current_due_date)} · {r.deadline.status==='Done'?t('filed'):t('open')}</p>}{r.extensions.map(e=><p key={e.id}>{t('extensions')} {e.extension_no} · {date(e.requested_date)} → {date(e.granted_until_date)}</p>)}{r.attempts.map(a=><p key={a.id}>{t(a.result)} · {t(a.method||'unknown')} · {date(a.attempted_on)} · {a.failure_reason||a.note||a.void_reason}</p>)}</div>)}
 {[...(value.filings||[]),...(value.counterclaims||[])].map((f,i)=><div key={f.id}><strong>{t('filing_id' in f?'counterclaim':'filing')} {i+1} · {date(f.filed_on)} · {t(f.lifecycle)}</strong>{f.coverage.map((c,j)=><p key={j}>{c.coverage_version===f.coverage_version?'':'↳ '}{c.side?t(c.side==='target'?'targets':'claimants')+': ':''}{name(c.party_id)}</p>)}{f.document_ref&&<a href={f.document_ref} target="_blank" rel="noreferrer">{t('document')}</a>}{f.note&&<p>{f.note}</p>}{f.reason&&<p>{t('reason')}: {f.reason}</p>}</div>)}
 {(value.extension_groups||[]).map(g=><div key={g.id}><strong>{t('extension')} · {t(g.lifecycle==='pending'?'pendingExtension':'granted')}</strong><p>{g.coverage.map(c=>name(c.party_id)).join(' · ')} · {date(g.requested_on)}</p>{g.note&&<p>{g.note}</p>}{g.document_ref&&<a href={g.document_ref} target="_blank" rel="noreferrer">{t('document')}</a>}</div>)}
 </div>;
}
