'use client';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { supabase } from '../../../lib/supabase';
import { SearchableCombobox } from '../../finance/expenses/searchable-combobox';
import CaseEditModal from './CaseEditModal';
import { useCaseDetailText } from './labels';
import { loadAssignmentPeople } from './core-people';
import { linkedTaskAvailable, personLabel, type CoreData } from './core-model';
import { canReportHearing, EVENT_KINDS, proceedingFacts, proceedingsError, type Hearing, type Proceeding, type ProceedingFacts } from './proceedings-model';
import css from './case-detail.module.css';

type Editor = {record?:Proceeding;hearing?:Hearing};
export default function CaseProceedings<T extends Hearing>({caseId,hearings,canEdit,canViewHistory,renderHearing}:{caseId:number;hearings:T[];canEdit:boolean;canViewHistory:boolean;renderHearing:(hearing:T,report:ReactNode)=>ReactNode}) {
 const {tr,date}=useCaseDetailText();
 const [records,setRecords]=useState<Proceeding[]>([]),[core,setCore]=useState<CoreData|null>(null),[error,setError]=useState(false),[revision,setRevision]=useState(0);
 const [editor,setEditor]=useState<Editor|null>(null),[detail,setDetail]=useState<Proceeding|null>(null);
 useEffect(()=>{const refresh=()=>setRevision(n=>n+1);window.addEventListener('case-detail-updated',refresh);return()=>window.removeEventListener('case-detail-updated',refresh);},[]);
 useEffect(()=>{let live=true;void(async()=>{try{const [reports,result]=await Promise.all([supabase.rpc('case099_read',{p_case_id:caseId}),supabase.rpc('case098_read',{p_case_id:caseId})]);if(reports.error)throw reports.error;if(result.error)throw result.error;const people=await loadAssignmentPeople(result.data as CoreData,supabase);if(live){setRecords(reports.data as Proceeding[]);setCore(people);setError(false);}}catch{if(live)setError(true);}})();return()=>{live=false;};},[caseId,revision]);
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const feed=[...hearings.map(hearing=>({id:hearing.id,date:hearing.event_date||'',hearing,record:records.find(r=>r.hearing_id===hearing.id)})),...records.filter(r=>!r.hearing_id||!hearings.some(h=>h.id===r.hearing_id)).map(record=>({id:record.id,date:record.event_date,hearing:null,record}))].sort((a,b)=>b.date.localeCompare(a.date)||a.id.localeCompare(b.id));
 return <div className={css.proceedings}>
  <header className={css.proceedingsHeader}><h4>{tr('Hearing and event history')}</h4>{canEdit&&<button className={css.secondary} disabled={!core||error} onClick={()=>setEditor({})}>{tr('Record motion / order')}</button>}</header>
  {error&&<p role="alert" className={css.coreError}>{tr('Could not load proceedings. Please reload.')} <button type="button" onClick={()=>setRevision(n=>n+1)}>{tr('Reload')}</button></p>}
  {!feed.length&&<p className={css.coreMuted}>{tr('No hearings or proceedings recorded.')}</p>}
  {feed.map(entry=>entry.hearing?<div key={entry.id}>{renderHearing(entry.hearing,<div className={css.reportSummary}>{entry.record?<><span>{tr('Hearing report')}</span><p>{entry.record.court_result||entry.record.details}</p><button className={css.secondary} onClick={()=>setDetail(entry.record!)}>{tr('View report')}</button></>:<><span className={css.coreMuted}>{tr('No hearing report recorded')}</span>{canEdit&&canReportHearing(entry.hearing,today)&&<button className={css.secondary} disabled={!core||error} onClick={()=>setEditor({hearing:entry.hearing!})}>{tr('Record hearing result')}</button>}</>}</div>)}</div>:entry.record?<article key={entry.id} className={css.proceedingRow}><div><span className={css.coreMuted}>{date(entry.date)} · {tr('proceeding.'+entry.record.kind)}</span><h4>{entry.record.title}</h4><p>{entry.record.court_result||entry.record.details}</p></div><button className={css.secondary} onClick={()=>setDetail(entry.record!)}>{tr('View details')}</button></article>:null)}
  {detail&&<ProceedingDetail canViewHistory={canViewHistory} record={detail} onClose={()=>setDetail(null)} onEdit={canEdit&&core&&!error?()=>{setEditor({record:detail});setDetail(null);}:undefined}/>}
  {editor&&core&&<ProceedingEditor key={editor.record?.id||editor.hearing?.id||'new'} caseId={caseId} core={core} record={editor.record} hearing={editor.hearing} onClose={()=>{setEditor(null);setCore(null);window.dispatchEvent(new Event('case-detail-updated'));}} onSaved={()=>{setEditor(null);window.dispatchEvent(new Event('case-detail-updated'));}}/>}
 </div>;
}
function ProceedingDetail({record:r,onClose,onEdit,canViewHistory}:{record:Proceeding;canViewHistory:boolean;onClose:()=>void;onEdit?:()=>void}){
 const {tr,date}=useCaseDetailText();const h=r.handoff;
 const name=(id?:string|null)=>h.people?.find(p=>p.id===id)?.name||tr('Unassigned');
 const next=h.core?.next_mode==='task'?(h.task?.task_type==='อื่นๆ'?h.task.task_other:tr(h.task?.task_type)):h.core?.next_title;
 return <CaseEditModal title={tr('proceeding.'+r.kind)} className={css.proceedingsEditor} onClose={onClose}><div className={css.coreForm}>
  <div><p className={css.coreMuted}>{date(r.event_date)}</p><h3 className={css.proceedingTitle}>{r.title}</h3></div>
  <dl className={css.proceedingFacts}>{[['What happened',r.details],['Court result / order',r.court_result],['Key points / party statements',r.party_statement],['Notes',r.note]].filter(([,value])=>value).map(([label,value])=><div key={label}><dt>{tr(label)}</dt><dd>{value}</dd></div>)}</dl>
  {r.document_ref&&<a href={r.document_ref} target="_blank" rel="noopener noreferrer">{tr('Open referenced document')}</a>}
  {(r.next_hearing_id||r.deadline_id||h.requested)&&<section className={css.proceedingFollowups}><h4>{tr('Recorded follow-ups')}</h4>{r.next_hearing_id&&<p><a href="#timeline" onClick={onClose}>{tr('Next hearing saved in appointments')}</a>{r.next_hearing&&<> · {r.next_hearing.title} · {date(r.next_hearing.date)} · {tr(r.next_hearing.deleted?'Removed':r.next_hearing.status)}</>}</p>}{r.deadline_id&&<p><a href="#deadlines" onClick={onClose}>{tr('Deadline saved in deadlines')}</a>{r.deadline&&<> · {r.deadline.title} · {date(r.deadline.date)} · {tr(r.deadline.deleted?'Removed':r.deadline.status)}</>}</p>}{!!h.requested?.next&&<p><strong>{tr('Primary next action')}: </strong>{next||tr('Linked task')} · {h.core?.next_mode==='task'?h.task?.assignee_name||tr('Unassigned'):name(h.core?.next_assignee_id)}{(h.task?.due_date||h.core?.next_due)&&<> · {date(h.task?.due_date||h.core?.next_due)}</>}</p>}{h.requested?.current_actor&&<p><strong>{tr('role.current_actor')}: </strong>{name(h.requested.current_actor)}</p>}<p className={css.coreMuted}>{tr('Follow-ups are already saved. Edit them in their existing sections.')}</p></section>}
  <div className={css.proceedingByline}><p>{tr('Recorded by')}: {r.author_name} · {date(r.created_at,true)}</p><p>{tr('Last edited by')}: {r.editor_name} · {date(r.updated_at,true)}</p>{canViewHistory&&<a href="#history" onClick={onClose}>{tr('View history')}</a>}</div>
  <footer className={css.coreFooter}><button className={css.secondary} onClick={onClose}>{tr('Close')}</button>{onEdit&&<button className={css.primary} onClick={onEdit}>{tr('Edit')}</button>}</footer>
 </div></CaseEditModal>;
}
function ProceedingEditor({caseId,core,record,hearing,onClose,onSaved}:{caseId:number;core:CoreData;record?:Proceeding;hearing?:Hearing;onClose:()=>void;onSaved:()=>void}){
 const {tr}=useCaseDetailText();
 const [facts,setFacts]=useState<ProceedingFacts>(()=>record?proceedingFacts(record):{kind:hearing?'hearing_report':'own_motion',hearing_id:hearing?.id||null,event_date:hearing?.event_date||new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok'}).format(new Date()),title:hearing?(hearing.appointment_type==='นัดอื่นๆ'?hearing.appointment_other||'':tr(hearing.appointment_type)):'',details:'',court_result:'',party_statement:'',note:'',document_ref:''});
 const [withHearing,setWithHearing]=useState(false),[hearingDate,setHearingDate]=useState(''),[hearingTime,setHearingTime]=useState(''),[hearingTitle,setHearingTitle]=useState('');
 const [withDeadline,setWithDeadline]=useState(false),[deadlineDate,setDeadlineDate]=useState(''),[deadlineTitle,setDeadlineTitle]=useState('');
 const [withNext,setWithNext]=useState(false),[nextMode,setNextMode]=useState('manual'),[task,setTask]=useState(''),[nextTitle,setNextTitle]=useState(''),[assignee,setAssignee]=useState(''),[due,setDue]=useState('');
 const [withActor,setWithActor]=useState(false),[actor,setActor]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const id=useRef(record?.id||crypto.randomUUID()),attempt=useRef<{body:string;request:string}|null>(null);
 const eligible=core.people.filter(p=>p.eligible);
 const person=(label:string,value:string,onChange:(s:string)=>void,required=false)=><div className={css.coreField}><label htmlFor={'proceeding-'+label}>{tr(label)}</label><SearchableCombobox id={'proceeding-'+label} label={tr(label)} placeholder={tr('Search people')} disabled={busy} value={value} onChange={onChange} options={[...(!required?[{value:'',label:{th:tr('Unassigned'),en:tr('Unassigned')}}]:[]),...eligible.map(p=>({value:p.id,label:{th:personLabel(p,eligible),en:personLabel(p,eligible)},keywords:[p.name,p.full_name].filter(Boolean).join(' ')}))]}/></div>;
 const field=(key:keyof ProceedingFacts,label:string,multiline=false,required=false)=><label>{tr(label)}{multiline?<textarea required={required} rows={3} maxLength={20000} value={facts[key]||''} onChange={e=>setFacts({...facts,[key]:e.target.value})}/>:<input required={required} type={key==='event_date'?'date':key==='document_ref'?'url':'text'} maxLength={key==='document_ref'?2000:500} value={facts[key]||''} onChange={e=>setFacts({...facts,[key]:e.target.value})}/>}</label>;
 async function save(e:React.FormEvent){e.preventDefault();if(withActor&&!actor){setError('Choose a current actor or leave the handoff unchanged.');return;}setBusy(true);setError('');
  const followups=record?{}:{...(withHearing?{hearing:{date:hearingDate,time:hearingTime,title:hearingTitle}}:{}),...(withDeadline?{deadline:{date:deadlineDate,title:deadlineTitle}}:{}),...(withNext?{next:nextMode==='task'?{mode:'task',task_id:task}:{mode:'manual',title:nextTitle,assignee_id:assignee||null,due:due||null}}:{}),...(withActor?{current_actor:actor}:{})};
  const data={facts,followups,hearing_updated_at:hearing?.updated_at||null,core_version:core.core?.version||0};const body=JSON.stringify(data);
  if(!attempt.current||attempt.current.body!==body)attempt.current={body,request:crypto.randomUUID()};
  try{const r=await supabase.rpc('case099_save',{p_case_id:caseId,p_id:id.current,p_version:record?.version||0,p_request_id:attempt.current.request,p_data:data});if(r.error){setError(proceedingsError(r.error.message));return;}onSaved();}catch{setError('Could not save proceedings. Retry the same save or reload.');}finally{setBusy(false);}
 }
 const toggle=(label:string,value:boolean,set:(v:boolean)=>void)=><label className={css.proceedingToggle}><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/>{tr(label)}</label>;
 return <CaseEditModal title={tr(record?'Edit proceedings':hearing?'Record hearing result':'Record motion / order')} className={css.proceedingsEditor} onClose={onClose} busy={busy}><form className={css.coreForm} onSubmit={save}><fieldset disabled={busy} className={css.proceedingFieldset}>
  {facts.kind==='hearing_report'?<p className={css.coreMuted}>{tr('Saving this report marks the original hearing as done.')}</p>:<label>{tr('Event type')}<select value={facts.kind} onChange={e=>setFacts({...facts,kind:e.target.value as ProceedingFacts['kind']})}>{EVENT_KINDS.map(kind=><option key={kind} value={kind}>{tr('proceeding.'+kind)}</option>)}</select></label>}
  <div className={css.coreFormGrid}>{facts.kind==='hearing_report'?<label>{tr('Hearing date')}<input type="date" readOnly value={facts.event_date}/></label>:field('event_date','Date',false,true)}{field('title','Subject',false,true)}</div>
  {field('details','What happened',true,true)}{field('court_result','Court result / order',true)}{facts.kind==='hearing_report'&&field('party_statement','Key points / party statements',true)}
  <details className={css.proceedingOptional}><summary>{tr('Notes / document reference (optional)')}</summary>{field('note','Notes',true)}{field('document_ref','Document link')}</details>
  {!record&&<section className={css.proceedingFollowups}><h4>{tr('Follow-ups (only if needed)')}</h4><p className={css.coreMuted}>{tr('Only selected follow-ups will be saved. Existing assignments stay unchanged otherwise.')}</p>
   {toggle('Add next hearing',withHearing,setWithHearing)}{withHearing&&<div className={css.proceedingFields}><label>{tr('Hearing title')}<input required maxLength={500} value={hearingTitle} onChange={e=>setHearingTitle(e.target.value)}/></label><div className={css.coreFormGrid}><label>{tr('Date')}<input required type="date" value={hearingDate} onChange={e=>setHearingDate(e.target.value)}/></label><label>{tr('Time (optional)')}<input type="time" value={hearingTime} onChange={e=>setHearingTime(e.target.value)}/></label></div></div>}
   {toggle('Add deadline',withDeadline,setWithDeadline)}{withDeadline&&<div className={css.proceedingFields}><label>{tr('Deadline subject')}<input required maxLength={500} value={deadlineTitle} onChange={e=>setDeadlineTitle(e.target.value)}/></label><label>{tr('Explicit due date')}<input required type="date" value={deadlineDate} onChange={e=>setDeadlineDate(e.target.value)}/></label><p className={css.coreMuted}>{tr('Enter the confirmed date. The system does not calculate legal deadlines here.')}</p></div>}
   {toggle('Set primary next action',withNext,setWithNext)}{withNext&&<div className={css.proceedingFields}><label>{tr('Action source')}<select value={nextMode} onChange={e=>setNextMode(e.target.value)}><option value="manual">{tr('Record an action without creating a task')}</option><option value="task">{tr('Link existing task')}</option></select></label>{nextMode==='task'?<label>{tr('Task')}<select required value={task} onChange={e=>setTask(e.target.value)}><option value="">{tr('Choose an existing task')}</option>{core.tasks.filter(linkedTaskAvailable).map(t=><option key={t.id} value={t.id}>{t.task_type==='อื่นๆ'?t.task_other:tr(t.task_type)}</option>)}</select></label>:<><label>{tr('Next action task')}<input required maxLength={500} value={nextTitle} onChange={e=>setNextTitle(e.target.value)}/></label><div className={css.coreFormGrid}>{person('Responsible person',assignee,setAssignee)}<label>{tr('Due date')}<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label></div></>}</div>}
   {toggle('Hand off to current actor',withActor,setWithActor)}{withActor&&<div className={css.proceedingFields}>{person('role.current_actor',actor,setActor,true)}</div>}
  </section>}
  {record&&<p className={css.coreMuted}>{tr('Edits retain the original facts in history. Existing follow-ups are not recreated.')}</p>}
 </fieldset>{error&&<p role="alert" className={css.coreError}>{tr(error)}</p>}<footer className={css.coreFooter}><button type="button" className={css.secondary} onClick={onClose} disabled={busy}>{tr('Cancel')}</button><button className={css.primary} disabled={busy}>{tr(busy?'Saving...':'Save')}</button></footer></form></CaseEditModal>;
}
