'use client';
import {useCaseDetailText} from './labels';
const labels:Record<string,[string,string]>={
 title:['คดีแพ่งสามัญ — ฝ่ายจำเลย','Civil ordinary — Defendant'],
 selectDefendant:['ดำเนินงานคดีแพ่งสามัญฝั่งจำเลย','Work on civil ordinary defence'],
 voidAction:['ยกเลิกรายการนี้','Void this record'],back:['กลับ','Back'],close:['ปิด','Close'],cancel:['ยกเลิก','Cancel'],save:['บันทึก','Save'],saving:['กำลังบันทึก…','Saving…'],reload:['โหลดใหม่','Reload'],details:['ดูรายละเอียด','View details'],none:['ยังไม่มีข้อมูล','Not recorded'],search:['ค้นหาชื่อคู่ความ','Search party names'],choose:['เลือก','Choose'],readonly:['อ่านอย่างเดียว','Read only'],
 represented:['จำเลยที่สำนักงานรับว่าความ','Defendants represented by VP'],manage:['จัดการจำเลยที่รับว่าความ','Manage represented defendants'],representedYes:['รับว่าความ','Represented'],representedNo:['ยังไม่รับว่าความ','Not represented'],withdrawn:['ถอนการรับว่าความแล้ว','Representation withdrawn'],add:['เพิ่มจำเลยที่รับว่าความ','Add represented defendants'],withdraw:['ถอนการรับว่าความ','Withdraw representation'],membershipHint:['การถอนเปลี่ยนเฉพาะการรับว่าความ กำหนดเวลา เอกสาร และประวัติเดิมยังคงอยู่','Withdrawal changes representation only. Deadlines, filings and history are preserved.'],noParties:['ยังไม่มีคู่ความฝ่ายจำเลย กรุณาบันทึกในส่วนคู่ความก่อน','No defendant parties yet. Record parties in the Parties section first.'],
 answer:['คำให้การจำเลย','Defendant Answer'],summons:['การรับหมายและกำหนดยื่นคำให้การจำเลย','Summons & Defendant Answer deadlines'],manageSummons:['จัดการหมายและกำหนดเวลา','Manage summons & deadlines'],service:['บันทึกข้อมูลหมาย','Record summons facts'],serviceEdit:['แก้ผลการรับหมายที่รอผล','Update pending summons result'],serviceVoid:['ยกเลิกข้อมูลหมาย','Void summons record'],result:['ผลการส่งหมาย','Service result'],served:['ส่งได้','Served'],failed:['ส่งไม่ได้','Failed'],pending:['รอผล','Pending'],void:['ยกเลิกแล้ว','Voided'],corrected:['แก้ไขโดยฉบับใหม่','Replaced'],active:['ใช้งานอยู่','Active'],method:['วิธีส่งหมาย','Service method'],normal:['ส่งปกติ','Ordinary service'],posting:['ปิดหมาย','Posting'],electronic:['ประกาศสื่ออิเล็กทรอนิกส์','Electronic publication'],other:['อื่น','Other'],unknown:['ยังไม่ทราบ','Not known'],serviceDate:['วันที่ส่ง / วันที่มีผล','Service / effective date'],failureReason:['เหตุผลที่ส่งไม่ได้','Reason service failed'],note:['หมายเหตุ','Notes'],optional:['ไม่บังคับ','Optional'],
 confirmDue:['ตรวจและยืนยันกำหนดยื่นคำให้การจำเลย','Review & confirm Defendant Answer deadline'],due:['กำหนดยื่นคำให้การจำเลย','Defendant Answer deadline'],originalDue:['วันครบกำหนดเดิม','Original due date'],currentDue:['วันครบกำหนดปัจจุบัน','Current due date'],unconfirmed:['ยังไม่ได้ยืนยันกำหนดยื่นคำให้การจำเลย','Defendant Answer deadline not yet confirmed'],open:['ยังไม่ได้ยื่นคำให้การจำเลย','Defendant Answer not yet filed'],filed:['ยื่นคำให้การจำเลยแล้ว','Defendant Answer filed'],review:['ต้องตรวจสอบกำหนดเวลา','Deadline needs review'],daysRemaining:['เหลือ {days} วัน','{days} days remaining'],daysOverdue:['เกินกำหนด {days} วัน','{days} days overdue'],today:['ครบกำหนดวันนี้','Due today'],suggested:['วันที่เสนอ','Suggested due date'],suggestionHint:['วันที่เสนอเป็นเพียงข้อมูลช่วยตรวจ ทนายต้องยืนยันวันจริง โดยไม่นับวันเริ่มต้นเป็นวันที่ 1','Review and confirm the actual due date. The suggested date excludes the trigger date.'],humanConfirm:['ตรวจสอบข้อเท็จจริงและยืนยันการบันทึก','I have checked the facts and confirm this record'],createDue:['ยืนยันกำหนดใหม่','Confirm a new deadline'],linkDue:['ใช้กำหนดเดิมที่บันทึกไว้','Use an existing deadline'],source:['ที่มา','Source'],goAnswer:['ไปที่คำให้การจำเลย','Go to Defendant Answer'],linkedHint:['ดำเนินการยื่นหรือขยายเวลาที่ส่วนคำให้การจำเลย ระบบจะปรับกำหนดเวลาที่เชื่อมไว้ให้','Record filings and extensions in Defendant Answer. Linked deadlines are updated there.'],
 filings:['การยื่นคำให้การจำเลยที่บันทึกแล้ว','Recorded Defendant Answer filings'],filing:['คำให้การจำเลยฉบับที่','Defendant Answer filing'],fileAnswer:['บันทึกการยื่นคำให้การจำเลย','Record Defendant Answer filing'],filingMode:['รูปแบบการยื่น','Filing arrangement'],separate:['ยื่นแยก — ครอบคลุมจำเลยหนึ่งราย','Separate — one defendant'],joint:['ยื่นร่วม — ฉบับเดียวครอบคลุมหลายจำเลย','Joint — one filing for multiple defendants'],coverage:['ครอบคลุมจำเลย','Covered defendants'],filedOn:['วันที่ยื่น','Filing date'],document:['ลิงก์เอกสาร / หลักฐาน','Document / evidence link'],documentHint:['ใช้ลิงก์เอกสารที่ขึ้นต้นด้วย https://','Use an https:// document link'],filingHint:['ระบบบันทึกฉบับเดียวและปิดกำหนดที่เชื่อมไว้เฉพาะจำเลยที่เลือก','One filing resolves only the selected defendants’ linked deadlines.'],counterclaimSeparate:['มีฟ้องแย้งหรือไม่? บันทึกคำให้การจำเลยให้สำเร็จก่อน แล้วเลือก “บันทึกฟ้องแย้ง” จากฉบับนั้น','Counterclaim? Save this Defendant Answer first, then choose “Record counterclaim” on the saved filing.'],
 correct:['แก้ไขข้อเท็จจริง','Correct facts'],voidFiling:['ยกเลิกฉบับนี้','Void this filing'],reason:['เหตุผล','Reason'],replacement:['บันทึกฉบับใหม่แทนฉบับเดิม','Replace with a new filing'],preserveHint:['ระบบเก็บฉบับเดิม ความครอบคลุมเดิม และประวัติการแก้ไขไว้','Original records, coverage and correction history are preserved.'],history:['ประวัติการดำเนินการ','Action history'],before:['ก่อนแก้ไข','Before'],after:['หลังแก้ไข','After'],actor:['ผู้บันทึก','Recorded by'],
 extension:['ขอ / บันทึกการขยายเวลายื่นคำให้การจำเลย','Request / record Defendant Answer extension'],extensions:['การขยายเวลายื่นคำให้การจำเลย','Defendant Answer extensions'],requested:['วันที่ยื่นคำขอ','Request date'],pendingExtension:['รอคำสั่งขยายเวลา','Extension order pending'],granted:['มีคำสั่งขยายเวลาแล้ว','Extension granted'],grant:['บันทึกผลคำสั่ง','Record court order'],newDue:['วันใหม่ตามคำสั่งจริง','New due date from the actual order'],extensionHint:['ระบุวันใหม่แยกรายจำเลยได้ คำขอที่ยังรอคำสั่งจะไม่เปลี่ยนกำหนดปัจจุบัน','Each defendant may have a different new due date. A pending request does not change current deadlines.'],pendingReview:['มีจำเลยที่ยังไม่ได้ยื่นคำให้การจำเลยและมีคำขอขยายเวลารอคำสั่ง','Some defendants have not filed their Defendant Answer and have a pending extension request.'],pendingFiled:['ยื่นคำให้การจำเลยแล้ว — คำขอขยายเวลาเดิมไม่เป็นภาระค้างของคำให้การจำเลย','Defendant Answer filed — the existing extension request is no longer an outstanding Defendant Answer obligation.'],pendingBlocked:['คำขอร่วมนี้มีทั้งจำเลยที่ยังต้องดำเนินการและจำเลยที่ยื่นแล้วหรือถอนการรับว่าความ ระบบยังไม่รองรับการบันทึกผลคำสั่งเฉพาะบางรายในคำขอเดิม กำหนดเวลาและประวัติเดิมยังคงอยู่','This joint request includes defendants still needing action and defendants who have filed or whose representation was withdrawn. Recording a court order for only some parties in the original request is not supported. Existing deadlines and history are preserved.'],
 counterclaims:['ฟ้องแย้ง','Counterclaims'],counterclaim:['ฟ้องแย้ง','Counterclaim'],recordCounterclaim:['บันทึกฟ้องแย้ง','Record counterclaim'],claimants:['จำเลยผู้ฟ้องแย้ง','Defendant counterclaimants'],targets:['โจทก์ผู้ถูกฟ้องแย้ง','Plaintiff targets'],relink:['เชื่อมกับคำให้การจำเลยฉบับอื่น','Relink to another Defendant Answer'],hasCounterclaim:['มีฟ้องแย้ง','Has counterclaim'],noCounterclaim:['ไม่มีฟ้องแย้ง','No counterclaim'],
 procedure:['กระบวนพิจารณา','Case procedure'],start:['เริ่มใช้ขั้นตอนคดีฝั่งจำเลย','Start Defendant case procedure'],viewFlow:['ดูขั้นตอนคดี','View case steps'],currentStage:['ขั้นตอนปัจจุบันจริง','Actual current stage'],filingMethod:['รูปแบบการยื่น','Filing method'],notSpecified:['ยังไม่ระบุรูปแบบการยื่น','Filing method not specified'],paper:['กระดาษ / ยื่นที่ศาล','Paper / at court'],not_filed:['ยังไม่ยื่น','Not filed'],efiling_v3:['e-Filing V3','e-Filing V3'],efiling_v4:['e-Filing V4','e-Filing V4'],cutInHint:['เริ่มใช้ขั้นตอนคดีใหม่จากจุดนี้ บันทึกจากปัจจุบันไปข้างหน้าเท่านั้น ไม่สร้างประวัติย้อนหลัง','Start a new flow at this stage. Recording begins here; no past events are backfilled.'],nextStage:['บันทึกขั้นถัดไป','Record next stage'],prepare:['ไปขั้นจัดทำและยื่นคำให้การจำเลย','Proceed to prepare and file Defendant Answer'],awaitHearing:['ไปขั้นรอนัดแรก','Proceed to await first hearing'],return:['กลับไปขั้นจัดทำและยื่นคำให้การจำเลย','Return to prepare and file Defendant Answer'],inconsistency:['มีจำเลยที่ยังไม่มีคำให้การจำเลยฉบับใช้งานอยู่ แต่ขั้นตอนยังเป็นรอนัดแรก กรุณาตรวจและยืนยันการกลับขั้น ระบบไม่เปลี่ยนขั้นเอง','A Defendant Answer obligation has reopened while the flow remains at first-hearing preparation. Review and confirm a return; the stage is not changed automatically.'],flowCorrect:['แก้ไขการบันทึกขั้นล่าสุด','Correct latest stage record'],current:['ขั้นตอนปัจจุบัน','Current stage'],recorded:['มีประวัติบันทึก','Recorded'],unrecorded:['ยังไม่มีประวัติบันทึก','No recorded visit'],
 loading:['กำลังโหลดข้อมูลฝ่ายจำเลย…','Loading Defendant case data…'],loadFailed:['โหลดข้อมูลฝ่ายจำเลยไม่สำเร็จ กรุณาลองใหม่','Defendant case data could not be loaded. Please retry.'],saved:['บันทึกสำเร็จ','Saved'],savedReload:['บันทึกสำเร็จแล้ว แต่ยังโหลดข้อมูลล่าสุดไม่สำเร็จ กรุณาโหลดใหม่ก่อนดำเนินการต่อ','Saved, but the latest data could not be loaded. Reload before continuing.'],retry:['ลองคำขอเดิมอีกครั้ง','Retry the same request'],uncertainHint:['ยังยืนยันผลบันทึกไม่ได้ กรุณาลองคำขอเดิมก่อนเปลี่ยนข้อมูล เพื่อป้องกันการบันทึกซ้ำ','The save result is uncertain. Retry this same request before changing facts to prevent duplicates.'],
 'error.stale':['ข้อมูลมีการเปลี่ยนแปลง กรุณาโหลดข้อมูลล่าสุดแล้วเปิดรายการใหม่','Data changed. Reload the latest data and reopen this action.'],
 'error.dependency':['มีฟ้องแย้งที่เชื่อมอยู่ ต้องแก้ไข ยกเลิก หรือเชื่อมฟ้องแย้งใหม่อย่างชัดเจนก่อนเปลี่ยนความครอบคลุมหรือยกเลิกฉบับนี้','An active counterclaim depends on this filing. Explicitly correct, void or relink it before changing coverage or voiding this filing.'],
 'error.conflict':['คดีนี้มีขั้นตอนคดีฝั่งโจทก์หรือเส้นทางหลักอื่นอยู่แล้ว ไม่สามารถแทนที่ด้วยฝั่งจำเลยได้','This case already has a Plaintiff or other main track. It cannot be overwritten by a Defendant flow.'],
 'error.legacyReview':['มีข้อเท็จจริงการยื่นคำให้การจำเลยเดิม ต้องตรวจสอบก่อนเริ่มรับว่าความในระบบนี้ ห้ามสร้างประวัติย้อนหลัง','An existing legacy Defendant Answer filing needs review before activating representation. Do not backfill history.'],
 'error.forbidden':['คุณไม่มีสิทธิ์ดำเนินการนี้ หรือบัญชียังไม่พร้อมใช้งาน','Your account cannot perform this action or is not ready for use.'],
 'error.deadlineReview':['กำหนดเวลาที่เชื่อมไว้มีข้อเท็จจริงที่ต้องตรวจสอบ กรุณาตรวจข้อมูลล่าสุดก่อนดำเนินการ','The linked deadline requires review. Check current facts before proceeding.'],
 'error.partyReview':['กรุณาตรวจสอบจำเลยที่รับว่าความและคู่ความที่เลือกอีกครั้ง','Review represented defendants and selected parties.'],
 'error.unresolved':['ยังมีจำเลยที่ไม่มีคำให้การจำเลยฉบับใช้งานอยู่','Some represented defendants do not have an active Defendant Answer filing.'],
 'error.requestConflict':['คำขอบันทึกนี้ถูกใช้กับข้อมูลอื่นแล้ว กรุณาโหลดใหม่','This request was already used for different facts. Reload the data.'],
 'error.attemptFinal':['ผลรายการนี้สิ้นสุดแล้ว ต้องตรวจประวัติและใช้การยกเลิกพร้อมเหตุผลเมื่อข้อเท็จจริงที่เชื่อมไว้อนุญาต','This summons record is final. Review its history and use a reasoned void where permitted.'],
 'error.invalidDate':['ตรวจสอบวันที่จริงและอย่าใช้วันที่ในอนาคตสำหรับเหตุการณ์ที่เกิดแล้ว','Check actual dates. Recorded events cannot be future-dated.'],
 'error.reasonRequired':['กรุณาระบุเหตุผล','Please provide a reason.'],
 'error.confirmRequired':['กรุณาตรวจสอบและยืนยันข้อเท็จจริงก่อนบันทึก','Review and confirm the facts before saving.'],
 'error.invalid':['ตรวจสอบข้อมูล คู่ความ วันที่ และลิงก์เอกสารให้ครบตามรายการ','Check party coverage, dates, document links and required fields.'],
 'error.uncertain':['ยังยืนยันผลการบันทึกไม่ได้','The save result could not be confirmed.'],
};
export function defendantText(key:string,locale:'th'|'en'){return labels[key]?.[locale==='th'?0:1]||key;}
export function useDefendantText(){const text=useCaseDetailText();return {...text,t:(key:string)=>labels[key]?defendantText(key,text.locale):text.tr(key)};}
