import type { CoreData, CoreTask } from './core-model';
export const EVENT_KINDS = ['own_motion','opponent_motion','court_order'] as const;
export type ProceedingKind = 'hearing_report' | typeof EVENT_KINDS[number];
export type Hearing = { id:string; event_type?:string|null; event_date?:string|null; updated_at?:string|null; status?:string|null; appointment_type?:string|null; appointment_other?:string|null };
export type ProceedingFacts = {kind:ProceedingKind;hearing_id:string|null;event_date:string;title:string;details:string;court_result:string;party_statement:string;note:string;document_ref:string};
export type Proceeding = ProceedingFacts & {id:string;version:number;created_at:string;updated_at:string;author_name:string;editor_name:string;next_hearing_id:string|null;deadline_id:string|null;next_hearing?:{date:string;title:string;status:string;deleted:boolean};deadline?:{date:string;title:string;status:string;deleted:boolean};handoff:{requested?:{next?:unknown;current_actor?:string};core?:CoreData['core'];team?:CoreData['team'];people?:CoreData['people'];task?:CoreTask}};
export function canReportHearing(hearing:Hearing,today:string){return hearing.event_type==='hearing' && hearing.status!=='Cancelled' && !!hearing.event_date && /^\d{4}-\d{2}-\d{2}$/.test(hearing.event_date) && hearing.event_date<=today;}
export function proceedingFacts(record:Proceeding):ProceedingFacts {
 return Object.fromEntries(['kind','hearing_id','event_date','title','details','court_result','party_statement','note','document_ref'].map(key=>[key,record[key as keyof Proceeding]??(key==='hearing_id'?null:'')])) as ProceedingFacts;
}
export function proceedingsError(message:string){
 const match=message.match(/CASE(?:099|098)_[A-Z_]+/)?.[0];
 const map:Record<string,string>={CASE099_FORBIDDEN:'Proceedings permission denied',CASE099_NOT_FOUND:'Proceedings case unavailable',CASE099_STALE:'Proceedings changed. Close and reopen to reload.',CASE099_CORE_STALE:'Case assignments changed. Close and reopen to reload.',CASE098_STALE:'Case assignments changed. Close and reopen to reload.',CASE099_HEARING_STALE:'Hearing changed. Close and reopen to reload.',CASE099_HEARING_UNAVAILABLE:'Hearing is no longer available',CASE099_HEARING_NOT_HELD:'Only a hearing that has taken place can have a report.',CASE099_REPORT_EXISTS:'This hearing already has a report. Reload to edit it.',CASE099_PERSON_INELIGIBLE:'The selected person is no longer available for assignment.',CASE098_PERSON_INELIGIBLE:'The selected person is no longer available for assignment.',CASE098_TASK_UNAVAILABLE:'The selected task is no longer available.',CASE099_INVALID_HEARING:'Check the next hearing title, date and time.',CASE099_INVALID_DEADLINE:'Enter the deadline title and an explicit due date.',CASE099_IDENTITY_FIXED:'The original hearing and record type cannot be changed.',CASE099_FOLLOWUPS_ALREADY_SAVED:'Follow-ups are already saved. Edit them in their existing sections.',CASE099_REQUEST_CONFLICT:'This save was already received with different details. Reload before continuing.',CASE099_INVALID_INPUT:'Check the required facts, dates and document link.',CASE098_INVALID_INPUT:'Check the required facts, dates and document link.'};
 return map[match||'']||'Could not save proceedings. Retry the same save or reload.';
}
