"use client";
import { useEffect, useState } from "react";
import { Link2, ShieldCheck } from "lucide-react";
import { FieldGroup } from "../../components/ui/patterns";
import ui from "../../components/ui/vp-ui.module.css";
import { useI18n } from "../../../lib/i18n/provider";
import { supabase } from "../../../lib/supabase";
import type { ExpenseAccess, ExpenseAccount, ExpenseLookups } from "./shared";
import type { ExpenseRun } from "./forms";
import css from "./expenses.module.css";
type Authority = { id: string; user_id: string; bank_account_id: string | null; cash_location_id: string | null; version: number; view_balance: boolean; view_movements: boolean; record_outflow: boolean; confirm_outflow: boolean };
export function ExpenseAdminTools({ access, accounts, lookups, run, busy, fixture, onBridge, showAuthorities = true }: { access: ExpenseAccess; accounts: ExpenseAccount[]; lookups: ExpenseLookups; run: ExpenseRun; busy: boolean; fixture: boolean; onBridge: (id: string) => void; showAuthorities?: boolean }) {
 const { t } = useI18n(), [legacy, setLegacy] = useState(""), [reason, setReason] = useState(""), [ack, setAck] = useState(false), [id] = useState(() => crypto.randomUUID());
 const [user, setUser] = useState(""), [account, setAccount] = useState(""), [grantReason, setGrantReason] = useState(""), [authorities, setAuthorities] = useState<Authority[] | null>(null);
 const [rights, setRights] = useState({ view_balance: false, view_movements: false, record_outflow: false, confirm_outflow: false });
 const load = async () => { if (fixture || !access.is_admin || !showAuthorities) return; const r = await supabase.rpc("get_finance_treasury_authorities"); if (!r.error) setAuthorities(r.data); };
 useEffect(() => { if (!fixture && access.is_admin && showAuthorities) { let live = true; void supabase.rpc("get_finance_treasury_authorities").then(r => { if (live && !r.error) setAuthorities(r.data); }); return () => { live = false; }; } }, [access.is_admin, fixture, showAuthorities]);
 const existing = authorities?.find(a => a.user_id === user && (a.bank_account_id || a.cash_location_id) === account);
 function choose(nextUser: string, nextAccount: string) { setUser(nextUser); setAccount(nextAccount); const a = authorities?.find(a => a.user_id === nextUser && (a.bank_account_id || a.cash_location_id) === nextAccount); setRights({ view_balance: !!a?.view_balance, view_movements: !!a?.view_movements, record_outflow: !!a?.record_outflow, confirm_outflow: !!a?.confirm_outflow }); }
 if (!access.is_admin) return null;
 return <details className={`${css.disclosure} ${css.adminTools}`}><summary>{t("expenses.adminTools")}</summary>
  <details className={css.disclosure}><summary><Link2 size={16} aria-hidden="true" /> {t("expenses.bridge")}</summary><form className={css.form} onSubmit={async e => { e.preventDefault(); const value = await run("bridge_finance_legacy_expense", { p_legacy_id: legacy.trim(), p_id: id, p_reason: reason, p_acknowledged: ack }); if (value) onBridge(value); }}><div className={css.formGrid}><FieldGroup id="legacy-id" label={t("expenses.legacyId")}><input required value={legacy} disabled={busy} onChange={e => setLegacy(e.target.value)} /></FieldGroup><FieldGroup id="legacy-reason" label={t("expenses.reason")}><input required maxLength={2000} value={reason} disabled={busy} onChange={e => setReason(e.target.value)} /></FieldGroup></div><label className={css.check}><input type="checkbox" required checked={ack} disabled={busy} onChange={e => setAck(e.target.checked)} /><span>{t("expenses.bridgeAck")}</span></label><div className={css.footer}><button type="submit" className={ui.secondary} disabled={busy || !ack}>{t("expenses.bridge")}</button></div></form></details>
  {showAuthorities ? <details className={css.disclosure}><summary><ShieldCheck size={16} aria-hidden="true" /> {t("expenses.authorities")}</summary><p className={css.muted}>{t("expenses.authorityHelp")}</p><form className={css.form} onSubmit={async e => { e.preventDefault(); const a = accounts.find(a => a.id === account); await run("set_finance_treasury_authority", { p_user: user, p_bank: a?.bank_account_id || null, p_cash: a?.cash_location_id || null, p_rights: rights, p_version: existing?.version ?? null, p_reason: grantReason }); await load(); }}>
   <div className={css.formGrid}><FieldGroup id="authority-person" label={t("expenses.claimant")}><select required value={user} disabled={busy || !authorities} onChange={e => choose(e.target.value, account)}><option value="">{t("expenses.choose")}</option>{lookups.people.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></FieldGroup><FieldGroup id="authority-account" label={t("expenses.account")}><select required value={account} disabled={busy || !authorities} onChange={e => choose(user, e.target.value)}><option value="">{t("expenses.choose")}</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></FieldGroup></div>
   <div className={css.checks}>{(Object.keys(rights) as (keyof typeof rights)[]).map(key => <label className={css.check} key={key}><input type="checkbox" checked={rights[key]} disabled={busy} onChange={e => setRights(r => ({ ...r, [key]: e.target.checked, ...(key === "confirm_outflow" && e.target.checked ? { record_outflow: true } : key === "record_outflow" && !e.target.checked ? { confirm_outflow: false } : {}) }))} /><span>{t(`expenses.${key}`)}</span></label>)}</div>
   <FieldGroup id="authority-reason" label={t("expenses.reason")}><input required maxLength={2000} value={grantReason} disabled={busy} onChange={e => setGrantReason(e.target.value)} /></FieldGroup><div className={css.footer}><button type="submit" className={ui.secondary} disabled={busy || !authorities}>{t("expenses.grant")}</button></div>
  </form></details> : null}
 </details>;
}
