"use client";
import { FinanceStatusBadge } from "../ui/primitives";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, RefreshCw, Search } from "lucide-react";
import { supabase } from "../../../lib/supabase";
import { useI18n } from "../../../lib/i18n/provider";
import { Callout, PageShell } from "../../components/ui/patterns";
import ui from "../../components/ui/vp-ui.module.css";
import { revenueHref, type RevenueWorkspaceData, type RevenueState } from "./shared";
import css from "./workspace.module.css";
export function RevenueBadge({ state }: { state: RevenueState }) { const { t } = useI18n(); return <FinanceStatusBadge status={state} label={t(`revenueDistribution.${state}`)}/>; }
export function RevenueWorkspace() {
 const { t, locale, date } = useI18n(), seq = useRef(0);
 const [data, setData] = useState<RevenueWorkspaceData | null>(null), [failed, setFailed] = useState(false), [loading, setLoading] = useState(true);
 const [month, setMonth] = useState(""), [source, setSource] = useState("all"), [status, setStatus] = useState("pending"), [search, setSearch] = useState(""), [offset, setOffset] = useState(0), [refresh, setRefresh] = useState(0);
 const w = (key: string) => t(`revenueDistribution.${key}`), money = (n: number | null, currency = "THB") => n === null ? w("unknown") : `${n.toLocaleString(locale, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${currency}`;
 useEffect(() => { let live = true; const id = ++seq.current; const timer = setTimeout(() => { setLoading(true); setFailed(false); void supabase.rpc("get_finance_revenue_distribution_workspace", { p_month: month ? `${month}-01` : null, p_source_type: source, p_status: status, p_search: search, p_offset: offset }).then(r => {
  if (!live || id !== seq.current) return; if (r.error || !Array.isArray(r.data?.rows) || !Array.isArray(r.data?.summary)) { setFailed(true); setData(null); } else setData(r.data); setLoading(false);
 }, () => { if (live && id === seq.current) { setFailed(true); setData(null); setLoading(false); } }); }, 150); return () => { live = false; clearTimeout(timer); }; }, [month, source, status, search, offset, refresh]);
 function filter(change: () => void) { seq.current++; setData(null); setLoading(true); setOffset(0); change(); }
 return <PageShell className={css.page}><header className={css.header}><div><h1>{w("title")}</h1><p>{w("description")}</p></div><button className={ui.secondary} aria-label={w("retry")} onClick={() => setRefresh(n => n + 1)}><RefreshCw size={17} /></button></header>
  <div className={css.cards}>{(["pending", "unpaid", "partial", "paid"] as RevenueState[]).map(state => { const rows = data?.summary.filter(s => s.state === state) || []; return <button className={`${css.card} ${css[state]}`} key={state} onClick={() => filter(() => setStatus(state))}><span>{w(state)}</span><div><strong>{loading || failed ? "—" : rows.reduce((n, r) => n + r.count, 0)}</strong><small>{w("rows")}</small></div><b><small>{w("basis")} · </small>{loading || failed ? "—" : rows.length ? rows.map(r => money(r.amount, r.currency)).join(" / ") : money(0)}</b>{rows.some(r => r.unresolved > 0) ? <small>{w("unresolved")}</small> : null}</button>; })}</div>
  <nav className={css.tabs} aria-label={w("status")}>{["pending", "unpaid", "partial", "paid", "history", "all"].map(s => <button key={s} aria-current={status === s ? "page" : undefined} onClick={() => filter(() => setStatus(s))}>{w(s)}</button>)}</nav>
  <div className={css.filters}><label>{w("month")}<input aria-label={w("month")} type="month" lang={locale} value={month} onChange={e => filter(() => setMonth(e.target.value))} /></label><label>{w("source")}<select value={source} onChange={e => filter(() => setSource(e.target.value))}>{["all", "payment", "direct_money_receipt"].map(s => <option key={s} value={s}>{w(s)}</option>)}</select></label><label className={css.search}><span><Search size={14} /> {w("search")}</span><input type="search" value={search} onChange={e => filter(() => setSearch(e.target.value))} /></label></div>
  {failed ? <Callout tone="negative" role="alert">{w("conflict")}</Callout> : loading ? <p role="status">{t("common.state.loading")}</p> : data ? <><div className={css.tableWrap}><table className={css.table}><thead><tr>{["date", "reference", "source", "client", "matter", "cash", "basis", "status", "detail"].map(k => <th key={k}>{w(k)}</th>)}</tr></thead><tbody>{data.rows.map(r => <tr key={`${r.source_type}:${r.source_id}`}><td data-label={w("date")}>{date(r.received_on)}</td><td data-label={w("reference")}><strong>{r.reference}</strong></td><td data-label={w("source")}>{w(r.source_type)}</td><td data-label={w("client")}>{r.client || "—"}</td><td data-label={w("matter")}>{r.matter || "—"}</td><td className={css.number} data-label={w("cash")}>{money(r.cash, r.currency)}</td><td className={css.number} data-label={w("basis")}>{money(r.basis, r.currency)}</td><td data-label={w("status")}><RevenueBadge state={r.state} />{r.blockers.length ? <small className={css.warning}>{w("blocked")}</small> : null}</td><td><Link className={r.distribution_id || !data.can_manage ? ui.secondary : ui.primary} href={revenueHref(r.source_type, r.source_id)}>{w(r.distribution_id || !data.can_manage ? "detail" : "allocate")}<ArrowRight size={14} /></Link></td></tr>)}</tbody></table>{!data.rows.length ? <p className={css.empty}>{w("empty")}</p> : null}</div><footer className={css.pagination}><span>{data.count} {w("rows")}</span><div><button className={ui.secondary} disabled={!offset} onClick={() => setOffset(n => n - 50)}>{w("previous")}</button><span>{Math.floor(offset / 50) + 1}</span><button className={ui.secondary} disabled={offset + 50 >= data.count} onClick={() => setOffset(n => n + 50)}>{w("next")}</button></div></footer></> : null}
 </PageShell>;
}
