const labels={
 routing:['เส้นทางตามผลลัพธ์','Outcome routes'],enable:['เพิ่มเส้นทางตามผลลัพธ์ในเวอร์ชันใหม่','Add outcome routes to the new version'],enableHint:['เลือกผลลัพธ์เมื่อจบขั้นตอนเท่านั้น รูปแบบเดิมและงานเดิมยังคงเดิม','Outcomes are chosen only on completion. Existing versions and matters stay unchanged.'],
 stage:['ขั้นตอน','Stage'],outcomes:['ผลลัพธ์เมื่อจบขั้นตอน','Completion outcomes'],addOutcome:['เพิ่มผลลัพธ์','Add outcome'],removeOutcome:['ลบผลลัพธ์','Remove outcome'],nameTh:['ชื่อภาษาไทย','Thai name'],nameEn:['ชื่อภาษาอังกฤษ','English name'],target:['ไปขั้นตอน','Target stage'],reasonRequired:['บังคับเหตุผล','Reason required'],conditional:['ขั้นตอนตามเงื่อนไข','Conditional stage'],conditionalHint:['เปิดเมื่อเลือกเส้นทางมาถึงเท่านั้น การไม่เลือกไม่ใช่การข้าม','Activated only when routed here. An unchosen branch is not a skipped stage.'],
 terminal:['ปิดงานเป็นการดำเนินการแยกต่างหาก โดยยังต้องผ่านการตรวจงานค้างเดิม','Closing the matter remains a separate action with the existing readiness checks.'],
 routeMissing:['ทุกขั้นตอนก่อนปิดงานต้องมีผลลัพธ์และขั้นตอนปลายทางที่ถูกต้อง','Every non-closing stage needs outcomes with valid targets.'],routeDisconnected:['ทุกขั้นตอนต้องมีเส้นทางจากขั้นตอนแรกและมีทางไปปิดงาน ตรวจเส้นทางที่ยังไม่เชื่อมต่อหรือวนโดยไม่มีทางออก','Every stage must be reachable from intake and have a route to close. Check disconnected stages or loops without an exit.'],
 actual:['เส้นทางที่เกิดขึ้นจริง','Actual path'],possible:['เส้นทางที่เป็นไปได้','Possible routes'],possibleHint:['แสดงเพื่อวางแผนเท่านั้น ยังไม่ใช่ประวัติการดำเนินงาน','For planning only; these are not recorded stage visits.'],notActivated:['ยังไม่เปิดใช้งาน','Not activated'],
 decisions:['ประวัติการตัดสินใจ','Decision history'],emptyDecisions:['ยังไม่มีผลลัพธ์ที่บันทึกจากการจบขั้นตอน','No completion outcomes have been recorded.'],outcome:['ผลลัพธ์','Outcome'],reason:['เหตุผล / บันทึกประกอบ','Reason / note'],actor:['ผู้ดำเนินการ','Actor'],time:['วันและเวลา','Date and time'],from:['จากขั้นตอน','From stage'],to:['ไปขั้นตอน','To stage'],
 choose:['เลือกผลลัพธ์เพื่อกำหนดขั้นตอนถัดไป','Choose an outcome to determine the next stage'],automatic:['มีผลลัพธ์เดียว ระบบเลือกให้อัตโนมัติ','The sole outcome is selected automatically'],summary:['สรุปการเปลี่ยนแปลง','Transition summary'],auditHint:['จบขั้นตอนปัจจุบัน บันทึกผลลัพธ์และเหตุผล เปิดขั้นตอนถัดไป พร้อมประวัติผู้ดำเนินการในรายการเดียว','Complete the current visit, record the outcome and reason, open the next visit, and audit the actor in one transaction.'],selectOutcome:['กรุณาเลือกผลลัพธ์','Please select an outcome'],enterReason:['กรุณาระบุเหตุผลของผลลัพธ์นี้','Please enter a reason for this outcome'],
 completeInstead:['ขั้นตอนนี้ต้องจบโดยเลือกผลลัพธ์ ไม่สามารถใช้การข้ามเพื่อเลือกเส้นทาง','Complete this stage using its outcome; Skip cannot select a branch.'],showRoutes:['ดูรูปแบบการดำเนินงาน','View journey routes'],visit:['ครั้งที่','Visit'],noVisits:['ยังไม่มีการเริ่มขั้นตอน','No stage visit has started'],skipped:['ข้ามแล้ว','Skipped'],skipReason:['เหตุผลที่ข้าม','Skip reason'],
} as const;
export type ControlledLabel=keyof typeof labels;
export function controlledText(locale:string,key:ControlledLabel){return labels[key][locale==='en'?1:0];}
