"use client";
import {useState} from 'react';
import {Flag,Search,FileText,Handshake,Check,SkipForward,Compass,MapPin} from 'lucide-react';
import {defaultTemplate,stageState,templates,type Matter,type Stage} from '../../../lib/advisory-control';
import {useAdvisoryLabels} from './shared';
import type {EditRequest} from './MatterEditor';
import css from './control.module.css';
export default function Journey({matter,stages,canEdit,onEdit}:{matter:Matter;stages:Stage[];canEdit:boolean;onEdit:(request:EditRequest)=>void}){const {a,label,date}=useAdvisoryLabels();const [selected,setSelected]=useState(''),[template,setTemplate]=useState(stages[0]?.template_key||defaultTemplate(matter.matter_type));
 const plan:Stage[]=stages.length?stages:templates[template].map((key,position)=>({id:'',stage_key:key,template_key:template,position,visits:[],minutes:null}));
 const chosen=plan.find(s=>s.stage_key===(selected||matter.stage_key))||plan[0];
 const latest=chosen.visits.find(v=>v.kind==='visit');
 const current=chosen.visits.find(v=>v.kind==='visit'&&!v.exited_at),state=stageState(chosen,matter.stage_key,!!matter.closed_at);
 return <section className={css.journeySection}><div className={css.sectionHeading}><div><h2>{a('journey')}</h2><p>{a('journeyHint')}</p></div>{!stages.length&&!matter.closed_at&&<label>{a('template')}<select value={template} onChange={e=>{setTemplate(e.target.value);setSelected('');}}>{Object.keys(templates).map(k=><option key={k} value={k}>{label(k)}</option>)}</select></label>}</div>
 {!matter.stage_key&&!matter.closed_at&&<p className={css.notice}>{a('unset')} · {a('stageUnsetHint')}</p>}
 <div className={css.journey} style={{'--stage-count':plan.length} as React.CSSProperties}><div className={css.path}/>{plan.map((s,i)=>{const status=stageState(s,matter.stage_key,!!matter.closed_at);const Icon=status==='visited'||status==='finished'?Check:status==='skipped'?SkipForward:s.stage_key==='close'?Flag:['analysis','research','facts'].includes(s.stage_key)?Search:['draft','review','preparation'].includes(s.stage_key)?FileText:['negotiation','delivery','client_delivery'].includes(s.stage_key)?Handshake:i===0?MapPin:Compass;return <button key={s.stage_key} className={css.station} data-state={status} aria-pressed={chosen.stage_key===s.stage_key} onClick={()=>setSelected(s.stage_key)}><span className={css.stationIcon}><Icon size={25}/></span><span className={css.stationText}><strong>{label(s.stage_key)}</strong><small>{a(status)}</small>{status==='current'&&<small>{date(matter.entered_at)}</small>}</span></button>;})}</div>
 <div className={css.stageDetail}><div><strong>{label(chosen.stage_key)}</strong><span className={css.badge}>{a(state)}</span></div><dl><div><dt>{a('entered')}</dt><dd>{date(current?.entered_at||chosen.visits.find(v=>v.kind==='visit')?.entered_at)}</dd></div><div><dt>{a('stageDays')}</dt><dd>{chosen.elapsed_seconds!=null?a('days',{n:Math.max(0,Math.floor(chosen.elapsed_seconds/86400))}):state==='current'&&matter.stage_days!==null?a('days',{n:matter.stage_days}):'—'}</dd></div><div><dt>{a('exited')}</dt><dd>{date(latest?.exited_at)}</dd></div><div><dt>{a('actual')}</dt><dd>{chosen.minutes===null?a('unclassified'):a('minutes',{n:chosen.minutes})}</dd></div><div><dt>{a('next')}</dt><dd>{matter.next_action||a('noNext')}</dd></div><div><dt>{a('taskCompletion')}</dt><dd>{chosen.task_completed||0} / {chosen.task_total||0}</dd></div><div><dt>{a('actor')}</dt><dd>{matter.next_owner_name||'—'}</dd></div><div><dt>{a('due')}</dt><dd>{date(matter.next_due)}</dd></div></dl>
 {canEdit&&!matter.closed_at&&chosen.stage_key!=='close'&&state!=='current'&&<div className={css.actions}><button className={css.primary} onClick={()=>onEdit({action:'stage',title:a('activate'),values:{template,stage_key:chosen.stage_key}})}>{a('activate')}</button>{!chosen.visits.length&&<button onClick={()=>onEdit({action:'stage_skip',title:a('skip'),values:{template,stage_key:chosen.stage_key}})}>{a('skip')}</button>}</div>}</div></section>;
}
