"use client";
import {matterClosed} from '../../../lib/advisory-workflow';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Check,Plus,ArrowRight,FileCheck2,Clock3,ListTodo,FileText} from 'lucide-react';
import {supabase} from '../../../lib/supabase';
import {personName,type Activity,type Deliverable,type Matter,type Person,type Task} from '../../../lib/advisory-control';
import {Badge,Pagination,useAdvisoryLabels} from './shared';
import {OverdueDays} from './MatterOverdue';
import type {EditRequest} from './MatterEditor';
import css from './control.module.css';
import ui from './overview.module.css';
type SectionProps={matter:Matter;section:'tasks'|'activity'|'deliverables';people:Person[];canEdit:boolean;onEdit:(e:EditRequest)=>void;onAction:(action:string,payload:Record<string,string>)=>Promise<void>;busy:boolean;canSetNext?:boolean;canDelete?:boolean;issueId?:string;overview?:boolean;focused?:boolean;onFocus?:()=>void};
export default function MatterSections({matter,section,people,canEdit,onEdit,onAction,busy,issueId,canSetNext=false,canDelete=false,overview=false,focused=false,onFocus}:SectionProps){const {a,label,date}=useAdvisoryLabels();const [rows,setRows]=useState<(Task|Activity|Deliverable)[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[error,setError]=useState(false),[expanded,setExpanded]=useState(false),[deleted,setDeleted]=useState(false),[loadedKey,setLoadedKey]=useState('');
 const showDeleted=deleted&&(!overview||focused);
 const requestOffset=overview&&!focused?0:offset;
 const queryKey=JSON.stringify([matter.id,matter.version,section,requestOffset,issueId,showDeleted]);
 useEffect(()=>{let live=true;void Promise.resolve(supabase.rpc('advisory_control_section',{p_matter_id:matter.id,p_section:showDeleted?'deleted_tasks':section,p_offset:requestOffset,p_issue_id:issueId||null})).then(r=>{if(live){setError(!!r.error);setRows(r.error?[]:r.data?.items||[]);setTotal(r.error?0:r.data?.total||0);setLoadedKey(queryKey);}}).catch(()=>{if(live){setError(true);setLoadedKey(queryKey);}});return()=>{live=false;};},[matter.id,matter.version,section,requestOffset,issueId,showDeleted,queryKey]);
 const loading=overview&&loadedKey!==queryKey;
 const visible=(overview?focused:expanded)?rows:rows.slice(0,5);
 const Icon=section==='tasks'?ListTodo:section==='activity'?Clock3:FileCheck2;
 const addKey=section==='tasks'?'addTask':section==='activity'?'addNote':'addDeliverable';
 return <section className={`${css.panel} ${overview?ui.panel:''}`} aria-label={a(section)}>
 <div className={overview?ui.panelHeading:css.sectionHeading}><h2>{overview&&<Icon size={19}/>} {a(section)}{overview&&<small>({loading||error?'—':total})</small>}</h2><div className={ui.panelActions}>{canEdit&&!matterClosed(matter)&&<button className={css.textButton} onClick={()=>onEdit({action:section==='tasks'?'task_save':section==='activity'?'note':'deliverable',title:a(addKey),values:issueId?{issue_id:issueId}:undefined})}><Plus size={15}/>{a(addKey)}</button>}{overview&&!focused&&onFocus&&<button className={css.textButton} onClick={()=>{setOffset(0);onFocus();}}>{a('viewAll')} →</button>}</div></div>
 {section==='tasks'&&canDelete&&(!overview||focused)&&<button className={css.textButton} onClick={()=>{setDeleted(v=>!v);setOffset(0);}}>{a(showDeleted?'tasks':'deletedTasks')}</button>}
 {loading?<p role="status" className={ui.compactEmpty}>{a('loading')}</p>:error?<p role="alert" className={css.error}>{a('loadError')}</p>:!rows.length?overview?<div className={ui.compactEmpty}><FileText size={21}/><strong>{a(showDeleted?'empty':'empty.'+section)}</strong>{!showDeleted&&<small>{a('emptyHint.'+section)}</small>}</div>:<p className={css.empty}>{a('empty')}</p>:<ul className={css.rows}>{visible.map(row=>{if(section==='tasks'){const t=row as Task,done=['completed','cancelled'].includes(t.status);if(showDeleted)return <li key={t.id}><strong>{t.title}</strong>{canDelete&&!matterClosed(matter)&&<button disabled={busy} onClick={()=>onAction('task_restore',{id:t.id})}>{a('restoreTask')}</button>}</li>;return <li key={t.id}><div className={css.rowMain}>{canEdit&&!matterClosed(matter)&&!done?<button className={css.complete} disabled={busy} aria-label={a('complete')+': '+t.title} onClick={()=>onAction('task_complete',{id:t.id})}><Check size={16}/></button>:<Check size={16} className={done?css.done:css.muted}/>}<div><strong>{t.title}</strong><small className={t.overdue_days?css.overdueDate:undefined}>{date(t.due_date)} · {personName(people,t.assignee_user_id,t.assignee_name)}</small><div className={css.inlineBadges}><Badge value={t.status}/>{t.overdue_days?<OverdueDays days={t.overdue_days}/>:<Badge value={t.priority}/>}</div>{t.completed_at&&!done&&<small className={css.warning}>{a('legacyCompletion')}</small>}</div></div>{canEdit&&!matterClosed(matter)&&<div className={css.rowActions}><button disabled={busy} className={css.textButton} onClick={()=>onEdit({action:'task_save',title:a('edit'),values:{id:t.id,title:t.title,status:t.status,priority:t.priority,assignee_user_id:t.assignee_user_id,assignee_name:t.assignee_name,stage_id:t.stage_id,due_date:t.due_date,completed_at:t.completed_at,note:t.note,issue_id:t.advisory_issue_id}})}>{a('edit')}</button>{canDelete&&<button className={css.textButton} onClick={()=>onEdit({action:'task_delete',title:a('deleteTask'),values:{id:t.id}})}>{a('deleteTask')}</button>}{canSetNext&&!done&&!t.completed_at&&<button disabled={busy} className={css.textButton} onClick={()=>onAction('next_action',{task_id:t.id})}>{a('setNext')} <ArrowRight size={12}/></button>}</div>}{t.advisory_issue_id&&<Link className={css.sourceLink} href={`/advisory/${matter.id}/issues/${t.advisory_issue_id}`}>{a('details')} →</Link>}</li>;}
 if(section==='deliverables'){const d=row as Deliverable;return <li key={d.id}><div className={css.rowMain}><FileCheck2 size={18}/><div><strong>{d.title}</strong><small>{date(d.due_date)} · {personName(people,d.owner_id)}</small><Badge value={d.status}/>{d.version_label&&<small>{a('version')}: {d.version_label}</small>}</div></div><div className={css.rowActions}>{d.drive_url&&<a href={d.drive_url} target="_blank" rel="noopener noreferrer">{a('details')} ↗</a>}{canEdit&&!matterClosed(matter)&&<button className={css.textButton} onClick={()=>onEdit({action:'deliverable',title:a('edit'),values:{...d}})}>{a('edit')}</button>}</div></li>;}
 const e=row as Activity;return <li key={e.id}><div className={css.rowMain}><Clock3 size={18}/><div><strong>{e.kind==='team'&&String(e.detail.input?.remove)==='true'?a('activityTeamRemoved'):label(e.kind)}</strong>{e.detail.completed_stage_key&&<p>{a('activityStageTransition',{from:label(e.detail.completed_stage_key,matter.template_key),to:e.detail.ready_for_closing?a('closeMatter'):label(e.detail.next_stage_key,matter.template_key)})}</p>}{['team','team_edit'].includes(e.kind)&&<p>{personName(people,e.detail.input?.user_id||null)} · {e.detail.input?.previous_role&&<>{label(e.detail.input.previous_role)} → </>}{label(e.detail.input?.role)}</p>}<p>{e.detail.title||e.detail.input?.text||e.detail.input?.summary||e.detail.input?.reason||e.detail.input?.title||''}</p>{e.detail.input?.stage_key&&<p>{label(e.detail.input.stage_key,e.detail.input.template||matter.template_key)}</p>}{e.detail.input?.state&&<p>{label(e.detail.input.state)}</p>}<small>{personName(people,e.actor_id)} · {date(e.occurred_at,true)}</small></div></div></li>;})}</ul>}
 {!overview&&total>5&&<button className={css.textButton} onClick={()=>{setExpanded(e=>!e);setOffset(0);}}>{expanded?a('overview'):a('count',{n:total})} →</button>}{!loading&&!error&&(overview?focused:expanded)&&<Pagination offset={requestOffset} total={total} onChange={setOffset}/>}</section>;
}
