"use client";
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import DetailModal from '../../components/DetailModal';
import {supabase} from '../../../lib/supabase';
import {errorKey,type Matter,type Stage} from '../../../lib/advisory-control';
import {matterClosed,timeMinutes,timeTypes} from '../../../lib/advisory-workflow';
import {useAdvisoryLabels} from './shared';
import MatterTimeSummary from './MatterTimeSummary';
import type {ControlRead} from '../../../lib/advisory-control';
import css from './control.module.css';
type TimeRow={id:string;work_date:string;staff_name:string|null;minutes:number;work_type:string|null;work_other:string|null;note:string|null;stage_id:string|null;billable:boolean};
type Actor={id:string;email:string;name:string};
export default function MatterTime({matter,stages,time,canAdd,focused,onFocus,onSaved}:{matter:Matter;stages:Stage[];time:ControlRead['time'];canAdd:boolean;focused:boolean;onFocus:()=>void;onSaved:()=>Promise<void>}){const {a,label,date}=useAdvisoryLabels();const [rows,setRows]=useState<TimeRow[]>([]),[error,setError]=useState(false),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[limit,setLimit]=useState(30);const sequence=useRef(0);
 const load=useCallback(async()=>{const n=++sequence.current;setLoading(true);setError(false);try{const r=await supabase.from('advisory_time_logs').select('id,work_date,staff_name,minutes,work_type,work_other,note,stage_id,billable').eq('advisory_matter_id',matter.id).is('deleted_at',null).order('work_date',{ascending:false}).order('id').limit(limit);if(n===sequence.current){setRows(r.data||[]);setError(!!r.error);}}catch{if(n===sequence.current)setError(true);}finally{if(n===sequence.current)setLoading(false);}},[matter.id,limit]);
 const cancel=useCallback(()=>{sequence.current++;},[]);
 useEffect(()=>{if(focused)void load();return cancel;},[load,focused,cancel]);
 return <div className={css.timeWorkspace}><MatterTimeSummary matterId={matter.id} time={time} onDetails={onFocus} onAdd={canAdd&&!matterClosed(matter)?()=>setOpen(true):undefined}/>
 {focused&&<section className={css.panel}><h2>{a('timeLogs')}</h2>{loading?<p role="status">{a('loading')}</p>:error?<p role="alert" className={css.error}>{a('loadError')} <button onClick={load}>{a('refresh')}</button></p>:!rows.length?<p className={css.empty}>{a('noTime')}</p>:<ul className={css.rows}>{rows.map(t=><li key={t.id}><div className={css.rowMain}><div><strong>{t.note||a('noDescription')}</strong><small>{date(t.work_date)} · {t.staff_name||a('unassigned')}</small><small>{t.stage_id?label(stages.find(s=>s.id===t.stage_id)?.stage_key)||a('notAvailable'):a('legacyNoStage')}</small><small>{t.work_type==='อื่นๆ'&&t.work_other?t.work_other:label(timeTypes.find(([v])=>v===t.work_type)?.[1]||t.work_type)} · {a(t.billable?'core':'support')}</small></div></div><strong>{a('hoursMinutes',{hours:Math.floor(t.minutes/60),minutes:t.minutes%60})}</strong></li>)}</ul>}{!loading&&rows.length===limit&&<button onClick={()=>setLimit(n=>n+30)}>{a('loadMore')}</button>}</section>}
 {open&&<TimeDialog matter={matter} stages={stages} onClose={()=>setOpen(false)} onSaved={async()=>{await Promise.all([load(),onSaved()]);}}/>}</div>;
}
function TimeDialog({matter,stages,onClose,onSaved}:{matter:Matter;stages:Stage[];onClose:()=>void;onSaved:()=>Promise<void>}){const {a,label}=useAdvisoryLabels();const [actor,setActor]=useState<Actor|null>(null),[actorError,setActorError]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);const id=useRef(crypto.randomUUID()),lock=useRef(false);const current=stages.find(s=>s.stage_key===matter.stage_key);const [stage,setStage]=useState(current?.id||''),[workType,setWorkType]=useState<string>(timeTypes[0][0]);
 useEffect(()=>{let live=true;void(async()=>{try{const u=await supabase.auth.getUser();if(!u.data.user)throw Error('FORBIDDEN');const p=await supabase.from('user_profiles').select('full_name,staff_name').eq('id',u.data.user.id).single();if(p.error)throw p.error;if(live)setActor({id:u.data.user.id,email:u.data.user.email||'',name:p.data.staff_name||p.data.full_name});}catch{if(live)setActorError(true);}})();return()=>{live=false;};},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current||!actor)return;const f=Object.fromEntries(new FormData(e.currentTarget));const minutes=timeMinutes(String(f.hours),String(f.minutes));if(!minutes){setError(a('durationInvalid'));return;}const payload={id:id.current,advisory_matter_id:matter.id,client_id:matter.client_id,advisory_issue_id:null,stage_id:stage||null,work_date:String(f.work_date),minutes,work_type:workType,work_other:workType==='อื่นๆ'?String(f.work_other).trim():'',billable:f.effort==='core',note:String(f.note).trim(),staff_name:actor.name,created_by_user_id:actor.id,created_by_email:actor.email,created_by_name:actor.name};lock.current=true;setBusy(true);setError('');try{const r=await supabase.from('advisory_time_logs').insert(payload);if(r.error){if(r.error.code!=='23505')throw r.error;const existing=await supabase.from('advisory_time_logs').select('*').eq('id',id.current).single();if(existing.error||!existing.data||Object.entries(payload).some(([k,v])=>existing.data[k]!==v))throw Error('ADVISORY_CHANGED');}await onSaved();onClose();}catch(e){setError(a(errorKey(String((e as {message?:string})?.message||e))));}finally{lock.current=false;setBusy(false);}}
 return <DetailModal open size="edit" title={a('addTime')} subtitle={matter.matter_no} onClose={()=>{if(!busy)onClose();}}><form className={css.form} onSubmit={save}>{actorError&&<p role="alert" className={css.error}>{a('loadError')}</p>}{error&&<p role="alert" className={css.error}>{error}</p>}<p className={css.notice}>{a('recorder')}: <strong>{actor?.name||a('loading')}</strong> · {a('ownTimeHint')}</p><label>{a('workDate')}<input name="work_date" type="date" required defaultValue={new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}/></label><div className={css.durationFields}><label>{a('hours')}<input name="hours" type="number" min="0" step="1" defaultValue="0" required/></label><label>{a('minuteField')}<input name="minutes" type="number" min="0" max="59" step="1" defaultValue="30" required/></label></div><label>{a('type')}<select name="work_type" value={workType} onChange={e=>setWorkType(e.target.value)}>{timeTypes.map(([v,k])=><option key={v} value={v}>{label(k)}</option>)}</select></label>{workType==='อื่นๆ'&&<label>{a('otherTimeType')}<input name="work_other" required maxLength={500}/></label>}<label>{a('effortType')}<select name="effort"><option value="core">{a('core')}</option><option value="support">{a('support')}</option></select></label><label className={css.wide}>{a('workDescription')}<textarea name="note" required rows={3} maxLength={4000}/></label><p className={css.notice}>{a('timeStage')}: <strong>{stage?label(stages.find(s=>s.id===stage)?.stage_key):a('noStage')}</strong></p><details className={css.wide}><summary>{a('changeTimeStage')}</summary><label>{a('timeStage')}<select value={stage} onChange={e=>setStage(e.target.value)}><option value="">{a('noStage')}</option>{stages.map(s=><option key={s.id} value={s.id}>{label(s.stage_key)}</option>)}</select></label></details><div className={css.formActions}><button type="button" onClick={onClose} disabled={busy}>{a('cancel')}</button><button type="submit" disabled={busy||!actor} className={css.primary}>{a(busy?'saving':'save')}</button></div></form></DetailModal>;
}
