"use client";
import {useEffect,useState,type FormEvent} from 'react';
import DetailModal from '../../components/DetailModal';
import {SearchableCombobox} from '../../finance/expenses/searchable-combobox';
import {supabase} from '../../../lib/supabase';
import {personName,type Matter,type Person,type Task} from '../../../lib/advisory-control';
import {useAdvisoryLabels} from './shared';
import {useMatterWrite} from './workflow-shared';
import css from './control.module.css';
export default function MatterNextAction({matter,people,onClose,onSaved}:{matter:Matter;people:Person[];onClose:()=>void;onSaved:()=>Promise<void>}){
 const {a,date}=useAdvisoryLabels(),{write,busy,error}=useMatterWrite(matter);const [mode,setMode]=useState(matter.next_action&&!matter.next_task_id?'standalone':'task'),[taskId,setTaskId]=useState(matter.next_task_id||''),[owner,setOwner]=useState(matter.next_task_id?'':matter.next_owner_id||''),[tasks,setTasks]=useState<Pick<Task,'id'|'title'|'status'|'assignee_user_id'|'assignee_name'|'due_date'>[]>([]),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false);
 useEffect(()=>{let live=true;const timer=setTimeout(()=>{setLoading(true);setLoadError(false);void Promise.resolve(supabase.from('advisory_issue_tasks').select('id,title,status,assignee_user_id,assignee_name,due_date').eq('advisory_matter_id',matter.id).is('deleted_at',null).is('completed_at',null).not('status','in','(completed,cancelled)').ilike('title','%'+search+'%').order('title').order('id').limit(100)).then(r=>{if(live){setTasks(r.data||[]);setLoadError(!!r.error);setLoading(false);}}).catch(()=>{if(live){setLoadError(true);setLoading(false);}});},150);return()=>{live=false;clearTimeout(timer);};},[matter.id,search]);
 const selected=tasks.find(t=>t.id===taskId);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(mode==='task'&&(!selected||loading||loadError))return;const values=Object.fromEntries(new FormData(e.currentTarget));const result=await write('next_action',mode==='task'?{task_id:taskId}:{...values,owner_id:owner});if(result){await onSaved();onClose();}}
 return <DetailModal open size="edit" title={a('setNextAction')} onClose={()=>{if(!busy)onClose();}}><form className={css.form} onSubmit={save}>{error&&<p role="alert" className={css.error}>{error}</p>}<label>{a('nextSource')}<select value={mode} onChange={e=>setMode(e.target.value)}><option value="task">{a('fromTask')}</option><option value="standalone">{a('standalone')}</option></select></label>
 {mode==='task'?<><label className={css.wide}>{a('findTask')}<input value={search} onChange={e=>setSearch(e.target.value)}/></label>{loading?<p role="status">{a('loading')}</p>:loadError?<p role="alert" className={css.error}>{a('loadError')}</p>:<label className={css.wide}>{a('tasks')}<select value={taskId} onChange={e=>setTaskId(e.target.value)} required><option value="">{a('chooseTask')}</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select>{!tasks.length&&<small>{a('noAvailableTask')}</small>}</label>}{selected&&<div className={css.notice}><strong>{selected.title}</strong><p>{a('actor')}: {personName(people,selected.assignee_user_id,selected.assignee_name)}</p><p>{a('due')}: {date(selected.due_date)}</p><small>{a('taskDerivedHint')}</small></div>}</>:<><label className={css.wide}>{a('next')}<input name="title" required maxLength={500} defaultValue={matter.next_task_id?'':matter.next_action||''}/></label><div><label htmlFor="next-owner">{a('owner')}</label><SearchableCombobox id="next-owner" disabled={busy} label={a('owner')} placeholder={a('searchPerson')} value={owner} onChange={setOwner} options={[{value:'',label:{th:a('unassigned'),en:a('unassigned')}},...people.map(p=>({value:p.id,label:{th:p.staff_name||p.full_name,en:p.staff_name||p.full_name},keywords:p.full_name}))]}/></div><label>{a('due')}<input name="due_date" type="date" defaultValue={matter.next_task_id?'':matter.next_due||''}/></label></>}
 <div className={css.formActions}><button type="button" disabled={busy} onClick={onClose}>{a('cancel')}</button><button type="submit" className={css.primary} disabled={busy||mode==='task'&&(!selected||loading||loadError)}>{a(busy?'saving':'save')}</button></div></form></DetailModal>;
}
