"use client";
import {useRef,useState} from 'react';
import {useParams} from 'next/navigation';
import Link from 'next/link';
import {ArrowLeft,Building2,CalendarDays,Users,Timer,Plus} from 'lucide-react';
import AppTopNav from '../../components/AppTopNav';
import AuthGuard from '../../components/AuthGuard';
import {supabase} from '../../../lib/supabase';
import {errorKey} from '../../../lib/advisory-control';
import {Badge,useAdvisoryLabels,useControl,usePeople} from './shared';
import MatterEditor,{type EditRequest} from './MatterEditor';
import MatterSections from './MatterSections';
import Journey from './Journey';
import css from './control.module.css';
export default function MatterDetail(){const params=useParams(),id=String(params.id);const {data,loading,error,reload}=useControl(id),people=usePeople(),{a,label,date}=useAdvisoryLabels();const [edit,setEdit]=useState<EditRequest|null>(null),[busy,setBusy]=useState(false),[actionError,setActionError]=useState('');const pending=useRef<{body:string;id:string}|null>(null);
 const m=data?.items[0],permissions=data?.permissions;
 async function action(name:string,payload:Record<string,string>){if(!m||busy)return;setBusy(true);setActionError('');const body=JSON.stringify({name,payload,version:m.version});if(pending.current?.body!==body)pending.current={body,id:crypto.randomUUID()};try{const r=await supabase.rpc('advisory_control_write',{p_matter_id:id,p_action:name,p_payload:payload,p_request_id:pending.current.id,p_expected_version:m.version});if(r.error)throw r.error;pending.current=null;await reload();}catch(e){setActionError(a(errorKey(String((e as {message?:string})?.message||e))));}finally{setBusy(false);}}
 return <AuthGuard><main className={css.page}><div className={css.shellHeader}><AppTopNav title={a('title')} activePage="advisory"/></div><Link className={css.back} href="/advisory"><ArrowLeft size={16}/>{a('back')}</Link>{(error||actionError)&&<p role="alert" className={css.error}>{actionError||a('loadError')} <button onClick={reload}>{a('refresh')}</button></p>}
 {!m?<p className={css.empty}>{a(loading?'loading':'empty')}</p>:<>
 <header className={css.pageHeader}><div><div className={css.headingLine}><h1>{m.title}</h1><Badge value={m.status}/></div><p><strong>{m.matter_no}</strong> · <Link href={'/clients/'+m.client_id}>{m.client_name}</Link></p></div><div className={css.actions}><button onClick={reload}>{a('refresh')}</button>{permissions?.manage&&<button className={css.primary} onClick={()=>setEdit({action:m.closed_at?'reopen':'task_save',title:a(m.closed_at?'reopen':'addTask')})}><Plus size={16}/>{a(m.closed_at?'reopen':'addTask')}</button>}</div></header>
 <div className={css.controlSummary}><div><Building2/><span>{a('type')}<strong>{label(m.matter_type)}</strong></span></div><div><Users/><span>{a('lead')}<strong>{m.lead_name||a('unassigned')}</strong></span></div><div><CalendarDays/><span>{a('actor')}<strong>{m.next_owner_name||a('unassigned')}</strong></span></div><div><Timer/><span>{a('age')}<strong>{a('days',{n:m.age_days})}</strong><small>{date(m.start_date||m.created_at)}</small></span></div><div><span>{a('state')}<Badge value={m.work_state||m.status}/>{permissions?.manage&&!m.closed_at&&<button className={css.textButton} onClick={()=>setEdit({action:'work_state',title:a('state'),values:{state:m.work_state||'working'}})}>{a('edit')}</button>}</span></div></div>
 <nav className={css.tabs} aria-label={a('overview')}>{['journey','tasks','time','activity','deliverables','team'].map(k=><a key={k} href={'#'+k}>{a(k)}</a>)}<Link href={`/advisory/${id}/records`}>{a('records')}</Link></nav>
 <details className={css.stateHistory}><summary>{a('stateHistory')}</summary><ul className={css.rows}>{data?.state_history?.map(h=><li key={h.started_at}><Badge value={h.work_state}/><span>{date(h.started_at,true)} → {h.ended_at?date(h.ended_at,true):a('current')}</span>{h.reason&&<p>{h.reason}</p>}</li>)}</ul></details>
 <div id="journey"><Journey matter={m} stages={data?.stages||[]} canEdit={!!permissions?.manage} onEdit={setEdit}/></div>
 <div className={css.detailGrid}>
 <div className={css.primaryColumn}><section className={css.nextAction}><div className={css.sectionHeading}><h2>{a('next')}</h2>{permissions?.manage&&!m.closed_at&&<button className={css.textButton} onClick={()=>setEdit({action:'next_action',title:a('standalone'),values:{title:m.next_task_id?'':m.next_action,owner_id:m.next_task_id?'':m.next_owner_id,due_date:m.next_task_id?'':m.next_due}})}>{a('edit')}</button>}</div><strong>{m.next_action||a('noNext')}</strong><p>{m.next_owner_name||'—'} · {date(m.next_due)}</p></section>
 <div id="tasks"><MatterSections matter={m} section="tasks" canSetNext={!!permissions?.manage} canDelete={!!permissions?.delete} people={people} canEdit={!!permissions?.task} onEdit={setEdit} onAction={action} busy={busy}/></div>
 <div id="activity"><MatterSections matter={m} section="activity" people={people} canEdit={!!permissions?.manage} onEdit={setEdit} onAction={action} busy={busy}/></div></div>
 <div className={css.secondaryColumn}><section className={css.panel} id="time"><div className={css.sectionHeading}><h2>{a('time')}</h2><Link href={`/advisory/${id}/records#time`}>{a('details')} →</Link></div><div className={css.timeSummary}><div className={css.timeRing} style={{'--core-angle':data?.time?.minutes?360*data.time.core/data.time.minutes+'deg':'0deg'} as React.CSSProperties}><span><strong>{a('minutes',{n:data?.time?.minutes||0})}</strong></span></div><div><p>{a('core')}<strong>{a('minutes',{n:data?.time?.core||0})}</strong></p><p>{a('support')}<strong>{a('minutes',{n:data?.time?.support||0})}</strong></p></div></div><small>{a('timeHint')}</small><p className={css.notice}>{a('unclassifiedCount',{n:data?.time?.unclassified||0})}</p></section>
 <div id="deliverables"><MatterSections matter={m} section="deliverables" people={people} canEdit={!!permissions?.manage} onEdit={setEdit} onAction={action} busy={busy}/></div>
 <section className={css.panel} id="team"><div className={css.sectionHeading}><h2>{a('team')}</h2>{permissions?.manage&&!m.closed_at&&<button className={css.textButton} onClick={()=>setEdit({action:'team',title:a('team'),values:{role:'lead'}})}>{a('edit')}</button>}</div><ul className={css.rows}>{data?.team?.map(t=><li key={t.user_id+t.team_role}><span><Badge value={t.team_role}/> {t.name}</span>{permissions?.manage&&!m.closed_at&&<button className={css.textButton} onClick={()=>setEdit({action:'team',title:a('team'),values:{user_id:t.user_id,role:t.team_role,name:t.name}})}>{a('edit')}</button>}</li>)}</ul>{!data?.team?.length&&<p>{a('legacyPerson',{name:m.responsible_lawyer||'—'})}</p>}</section>
 <section className={css.panel} id="otherMatters"><h2>{a('otherMatters')}</h2><ul className={css.rows}>{data?.other_matters?.map(o=><li key={o.id}><Link href={'/advisory/'+o.id}><strong>{o.matter_no}</strong><p>{o.title}</p></Link><Badge value={o.status}/></li>)}</ul>{!data?.other_matters?.length&&<p className={css.empty}>{a('empty')}</p>}</section>
 </div></div>
 <section className={css.panel}><div className={css.sectionHeading}><h2>{m.closed_at?a('outcome'):a('closeMatter')}</h2>{permissions?.manage&&<button onClick={()=>setEdit({action:m.closed_at?'reopen':'close',title:a(m.closed_at?'reopen':'closeMatter')})}>{a(m.closed_at?'reopen':'closeMatter')}</button>}</div>{m.closed_at&&<><p><Badge value={m.outcome}/> · {date(m.closed_at,true)}</p><p>{m.outcome_summary}</p><p>{m.follow_up}</p><p>{m.case_reference}</p></>}</section>
 <footer className={css.secondaryLinks}><Link href={`/advisory/${id}/records`}>{a('records')} →</Link></footer>
 {edit&&<MatterEditor key={JSON.stringify(edit)} request={edit} matter={m} people={people} stages={data?.stages} onClose={()=>setEdit(null)} onSaved={reload}/>}
 </>}</main></AuthGuard>;
}
