"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Check,Plus,ArrowRight,FileCheck2,Clock3} from 'lucide-react';
import {supabase} from '../../../lib/supabase';
import {personName,type Activity,type Deliverable,type Matter,type Person,type Task} from '../../../lib/advisory-control';
import {Badge,Pagination,useAdvisoryLabels} from './shared';
import type {EditRequest} from './MatterEditor';
import css from './control.module.css';
type SectionProps={matter:Matter;section:'tasks'|'activity'|'deliverables';people:Person[];canEdit:boolean;onEdit:(e:EditRequest)=>void;onAction:(action:string,payload:Record<string,string>)=>Promise<void>;busy:boolean;canSetNext?:boolean;canDelete?:boolean;issueId?:string};
export default function MatterSections({matter,section,people,canEdit,onEdit,onAction,busy,issueId,canSetNext=false,canDelete=false}:SectionProps){const {a,label,date}=useAdvisoryLabels();const [rows,setRows]=useState<(Task|Activity|Deliverable)[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[error,setError]=useState(false),[expanded,setExpanded]=useState(false),[deleted,setDeleted]=useState(false);
 useEffect(()=>{let live=true;void supabase.rpc('advisory_control_section',{p_matter_id:matter.id,p_section:deleted?'deleted_tasks':section,p_offset:offset,p_issue_id:issueId||null}).then(r=>{if(live){setError(!!r.error);setRows(r.data?.items||[]);setTotal(r.data?.total||0);}});return()=>{live=false;};},[matter.id,matter.version,section,offset,issueId,deleted]);
 const visible=expanded?rows:rows.slice(0,5);
 return <section className={css.panel}><div className={css.sectionHeading}><h2>{a(section)}</h2>{canEdit&&!matter.closed_at&&<button className={css.textButton} onClick={()=>onEdit({action:section==='tasks'?'task_save':section==='activity'?'note':'deliverable',title:a(section==='tasks'?'addTask':section==='activity'?'addNote':'addDeliverable'),values:issueId?{issue_id:issueId}:undefined})}><Plus size={15}/>{a(section==='tasks'?'addTask':section==='activity'?'addNote':'addDeliverable')}</button>}</div>
 {section==='tasks'&&canDelete&&<button className={css.textButton} onClick={()=>{setDeleted(v=>!v);setOffset(0);}}>{a(deleted?'tasks':'deletedTasks')}</button>}
 {error?<p role="alert" className={css.error}>{a('loadError')}</p>:!rows.length?<p className={css.empty}>{a('empty')}</p>:<ul className={css.rows}>{visible.map(row=>{if(section==='tasks'){const t=row as Task,done=['completed','cancelled'].includes(t.status);if(deleted)return <li key={t.id}><strong>{t.title}</strong>{canDelete&&!matter.closed_at&&<button disabled={busy} onClick={()=>onAction('task_restore',{id:t.id})}>{a('restoreTask')}</button>}</li>;return <li key={t.id}><div className={css.rowMain}>{canEdit&&!matter.closed_at&&!done?<button className={css.complete} disabled={busy} aria-label={a('complete')+': '+t.title} onClick={()=>onAction('task_complete',{id:t.id})}><Check size={16}/></button>:<Check size={16} className={done?css.done:css.muted}/>}<div><strong>{t.title}</strong><small>{date(t.due_date)} · {personName(people,t.assignee_user_id,t.assignee_name)}</small><div className={css.inlineBadges}><Badge value={t.status}/><Badge value={t.priority}/></div>{t.completed_at&&!done&&<small className={css.warning}>{a('legacyCompletion')}</small>}</div></div>{canEdit&&!matter.closed_at&&<div className={css.rowActions}><button disabled={busy} className={css.textButton} onClick={()=>onEdit({action:'task_save',title:a('edit'),values:{...t,issue_id:t.advisory_issue_id}})}>{a('edit')}</button>{canDelete&&<button className={css.textButton} onClick={()=>onEdit({action:'task_delete',title:a('deleteTask'),values:{id:t.id}})}>{a('deleteTask')}</button>}{canSetNext&&!done&&!t.completed_at&&<button disabled={busy} className={css.textButton} onClick={()=>onAction('next_action',{task_id:t.id})}>{a('setNext')} <ArrowRight size={12}/></button>}</div>}{t.advisory_issue_id&&<Link className={css.sourceLink} href={`/advisory/${matter.id}/issues/${t.advisory_issue_id}`}>{a('details')} →</Link>}</li>;}
 if(section==='deliverables'){const d=row as Deliverable;return <li key={d.id}><div className={css.rowMain}><FileCheck2 size={18}/><div><strong>{d.title}</strong><small>{date(d.due_date)} · {personName(people,d.owner_id)}</small><Badge value={d.status}/>{d.version_label&&<small>{a('version')}: {d.version_label}</small>}</div></div><div className={css.rowActions}>{d.drive_url&&<a href={d.drive_url} target="_blank" rel="noopener noreferrer">{a('details')} ↗</a>}{canEdit&&!matter.closed_at&&<button className={css.textButton} onClick={()=>onEdit({action:'deliverable',title:a('edit'),values:{...d}})}>{a('edit')}</button>}</div></li>;}
 const e=row as Activity;return <li key={e.id}><div className={css.rowMain}><Clock3 size={18}/><div><strong>{label(e.kind)}</strong><p>{e.detail.title||e.detail.input?.text||e.detail.input?.summary||e.detail.input?.reason||e.detail.input?.title||''}</p>{e.detail.input?.stage_key&&<p>{label(e.detail.input.stage_key)}</p>}{e.detail.input?.state&&<p>{label(e.detail.input.state)}</p>}<small>{personName(people,e.actor_id)} · {date(e.occurred_at,true)}</small></div></div></li>;})}</ul>}
 {total>5&&<button className={css.textButton} onClick={()=>{setExpanded(e=>!e);setOffset(0);}}>{expanded?a('overview'):a('count',{n:total})} →</button>}{expanded&&<Pagination offset={offset} total={total} onChange={setOffset}/>}</section>;
}
