'use client';
import {useCallback,useEffect,useRef,useState,useContext,createContext,type FormEvent,type ReactNode,type ComponentProps} from 'react';
import {ArrowLeft,CalendarDays,LockKeyhole,Plus,RefreshCw,Users,Wallet} from 'lucide-react';
import BaseModal,{type DetailModalProps} from '../../components/DetailModal';
import ui from '../../components/ui/vp-ui.module.css';
import {useI18n} from '../../../lib/i18n/provider';
import {PayeeModal} from '../payouts/payee-modal';
import type {Payee} from '../payouts/shared';
import {payrollRequest} from './client';
import {payrollText,payrollError,type PayrollLabel} from './labels';
import {effective,payrollLandingTab,netPay,selectedTotal,reviewInput,paymentItems,accountKey,type PayrollData,type Person,type Period,type Line} from './model';
import css from './payroll.module.css';
const Feedback=createContext('');
function DetailModal(props:DetailModalProps){const error=useContext(Feedback);return <BaseModal {...props}>{error&&<p className={css.error} role="alert">{error}</p>}{props.children}</BaseModal>;}
type Body={action:string;payload?:unknown;items?:unknown;acknowledged?:boolean};
type Change=(body:Body)=>Promise<boolean>;
type Text=(key:PayrollLabel)=>string;
function Field({label,children}:{label:string;children:ReactNode}){return <label className={css.field}><span>{label}</span>{children}</label>;}
function Empty({children}:{children:ReactNode}){return <div className={css.empty}>{children}</div>;}
// Keep existing HTML constraints, but present validation in the shared app language.
function PayrollForm({children,onSubmit,...props}:ComponentProps<'form'>){
 const {locale}=useI18n(),[invalid,setInvalid]=useState(false);
 return <form {...props} noValidate onSubmit={e=>{
  e.preventDefault();
  if(!e.currentTarget.checkValidity()){
   setInvalid(true);
   e.currentTarget.querySelector<HTMLElement>(':invalid')?.focus();
   return;
  }
  setInvalid(false);
  onSubmit?.(e);
 }}>{invalid&&<p className={css.error} role="alert">{payrollText(locale,'inputInvalid')}</p>}{children}</form>;
}
const monthName=(value:string,locale:string)=>new Intl.DateTimeFormat(locale==='th'?'th-TH':'en-GB',{month:'long',year:'numeric',timeZone:'Asia/Bangkok'}).format(new Date(value+'T12:00:00+07:00'));
export default function PayrollWorkspace(){
 const {locale}=useI18n(),t:Text=k=>payrollText(locale,k),money=(n:number)=>Number(n).toLocaleString(locale,{minimumFractionDigits:2,maximumFractionDigits:2});
 const [data,setData]=useState<PayrollData|null>(null),[tab,setTab]=useState<'people'|'periods'|'obligations'|null>(null),[periodId,setPeriodId]=useState('');
 const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState<unknown>(null),[notice,setNotice]=useState<PayrollLabel|null>(null),[stale,setStale]=useState(false);
 const [modal,setModal]=useState<'period'|'edit_period'|'engagement'|'rate'|'approve'|'prepare'|'confirm'|'cancel'|'reset'|null>(null),[person,setPerson]=useState<Person|null>(null),[line,setLine]=useState<Line|null>(null),[payee,setPayee]=useState<Payee|null|undefined>(undefined),[selected,setSelected]=useState<string[]>([]);
 const lock=useRef(false),sequence=useRef(0),pending=useRef<{body:string;id:string}|null>(null);
 const invalidate=useCallback(()=>{sequence.current++;},[]);
 const load=useCallback(async(id=periodId)=>{const seq=++sequence.current;setLoading(true);try{const result=await payrollRequest(undefined,id);if(seq!==sequence.current)return;if(!Array.isArray(result.lines)||!Array.isArray(result.people)||!Array.isArray(result.periods))throw Error('PAYROLL_FAILED');setData(result);setTab(current=>current??payrollLandingTab(result));setStale(false);}finally{if(seq===sequence.current)setLoading(false);}},[periodId]);
 useEffect(()=>{void load().catch(e=>{setStale(true);setError(e);});return invalidate;},[load,locale,invalidate]);
 async function mutate(body:Body){
  if(lock.current||stale)return false;lock.current=true;setBusy(true);setError('');setNotice(null);
  const encoded=JSON.stringify(body);if(pending.current?.body!==encoded)pending.current={body:encoded,id:crypto.randomUUID()};
  try{const result=await payrollRequest({...body,request_id:pending.current.id});pending.current=null;
   const id=body.action==='create_period'?result.id:periodId;
   try{await load(id);setNotice(body.action==='confirm'?'paymentDone':'saved');}catch{setStale(true);setNotice('savedReadFailed');}
   if(body.action==='create_period'){setPeriodId(id);setTab('periods');}return true;
  }catch(e){setError(e);return false;}finally{lock.current=false;setBusy(false);}
 }
 function close(){if(!lock.current){setModal(null);setLine(null);}}
 async function reload(){setError('');setNotice(null);try{await load();}catch(e){setStale(true);setError(e);}}
 const period=data?.periods.find(p=>p.id===periodId),lines=data?.lines||[],chosen=lines.filter(l=>selected.includes(l.id)),blocked=busy||loading||stale;
 const canPrepare=chosen.length>0&&chosen.every(l=>!l.payment),canConfirm=chosen.length>0&&chosen.every(l=>l.payment?.status==='draft');
 const errorMessage=error?payrollError(locale,error):'';
 return <Feedback.Provider value={errorMessage}><main className={`${ui.scope} ${css.root}`}>
  <header className={css.header}><div><span className={css.badge}><LockKeyhole size={13}/>&nbsp;{t('private')}</span><h1>{t('title')}</h1><p className={css.muted}>{t('intro')}</p></div><button className={ui.secondary} disabled={busy||loading} onClick={()=>void reload()}><RefreshCw size={16}/>{t('reload')}</button></header>
  <nav className={css.tabs} role="tablist" aria-label={t('title')}>{(['people','periods','obligations'] as const).map(k=><button key={k} role="tab" aria-selected={tab===k} onClick={()=>setTab(k)}>{t(k)}</button>)}</nav>
  {errorMessage&&<div className={css.error} role="alert">{errorMessage}</div>}{notice&&<div className={css.success} role="status">{t(notice)}</div>}
  {loading&&!data?<p role="status">{t('loading')}</p>:data&&<>
   {tab==='periods'&&!period&&<><div className={css.toolbar}><h2><CalendarDays size={19}/> {t('periods')}</h2><button className={ui.primary} disabled={blocked} onClick={()=>setModal('period')}><Plus size={16}/>{t('newPeriod')}</button></div>
    {data.periods.length?<div className={css.cards}>{data.periods.map(p=><article className={css.card} key={p.id}><div className={css.toolbar}><h3>{monthName(p.month,locale)}</h3><span className={css.badge}>{t(p.payment_status)}</span></div><p className={css.money}>{money(p.net_total)} <small>THB</small></p><p className={css.muted}>{p.line_count} {t('lineCount')} · {t('targetDate')} {p.target_payment_date}</p><button className={ui.secondary} disabled={busy} onClick={()=>{setSelected([]);setPeriodId(p.id);}}>{t('view')}</button></article>)}</div>:<Empty><Wallet/><h2>{t('empty')}</h2><p>{t('emptyPeople')}</p></Empty>}</>}
   {tab==='periods'&&period&&<>
    <div className={css.toolbar}><button className={ui.secondary} onClick={()=>{setPeriodId('');setSelected([]);}} disabled={busy}><ArrowLeft size={16}/>{t('periods')}</button><span className={css.badge}>{t(period.payment_status)}</span></div>
    <div className={css.summary}><div><h2>{monthName(period.month,locale)}</h2><p className={css.muted}>{t('targetDate')}: {period.target_payment_date}</p></div><div><p className={css.muted}>{t('total')}</p><strong>{money(period.net_total)} THB</strong></div></div>
    <p className={css.notice}>{t(period.status==='draft'?'approveHint':'frozen')}</p>
    {period.status==='draft'?<div className={css.actions}><button className={ui.secondary} disabled={blocked} onClick={()=>setModal('edit_period')}>{t('editPeriod')}</button><button className={ui.primary} disabled={blocked||lines.some(l=>!l.reviewed)} onClick={()=>setModal('approve')}>{t('approve')}</button><button className={ui.secondary} disabled={blocked} onClick={()=>setModal('reset')}>{t('resetDraft')}</button></div>:
     <div className={css.panel}><label className={css.check}><input type="checkbox" disabled={blocked} checked={lines.some(l=>l.net_amount>0&&l.payment?.status!=='confirmed')&&lines.filter(l=>l.net_amount>0&&l.payment?.status!=='confirmed').every(l=>selected.includes(l.id))} onChange={e=>setSelected(e.target.checked?lines.filter(l=>l.net_amount>0&&l.payment?.status!=='confirmed').map(l=>l.id):[])}/>{t('selectAll')}</label><strong>{t('selected').replace('{n}',String(chosen.length)).replace('{amount}',money(selectedTotal(chosen)))}</strong><div className={css.actions}><button className={ui.primary} disabled={blocked||!canPrepare} onClick={()=>setModal('prepare')}>{t('prepare')}</button><button className={ui.primary} disabled={blocked||!canConfirm} onClick={()=>setModal('confirm')}>{t('confirm')}</button><button className={ui.secondary} disabled={blocked||!canConfirm} onClick={()=>setModal('cancel')}>{t('cancelPrepared')}</button></div></div>}
    {(['employee','contractor'] as const).map(kind=><section className={css.section} key={kind}><h2>{kind==='employee'?<Users size={18}/>:<Wallet size={18}/>} {t(kind)} ({lines.filter(l=>l.kind===kind).length})</h2>{kind==='contractor'&&<p className={css.muted}>{t('contractorHint')}</p>}<div className={css.cards}>{lines.filter(l=>l.kind===kind).map(l=><article key={l.id} className={css.card} data-track={kind} data-selected={selected.includes(l.id)}>
     <div className={css.lineHeader}>{period.status==='approved'&&l.net_amount>0&&l.payment?.status!=='confirmed'?<label className={css.check}><input type="checkbox" aria-label={t('select')+': '+l.name} checked={selected.includes(l.id)} disabled={blocked} onChange={e=>setSelected(s=>e.target.checked?[...s,l.id]:s.filter(id=>id!==l.id))}/><strong>{l.name}</strong></label>:<h3>{l.name}</h3>}<span className={css.badge}>{t(l.payment?.status==='confirmed'?'paid':l.payment?'prepared':l.reviewed?'reviewed':'unreviewed')}</span></div>
     <p className={css.muted}>{l.service_from} – {l.service_to}</p><dl className={css.numbers}>{([['base_amount',kind==='employee'?'salary':'base'],['additions','additions'],['deductions','deductions'],...(kind==='employee'?[['employee_ss','employee_ss'],['employer_ss','employer_ss']]:[]),['wht_amount','wht']] as [keyof Line,PayrollLabel][]).map(([key,label])=><div key={key}><dt>{t(label)}</dt><dd>{money(Number(l[key]))}</dd></div>)}<div className={css.net}><dt>{t('net')}</dt><dd>{money(l.net_amount)}</dd></div></dl>
     {l.requires_base_review&&<p className={css.warning}>{t('baseReview')}</p>}{period.status==='draft'&&<button className={ui.secondary} disabled={blocked} onClick={()=>setLine(l)}>{t('review')}</button>}{l.note&&<p className={css.muted}>{l.note}</p>}</article>)}</div></section>)}
   </>}
   {tab==='people'&&<><div className={css.toolbar}><h2>{t('people')}</h2><div className={css.actions}><button className={ui.secondary} disabled={blocked} onClick={()=>setPayee(null)}>{t('addPayee')}</button><button className={ui.primary} disabled={blocked} onClick={()=>{setPerson(null);setModal('engagement');}}><Plus size={16}/>{t('addPerson')}</button></div></div><p className={css.notice}>{t('identityHint')}</p>
    {!data.people.some(p=>p.engagements.length)?<Empty>{t('emptyPeople')}</Empty>:<div className={css.cards}>{data.people.filter(p=>p.engagements.length).map(p=>{const engagement=effective(p.engagements,data.today),rate=effective(p.rates,data.today);return <article className={css.card} key={p.id} data-track={engagement?.kind}><div className={css.toolbar}><h3>{p.legal_name}</h3>{engagement&&<span className={css.badge}>{t(engagement.kind)}</span>}</div><p className={css.muted}>{t(!engagement?'notStarted':engagement.active?'active':'inactive')}</p><p className={css.money}>{rate?money(rate.monthly_amount):'—'} <small>THB</small></p><p className={css.muted}>{t('effective')}: {rate?.effective_from||'—'}</p><button className={ui.primary} disabled={blocked} onClick={()=>{setPerson(p);setModal('rate');}}>{t('changeRate')}</button><button className={ui.secondary} disabled={blocked} onClick={()=>{setPerson(p);setModal('engagement');}}>{t('changeEngagement')}</button><button className={ui.secondary} disabled={blocked} onClick={()=>setPayee(data.people_options.find(y=>y.id===p.id))}>{t('paymentIdentity')}</button><details><summary>{t('history')}</summary><div className={css.history}>{p.rates.map(r=><article key={r.id}><strong>{r.effective_from} · {money(r.monthly_amount)} THB</strong><p className={css.muted}>{r.reason}</p></article>)}</div></details><details><summary>{t('engagementHistory')}</summary><div className={css.history}>{p.engagements.map(e=><article key={e.id}><strong>{e.effective_from} · {t(e.kind)} · {t(e.active?'active':'inactive')}</strong><p className={css.muted}>{e.reason}</p></article>)}</div></details></article>;})}</div>}</>}
   {tab==='obligations'&&<><h2>{t('obligations')}</h2><p className={css.notice}>{t('obligationHint')}</p>{data.obligations.length?<div className={css.cards}>{data.obligations.map(o=><article className={css.card} key={o.id}><span className={css.badge}>{t('pending')}</span><h3>{t(o.kind)}</h3><p>{o.name}</p><p className={css.muted}>{monthName(o.month,locale)}</p><strong className={css.money}>{money(o.amount)} THB</strong></article>)}</div>:<Empty>{t('empty')}</Empty>}</>}
   {(modal==='rate'||modal==='engagement')&&<PersonForm mode={modal} data={data} person={person} t={t} busy={busy} onClose={close} onChange={mutate} onPayee={p=>setPayee(p)}/>}
   {(modal==='period'||modal==='edit_period')&&<PeriodForm period={modal==='edit_period'?period:undefined} today={data.today} t={t} busy={busy} onClose={close} onChange={mutate}/>}
   {line&&period&&<LineForm key={line.id} line={line} period={period} t={t} busy={busy} onClose={close} onChange={mutate} money={money}/>}
   {(modal==='approve'||modal==='reset')&&period&&<Approval mode={modal} period={period} lines={lines} t={t} busy={busy} onClose={close} onChange={mutate} money={money}/>}
   {(modal==='prepare'||modal==='confirm'||modal==='cancel')&&period&&<PaymentForm action={modal} data={data} period={period} lines={chosen} t={t} busy={busy} onClose={close} onChange={async b=>{const ok=await mutate(b);if(ok&&b.action!=='prepare')setSelected([]);return ok;}} money={money} locale={locale}/>}
   {payee!==undefined&&<PayeeModal payee={payee||undefined} onClose={()=>setPayee(undefined)} onSaved={()=>{setPayee(undefined);void reload();}}/>}
  </>}
 </main></Feedback.Provider>;
}
function PersonForm({mode,data,person,t,busy,onClose,onChange,onPayee}:{mode:'engagement'|'rate';data:PayrollData;person:Person|null;t:Text;busy:boolean;onClose:()=>void;onChange:Change;onPayee:(p:Payee)=>void}){
 const [id]=useState(()=>crypto.randomUUID()),[selected,setSelected]=useState(person?.id||''),option=data.people_options.find(p=>p.id===selected);
 const [kind,setKind]=useState(effective(person?.engagements||[],data.today)?.kind||'employee');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),payload={id,payee_id:selected,effective_from:String(f.get('effective_from')),reason:String(f.get('reason')), ...(mode==='rate'?{monthly_amount:Number(f.get('monthly_amount'))}:{kind,active:f.get('active')==='yes'})};if(await onChange({action:mode,payload}))onClose();}
 return <DetailModal open title={t(mode==='rate'?'changeRate':person?'changeEngagement':'addPerson')} size="edit" onClose={onClose} closeOnBackdrop={!busy}><PayrollForm className={css.form} onSubmit={submit}><p className={css.notice}>{t('effectiveHint')}</p><Field label={t('name')}><select value={selected} required disabled={busy||!!person} onChange={e=>{setSelected(e.target.value);if(!data.people_options.find(p=>p.id===e.target.value)?.profile_id)setKind('contractor');}}><option value="">{t('select')}</option>{data.people_options.filter(p=>p.entity_type==='natural_person').map(p=><option key={p.id} value={p.id}>{p.legal_name}</option>)}</select></Field>
  {option&&!option.version?<><p className={css.warning}>{t('destinationRequired')}</p><button type="button" className={ui.secondary} onClick={()=>onPayee(option)}>{t('paymentIdentity')}</button></>:null}
  {mode==='rate'?<Field label={t('rate')}><input name="monthly_amount" type="number" min="0.01" step="0.01" required disabled={busy}/></Field>:<><Field label={t('kind')}><select value={kind} onChange={e=>setKind(e.target.value as typeof kind)} disabled={busy}><option value="employee" disabled={!option?.profile_id}>{t('employee')}</option><option value="contractor">{t('contractor')}</option></select></Field><Field label={t('active')}><select name="active" defaultValue="yes" disabled={busy}><option value="yes">{t('active')}</option><option value="no">{t('inactive')}</option></select></Field>{kind==='contractor'&&<p className={css.notice}>{t('contractorHint')}</p>}</>}
  <Field label={t('effective')}><input name="effective_from" type="date" required disabled={busy} defaultValue={data.today}/></Field><Field label={t('reason')}><textarea name="reason" required maxLength={2000} disabled={busy}/></Field><button className={ui.primary} disabled={busy||!option?.version}>{t('save')}</button>
 </PayrollForm></DetailModal>;
}
function PeriodForm({period,today,t,busy,onClose,onChange}:{period?:Period;today:string;t:Text;busy:boolean;onClose:()=>void;onChange:Change}){
 const [id]=useState(()=>crypto.randomUUID());async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await onChange({action:period?'period':'create_period',payload:{...(period?{period_id:period.id,version:period.version}:{id,month:f.get('month')+'-01'}),target_payment_date:f.get('date'),note:f.get('note')}}))onClose();}
 return <DetailModal open title={t(period?'editPeriod':'newPeriod')} size="edit" onClose={onClose} closeOnBackdrop={!busy}><PayrollForm className={css.form} onSubmit={submit}><div className={css.formGrid}><Field label={t('month')}><input name="month" type="month" required defaultValue={(period?.month||today).slice(0,7)} disabled={busy||!!period}/></Field><Field label={t('targetDate')}><input name="date" type="date" required defaultValue={period?.target_payment_date||today} disabled={busy}/></Field></div><Field label={t('note')}><textarea name="note" maxLength={2000} defaultValue={period?.note||''} disabled={busy}/></Field><p className={css.notice}>{t('approveHint')}</p><button className={ui.primary} disabled={busy}>{t(period?'save':'newPeriod')}</button></PayrollForm></DetailModal>;
}
function LineForm({line,period,t,busy,onClose,onChange,money}:{line:Line;period:Period;t:Text;busy:boolean;onClose:()=>void;onChange:Change;money:(n:number)=>string}){
 const [net,setNet]=useState(line.net_amount),[localError,setLocalError]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();try{const payload=reviewInput(period,line,new FormData(e.currentTarget));if(netPay(payload)<0)throw Error('PAYROLL_INPUT_INVALID');if(await onChange({action:'line',payload}))onClose();}catch{setLocalError(true);}}
 return <DetailModal open title={t('review')+' · '+line.name} size="edit" onClose={onClose} closeOnBackdrop={!busy}><PayrollForm className={css.form} onSubmit={submit} onChange={e=>{try{setNet(netPay(reviewInput(period,line,new FormData(e.currentTarget))));}catch{/* incomplete input */}}}><p className={css.notice}>{t('manualHint')}</p>{localError&&<p role="alert" className={css.error}>{t('inputInvalid')}</p>}{line.requires_base_review&&<p className={css.warning}>{t('baseReview')}</p>}<div className={css.formGrid}>{(['base_amount','additions','deductions',...(line.kind==='employee'?['employee_ss','employer_ss']:[]),'wht_amount'] as const).map(key=><Field key={key} label={t(key==='base_amount'?(line.kind==='employee'?'salary':'base'):key==='wht_amount'?'wht':key as PayrollLabel)}><input name={key} type="number" min="0" step="0.01" required defaultValue={Number(line[key as keyof Line])} disabled={busy}/></Field>)}</div>
  <Field label={t('whtTreatment')}><select name="wht_treatment" defaultValue={line.wht_treatment} disabled={busy}><option value="none">{t('none')}</option><option value="withhold">{t('withhold')}</option></select></Field><p className={css.muted}>{t(line.kind==='employee'?'employerHint':'contractorHint')}</p><Field label={t('baseReason')}><textarea name="adjustment_reason" defaultValue={line.adjustment_reason} maxLength={2000} required={line.requires_base_review} disabled={busy}/></Field><Field label={t('note')}><textarea name="note" defaultValue={line.note} required maxLength={2000} disabled={busy}/></Field><div className={css.summary}><span>{t('net')}</span><strong>{money(net)} THB</strong></div><button className={ui.primary} disabled={busy||net<0}>{t('save')}</button></PayrollForm></DetailModal>;
}
function Approval({mode,period,lines,t,busy,onClose,onChange,money}:{mode:'approve'|'reset';period:Period;lines:Line[];t:Text;busy:boolean;onClose:()=>void;onChange:Change;money:(n:number)=>string}){
 const [ack,setAck]=useState(false);return <DetailModal open title={t(mode==='approve'?'approve':'resetDraft')} size="confirm" onClose={onClose} closeOnBackdrop={!busy}><div className={css.form}><p className={css.notice}>{t(mode==='approve'?'approveHint':'resetHint')}</p>{mode==='approve'&&<><strong>{lines.length} {t('lineCount')} · {money(selectedTotal(lines))} THB</strong>{(['employee','contractor'] as const).map(kind=><p key={kind}>{t(kind)}: {money(selectedTotal(lines.filter(l=>l.kind===kind)))} THB</p>)}</>}<label className={css.check}><input type="checkbox" checked={ack} disabled={busy} onChange={e=>setAck(e.target.checked)}/>{t(mode==='approve'?'approveAck':'resetHint')}</label><button className={ui.primary} disabled={busy||!ack} onClick={async()=>{if(await onChange({action:mode==='approve'?'approve':'reload_period',payload:{period_id:period.id,version:period.version,acknowledged:ack}}))onClose();}}>{t(mode==='approve'?'approve':'resetDraft')}</button></div></DetailModal>;
}
function PaymentForm({action,data,period,lines,t,busy,onClose,onChange,money,locale}:{action:'prepare'|'confirm'|'cancel';data:PayrollData;period:Period;lines:Line[];t:Text;busy:boolean;onClose:()=>void;onChange:Change;money:(n:number)=>string;locale:string}){
 const [choices,setChoices]=useState(()=>Object.fromEntries(lines.map(l=>[l.id,{id:crypto.randomUUID(),account:'',date:period.target_payment_date}]))),[ack,setAck]=useState(false),[error,setError]=useState<unknown>(null);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();try{const items=paymentItems(lines,data.people,data.accounts,choices,action);if(await onChange({action,items,acknowledged:ack}))onClose();}catch(e){setError(e);}}
 return <DetailModal open title={t(action==='prepare'?'prepare':action==='cancel'?'cancelPrepared':'confirm')} size="workflow" onClose={onClose} closeOnBackdrop={!busy}><PayrollForm className={css.form} onSubmit={submit}><p className={css.notice}>{t('paymentHint')}</p>{!!error&&<p className={css.error} role="alert">{payrollError(locale,error)}</p>}<strong>{t('selected').replace('{n}',String(lines.length)).replace('{amount}',money(selectedTotal(lines)))}</strong><div className={css.paymentRows}>{lines.map(l=>{const account=data.accounts.find(a=>a.bank_account_id===l.payment?.bank_account_id&&a.cash_location_id===l.payment?.cash_location_id);return <article className={css.paymentRow} key={l.id}><div className={css.toolbar}><strong>{l.name}</strong><strong>{money(l.net_amount)} THB</strong></div><p className={css.muted}>{t(l.kind)} · {monthName(period.month,locale)}</p>{action==='prepare'?<div className={css.formGrid}><Field label={t('account')}><select value={choices[l.id].account} required disabled={busy} onChange={e=>setChoices(c=>({...c,[l.id]:{...c[l.id],account:e.target.value}}))}><option value="">{t('chooseAccount')}</option>{data.accounts.map(a=><option key={accountKey(a)} value={accountKey(a)}>{locale==='en'?a.name_en:a.name_th}</option>)}</select></Field><Field label={t('paymentDate')}><input type="date" value={choices[l.id].date} required disabled={busy} onChange={e=>setChoices(c=>({...c,[l.id]:{...c[l.id],date:e.target.value}}))}/></Field></div>:<p className={css.muted}>{t('account')}: {(locale==='en'?account?.name_en:account?.name_th)||'—'} · {l.payment?.paid_on}</p>}</article>;})}</div>{action!=='prepare'&&<label className={css.check}><input type="checkbox" checked={ack} disabled={busy} onChange={e=>setAck(e.target.checked)}/>{t(action==='cancel'?'cancelAck':'paymentAck')}</label>}<button className={ui.primary} disabled={busy||(action!=='prepare'&&!ack)}>{t(action==='prepare'?'prepare':action==='cancel'?'cancelPrepared':'confirm')}</button></PayrollForm></DetailModal>;
}
