-- Extend the existing Draft -> Sent freeze without changing Accepted/Cancelled behavior.
create or replace function public.freeze_finance_quotation_commercial_terms_v2()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_client jsonb; v_items jsonb; v_payment jsonb; v_snapshot jsonb;
begin
  if not (old.status='draft' and new.status='sent') then return new; end if;
  select jsonb_build_object('id',c.id,'name',c.name,'client_type',c.client_type,'client_display_name',case when c.client_type='individual' then 'คุณ'||regexp_replace(c.name,'^(นาย|นางสาว|นาง|คุณ)[[:space:]]*','') else c.name end,'tax_id',c.tax_id,'address',c.address,'phone',c.phone,'email',c.email) into v_client from public.clients c where c.id=new.client_id;
  select coalesce(jsonb_agg(jsonb_build_object('quotation_item_id',i.id,'description',i.description,'quantity',i.quantity,'unit_price',i.unit_price,'price_tax_mode',i.price_tax_mode,'vat_applicable',i.vat_applicable,'vat_rate',i.vat_rate,'amount_before_tax',i.amount_before_tax,'vat_amount',i.vat_amount,'line_total',i.line_total,'sort_order',i.sort_order) order by i.sort_order,i.id),'[]'::jsonb) into v_items from public.finance_quotation_items i where i.quotation_id=new.id;
  select jsonb_build_object('version',2,'payment_method_type',pt.payment_method_type,'allocation_mode',pt.allocation_mode,'currency',pt.currency,'client_summary',pt.client_summary,'amount_before_tax',pt.amount_before_tax,'vat_amount',pt.vat_amount,'total_amount',pt.total_amount,'installments',coalesce(jsonb_agg(jsonb_build_object('installment_no',pi.installment_no,'title',pi.title,'calculation_type',pi.calculation_type,'percentage',pi.percentage,'trigger_type',pi.trigger_type,'trigger_description',pi.trigger_description,'due_date',pi.due_date,'payment_due_days',pi.payment_due_days,'client_note',pi.client_note,'amount_before_tax',pi.amount_before_tax,'vat_amount',pi.vat_amount,'total_amount',pi.total_amount,'items',coalesce((select jsonb_agg(jsonb_build_object('quotation_item_id',ai.quotation_item_id,'description_snapshot',qi.description,'price_tax_mode',qi.price_tax_mode,'vat_applicable',qi.vat_applicable,'vat_rate',qi.vat_rate,'allocation_percentage',ai.allocation_percentage,'allocated_amount_before_tax',ai.allocated_amount_before_tax,'allocated_vat_amount',ai.allocated_vat_amount,'allocated_total',ai.allocated_total) order by ai.sort_order,ai.id) from public.finance_quotation_payment_installment_items ai join public.finance_quotation_items qi on qi.id=ai.quotation_item_id where ai.payment_installment_id=pi.id),'[]'::jsonb)) order by pi.installment_no)) into v_payment from public.finance_quotation_payment_terms pt join public.finance_quotation_payment_installments pi on pi.payment_terms_id=pt.id where pt.quotation_id=new.id group by pt.id;
  v_snapshot:=coalesce(new.document_data_snapshot_json,'{}'::jsonb) || jsonb_build_object('version',2,'client',coalesce(v_client,'{}'::jsonb),'items',v_items,'payment_terms',coalesce(v_payment,'{}'::jsonb));
  update public.finance_quotations set document_data_snapshot_json=v_snapshot where id=new.id;
  return new;
end; $$;
drop trigger if exists finance_quotation_freeze_commercial_terms_v2 on public.finance_quotations;
create trigger finance_quotation_freeze_commercial_terms_v2 after update of status on public.finance_quotations for each row execute function public.freeze_finance_quotation_commercial_terms_v2();
