'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import AppTopNav from '../../components/AppTopNav';
import {useAdvisoryLabels} from '../../advisory/control/shared';
import {journeyFamilies,errorKey} from '../../../lib/advisory-control';
import {journeyName,type JourneyVariant,type JourneyDefinition,type JourneyStep} from '../../../lib/advisory-flexible-journey';
import JourneyRoutingEditor from './JourneyRoutingEditor';
import {journeyIssues} from '../../../lib/advisory-journey-presentation';
import {journeyRequest} from './client';
import {journeyText,type JourneyLabel} from './labels';
import css from './journey-templates.module.css';
export default function JourneyTemplates(){
 const {a,locale}=useAdvisoryLabels(),t=(k:JourneyLabel)=>journeyText(locale,k);
 const [variants,setVariants]=useState<JourneyVariant[]>([]),[family,setFamily]=useState(journeyFamilies[0].key),[selected,setSelected]=useState(''),[editing,setEditing]=useState(false),[draft,setDraft]=useState<JourneyDefinition|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const lock=useRef(false),ticket=useRef<{body:string;id:string}|null>(null),sequence=useRef(0);
 const reload=useCallback(async()=>{const n=++sequence.current;try{const r=await journeyRequest();if(n===sequence.current){setVariants(r.variants);setLoading(false);}return true;}catch(e){if(n===sequence.current){setError(String((e as Error).message));setLoading(false);}return false;}},[]);
 useEffect(()=>{const counter=sequence;void reload();return()=>{counter.current++;};},[reload]);
 const choices=variants.filter(v=>v.family_key===family),current=choices.find(v=>v.id===selected)||choices.find(v=>v.is_default)||choices[0];
 function start(create=false){setError('');setNotice('');setEditing(true);if(create){setSelected('new');const f=journeyFamilies.find(f=>f.key===family)!;setDraft({name_th:'',name_en:'',stages:f.stages.map((key,i)=>({key,name_th:f.stage_labels_th[i],name_en:f.stage_labels_en[i],required:true}))});}else{setSelected(current.id);setDraft(structuredClone(current.definition));}}
 async function perform(action:string,payload:unknown){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');const body={action,id:action==='create'?null:current.id,revision:action==='create'?null:current.revision,payload},serialized=JSON.stringify(body);if(ticket.current?.body!==serialized)ticket.current={body:serialized,id:crypto.randomUUID()};try{const r=await journeyRequest({...body,request_id:ticket.current.id});ticket.current=null;setSelected(r.id);setEditing(false);setDraft(null);setNotice(t('saved'));await reload();}catch(e){setError(String((e as Error).message));}finally{lock.current=false;setBusy(false);}}
 function update(index:number,patch:Partial<JourneyStep>){setDraft(d=>d&&({...d,stages:d.stages.map((s,i)=>i===index?{...s,...patch}:s)}));}
 function move(index:number,delta:number){setDraft(d=>{if(!d)return d;const stages=[...d.stages],to=index+delta;if(to<0||to>=stages.length-1||index===stages.length-1)return d;[stages[to],stages[index]]=[stages[index],stages[to]];stages[0]={...stages[0],required:true,...(d.format===2?{conditional:false}:{})};return {...d,stages};});}
 function submit(e:FormEvent){e.preventDefault();if(draft&&!journeyIssues(draft).length)void perform(selected==='new'?'create':'publish',{...(selected==='new'?{family_key:family}:{}),definition:draft});}
 return <main className={css.page}><AppTopNav activePage="journeyTemplates" title={t('title')}/><header><p>{t('intro')}</p><button disabled={busy||editing} onClick={()=>void reload()}>{t('refresh')}</button></header>
 {error&&<p className={css.error} role="alert">{a(errorKey(error))}</p>}{notice&&<p role="status" className={css.notice}>{notice}</p>}
 <label className={css.family}>{t('family')}<select value={family} disabled={busy||editing} onChange={e=>{setFamily(e.target.value);setSelected('');}}>{journeyFamilies.map(f=><option key={f.key} value={f.key}>{a('family.'+f.key)}</option>)}</select></label>
 <div className={css.columns} data-controlled={(editing?draft:current?.definition)?.format===2}><section className={css.panel}><header><h2>{t('variants')}</h2><button disabled={loading||busy||editing} onClick={()=>start(true)}>{t('add')}</button></header>{loading?<p>{t('loading')}</p>:!choices.length?<p>{t('empty')}</p>:<ul className={css.variants}>{choices.map(v=><li key={v.id} data-selected={current?.id===v.id&&selected!=='new'}><button disabled={busy||editing} onClick={()=>setSelected(v.id)}><strong>{journeyName(v.definition,locale)}</strong><span>v{v.version} · {t(v.active?'active':'inactive')}</span>{v.is_default&&<small>{t('default')}</small>}</button></li>)}</ul>}
 {current&&!editing&&<div className={css.actions}><button disabled={busy||current.is_default} onClick={()=>void perform('configure',{active:!current.active,is_default:false})}>{t(current.active?'deactivate':'activate')}</button><button disabled={busy||!current.active||current.is_default} onClick={()=>void perform('configure',{active:true,is_default:true})}>{t('setDefault')}</button><small>{t('defaultHint')}</small></div>}</section>
 <section className={css.panel}>{editing&&draft?<form onSubmit={submit}><h2>{t(selected==='new'?'add':'edit')}</h2><div className={css.names}><label>{t('nameTh')}<input required maxLength={160} value={draft.name_th} onChange={e=>setDraft({...draft,name_th:e.target.value})}/></label><label>{t('nameEn')}<input required maxLength={160} value={draft.name_en} onChange={e=>setDraft({...draft,name_en:e.target.value})}/></label></div><p>{t('readOnly')}</p>{draft.format!==2&&<ol className={css.stages}>{draft.stages.map((s,i)=><li key={s.key}><div className={css.names}><label>{t('nameTh')}<input required maxLength={160} value={s.name_th} onChange={e=>update(i,{name_th:e.target.value})}/></label><label>{t('nameEn')}<input required maxLength={160} value={s.name_en} onChange={e=>update(i,{name_en:e.target.value})}/></label></div><div className={css.actions}><label><input type="checkbox" checked={s.required} disabled={i===0||s.key==='close'} onChange={e=>update(i,{required:e.target.checked})}/>{t('required')}</label><button type="button" disabled={i===0||s.key==='close'} onClick={()=>move(i,-1)} aria-label={t('up')}>↑</button><button type="button" disabled={i>=draft.stages.length-2} onClick={()=>move(i,1)} aria-label={t('down')}>↓</button><button type="button" disabled={i===0||s.key==='close'} onClick={()=>setDraft({...draft,stages:draft.stages.filter((_,j)=>j!==i)})}>{t('remove')}</button></div></li>)}</ol>}<button type="button" disabled={busy||draft.stages.length>=20} onClick={()=>setDraft({...draft,stages:[...draft.stages.slice(0,-1),{key:'step_'+crypto.randomUUID().replaceAll('-',''),name_th:'',name_en:'',required:true,...(draft.format===2?{conditional:false,outcomes:[{key:'continue',name_th:'ไปต่อ',name_en:'Continue',target:'close',requires_reason:false}]}:{})},draft.stages.at(-1)!]})}>{t('addStage')}</button><JourneyRoutingEditor definition={draft} locale={locale} onChange={setDraft} onMove={move} onRemove={i=>setDraft({...draft,stages:draft.stages.filter((_,j)=>j!==i)})} disabled={busy}/><p className={css.notice}>{t('saveHint')}</p><div className={css.actions}><button type="button" disabled={busy} onClick={()=>{setEditing(false);setDraft(null);setSelected(current?.id||'');}}>{t('cancel')}</button><button type="submit" disabled={busy||!!journeyIssues(draft).length}>{t(busy?'busy':selected==='new'?'create':'publish')}</button></div></form>:current&&<><header><h2>{journeyName(current.definition,locale)} · v{current.version}</h2><button disabled={busy} onClick={()=>start()}>{t('edit')}</button></header>{current.definition.format!==2&&<><h3>{t('stages')}</h3><ol className={css.stages}>{current.definition.stages.map(s=><li key={s.key}><strong>{journeyName(s,locale)}</strong><span className={css.badge} data-required={s.required}>{t(s.required?'required':'optional')}</span></li>)}</ol></>}<JourneyRoutingEditor definition={current.definition} locale={locale}/><p className={css.notice}>{t('saveHint')}</p></>}</section></div></main>;
}
