'use client';
import {useState} from 'react';
import {journeyName,type JourneyDefinition,type JourneyStep} from '../../../lib/advisory-flexible-journey';
import {controlledDraft,type JourneyOutcome} from '../../../lib/advisory-controlled-journey';
import {controlledText,type ControlledLabel} from '../../advisory/control/controlled-journey-labels';
import {journeyIssues} from '../../../lib/advisory-journey-presentation';
import JourneyRouteMap from '../../advisory/control/JourneyRouteMap';
import {journeyText} from './labels';
import css from './journey-templates.module.css';
export default function JourneyRoutingEditor({definition,locale,onChange,onMove,onRemove,disabled=false}:{definition:JourneyDefinition;locale:string;onChange?:(d:JourneyDefinition)=>void;onMove?:(i:number,delta:number)=>void;onRemove?:(i:number)=>void;disabled?:boolean}){
 const [selected,setSelected]=useState('');const t=(k:ControlledLabel)=>controlledText(locale,k),stages=definition.stages,stage=stages.find(s=>s.key===selected)||stages[0],index=stages.indexOf(stage),issues=journeyIssues(definition);
 function update(patch:Partial<JourneyStep>){onChange?.({...definition,stages:stages.map(s=>s.key===stage.key?{...s,...patch}:s)});}
 function outcome(index:number,patch:Partial<JourneyOutcome>){update({outcomes:stage.outcomes?.map((o,i)=>i===index?{...o,...patch}:o)});}
 if(definition.format!==2)return onChange?<div className={css.notice}><p>{t('enableHint')}</p><button type="button" disabled={disabled} onClick={()=>onChange(controlledDraft(definition))}>{t('enable')}</button></div>:null;
 return <section className={css.routing}><h3>{t('routing')}</h3><p>{t('enableHint')}</p>{issues.length>0&&<div role="alert" className={css.error}><strong>{t('reviewIssues')}</strong><ul>{issues.map((issue,i)=>{const at=stages.findIndex(s=>s.key===issue.stage);return <li key={i}><button type="button" onClick={()=>setSelected(issue.stage)}>{t('stage')} {at+1} · {journeyName(stages[at]||{},locale)}{issue.outcome&&` · ${t('outcome')} ${issue.outcome}`}: {t(issue.problem)}</button></li>;})}</ul></div>}<div className={css.routeColumns}>
 <nav aria-label={t('stage')} className={css.stageNav}>{stages.map((s,i)=><button key={s.key} type="button" aria-current={s.key===stage.key?'step':undefined} onClick={()=>setSelected(s.key)}>{i+1}. {journeyName(s,locale)}{s.conditional&&<small>{t('conditional')}</small>}</button>)}</nav>
 <div className={css.routeDetail}><h4>{journeyName(stage,locale)}</h4>{onChange?<><div className={css.names}><label>{t('nameTh')}<input required disabled={disabled} maxLength={160} value={stage.name_th} onChange={e=>update({name_th:e.target.value})}/></label><label>{t('nameEn')}<input required disabled={disabled} maxLength={160} value={stage.name_en} onChange={e=>update({name_en:e.target.value})}/></label></div><div className={css.actions}><label><input type="checkbox" checked={stage.required} disabled={disabled||index===0||stage.key==='close'} onChange={e=>update({required:e.target.checked})}/>{journeyText(locale,'required')}</label><button type="button" disabled={disabled||index===0||stage.key==='close'} aria-label={journeyText(locale,'up')} onClick={()=>onMove?.(index,-1)}>↑</button><button type="button" disabled={disabled||index>=stages.length-2} aria-label={journeyText(locale,'down')} onClick={()=>onMove?.(index,1)}>↓</button><button type="button" disabled={disabled||index===0||stage.key==='close'||stages.some(s=>s.outcomes?.some(o=>o.target===stage.key))} onClick={()=>onRemove?.(index)}>{journeyText(locale,'remove')}</button></div></>:<span className={css.badge} data-required={stage.required}>{journeyText(locale,stage.required?'required':'optional')}</span>}{onChange?<label><input type="checkbox" checked={!!stage.conditional} disabled={disabled||stage===stages[0]||stage.key==='close'} onChange={e=>update({conditional:e.target.checked})}/>{t('conditional')}</label>:stage.conditional&&<span className={css.badge}>{t('conditional')}</span>}<p>{t('conditionalHint')}</p>
 {stage.key==='close'?<p className={css.notice}>{t('terminal')}</p>:<><h4>{t('completionQuestion')}</h4><p>{t('completionHelp')}</p><div className={css.outcomes}>{(stage.outcomes||[]).map((o,i)=><fieldset key={o.key} disabled={disabled}><legend>{i+1}</legend>{onChange?<><div className={css.names}><label>{t('nameTh')}<input required maxLength={160} value={o.name_th} onChange={e=>outcome(i,{name_th:e.target.value})}/></label><label>{t('nameEn')}<input required maxLength={160} value={o.name_en} onChange={e=>outcome(i,{name_en:e.target.value})}/></label></div><label className={css.target}>{t('target')}<select required value={o.target} onChange={e=>outcome(i,{target:e.target.value})}><option value="">—</option>{stages.map(s=><option key={s.key} value={s.key}>{journeyName(s,locale)}</option>)}</select></label><div className={css.actions}><label><input type="checkbox" checked={o.requires_reason} onChange={e=>outcome(i,{requires_reason:e.target.checked})}/>{t('reasonRequired')}</label><button type="button" onClick={()=>update({outcomes:stage.outcomes?.filter((_,j)=>i!==j)})}>{t('removeOutcome')}</button></div></>:<><strong>{journeyName(o,locale)}</strong><p>→ {journeyName(stages.find(s=>s.key===o.target)||{},locale)}</p><small>{t(o.requires_reason?'reasonRequired':'reasonOptional')}</small></>}</fieldset>)}</div>{onChange&&<button type="button" disabled={disabled||(stage.outcomes?.length||0)>=8} onClick={()=>update({outcomes:[...(stage.outcomes||[]),{key:'outcome_'+crypto.randomUUID().replaceAll('-',''),name_th:'',name_en:'',target:'',requires_reason:false}]})}>{t('addOutcome')}</button>}</>}
 </div><aside className={css.preview}><h4>{t('preview')}</h4><JourneyRouteMap definition={definition} locale={locale} selected={stage.key} onSelect={setSelected}/>{!issues.length&&<p className={css.valid}>{t('routesValid')}</p>}</aside></div></section>;
}
